# Databricks notebook source
# COMMAND ----------

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.ALLIVET_ORDER_STATUS_DAY(ALLIVET_ORDER_NBR STRING,
RX_HOLD_DT DATE,
OPEN_DT DATE,
COMPLETE_DT DATE,
VOID_DT DATE,
UPDATE_TSTMP TIMESTAMP,
LOAD_TSTMP TIMESTAMP) USING DELTA;