# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ../WorkflowUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_A_Invoice_Line_Pre")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_DDS_OMS_A_Invoice_Line_Pre", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_PURCH_ORDER_LOAD_CTRL_0


query_0 = f"""SELECT
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  TC_PURCHASE_ORDERS_ID AS TC_PURCHASE_ORDERS_ID
FROM
  OMS_PURCH_ORDER_LOAD_CTRL"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_OMS_PURCH_ORDER_LOAD_CTRL_0")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_A_INVOICE_LINE_1


query_1 = f"""SELECT
  INVOICE_LINE_ID AS INVOICE_LINE_ID,
  INVOICE_LINE_NUMBER AS INVOICE_LINE_NUMBER,
  INVOICE_ID AS INVOICE_ID,
  ENTITY_LINE_NUMBER AS ENTITY_LINE_NUMBER,
  ORDERED_ITEM_UOM_ID AS ORDERED_ITEM_UOM_ID,
  ORDERED_QTY AS ORDERED_QTY,
  INVOICED_QTY AS INVOICED_QTY,
  UNIT_PRICE AS UNIT_PRICE,
  LINE_CHARGE AS LINE_CHARGE,
  LINE_DISCOUNT AS LINE_DISCOUNT,
  LINE_TAX AS LINE_TAX,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_SOURCE AS LAST_UPDATED_SOURCE,
  LAST_UPDATED_SOURCE_TYPE AS LAST_UPDATED_SOURCE_TYPE,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  ORDER_LINE_ID AS ORDER_LINE_ID,
  ITEM_ID AS ITEM_ID,
  RETURN_ORDER_LINE_ID AS RETURN_ORDER_LINE_ID,
  RETURN_ORDER_LINE_NUMBER AS RETURN_ORDER_LINE_NUMBER,
  RETURN_TYPE AS RETURN_TYPE,
  IS_TAX_INCLUDED AS IS_TAX_INCLUDED,
  SHIPPED_QUANTITY AS SHIPPED_QUANTITY,
  SHIPPED_ITEM_ID AS SHIPPED_ITEM_ID,
  ORDERED_ITEM_ID AS ORDERED_ITEM_ID,
  SHIPPED_ITEM_UOM_ID AS SHIPPED_ITEM_UOM_ID
FROM
  A_INVOICE_LINE"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("Shortcut_to_A_INVOICE_LINE_1")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_A_INVOICE_2


query_2 = f"""SELECT
  INVOICE_ID AS INVOICE_ID,
  INVOICE_NUMBER AS INVOICE_NUMBER,
  TC_COMPANY_ID AS TC_COMPANY_ID,
  INVOICE_CREATION_DTTM AS INVOICE_CREATION_DTTM,
  ENTITY_TYPE AS ENTITY_TYPE,
  ENTITY_ID AS ENTITY_ID,
  INVOICE_TYPE AS INVOICE_TYPE,
  CURRENCY AS CURRENCY,
  HEADER_TAX AS HEADER_TAX,
  HEADER_CHARGE AS HEADER_CHARGE,
  HEADER_DISCOUNT AS HEADER_DISCOUNT,
  INVOICE_AMOUNT AS INVOICE_AMOUNT,
  STATUS AS STATUS,
  SHIPMENT_NUMBER AS SHIPMENT_NUMBER,
  INVOICE_AMOUNT_PROCESSED AS INVOICE_AMOUNT_PROCESSED,
  COLLECTED_EXTERNALLY AS COLLECTED_EXTERNALLY,
  ENTITY_NUMBER AS ENTITY_NUMBER,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  LAST_UPDATED_SOURCE AS LAST_UPDATED_SOURCE,
  LAST_UPDATED_SOURCE_TYPE AS LAST_UPDATED_SOURCE_TYPE,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  RETURN_ORDER_ID AS RETURN_ORDER_ID,
  RETURN_ORDER_NUMBER AS RETURN_ORDER_NUMBER,
  IS_PUBLISHED AS IS_PUBLISHED,
  C_INITIAL_IS_PUBLISHED AS C_INITIAL_IS_PUBLISHED,
  FACILITY_ID AS FACILITY_ID,
  PARTIALLY_SETTLED AS PARTIALLY_SETTLED
FROM
  A_INVOICE"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("Shortcut_to_A_INVOICE_2")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_A_INVOICE_LINE_3


query_3 = f"""SELECT
  Shortcut_to_A_INVOICE_LINE_1.INVOICE_LINE_ID AS INVOICE_LINE_ID,
  Shortcut_to_A_INVOICE_LINE_1.INVOICE_LINE_NUMBER AS INVOICE_LINE_NUMBER,
  Shortcut_to_A_INVOICE_LINE_1.INVOICE_ID AS INVOICE_ID,
  Shortcut_to_A_INVOICE_LINE_1.ENTITY_LINE_NUMBER AS ENTITY_LINE_NUMBER,
  Shortcut_to_A_INVOICE_LINE_1.ORDERED_ITEM_UOM_ID AS ORDERED_ITEM_UOM_ID,
  Shortcut_to_A_INVOICE_LINE_1.ORDERED_QTY AS ORDERED_QTY,
  Shortcut_to_A_INVOICE_LINE_1.INVOICED_QTY AS INVOICED_QTY,
  Shortcut_to_A_INVOICE_LINE_1.UNIT_PRICE AS UNIT_PRICE,
  Shortcut_to_A_INVOICE_LINE_1.LINE_CHARGE AS LINE_CHARGE,
  Shortcut_to_A_INVOICE_LINE_1.LINE_DISCOUNT AS LINE_DISCOUNT,
  Shortcut_to_A_INVOICE_LINE_1.LINE_TAX AS LINE_TAX,
  Shortcut_to_A_INVOICE_LINE_1.CREATED_DTTM AS CREATED_DTTM,
  Shortcut_to_A_INVOICE_LINE_1.LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  Shortcut_to_A_INVOICE_LINE_1.ORDER_LINE_ID AS ORDER_LINE_ID,
  Shortcut_to_A_INVOICE_LINE_1.RETURN_ORDER_LINE_ID AS RETURN_ORDER_LINE_ID,
  Shortcut_to_A_INVOICE_LINE_1.RETURN_ORDER_LINE_NUMBER AS RETURN_ORDER_LINE_NUMBER,
  Shortcut_to_A_INVOICE_LINE_1.RETURN_TYPE AS RETURN_TYPE,
  Shortcut_to_A_INVOICE_LINE_1.IS_TAX_INCLUDED AS IS_TAX_INCLUDED,
  Shortcut_to_A_INVOICE_LINE_1.SHIPPED_QUANTITY AS SHIPPED_QUANTITY,
  Shortcut_to_A_INVOICE_LINE_1.SHIPPED_ITEM_ID AS SHIPPED_ITEM_ID,
  Shortcut_to_A_INVOICE_LINE_1.ORDERED_ITEM_ID AS ORDERED_ITEM_ID,
  Shortcut_to_A_INVOICE_LINE_1.SHIPPED_ITEM_UOM_ID AS SHIPPED_ITEM_UOM_ID,
  Shortcut_to_OMS_PURCH_ORDER_LOAD_CTRL_0.PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  Shortcut_to_A_INVOICE_2.ENTITY_ID AS ENTITY_ID,
  Shortcut_to_A_INVOICE_2.INVOICE_ID AS INVOICE_ID1,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_A_INVOICE_LINE_1,
  Shortcut_to_OMS_PURCH_ORDER_LOAD_CTRL_0,
  Shortcut_to_A_INVOICE_2
WHERE
  Shortcut_to_OMS_PURCH_ORDER_LOAD_CTRL_0.PURCHASE_ORDERS_ID = Shortcut_to_A_INVOICE_2.ENTITY_ID
  AND Shortcut_to_A_INVOICE_2.INVOICE_ID = Shortcut_to_A_INVOICE_LINE_1.INVOICE_ID"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("SQ_Shortcut_to_A_INVOICE_LINE_3")

# COMMAND ----------
# DBTITLE 1, EXP_LOAD_TSTMP_4


query_4 = f"""SELECT
  INVOICE_LINE_ID AS INVOICE_LINE_ID,
  INVOICE_LINE_NUMBER AS INVOICE_LINE_NUMBER,
  INVOICE_ID AS INVOICE_ID,
  ENTITY_LINE_NUMBER AS ENTITY_LINE_NUMBER,
  ORDERED_ITEM_UOM_ID AS ORDERED_ITEM_UOM_ID,
  ORDERED_QTY AS ORDERED_QTY,
  INVOICED_QTY AS INVOICED_QTY,
  UNIT_PRICE AS UNIT_PRICE,
  LINE_CHARGE AS LINE_CHARGE,
  LINE_DISCOUNT AS LINE_DISCOUNT,
  LINE_TAX AS LINE_TAX,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  ORDER_LINE_ID AS ORDER_LINE_ID,
  RETURN_ORDER_LINE_ID AS RETURN_ORDER_LINE_ID,
  RETURN_ORDER_LINE_NUMBER AS RETURN_ORDER_LINE_NUMBER,
  RETURN_TYPE AS RETURN_TYPE,
  IS_TAX_INCLUDED AS IS_TAX_INCLUDED,
  SHIPPED_QUANTITY AS SHIPPED_QUANTITY,
  SHIPPED_ITEM_ID AS SHIPPED_ITEM_ID,
  ORDERED_ITEM_ID AS ORDERED_ITEM_ID,
  SHIPPED_ITEM_UOM_ID AS SHIPPED_ITEM_UOM_ID,
  now() AS o_LOAD_TSTMP,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_A_INVOICE_LINE_3"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("EXP_LOAD_TSTMP_4")

# COMMAND ----------
# DBTITLE 1, OMS_A_INVOICE_LINE_PRE


spark.sql("""INSERT INTO
  OMS_A_INVOICE_LINE_PRE
SELECT
  INVOICE_LINE_ID AS INVOICE_LINE_ID,
  INVOICE_LINE_NUMBER AS INVOICE_LINE_NUMBER,
  INVOICE_ID AS INVOICE_ID,
  ENTITY_LINE_NUMBER AS ENTITY_LINE_NUMBER,
  ORDERED_ITEM_UOM_ID AS ORDERED_ITEM_UOM_ID,
  ORDERED_QTY AS ORDERED_QTY,
  INVOICED_QTY AS INVOICED_QTY,
  UNIT_PRICE AS UNIT_PRICE,
  LINE_CHARGE AS LINE_CHARGE,
  LINE_DISCOUNT AS LINE_DISCOUNT,
  LINE_TAX AS LINE_TAX,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  ORDER_LINE_ID AS ORDER_LINE_ID,
  RETURN_ORDER_LINE_ID AS RETURN_ORDER_LINE_ID,
  RETURN_ORDER_LINE_NUMBER AS RETURN_ORDER_LINE_NUMBER,
  RETURN_TYPE AS RETURN_TYPE,
  IS_TAX_INCLUDED AS IS_TAX_INCLUDED,
  SHIPPED_QUANTITY AS SHIPPED_QUANTITY,
  SHIPPED_ITEM_ID AS SHIPPED_ITEM_ID,
  ORDERED_ITEM_ID AS ORDERED_ITEM_ID,
  SHIPPED_ITEM_UOM_ID AS SHIPPED_ITEM_UOM_ID,
  o_LOAD_TSTMP AS LOAD_TSTMP
FROM
  EXP_LOAD_TSTMP_4""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_A_Invoice_Line_Pre")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_DDS_OMS_A_Invoice_Line_Pre", mainWorkflowId, parentName)
