# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ../WorkflowUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_UCL_User")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_DDS_OMS_UCL_User", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_UCL_USER_PRE_0


query_0 = f"""SELECT
  UCL_USER_ID AS UCL_USER_ID,
  COMPANY_ID AS COMPANY_ID,
  USER_NAME AS USER_NAME,
  IS_ACTIVE AS IS_ACTIVE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  USER_TYPE_ID AS USER_TYPE_ID,
  USER_FIRST_NAME AS USER_FIRST_NAME,
  USER_MIDDLE_NAME AS USER_MIDDLE_NAME,
  USER_LAST_NAME AS USER_LAST_NAME,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_UCL_USER_PRE"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_OMS_UCL_USER_PRE_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_UCL_USER_PRE_1


query_1 = f"""SELECT
  UCL_USER_ID AS UCL_USER_ID,
  USER_NAME AS USER_NAME,
  IS_ACTIVE AS IS_ACTIVE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  USER_TYPE_ID AS USER_TYPE_ID,
  LOAD_TSTMP AS LOAD_TSTMP,
  USER_FIRST_NAME AS USER_FIRST_NAME,
  USER_MIDDLE_NAME AS USER_MIDDLE_NAME,
  USER_LAST_NAME AS USER_LAST_NAME,
  COMPANY_ID AS COMPANY_ID,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_UCL_USER_PRE_0"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("SQ_Shortcut_to_OMS_UCL_USER_PRE_1")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_UCL_USER_2


query_2 = f"""SELECT
  OMS_UCL_USER_ID AS OMS_UCL_USER_ID,
  OMS_COMPANY_ID AS OMS_COMPANY_ID,
  OMS_USER_TYPE_ID AS OMS_USER_TYPE_ID,
  USER_NAME AS USER_NAME,
  USER_FIRST_NAME AS USER_FIRST_NAME,
  USER_MIDDLE_NAME AS USER_MIDDLE_NAME,
  USER_LAST_NAME AS USER_LAST_NAME,
  ACTIVE_FLAG AS ACTIVE_FLAG,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_UCL_USER"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("Shortcut_to_OMS_UCL_USER_2")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_UCL_USER_3


query_3 = f"""SELECT
  OMS_UCL_USER_ID AS OMS_UCL_USER_ID,
  OMS_USER_TYPE_ID AS OMS_USER_TYPE_ID,
  USER_NAME AS USER_NAME,
  USER_FIRST_NAME AS USER_FIRST_NAME,
  USER_MIDDLE_NAME AS USER_MIDDLE_NAME,
  USER_LAST_NAME AS USER_LAST_NAME,
  ACTIVE_FLAG AS ACTIVE_FLAG,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  OMS_COMPANY_ID AS OMS_COMPANY_ID,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_UCL_USER_2"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("SQ_Shortcut_to_OMS_UCL_USER_3")

# COMMAND ----------
# DBTITLE 1, JNR_OMS_SYS_CODE_4


query_4 = f"""SELECT
  DETAIL.UCL_USER_ID AS UCL_USER_ID,
  DETAIL.USER_NAME AS USER_NAME,
  DETAIL.IS_ACTIVE AS IS_ACTIVE,
  DETAIL.CREATED_DTTM AS CREATED_DTTM,
  DETAIL.LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  DETAIL.USER_TYPE_ID AS USER_TYPE_ID,
  MASTER.OMS_UCL_USER_ID AS lkp_OMS_UCL_USER_ID,
  MASTER.OMS_USER_TYPE_ID AS lkp_OMS_USER_TYPE_ID,
  MASTER.USER_NAME AS lkp_USER_NAME,
  MASTER.USER_FIRST_NAME AS lkp_USER_FIRST_NAME,
  MASTER.USER_MIDDLE_NAME AS lkp_USER_MIDDLE_NAME,
  MASTER.USER_LAST_NAME AS lkp_USER_LAST_NAME,
  MASTER.ACTIVE_FLAG AS lkp_ACTIVE_FLAG,
  MASTER.OMS_CREATED_TSTMP AS lkp_OMS_CREATED_TSTMP,
  MASTER.OMS_LAST_UPDATED_TSTMP AS lkp_OMS_LAST_UPDATED_TSTMP,
  MASTER.LOAD_TSTMP AS lkp_LOAD_TSTMP,
  DETAIL.USER_FIRST_NAME AS USER_FIRST_NAME,
  DETAIL.USER_MIDDLE_NAME AS USER_MIDDLE_NAME,
  DETAIL.USER_LAST_NAME AS USER_LAST_NAME,
  DETAIL.COMPANY_ID AS COMPANY_ID,
  MASTER.OMS_COMPANY_ID AS lkp_OMS_COMPANY_ID,
  DETAIL.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_UCL_USER_3 MASTER
  RIGHT JOIN SQ_Shortcut_to_OMS_UCL_USER_PRE_1 DETAIL ON MASTER.OMS_UCL_USER_ID = DETAIL.UCL_USER_ID"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("JNR_OMS_SYS_CODE_4")

# COMMAND ----------
# DBTITLE 1, FTR_UNCHANGED_REC_5


query_5 = f"""SELECT
  UCL_USER_ID AS UCL_USER_ID,
  USER_NAME AS USER_NAME,
  IS_ACTIVE AS IS_ACTIVE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  USER_TYPE_ID AS USER_TYPE_ID,
  lkp_OMS_UCL_USER_ID AS lkp_OMS_UCL_USER_ID,
  lkp_OMS_USER_TYPE_ID AS lkp_OMS_USER_TYPE_ID,
  lkp_USER_NAME AS lkp_USER_NAME,
  lkp_USER_FIRST_NAME AS lkp_USER_FIRST_NAME,
  lkp_USER_MIDDLE_NAME AS lkp_USER_MIDDLE_NAME,
  lkp_USER_LAST_NAME AS lkp_USER_LAST_NAME,
  lkp_ACTIVE_FLAG AS lkp_ACTIVE_FLAG,
  lkp_OMS_CREATED_TSTMP AS lkp_OMS_CREATED_TSTMP,
  lkp_OMS_LAST_UPDATED_TSTMP AS lkp_OMS_LAST_UPDATED_TSTMP,
  lkp_LOAD_TSTMP AS lkp_LOAD_TSTMP,
  USER_FIRST_NAME AS USER_FIRST_NAME,
  USER_MIDDLE_NAME AS USER_MIDDLE_NAME,
  USER_LAST_NAME AS USER_LAST_NAME,
  COMPANY_ID AS COMPANY_ID,
  lkp_OMS_COMPANY_ID AS lkp_OMS_COMPANY_ID,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  JNR_OMS_SYS_CODE_4
WHERE
  ISNULL(lkp_OMS_UCL_USER_ID)
  OR (
    NOT ISNULL(lkp_OMS_UCL_USER_ID)
    AND (
      IFF(
        ISNULL(IS_ACTIVE),
        TO_INTEGER(999999999),
        IS_ACTIVE
      ) <> IFF(
        ISNULL(lkp_ACTIVE_FLAG),
        TO_INTEGER(999999999),
        lkp_ACTIVE_FLAG
      )
      OR IFF(
        ISNULL(USER_TYPE_ID),
        TO_INTEGER(999999999),
        USER_TYPE_ID
      ) <> IFF(
        ISNULL(lkp_OMS_USER_TYPE_ID),
        TO_INTEGER(999999999),
        lkp_OMS_USER_TYPE_ID
      )
      OR IFF(
        ISNULL(COMPANY_ID),
        TO_INTEGER(999999999),
        COMPANY_ID
      ) <> IFF(
        ISNULL(lkp_OMS_COMPANY_ID),
        TO_INTEGER(999999999),
        lkp_OMS_COMPANY_ID
      )
      OR IFF (
        ISNULL(LTRIM(RTRIM(USER_NAME))),
        ' ',
        LTRIM(RTRIM(USER_NAME))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_USER_NAME))),
        ' ',
        LTRIM(RTRIM(lkp_USER_NAME))
      )
      OR IFF (
        ISNULL(LTRIM(RTRIM(lkp_USER_FIRST_NAME))),
        ' ',
        LTRIM(RTRIM(lkp_USER_FIRST_NAME))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(USER_FIRST_NAME))),
        ' ',
        LTRIM(RTRIM(USER_FIRST_NAME))
      )
      OR IFF (
        ISNULL(LTRIM(RTRIM(USER_MIDDLE_NAME))),
        ' ',
        LTRIM(RTRIM(USER_MIDDLE_NAME))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_USER_MIDDLE_NAME))),
        ' ',
        LTRIM(RTRIM(lkp_USER_MIDDLE_NAME))
      )
      OR IFF (
        ISNULL(LTRIM(RTRIM(USER_LAST_NAME))),
        ' ',
        LTRIM(RTRIM(USER_LAST_NAME))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_USER_LAST_NAME))),
        ' ',
        LTRIM(RTRIM(lkp_USER_LAST_NAME))
      )
      OR IFF(
        ISNULL(CREATED_DTTM),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        CREATED_DTTM
      ) <> IFF(
        ISNULL(lkp_OMS_CREATED_TSTMP),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        lkp_OMS_CREATED_TSTMP
      )
      OR IFF(
        ISNULL(LAST_UPDATED_DTTM),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        LAST_UPDATED_DTTM
      ) <> IFF(
        ISNULL(lkp_OMS_LAST_UPDATED_TSTMP),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        lkp_OMS_LAST_UPDATED_TSTMP
      )
    )
  )"""

df_5 = spark.sql(query_5)

df_5.createOrReplaceTempView("FTR_UNCHANGED_REC_5")

# COMMAND ----------
# DBTITLE 1, EXP_VALID_FLAG_6


query_6 = f"""SELECT
  UCL_USER_ID AS UCL_USER_ID,
  USER_NAME AS USER_NAME,
  IS_ACTIVE AS IS_ACTIVE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  USER_TYPE_ID AS USER_TYPE_ID,
  lkp_OMS_UCL_USER_ID AS lkp_OMS_UCL_USER_ID,
  lkp_LOAD_TSTMP AS lkp_LOAD_TSTMP,
  now() AS UPDATE_TSTMP,
  IFF(ISNULL(lkp_LOAD_TSTMP), now(), lkp_LOAD_TSTMP) AS LOAD_TSTMP_exp,
  IFF(ISNULL(lkp_OMS_UCL_USER_ID), 1, 2) AS o_UPD_VALIDATOR,
  USER_FIRST_NAME AS USER_FIRST_NAME,
  USER_MIDDLE_NAME AS USER_MIDDLE_NAME,
  USER_LAST_NAME AS USER_LAST_NAME,
  COMPANY_ID AS COMPANY_ID,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  FTR_UNCHANGED_REC_5"""

df_6 = spark.sql(query_6)

df_6.createOrReplaceTempView("EXP_VALID_FLAG_6")

# COMMAND ----------
# DBTITLE 1, UPD_INS_UPD_7


query_7 = f"""SELECT
  UCL_USER_ID AS UCL_USER_ID,
  COMPANY_ID AS COMPANY_ID,
  USER_TYPE_ID AS USER_TYPE_ID,
  USER_NAME AS USER_NAME,
  USER_FIRST_NAME AS USER_FIRST_NAME,
  USER_MIDDLE_NAME AS USER_MIDDLE_NAME,
  USER_LAST_NAME AS USER_LAST_NAME,
  IS_ACTIVE AS IS_ACTIVE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP_exp AS LOAD_TSTMP_exp,
  o_UPD_VALIDATOR AS o_UPD_VALIDATOR,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id,
  DECODE(o_UPD_VALIDATOR, 1, 'DD_INSERT', 2, 'DD_UPDATE') AS UPDATE_STRATEGY_FLAG
FROM
  EXP_VALID_FLAG_6"""

df_7 = spark.sql(query_7)

df_7.createOrReplaceTempView("UPD_INS_UPD_7")

# COMMAND ----------
# DBTITLE 1, OMS_UCL_USER


spark.sql("""MERGE INTO OMS_UCL_USER AS TARGET
USING
  UPD_INS_UPD_7 AS SOURCE ON TARGET.OMS_UCL_USER_ID = SOURCE.UCL_USER_ID
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_UPDATE" THEN
UPDATE
SET
  TARGET.OMS_UCL_USER_ID = SOURCE.UCL_USER_ID,
  TARGET.OMS_COMPANY_ID = SOURCE.COMPANY_ID,
  TARGET.OMS_USER_TYPE_ID = SOURCE.USER_TYPE_ID,
  TARGET.USER_NAME = SOURCE.USER_NAME,
  TARGET.USER_FIRST_NAME = SOURCE.USER_FIRST_NAME,
  TARGET.USER_MIDDLE_NAME = SOURCE.USER_MIDDLE_NAME,
  TARGET.USER_LAST_NAME = SOURCE.USER_LAST_NAME,
  TARGET.ACTIVE_FLAG = SOURCE.IS_ACTIVE,
  TARGET.OMS_CREATED_TSTMP = SOURCE.CREATED_DTTM,
  TARGET.OMS_LAST_UPDATED_TSTMP = SOURCE.LAST_UPDATED_DTTM,
  TARGET.UPDATE_TSTMP = SOURCE.UPDATE_TSTMP,
  TARGET.LOAD_TSTMP = SOURCE.LOAD_TSTMP_exp
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_DELETE"
  AND TARGET.OMS_COMPANY_ID = SOURCE.COMPANY_ID
  AND TARGET.OMS_USER_TYPE_ID = SOURCE.USER_TYPE_ID
  AND TARGET.USER_NAME = SOURCE.USER_NAME
  AND TARGET.USER_FIRST_NAME = SOURCE.USER_FIRST_NAME
  AND TARGET.USER_MIDDLE_NAME = SOURCE.USER_MIDDLE_NAME
  AND TARGET.USER_LAST_NAME = SOURCE.USER_LAST_NAME
  AND TARGET.ACTIVE_FLAG = SOURCE.IS_ACTIVE
  AND TARGET.OMS_CREATED_TSTMP = SOURCE.CREATED_DTTM
  AND TARGET.OMS_LAST_UPDATED_TSTMP = SOURCE.LAST_UPDATED_DTTM
  AND TARGET.UPDATE_TSTMP = SOURCE.UPDATE_TSTMP
  AND TARGET.LOAD_TSTMP = SOURCE.LOAD_TSTMP_exp THEN DELETE
  WHEN NOT MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_INSERT" THEN
INSERT
  (
    TARGET.OMS_UCL_USER_ID,
    TARGET.OMS_COMPANY_ID,
    TARGET.OMS_USER_TYPE_ID,
    TARGET.USER_NAME,
    TARGET.USER_FIRST_NAME,
    TARGET.USER_MIDDLE_NAME,
    TARGET.USER_LAST_NAME,
    TARGET.ACTIVE_FLAG,
    TARGET.OMS_CREATED_TSTMP,
    TARGET.OMS_LAST_UPDATED_TSTMP,
    TARGET.UPDATE_TSTMP,
    TARGET.LOAD_TSTMP
  )
VALUES
  (
    SOURCE.UCL_USER_ID,
    SOURCE.COMPANY_ID,
    SOURCE.USER_TYPE_ID,
    SOURCE.USER_NAME,
    SOURCE.USER_FIRST_NAME,
    SOURCE.USER_MIDDLE_NAME,
    SOURCE.USER_LAST_NAME,
    SOURCE.IS_ACTIVE,
    SOURCE.CREATED_DTTM,
    SOURCE.LAST_UPDATED_DTTM,
    SOURCE.UPDATE_TSTMP,
    SOURCE.LOAD_TSTMP_exp
  )""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_UCL_User")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_DDS_OMS_UCL_User", mainWorkflowId, parentName)
