# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ../WorkflowUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_Object_Reason_Codes")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_DDS_OMS_Object_Reason_Codes", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_OBJECT_REASON_CODES_PRE_0


query_0 = f"""SELECT
  REASON_CODES_ID AS REASON_CODES_ID,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  REASON_CODE AS REASON_CODE,
  REASON_TYPE AS REASON_TYPE,
  COMMENTS AS COMMENTS,
  REF_FIELD_1 AS REF_FIELD_1,
  REF_FIELD_2 AS REF_FIELD_2,
  ACTIVE AS ACTIVE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_OBJECT_REASON_CODES_PRE"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_OMS_OBJECT_REASON_CODES_PRE_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_OBJECT_REASON_CODES_PRE_1


query_1 = f"""SELECT
  REASON_CODES_ID AS REASON_CODES_ID,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  REASON_CODE AS REASON_CODE,
  REASON_TYPE AS REASON_TYPE,
  COMMENTS AS COMMENTS,
  REF_FIELD_1 AS REF_FIELD_1,
  REF_FIELD_2 AS REF_FIELD_2,
  ACTIVE AS ACTIVE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  LOAD_TSTMP AS LOAD_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_OBJECT_REASON_CODES_PRE_0"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("SQ_Shortcut_to_OMS_OBJECT_REASON_CODES_PRE_1")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_OBJECT_REASON_CODES_2


query_2 = f"""SELECT
  OMS_REASON_CODES_ID AS OMS_REASON_CODES_ID,
  OMS_REASON_CODES_GROUP_ID AS OMS_REASON_CODES_GROUP_ID,
  OMS_REASON_CD AS OMS_REASON_CD,
  OMS_REASON_TYPE AS OMS_REASON_TYPE,
  COMMENTS AS COMMENTS,
  REF_FIELD_1 AS REF_FIELD_1,
  REF_FIELD_2 AS REF_FIELD_2,
  ACTIVE_FLAG AS ACTIVE_FLAG,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_OBJECT_REASON_CODES"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("Shortcut_to_OMS_OBJECT_REASON_CODES_2")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_OBJECT_REASON_CODES_3


query_3 = f"""SELECT
  OMS_REASON_CODES_ID AS OMS_REASON_CODES_ID,
  OMS_REASON_CODES_GROUP_ID AS OMS_REASON_CODES_GROUP_ID,
  OMS_REASON_CD AS OMS_REASON_CD,
  OMS_REASON_TYPE AS OMS_REASON_TYPE,
  COMMENTS AS COMMENTS,
  REF_FIELD_1 AS REF_FIELD_1,
  REF_FIELD_2 AS REF_FIELD_2,
  ACTIVE_FLAG AS ACTIVE_FLAG,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_OBJECT_REASON_CODES_2"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("SQ_Shortcut_to_OMS_OBJECT_REASON_CODES_3")

# COMMAND ----------
# DBTITLE 1, JNR_OMS_Object_Reason_Codes_4


query_4 = f"""SELECT
  DETAIL.REASON_CODES_ID AS REASON_CODES_ID,
  DETAIL.REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  DETAIL.REASON_CODE AS REASON_CODE,
  DETAIL.REASON_TYPE AS REASON_TYPE,
  DETAIL.COMMENTS AS COMMENTS,
  DETAIL.REF_FIELD_1 AS REF_FIELD_1,
  DETAIL.REF_FIELD_2 AS REF_FIELD_2,
  DETAIL.ACTIVE AS ACTIVE,
  DETAIL.CREATED_DTTM AS CREATED_DTTM,
  DETAIL.LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  MASTER.OMS_REASON_CODES_ID AS lkp_OMS_REASON_CODES_ID,
  MASTER.OMS_REASON_CODES_GROUP_ID AS lkp_OMS_REASON_CODES_GROUP_ID,
  MASTER.OMS_REASON_CD AS lkp_OMS_REASON_CD,
  MASTER.OMS_REASON_TYPE AS lkp_OMS_REASON_TYPE,
  MASTER.COMMENTS AS lkp_COMMENTS,
  MASTER.REF_FIELD_1 AS lkp_REF_FIELD_1,
  MASTER.REF_FIELD_2 AS lkp_REF_FIELD_2,
  MASTER.ACTIVE_FLAG AS lkp_ACTIVE_FLAG,
  MASTER.OMS_CREATED_TSTMP AS lkp_OMS_CREATED_TSTMP,
  MASTER.OMS_LAST_UPDATED_TSTMP AS lkp_OMS_LAST_UPDATED_TSTMP,
  MASTER.LOAD_TSTMP AS lkp_LOAD_TSTMP,
  DETAIL.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_OBJECT_REASON_CODES_3 MASTER
  RIGHT JOIN SQ_Shortcut_to_OMS_OBJECT_REASON_CODES_PRE_1 DETAIL ON MASTER.OMS_REASON_CODES_ID = DETAIL.REASON_CODES_ID"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("JNR_OMS_Object_Reason_Codes_4")

# COMMAND ----------
# DBTITLE 1, FTR_UNCHANGED_REC_5


query_5 = f"""SELECT
  REASON_CODES_ID AS REASON_CODES_ID,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  REASON_CODE AS REASON_CODE,
  REASON_TYPE AS REASON_TYPE,
  COMMENTS AS COMMENTS,
  REF_FIELD_1 AS REF_FIELD_1,
  REF_FIELD_2 AS REF_FIELD_2,
  ACTIVE AS ACTIVE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  lkp_OMS_REASON_CODES_ID AS lkp_OMS_REASON_CODES_ID,
  lkp_OMS_REASON_CODES_GROUP_ID AS lkp_OMS_REASON_CODES_GROUP_ID,
  lkp_OMS_REASON_CD AS lkp_OMS_REASON_CD,
  lkp_OMS_REASON_TYPE AS lkp_OMS_REASON_TYPE,
  lkp_COMMENTS AS lkp_COMMENTS,
  lkp_REF_FIELD_1 AS lkp_REF_FIELD_1,
  lkp_REF_FIELD_2 AS lkp_REF_FIELD_2,
  lkp_ACTIVE_FLAG AS lkp_ACTIVE_FLAG,
  lkp_OMS_CREATED_TSTMP AS lkp_OMS_CREATED_TSTMP,
  lkp_OMS_LAST_UPDATED_TSTMP AS lkp_OMS_LAST_UPDATED_TSTMP,
  lkp_LOAD_TSTMP AS lkp_LOAD_TSTMP,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  JNR_OMS_Object_Reason_Codes_4
WHERE
  ISNULL(lkp_OMS_REASON_CODES_ID)
  OR (
    NOT ISNULL(lkp_OMS_REASON_CODES_ID)
    AND (
      IFF(
        ISNULL(REASON_CODES_GROUP_ID),
        TO_INTEGER(999999999),
        REASON_CODES_GROUP_ID
      ) <> IFF(
        ISNULL(lkp_OMS_REASON_CODES_GROUP_ID),
        TO_INTEGER(999999999),
        lkp_OMS_REASON_CODES_GROUP_ID
      )
      OR IFF (
        ISNULL(LTRIM(RTRIM(REASON_CODE))),
        ' ',
        LTRIM(RTRIM(REASON_CODE))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_OMS_REASON_CD))),
        ' ',
        LTRIM(RTRIM(lkp_OMS_REASON_CD))
      )
      OR IFF (
        ISNULL(LTRIM(RTRIM(REASON_TYPE))),
        ' ',
        LTRIM(RTRIM(REASON_TYPE))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_OMS_REASON_TYPE))),
        ' ',
        LTRIM(RTRIM(lkp_OMS_REASON_TYPE))
      )
      OR IFF (
        ISNULL(LTRIM(RTRIM(COMMENTS))),
        ' ',
        LTRIM(RTRIM(COMMENTS))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_COMMENTS))),
        ' ',
        LTRIM(RTRIM(lkp_COMMENTS))
      )
      OR IFF (
        ISNULL(LTRIM(RTRIM(REF_FIELD_1))),
        ' ',
        LTRIM(RTRIM(REF_FIELD_1))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_REF_FIELD_1))),
        ' ',
        LTRIM(RTRIM(lkp_REF_FIELD_1))
      )
      OR IFF (
        ISNULL(LTRIM(RTRIM(REF_FIELD_2))),
        ' ',
        LTRIM(RTRIM(REF_FIELD_2))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_REF_FIELD_2))),
        ' ',
        LTRIM(RTRIM(lkp_REF_FIELD_2))
      )
      OR IFF(ISNULL(ACTIVE), TO_INTEGER(999999999), ACTIVE) <> IFF(
        ISNULL(lkp_ACTIVE_FLAG),
        TO_INTEGER(999999999),
        lkp_ACTIVE_FLAG
      )
      OR IFF(
        ISNULL(CREATED_DTTM),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        CREATED_DTTM
      ) <> IFF(
        ISNULL(lkp_OMS_CREATED_TSTMP),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        lkp_OMS_CREATED_TSTMP
      )
      OR IFF(
        ISNULL(LAST_UPDATED_DTTM),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        LAST_UPDATED_DTTM
      ) <> IFF(
        ISNULL(lkp_OMS_LAST_UPDATED_TSTMP),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        lkp_OMS_LAST_UPDATED_TSTMP
      )
    )
  )"""

df_5 = spark.sql(query_5)

df_5.createOrReplaceTempView("FTR_UNCHANGED_REC_5")

# COMMAND ----------
# DBTITLE 1, EXP_VALID_FLAG_6


query_6 = f"""SELECT
  REASON_CODES_ID AS REASON_CODES_ID,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  REASON_CODE AS REASON_CODE,
  REASON_TYPE AS REASON_TYPE,
  COMMENTS AS COMMENTS,
  REF_FIELD_1 AS REF_FIELD_1,
  REF_FIELD_2 AS REF_FIELD_2,
  ACTIVE AS ACTIVE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  lkp_OMS_REASON_CODES_ID AS lkp_OMS_REASON_CODES_ID,
  lkp_LOAD_TSTMP AS lkp_LOAD_TSTMP,
  now() AS UPDATE_TSTMP_exp,
  IFF(ISNULL(lkp_LOAD_TSTMP), now(), lkp_LOAD_TSTMP) AS LOAD_TSTMP_exp,
  IFF(ISNULL(lkp_OMS_REASON_CODES_ID), 1, 2) AS o_UPD_VALIDATOR,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  FTR_UNCHANGED_REC_5"""

df_6 = spark.sql(query_6)

df_6.createOrReplaceTempView("EXP_VALID_FLAG_6")

# COMMAND ----------
# DBTITLE 1, UPS_INS_UPD_7


query_7 = f"""SELECT
  REASON_CODES_ID AS REASON_CODES_ID,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  REASON_CODE AS REASON_CODE,
  REASON_TYPE AS REASON_TYPE,
  COMMENTS AS COMMENTS,
  REF_FIELD_1 AS REF_FIELD_1,
  REF_FIELD_2 AS REF_FIELD_2,
  ACTIVE AS ACTIVE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  UPDATE_TSTMP_exp AS UPDATE_TSTMP_exp,
  LOAD_TSTMP_exp AS LOAD_TSTMP_exp,
  o_UPD_VALIDATOR AS o_UPD_VALIDATOR,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id,
  DECODE(o_UPD_VALIDATOR, 1, 'DD_INSERT', 2, 'DD_UPDATE') AS UPDATE_STRATEGY_FLAG
FROM
  EXP_VALID_FLAG_6"""

df_7 = spark.sql(query_7)

df_7.createOrReplaceTempView("UPS_INS_UPD_7")

# COMMAND ----------
# DBTITLE 1, OMS_OBJECT_REASON_CODES


spark.sql("""MERGE INTO OMS_OBJECT_REASON_CODES AS TARGET
USING
  UPS_INS_UPD_7 AS SOURCE ON TARGET.OMS_REASON_CODES_ID = SOURCE.REASON_CODES_ID
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_UPDATE" THEN
UPDATE
SET
  TARGET.OMS_REASON_CODES_ID = SOURCE.REASON_CODES_ID,
  TARGET.OMS_REASON_CODES_GROUP_ID = SOURCE.REASON_CODES_GROUP_ID,
  TARGET.OMS_REASON_CD = SOURCE.REASON_CODE,
  TARGET.OMS_REASON_TYPE = SOURCE.REASON_TYPE,
  TARGET.COMMENTS = SOURCE.COMMENTS,
  TARGET.REF_FIELD_1 = SOURCE.REF_FIELD_1,
  TARGET.REF_FIELD_2 = SOURCE.REF_FIELD_2,
  TARGET.ACTIVE_FLAG = SOURCE.ACTIVE,
  TARGET.OMS_CREATED_TSTMP = SOURCE.CREATED_DTTM,
  TARGET.OMS_LAST_UPDATED_TSTMP = SOURCE.LAST_UPDATED_DTTM,
  TARGET.UPDATE_TSTMP = SOURCE.UPDATE_TSTMP_exp,
  TARGET.LOAD_TSTMP = SOURCE.LOAD_TSTMP_exp
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_DELETE"
  AND TARGET.OMS_REASON_CODES_GROUP_ID = SOURCE.REASON_CODES_GROUP_ID
  AND TARGET.OMS_REASON_CD = SOURCE.REASON_CODE
  AND TARGET.OMS_REASON_TYPE = SOURCE.REASON_TYPE
  AND TARGET.COMMENTS = SOURCE.COMMENTS
  AND TARGET.REF_FIELD_1 = SOURCE.REF_FIELD_1
  AND TARGET.REF_FIELD_2 = SOURCE.REF_FIELD_2
  AND TARGET.ACTIVE_FLAG = SOURCE.ACTIVE
  AND TARGET.OMS_CREATED_TSTMP = SOURCE.CREATED_DTTM
  AND TARGET.OMS_LAST_UPDATED_TSTMP = SOURCE.LAST_UPDATED_DTTM
  AND TARGET.UPDATE_TSTMP = SOURCE.UPDATE_TSTMP_exp
  AND TARGET.LOAD_TSTMP = SOURCE.LOAD_TSTMP_exp THEN DELETE
  WHEN NOT MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_INSERT" THEN
INSERT
  (
    TARGET.OMS_REASON_CODES_ID,
    TARGET.OMS_REASON_CODES_GROUP_ID,
    TARGET.OMS_REASON_CD,
    TARGET.OMS_REASON_TYPE,
    TARGET.COMMENTS,
    TARGET.REF_FIELD_1,
    TARGET.REF_FIELD_2,
    TARGET.ACTIVE_FLAG,
    TARGET.OMS_CREATED_TSTMP,
    TARGET.OMS_LAST_UPDATED_TSTMP,
    TARGET.UPDATE_TSTMP,
    TARGET.LOAD_TSTMP
  )
VALUES
  (
    SOURCE.REASON_CODES_ID,
    SOURCE.REASON_CODES_GROUP_ID,
    SOURCE.REASON_CODE,
    SOURCE.REASON_TYPE,
    SOURCE.COMMENTS,
    SOURCE.REF_FIELD_1,
    SOURCE.REF_FIELD_2,
    SOURCE.ACTIVE,
    SOURCE.CREATED_DTTM,
    SOURCE.LAST_UPDATED_DTTM,
    SOURCE.UPDATE_TSTMP_exp,
    SOURCE.LOAD_TSTMP_exp
  )""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_Object_Reason_Codes")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_DDS_OMS_Object_Reason_Codes", mainWorkflowId, parentName)
