# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ../WorkflowUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_Purchase_Orders_Line_Item")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_DDS_OMS_Purchase_Orders_Line_Item", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_PRE_0


query_0 = f"""SELECT
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  PURCHASE_ORDERS_LINE_ITEM_ID AS PURCHASE_ORDERS_LINE_ITEM_ID,
  O_FACILITY_ID AS O_FACILITY_ID,
  O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  D_FACILITY_ID AS D_FACILITY_ID,
  D_FACILITY_ALIAS_ID AS D_FACILITY_ALIAS_ID,
  D_NAME AS D_NAME,
  D_LAST_NAME AS D_LAST_NAME,
  D_ADDRESS_1 AS D_ADDRESS_1,
  D_ADDRESS_2 AS D_ADDRESS_2,
  D_ADDRESS_3 AS D_ADDRESS_3,
  D_CITY AS D_CITY,
  D_STATE_PROV AS D_STATE_PROV,
  D_POSTAL_CODE AS D_POSTAL_CODE,
  D_COUNTY AS D_COUNTY,
  D_COUNTRY_CODE AS D_COUNTRY_CODE,
  D_PHONE_NUMBER AS D_PHONE_NUMBER,
  D_EMAIL AS D_EMAIL,
  BILL_FACILITY_ALIAS_ID AS BILL_FACILITY_ALIAS_ID,
  BILL_FACILITY_ID AS BILL_FACILITY_ID,
  STORE_FACILITY_ALIAS_ID AS STORE_FACILITY_ALIAS_ID,
  STORE_FACILITY_ID AS STORE_FACILITY_ID,
  SKU AS SKU,
  MV_CURRENCY_CODE AS MV_CURRENCY_CODE,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  UNIT_TAX_AMOUNT AS UNIT_TAX_AMOUNT,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  RELEASED_QTY AS RELEASED_QTY,
  CANCELLED_QTY AS CANCELLED_QTY,
  PPACK_QTY AS PPACK_QTY,
  DELIVERY_TZ AS DELIVERY_TZ,
  PICKUP_TZ AS PICKUP_TZ,
  PICKUP_START_DTTM AS PICKUP_START_DTTM,
  PICKUP_END_DTTM AS PICKUP_END_DTTM,
  DELIVERY_START_DTTM AS DELIVERY_START_DTTM,
  DELIVERY_END_DTTM AS DELIVERY_END_DTTM,
  REQ_DLVR_DTTM AS REQ_DLVR_DTTM,
  MUST_DLVR_DTTM AS MUST_DLVR_DTTM,
  SHIP_BY_DATE AS SHIP_BY_DATE,
  IS_READY_TO_SHIP AS IS_READY_TO_SHIP,
  IS_CANCELLED AS IS_CANCELLED,
  IS_CLOSED AS IS_CLOSED,
  IS_DELETED AS IS_DELETED,
  SHIPPED_QTY AS SHIPPED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  DSG_CARRIER_ID AS DSG_CARRIER_ID,
  PURCHASE_ORDERS_LINE_STATUS AS PURCHASE_ORDERS_LINE_STATUS,
  TC_PO_LINE_ID AS TC_PO_LINE_ID,
  PARENT_PO_LINE_ITEM_ID AS PARENT_PO_LINE_ITEM_ID,
  ORDER_QTY AS ORDER_QTY,
  ALLOC_FINALIZER AS ALLOC_FINALIZER,
  CUST_SKU AS CUST_SKU,
  IS_DO_CREATED AS IS_DO_CREATED,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  RETAIL_PRICE AS RETAIL_PRICE,
  DSG_SHIP_VIA AS DSG_SHIP_VIA,
  LINE_TOTAL AS LINE_TOTAL,
  ADDR_VALID AS ADDR_VALID,
  REASON_ID AS REASON_ID,
  ORDER_FULFILLMENT_OPTION AS ORDER_FULFILLMENT_OPTION,
  IS_RETURNABLE AS IS_RETURNABLE,
  BACK_ORD_REASON AS BACK_ORD_REASON,
  PRICE_OVERRIDE AS PRICE_OVERRIDE,
  ORIGINAL_PRICE AS ORIGINAL_PRICE,
  EXT_CREATED_DTTM AS EXT_CREATED_DTTM,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  IS_EXCHANGEABLE AS IS_EXCHANGEABLE,
  ORIGINAL_PO_LINE_ITEM_ID AS ORIGINAL_PO_LINE_ITEM_ID,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_PURCHASE_ORDERS_LINE_ITEM_PRE"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_PRE_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_PRE_1


query_1 = f"""SELECT
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  PURCHASE_ORDERS_LINE_ITEM_ID AS PURCHASE_ORDERS_LINE_ITEM_ID,
  O_FACILITY_ID AS O_FACILITY_ID,
  O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  D_FACILITY_ID AS D_FACILITY_ID,
  D_FACILITY_ALIAS_ID AS D_FACILITY_ALIAS_ID,
  D_NAME AS D_NAME,
  D_LAST_NAME AS D_LAST_NAME,
  D_ADDRESS_1 AS D_ADDRESS_1,
  D_ADDRESS_2 AS D_ADDRESS_2,
  D_ADDRESS_3 AS D_ADDRESS_3,
  D_CITY AS D_CITY,
  D_STATE_PROV AS D_STATE_PROV,
  D_POSTAL_CODE AS D_POSTAL_CODE,
  D_COUNTY AS D_COUNTY,
  D_COUNTRY_CODE AS D_COUNTRY_CODE,
  D_PHONE_NUMBER AS D_PHONE_NUMBER,
  D_EMAIL AS D_EMAIL,
  BILL_FACILITY_ALIAS_ID AS BILL_FACILITY_ALIAS_ID,
  BILL_FACILITY_ID AS BILL_FACILITY_ID,
  STORE_FACILITY_ALIAS_ID AS STORE_FACILITY_ALIAS_ID,
  STORE_FACILITY_ID AS STORE_FACILITY_ID,
  SKU AS SKU,
  MV_CURRENCY_CODE AS MV_CURRENCY_CODE,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  UNIT_TAX_AMOUNT AS UNIT_TAX_AMOUNT,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  RELEASED_QTY AS RELEASED_QTY,
  CANCELLED_QTY AS CANCELLED_QTY,
  PPACK_QTY AS PPACK_QTY,
  DELIVERY_TZ AS DELIVERY_TZ,
  PICKUP_TZ AS PICKUP_TZ,
  PICKUP_START_DTTM AS PICKUP_START_DTTM,
  PICKUP_END_DTTM AS PICKUP_END_DTTM,
  DELIVERY_START_DTTM AS DELIVERY_START_DTTM,
  DELIVERY_END_DTTM AS DELIVERY_END_DTTM,
  REQ_DLVR_DTTM AS REQ_DLVR_DTTM,
  MUST_DLVR_DTTM AS MUST_DLVR_DTTM,
  SHIP_BY_DATE AS SHIP_BY_DATE,
  IS_READY_TO_SHIP AS IS_READY_TO_SHIP,
  IS_CANCELLED AS IS_CANCELLED,
  IS_CLOSED AS IS_CLOSED,
  IS_DELETED AS IS_DELETED,
  SHIPPED_QTY AS SHIPPED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  DSG_CARRIER_ID AS DSG_CARRIER_ID,
  PURCHASE_ORDERS_LINE_STATUS AS PURCHASE_ORDERS_LINE_STATUS,
  TC_PO_LINE_ID AS TC_PO_LINE_ID,
  PARENT_PO_LINE_ITEM_ID AS PARENT_PO_LINE_ITEM_ID,
  ORDER_QTY AS ORDER_QTY,
  ALLOC_FINALIZER AS ALLOC_FINALIZER,
  CUST_SKU AS CUST_SKU,
  IS_DO_CREATED AS IS_DO_CREATED,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  RETAIL_PRICE AS RETAIL_PRICE,
  DSG_SHIP_VIA AS DSG_SHIP_VIA,
  LINE_TOTAL AS LINE_TOTAL,
  ADDR_VALID AS ADDR_VALID,
  REASON_ID AS REASON_ID,
  ORDER_FULFILLMENT_OPTION AS ORDER_FULFILLMENT_OPTION,
  IS_RETURNABLE AS IS_RETURNABLE,
  BACK_ORD_REASON AS BACK_ORD_REASON,
  PRICE_OVERRIDE AS PRICE_OVERRIDE,
  ORIGINAL_PRICE AS ORIGINAL_PRICE,
  EXT_CREATED_DTTM AS EXT_CREATED_DTTM,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  IS_EXCHANGEABLE AS IS_EXCHANGEABLE,
  ORIGINAL_PO_LINE_ITEM_ID AS ORIGINAL_PO_LINE_ITEM_ID,
  LOAD_TSTMP AS LOAD_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_PRE_0"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("SQ_Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_PRE_1")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_2


query_2 = f"""SELECT
  OMS_PURCHASE_ORDERS_ID AS OMS_PURCHASE_ORDERS_ID,
  OMS_PURCHASE_ORDERS_LINE_ITEM_ID AS OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
  OMS_TC_PO_LINE_ID AS OMS_TC_PO_LINE_ID,
  OMS_PARENT_PO_LINE_ITEM_ID AS OMS_PARENT_PO_LINE_ITEM_ID,
  OMS_ORIGINAL_PO_LINE_ITEM_ID AS OMS_ORIGINAL_PO_LINE_ITEM_ID,
  OMS_PURCHASE_ORDERS_LINE_STATUS_ID AS OMS_PURCHASE_ORDERS_LINE_STATUS_ID,
  ORDER_FULFILLMENT_OPTION_ID AS ORDER_FULFILLMENT_OPTION_ID,
  SKU AS SKU,
  CUST_SKU AS CUST_SKU,
  OMS_PRODUCT_CLASS_ID AS OMS_PRODUCT_CLASS_ID,
  RETURNABLE_FLAG AS RETURNABLE_FLAG,
  EXCHANGEABLE_FLAG AS EXCHANGEABLE_FLAG,
  PRICE_OVERRIDE_FLAG AS PRICE_OVERRIDE_FLAG,
  OMS_STORE_FACILITY_ALIAS_ID AS OMS_STORE_FACILITY_ALIAS_ID,
  OMS_STORE_FACILITY_ID AS OMS_STORE_FACILITY_ID,
  OMS_O_FACILITY_ID AS OMS_O_FACILITY_ID,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  OMS_BILL_FACILITY_ALIAS_ID AS OMS_BILL_FACILITY_ALIAS_ID,
  OMS_BILL_FACILITY_ID AS OMS_BILL_FACILITY_ID,
  OMS_D_FACILITY_ID AS OMS_D_FACILITY_ID,
  OMS_D_FACILITY_ALIAS_ID AS OMS_D_FACILITY_ALIAS_ID,
  D_FIRST_NAME AS D_FIRST_NAME,
  D_LAST_NAME AS D_LAST_NAME,
  D_ADDR_1 AS D_ADDR_1,
  D_ADDR_2 AS D_ADDR_2,
  D_ADDR_3 AS D_ADDR_3,
  D_CITY AS D_CITY,
  D_STATE_PROV AS D_STATE_PROV,
  D_POSTAL_CD AS D_POSTAL_CD,
  D_COUNTY AS D_COUNTY,
  D_COUNTRY_CD AS D_COUNTRY_CD,
  D_PHONE_NBR AS D_PHONE_NBR,
  D_EMAIL AS D_EMAIL,
  ADDR_VALID_FLAG AS ADDR_VALID_FLAG,
  OMS_ALLOC_FINALIZER AS OMS_ALLOC_FINALIZER,
  OMS_DSG_CARRIER_ID AS OMS_DSG_CARRIER_ID,
  DSG_SHIP_VIA AS DSG_SHIP_VIA,
  DO_CREATED_FLAG AS DO_CREATED_FLAG,
  READY_TO_SHIP_FLAG AS READY_TO_SHIP_FLAG,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  CLOSED_FLAG AS CLOSED_FLAG,
  DELETED_FLAG AS DELETED_FLAG,
  OMS_REASON_ID AS OMS_REASON_ID,
  OMS_REASON_CODES_GROUP_ID AS OMS_REASON_CODES_GROUP_ID,
  OMS_BACK_ORD_REASON_ID AS OMS_BACK_ORD_REASON_ID,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PICKUP_TZ_ID AS OMS_PICKUP_TZ_ID,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_DELIVERY_TZ_ID AS OMS_DELIVERY_TZ_ID,
  OMS_REQ_DLVR_TSTMP AS OMS_REQ_DLVR_TSTMP,
  OMS_MUST_DLVR_TSTMP AS OMS_MUST_DLVR_TSTMP,
  OMS_SHIP_BY_DT AS OMS_SHIP_BY_DT,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  ORDER_QTY AS ORDER_QTY,
  CANCELLED_QTY AS CANCELLED_QTY,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  RELEASED_QTY AS RELEASED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  PPACK_QTY AS PPACK_QTY,
  SHIPPED_QTY AS SHIPPED_QTY,
  ORIGINAL_PRICE_AMT AS ORIGINAL_PRICE_AMT,
  RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  UNIT_TAX_AMT AS UNIT_TAX_AMT,
  LINE_TOTAL_AMT AS LINE_TOTAL_AMT,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  OMS_EXT_CREATED_TSTMP AS OMS_EXT_CREATED_TSTMP,
  OMS_CREATED_SOURCE_TYPE_ID AS OMS_CREATED_SOURCE_TYPE_ID,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_PURCHASE_ORDERS_LINE_ITEM"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_2")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_3


query_3 = f"""SELECT
  OMS_PURCHASE_ORDERS_ID AS OMS_PURCHASE_ORDERS_ID,
  OMS_PURCHASE_ORDERS_LINE_ITEM_ID AS OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
  OMS_TC_PO_LINE_ID AS OMS_TC_PO_LINE_ID,
  OMS_PARENT_PO_LINE_ITEM_ID AS OMS_PARENT_PO_LINE_ITEM_ID,
  OMS_ORIGINAL_PO_LINE_ITEM_ID AS OMS_ORIGINAL_PO_LINE_ITEM_ID,
  OMS_PURCHASE_ORDERS_LINE_STATUS_ID AS OMS_PURCHASE_ORDERS_LINE_STATUS_ID,
  ORDER_FULFILLMENT_OPTION_ID AS ORDER_FULFILLMENT_OPTION_ID,
  SKU AS SKU,
  CUST_SKU AS CUST_SKU,
  OMS_PRODUCT_CLASS_ID AS OMS_PRODUCT_CLASS_ID,
  RETURNABLE_FLAG AS RETURNABLE_FLAG,
  EXCHANGEABLE_FLAG AS EXCHANGEABLE_FLAG,
  PRICE_OVERRIDE_FLAG AS PRICE_OVERRIDE_FLAG,
  OMS_STORE_FACILITY_ALIAS_ID AS OMS_STORE_FACILITY_ALIAS_ID,
  OMS_STORE_FACILITY_ID AS OMS_STORE_FACILITY_ID,
  OMS_O_FACILITY_ID AS OMS_O_FACILITY_ID,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  OMS_BILL_FACILITY_ALIAS_ID AS OMS_BILL_FACILITY_ALIAS_ID,
  OMS_BILL_FACILITY_ID AS OMS_BILL_FACILITY_ID,
  OMS_D_FACILITY_ID AS OMS_D_FACILITY_ID,
  OMS_D_FACILITY_ALIAS_ID AS OMS_D_FACILITY_ALIAS_ID,
  D_FIRST_NAME AS D_FIRST_NAME,
  D_LAST_NAME AS D_LAST_NAME,
  D_ADDR_1 AS D_ADDR_1,
  D_ADDR_2 AS D_ADDR_2,
  D_ADDR_3 AS D_ADDR_3,
  D_CITY AS D_CITY,
  D_STATE_PROV AS D_STATE_PROV,
  D_POSTAL_CD AS D_POSTAL_CD,
  D_COUNTY AS D_COUNTY,
  D_COUNTRY_CD AS D_COUNTRY_CD,
  D_PHONE_NBR AS D_PHONE_NBR,
  D_EMAIL AS D_EMAIL,
  ADDR_VALID_FLAG AS ADDR_VALID_FLAG,
  OMS_ALLOC_FINALIZER AS OMS_ALLOC_FINALIZER,
  OMS_DSG_CARRIER_ID AS OMS_DSG_CARRIER_ID,
  DSG_SHIP_VIA AS DSG_SHIP_VIA,
  DO_CREATED_FLAG AS DO_CREATED_FLAG,
  READY_TO_SHIP_FLAG AS READY_TO_SHIP_FLAG,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  CLOSED_FLAG AS CLOSED_FLAG,
  DELETED_FLAG AS DELETED_FLAG,
  OMS_REASON_ID AS OMS_REASON_ID,
  OMS_REASON_CODES_GROUP_ID AS OMS_REASON_CODES_GROUP_ID,
  OMS_BACK_ORD_REASON_ID AS OMS_BACK_ORD_REASON_ID,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PICKUP_TZ_ID AS OMS_PICKUP_TZ_ID,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_DELIVERY_TZ_ID AS OMS_DELIVERY_TZ_ID,
  OMS_REQ_DLVR_TSTMP AS OMS_REQ_DLVR_TSTMP,
  OMS_MUST_DLVR_TSTMP AS OMS_MUST_DLVR_TSTMP,
  OMS_SHIP_BY_DT AS OMS_SHIP_BY_DT,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  ORDER_QTY AS ORDER_QTY,
  CANCELLED_QTY AS CANCELLED_QTY,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  RELEASED_QTY AS RELEASED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  PPACK_QTY AS PPACK_QTY,
  SHIPPED_QTY AS SHIPPED_QTY,
  ORIGINAL_PRICE_AMT AS ORIGINAL_PRICE_AMT,
  RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  UNIT_TAX_AMT AS UNIT_TAX_AMT,
  LINE_TOTAL_AMT AS LINE_TOTAL_AMT,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  OMS_EXT_CREATED_TSTMP AS OMS_EXT_CREATED_TSTMP,
  OMS_CREATED_SOURCE_TYPE_ID AS OMS_CREATED_SOURCE_TYPE_ID,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_2"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("SQ_Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_3")

# COMMAND ----------
# DBTITLE 1, JNR_OMS_PURCHASE_ORDERS_LINE_ITEM_4


query_4 = f"""SELECT
  DETAIL.PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  DETAIL.PURCHASE_ORDERS_LINE_ITEM_ID AS PURCHASE_ORDERS_LINE_ITEM_ID,
  DETAIL.O_FACILITY_ID AS O_FACILITY_ID,
  DETAIL.O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  DETAIL.D_FACILITY_ID AS D_FACILITY_ID,
  DETAIL.D_FACILITY_ALIAS_ID AS D_FACILITY_ALIAS_ID,
  DETAIL.D_NAME AS D_NAME,
  DETAIL.D_LAST_NAME AS D_LAST_NAME,
  DETAIL.D_ADDRESS_1 AS D_ADDRESS_1,
  DETAIL.D_ADDRESS_2 AS D_ADDRESS_2,
  DETAIL.D_ADDRESS_3 AS D_ADDRESS_3,
  DETAIL.D_CITY AS D_CITY,
  DETAIL.D_STATE_PROV AS D_STATE_PROV,
  DETAIL.D_POSTAL_CODE AS D_POSTAL_CODE,
  DETAIL.D_COUNTY AS D_COUNTY,
  DETAIL.D_COUNTRY_CODE AS D_COUNTRY_CODE,
  DETAIL.D_PHONE_NUMBER AS D_PHONE_NUMBER,
  DETAIL.D_EMAIL AS D_EMAIL,
  DETAIL.BILL_FACILITY_ALIAS_ID AS BILL_FACILITY_ALIAS_ID,
  DETAIL.BILL_FACILITY_ID AS BILL_FACILITY_ID,
  DETAIL.STORE_FACILITY_ALIAS_ID AS STORE_FACILITY_ALIAS_ID,
  DETAIL.STORE_FACILITY_ID AS STORE_FACILITY_ID,
  DETAIL.SKU AS SKU,
  DETAIL.MV_CURRENCY_CODE AS MV_CURRENCY_CODE,
  DETAIL.TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  DETAIL.UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  DETAIL.UNIT_TAX_AMOUNT AS UNIT_TAX_AMOUNT,
  DETAIL.PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  DETAIL.ALLOCATED_QTY AS ALLOCATED_QTY,
  DETAIL.RELEASED_QTY AS RELEASED_QTY,
  DETAIL.CANCELLED_QTY AS CANCELLED_QTY,
  DETAIL.PPACK_QTY AS PPACK_QTY,
  DETAIL.DELIVERY_TZ AS DELIVERY_TZ,
  DETAIL.PICKUP_TZ AS PICKUP_TZ,
  DETAIL.PICKUP_START_DTTM AS PICKUP_START_DTTM,
  DETAIL.PICKUP_END_DTTM AS PICKUP_END_DTTM,
  DETAIL.DELIVERY_START_DTTM AS DELIVERY_START_DTTM,
  DETAIL.DELIVERY_END_DTTM AS DELIVERY_END_DTTM,
  DETAIL.REQ_DLVR_DTTM AS REQ_DLVR_DTTM,
  DETAIL.MUST_DLVR_DTTM AS MUST_DLVR_DTTM,
  DETAIL.SHIP_BY_DATE AS SHIP_BY_DATE,
  DETAIL.IS_READY_TO_SHIP AS IS_READY_TO_SHIP,
  DETAIL.IS_CANCELLED AS IS_CANCELLED,
  DETAIL.IS_CLOSED AS IS_CLOSED,
  DETAIL.IS_DELETED AS IS_DELETED,
  DETAIL.SHIPPED_QTY AS SHIPPED_QTY,
  DETAIL.RECEIVED_QTY AS RECEIVED_QTY,
  DETAIL.CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  DETAIL.CREATED_SOURCE AS CREATED_SOURCE,
  DETAIL.CREATED_DTTM AS CREATED_DTTM,
  DETAIL.LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  DETAIL.DSG_CARRIER_ID AS DSG_CARRIER_ID,
  DETAIL.PURCHASE_ORDERS_LINE_STATUS AS PURCHASE_ORDERS_LINE_STATUS,
  DETAIL.TC_PO_LINE_ID AS TC_PO_LINE_ID,
  DETAIL.PARENT_PO_LINE_ITEM_ID AS PARENT_PO_LINE_ITEM_ID,
  DETAIL.ORDER_QTY AS ORDER_QTY,
  DETAIL.ALLOC_FINALIZER AS ALLOC_FINALIZER,
  DETAIL.CUST_SKU AS CUST_SKU,
  DETAIL.IS_DO_CREATED AS IS_DO_CREATED,
  DETAIL.ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  DETAIL.RETAIL_PRICE AS RETAIL_PRICE,
  DETAIL.DSG_SHIP_VIA AS DSG_SHIP_VIA,
  DETAIL.LINE_TOTAL AS LINE_TOTAL,
  DETAIL.ADDR_VALID AS ADDR_VALID,
  DETAIL.REASON_ID AS REASON_ID,
  DETAIL.ORDER_FULFILLMENT_OPTION AS ORDER_FULFILLMENT_OPTION,
  DETAIL.IS_RETURNABLE AS IS_RETURNABLE,
  DETAIL.BACK_ORD_REASON AS BACK_ORD_REASON,
  DETAIL.PRICE_OVERRIDE AS PRICE_OVERRIDE,
  DETAIL.ORIGINAL_PRICE AS ORIGINAL_PRICE,
  DETAIL.EXT_CREATED_DTTM AS EXT_CREATED_DTTM,
  DETAIL.REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  DETAIL.IS_EXCHANGEABLE AS IS_EXCHANGEABLE,
  DETAIL.ORIGINAL_PO_LINE_ITEM_ID AS ORIGINAL_PO_LINE_ITEM_ID,
  MASTER.OMS_PURCHASE_ORDERS_ID AS lkp_OMS_PURCHASE_ORDERS_ID,
  MASTER.OMS_PURCHASE_ORDERS_LINE_ITEM_ID AS lkp_OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
  MASTER.OMS_TC_PO_LINE_ID AS lkp_OMS_TC_PO_LINE_ID,
  MASTER.OMS_PARENT_PO_LINE_ITEM_ID AS lkp_OMS_PARENT_PO_LINE_ITEM_ID,
  MASTER.OMS_ORIGINAL_PO_LINE_ITEM_ID AS lkp_OMS_ORIGINAL_PO_LINE_ITEM_ID,
  MASTER.OMS_PURCHASE_ORDERS_LINE_STATUS_ID AS lkp_OMS_PURCHASE_ORDERS_LINE_STATUS_ID,
  MASTER.ORDER_FULFILLMENT_OPTION_ID AS lkp_ORDER_FULFILLMENT_OPTION_ID,
  MASTER.SKU AS lkp_SKU1,
  MASTER.CUST_SKU AS lkp_CUST_SKU1,
  MASTER.OMS_PRODUCT_CLASS_ID AS lkp_OMS_PRODUCT_CLASS_ID,
  MASTER.RETURNABLE_FLAG AS lkp_RETURNABLE_FLAG,
  MASTER.EXCHANGEABLE_FLAG AS lkp_EXCHANGEABLE_FLAG,
  MASTER.PRICE_OVERRIDE_FLAG AS lkp_PRICE_OVERRIDE_FLAG,
  MASTER.OMS_STORE_FACILITY_ALIAS_ID AS lkp_OMS_STORE_FACILITY_ALIAS_ID,
  MASTER.OMS_STORE_FACILITY_ID AS lkp_OMS_STORE_FACILITY_ID,
  MASTER.OMS_O_FACILITY_ID AS lkp_OMS_O_FACILITY_ID,
  MASTER.OMS_O_FACILITY_ALIAS_ID AS lkp_OMS_O_FACILITY_ALIAS_ID,
  MASTER.OMS_BILL_FACILITY_ALIAS_ID AS lkp_OMS_BILL_FACILITY_ALIAS_ID,
  MASTER.OMS_BILL_FACILITY_ID AS lkp_OMS_BILL_FACILITY_ID,
  MASTER.OMS_D_FACILITY_ID AS lkp_OMS_D_FACILITY_ID,
  MASTER.OMS_D_FACILITY_ALIAS_ID AS lkp_OMS_D_FACILITY_ALIAS_ID,
  MASTER.D_FIRST_NAME AS lkp_D_FIRST_NAME,
  MASTER.D_LAST_NAME AS lkp_D_LAST_NAME1,
  MASTER.D_ADDR_1 AS lkp_D_ADDR_1,
  MASTER.D_ADDR_2 AS lkp_D_ADDR_2,
  MASTER.D_ADDR_3 AS lkp_D_ADDR_3,
  MASTER.D_CITY AS lkp_D_CITY1,
  MASTER.D_STATE_PROV AS lkp_D_STATE_PROV1,
  MASTER.D_POSTAL_CD AS lkp_D_POSTAL_CD,
  MASTER.D_COUNTY AS lkp_D_COUNTY1,
  MASTER.D_COUNTRY_CD AS lkp_D_COUNTRY_CD,
  MASTER.D_PHONE_NBR AS lkp_D_PHONE_NBR,
  MASTER.D_EMAIL AS lkp_D_EMAIL1,
  MASTER.ADDR_VALID_FLAG AS lkp_ADDR_VALID_FLAG,
  MASTER.OMS_ALLOC_FINALIZER AS lkp_OMS_ALLOC_FINALIZER,
  MASTER.OMS_DSG_CARRIER_ID AS lkp_OMS_DSG_CARRIER_ID,
  MASTER.DSG_SHIP_VIA AS lkp_DSG_SHIP_VIA1,
  MASTER.DO_CREATED_FLAG AS lkp_DO_CREATED_FLAG,
  MASTER.READY_TO_SHIP_FLAG AS lkp_READY_TO_SHIP_FLAG,
  MASTER.CANCELLED_FLAG AS lkp_CANCELLED_FLAG,
  MASTER.CLOSED_FLAG AS lkp_CLOSED_FLAG,
  MASTER.DELETED_FLAG AS lkp_DELETED_FLAG,
  MASTER.OMS_REASON_ID AS lkp_OMS_REASON_ID,
  MASTER.OMS_REASON_CODES_GROUP_ID AS lkp_OMS_REASON_CODES_GROUP_ID,
  MASTER.OMS_BACK_ORD_REASON_ID AS lkp_OMS_BACK_ORD_REASON_ID,
  MASTER.OMS_PICKUP_START_TSTMP AS lkp_OMS_PICKUP_START_TSTMP,
  MASTER.OMS_PICKUP_END_TSTMP AS lkp_OMS_PICKUP_END_TSTMP,
  MASTER.OMS_PICKUP_TZ_ID AS lkp_OMS_PICKUP_TZ_ID,
  MASTER.OMS_DELIVERY_START_TSTMP AS lkp_OMS_DELIVERY_START_TSTMP,
  MASTER.OMS_DELIVERY_END_TSTMP AS lkp_OMS_DELIVERY_END_TSTMP,
  MASTER.OMS_DELIVERY_TZ_ID AS lkp_OMS_DELIVERY_TZ_ID,
  MASTER.OMS_REQ_DLVR_TSTMP AS lkp_OMS_REQ_DLVR_TSTMP,
  MASTER.OMS_MUST_DLVR_TSTMP AS lkp_OMS_MUST_DLVR_TSTMP,
  MASTER.OMS_SHIP_BY_DT AS lkp_OMS_SHIP_BY_DT,
  MASTER.ORIG_ORDER_QTY AS lkp_ORIG_ORDER_QTY1,
  MASTER.ORDER_QTY AS lkp_ORDER_QTY1,
  MASTER.CANCELLED_QTY AS lkp_CANCELLED_QTY1,
  MASTER.ALLOCATED_QTY AS lkp_ALLOCATED_QTY1,
  MASTER.RELEASED_QTY AS lkp_RELEASED_QTY1,
  MASTER.RECEIVED_QTY AS lkp_RECEIVED_QTY1,
  MASTER.PPACK_QTY AS lkp_PPACK_QTY1,
  MASTER.SHIPPED_QTY AS lkp_SHIPPED_QTY1,
  MASTER.ORIGINAL_PRICE_AMT AS lkp_ORIGINAL_PRICE_AMT,
  MASTER.RETAIL_PRICE_AMT AS lkp_RETAIL_PRICE_AMT,
  MASTER.UNIT_TAX_AMT AS lkp_UNIT_TAX_AMT,
  MASTER.LINE_TOTAL_AMT AS lkp_LINE_TOTAL_AMT,
  MASTER.UNIT_MONETARY_VALUE AS lkp_UNIT_MONETARY_VALUE1,
  MASTER.TOTAL_MONETARY_VALUE AS lkp_TOTAL_MONETARY_VALUE1,
  MASTER.MV_CURRENCY_CD AS lkp_MV_CURRENCY_CD,
  MASTER.OMS_EXT_CREATED_TSTMP AS lkp_OMS_EXT_CREATED_TSTMP,
  MASTER.OMS_CREATED_SOURCE_TYPE_ID AS lkp_OMS_CREATED_SOURCE_TYPE_ID,
  MASTER.OMS_CREATED_SOURCE AS lkp_OMS_CREATED_SOURCE,
  MASTER.OMS_CREATED_TSTMP AS lkp_OMS_CREATED_TSTMP,
  MASTER.OMS_LAST_UPDATED_TSTMP AS lkp_OMS_LAST_UPDATED_TSTMP,
  MASTER.LOAD_TSTMP AS lkp_LOAD_TSTMP,
  DETAIL.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_3 MASTER
  RIGHT JOIN SQ_Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_PRE_1 DETAIL ON MASTER.OMS_PURCHASE_ORDERS_ID = DETAIL.PURCHASE_ORDERS_ID
  AND MASTER.OMS_PURCHASE_ORDERS_LINE_ITEM_ID = DETAIL.PURCHASE_ORDERS_LINE_ITEM_ID"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("JNR_OMS_PURCHASE_ORDERS_LINE_ITEM_4")

# COMMAND ----------
# DBTITLE 1, EXP_FLAG_5


query_5 = f"""SELECT
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  PURCHASE_ORDERS_LINE_ITEM_ID AS PURCHASE_ORDERS_LINE_ITEM_ID,
  O_FACILITY_ID AS O_FACILITY_ID,
  O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  D_FACILITY_ID AS D_FACILITY_ID,
  D_FACILITY_ALIAS_ID AS D_FACILITY_ALIAS_ID,
  D_NAME AS D_NAME,
  D_LAST_NAME AS D_LAST_NAME,
  D_ADDRESS_1 AS D_ADDRESS_1,
  D_ADDRESS_2 AS D_ADDRESS_2,
  D_ADDRESS_3 AS D_ADDRESS_3,
  D_CITY AS D_CITY,
  D_STATE_PROV AS D_STATE_PROV,
  D_POSTAL_CODE AS D_POSTAL_CODE,
  D_COUNTY AS D_COUNTY,
  D_COUNTRY_CODE AS D_COUNTRY_CODE,
  D_PHONE_NUMBER AS D_PHONE_NUMBER,
  D_EMAIL AS D_EMAIL,
  BILL_FACILITY_ALIAS_ID AS BILL_FACILITY_ALIAS_ID,
  BILL_FACILITY_ID AS BILL_FACILITY_ID,
  STORE_FACILITY_ALIAS_ID AS STORE_FACILITY_ALIAS_ID,
  STORE_FACILITY_ID AS STORE_FACILITY_ID,
  SKU AS SKU,
  MV_CURRENCY_CODE AS MV_CURRENCY_CODE,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  UNIT_TAX_AMOUNT AS UNIT_TAX_AMOUNT,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  RELEASED_QTY AS RELEASED_QTY,
  CANCELLED_QTY AS CANCELLED_QTY,
  PPACK_QTY AS PPACK_QTY,
  DELIVERY_TZ AS DELIVERY_TZ,
  PICKUP_TZ AS PICKUP_TZ,
  PICKUP_START_DTTM AS PICKUP_START_DTTM,
  PICKUP_END_DTTM AS PICKUP_END_DTTM,
  DELIVERY_START_DTTM AS DELIVERY_START_DTTM,
  DELIVERY_END_DTTM AS DELIVERY_END_DTTM,
  REQ_DLVR_DTTM AS REQ_DLVR_DTTM,
  MUST_DLVR_DTTM AS MUST_DLVR_DTTM,
  SHIP_BY_DATE AS SHIP_BY_DATE,
  IS_READY_TO_SHIP AS IS_READY_TO_SHIP,
  IS_CANCELLED AS IS_CANCELLED,
  IS_CLOSED AS IS_CLOSED,
  IS_DELETED AS IS_DELETED,
  SHIPPED_QTY AS SHIPPED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  DSG_CARRIER_ID AS DSG_CARRIER_ID,
  PURCHASE_ORDERS_LINE_STATUS AS PURCHASE_ORDERS_LINE_STATUS,
  TC_PO_LINE_ID AS TC_PO_LINE_ID,
  PARENT_PO_LINE_ITEM_ID AS PARENT_PO_LINE_ITEM_ID,
  ORDER_QTY AS ORDER_QTY,
  ALLOC_FINALIZER AS ALLOC_FINALIZER,
  CUST_SKU AS CUST_SKU,
  IS_DO_CREATED AS IS_DO_CREATED,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  RETAIL_PRICE AS RETAIL_PRICE,
  DSG_SHIP_VIA AS DSG_SHIP_VIA,
  LINE_TOTAL AS LINE_TOTAL,
  ADDR_VALID AS ADDR_VALID,
  REASON_ID AS REASON_ID,
  ORDER_FULFILLMENT_OPTION AS ORDER_FULFILLMENT_OPTION,
  IS_RETURNABLE AS IS_RETURNABLE,
  BACK_ORD_REASON AS BACK_ORD_REASON,
  PRICE_OVERRIDE AS PRICE_OVERRIDE,
  ORIGINAL_PRICE AS ORIGINAL_PRICE,
  EXT_CREATED_DTTM AS EXT_CREATED_DTTM,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  IS_EXCHANGEABLE AS IS_EXCHANGEABLE,
  ORIGINAL_PO_LINE_ITEM_ID AS ORIGINAL_PO_LINE_ITEM_ID,
  IFF(
    ISNULL(lkp_OMS_PURCHASE_ORDERS_LINE_ITEM_ID),
    'INSERT',
    IFF(
      (
        (
          IFF(
            ISNULL(PICKUP_START_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            PICKUP_START_DTTM
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_PICKUP_START_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            lkp_OMS_PICKUP_START_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(PICKUP_END_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            PICKUP_END_DTTM
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_PICKUP_END_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            lkp_OMS_PICKUP_END_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(DELIVERY_START_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            DELIVERY_START_DTTM
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_DELIVERY_START_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            lkp_OMS_DELIVERY_START_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(DELIVERY_END_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            DELIVERY_END_DTTM
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_DELIVERY_END_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            lkp_OMS_DELIVERY_END_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(REQ_DLVR_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            REQ_DLVR_DTTM
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_REQ_DLVR_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            lkp_OMS_REQ_DLVR_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(MUST_DLVR_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            MUST_DLVR_DTTM
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_MUST_DLVR_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            lkp_OMS_MUST_DLVR_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(SHIP_BY_DATE),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            SHIP_BY_DATE
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_SHIP_BY_DT),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            lkp_OMS_SHIP_BY_DT
          )
        )
        OR (
          IFF(
            ISNULL(CREATED_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            CREATED_DTTM
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_CREATED_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            lkp_OMS_CREATED_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(LAST_UPDATED_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            LAST_UPDATED_DTTM
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_LAST_UPDATED_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            lkp_OMS_LAST_UPDATED_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(EXT_CREATED_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            EXT_CREATED_DTTM
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_EXT_CREATED_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            lkp_OMS_EXT_CREATED_TSTMP
          )
        )
        OR (
          IFF(ISNULL(PURCHASE_ORDERS_ID), 99, PURCHASE_ORDERS_ID)
        ) != (
          IFF(
            ISNULL(lkp_OMS_PURCHASE_ORDERS_ID),
            99,
            lkp_OMS_PURCHASE_ORDERS_ID
          )
        )
        OR (
          IFF(
            ISNULL(PURCHASE_ORDERS_LINE_ITEM_ID),
            99,
            PURCHASE_ORDERS_LINE_ITEM_ID
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_PURCHASE_ORDERS_LINE_ITEM_ID),
            99,
            lkp_OMS_PURCHASE_ORDERS_LINE_ITEM_ID
          )
        )
        OR (IFF(ISNULL(O_FACILITY_ID), 99, O_FACILITY_ID)) != (
          IFF(
            ISNULL(lkp_OMS_O_FACILITY_ID),
            99,
            lkp_OMS_O_FACILITY_ID
          )
        )
        OR (IFF(ISNULL(D_FACILITY_ID), 99, D_FACILITY_ID)) != (
          IFF(
            ISNULL(lkp_OMS_D_FACILITY_ID),
            99,
            lkp_OMS_D_FACILITY_ID
          )
        )
        OR (
          IFF(ISNULL(BILL_FACILITY_ID), 99, BILL_FACILITY_ID)
        ) != (
          IFF(
            ISNULL(lkp_OMS_BILL_FACILITY_ID),
            99,
            lkp_OMS_BILL_FACILITY_ID
          )
        )
        OR (
          IFF(ISNULL(STORE_FACILITY_ID), 99, STORE_FACILITY_ID)
        ) != (
          IFF(
            ISNULL(lkp_OMS_STORE_FACILITY_ID),
            99,
            lkp_OMS_STORE_FACILITY_ID
          )
        )
        OR (
          IFF(
            ISNULL(TOTAL_MONETARY_VALUE),
            99,
            TOTAL_MONETARY_VALUE
          )
        ) != (
          IFF(
            ISNULL(lkp_TOTAL_MONETARY_VALUE1),
            99,
            lkp_TOTAL_MONETARY_VALUE1
          )
        )
        OR (
          IFF(
            ISNULL(UNIT_MONETARY_VALUE),
            99,
            UNIT_MONETARY_VALUE
          )
        ) != (
          IFF(
            ISNULL(lkp_UNIT_MONETARY_VALUE1),
            99,
            lkp_UNIT_MONETARY_VALUE1
          )
        )
        OR (IFF(ISNULL(UNIT_TAX_AMOUNT), 99, UNIT_TAX_AMOUNT)) != (
          IFF(ISNULL(lkp_UNIT_TAX_AMT), 99, lkp_UNIT_TAX_AMT)
        )
        OR (
          IFF(ISNULL(PRODUCT_CLASS_ID), 99, PRODUCT_CLASS_ID)
        ) != (
          IFF(
            ISNULL(lkp_OMS_PRODUCT_CLASS_ID),
            99,
            lkp_OMS_PRODUCT_CLASS_ID
          )
        )
        OR (IFF(ISNULL(ALLOCATED_QTY), 99, ALLOCATED_QTY)) != (
          IFF(ISNULL(lkp_ALLOCATED_QTY1), 99, lkp_ALLOCATED_QTY1)
        )
        OR (IFF(ISNULL(RELEASED_QTY), 99, RELEASED_QTY)) != (
          IFF(ISNULL(lkp_RELEASED_QTY1), 99, lkp_RELEASED_QTY1)
        )
        OR (IFF(ISNULL(CANCELLED_QTY), 99, CANCELLED_QTY)) != (
          IFF(ISNULL(lkp_CANCELLED_QTY1), 99, lkp_CANCELLED_QTY1)
        )
        OR (IFF(ISNULL(PPACK_QTY), 99, PPACK_QTY)) != (IFF(ISNULL(lkp_PPACK_QTY1), 99, lkp_PPACK_QTY1))
        OR (IFF(ISNULL(DELIVERY_TZ), 99, DELIVERY_TZ)) != (
          IFF(
            ISNULL(lkp_OMS_DELIVERY_TZ_ID),
            99,
            lkp_OMS_DELIVERY_TZ_ID
          )
        )
        OR (IFF(ISNULL(PICKUP_TZ), 99, PICKUP_TZ)) != (
          IFF(
            ISNULL(lkp_OMS_PICKUP_TZ_ID),
            99,
            lkp_OMS_PICKUP_TZ_ID
          )
        )
        OR (
          IFF(ISNULL(IS_READY_TO_SHIP), 99, IS_READY_TO_SHIP)
        ) != (
          IFF(
            ISNULL(lkp_READY_TO_SHIP_FLAG),
            99,
            lkp_READY_TO_SHIP_FLAG
          )
        )
        OR (IFF(ISNULL(IS_CANCELLED), 99, IS_CANCELLED)) != (
          IFF(ISNULL(lkp_CANCELLED_FLAG), 99, lkp_CANCELLED_FLAG)
        )
        OR (IFF(ISNULL(IS_CLOSED), 99, IS_CLOSED)) != (IFF(ISNULL(lkp_CLOSED_FLAG), 99, lkp_CLOSED_FLAG))
        OR (IFF(ISNULL(IS_DELETED), 99, IS_DELETED)) != (
          IFF(ISNULL(lkp_DELETED_FLAG), 99, lkp_DELETED_FLAG)
        )
        OR (IFF(ISNULL(SHIPPED_QTY), 99, SHIPPED_QTY)) != (
          IFF(ISNULL(lkp_SHIPPED_QTY1), 99, lkp_SHIPPED_QTY1)
        )
        OR (IFF(ISNULL(RECEIVED_QTY), 99, RECEIVED_QTY)) != (
          IFF(ISNULL(lkp_RECEIVED_QTY1), 99, lkp_RECEIVED_QTY1)
        )
        OR (
          IFF(
            ISNULL(CREATED_SOURCE_TYPE),
            99,
            CREATED_SOURCE_TYPE
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_CREATED_SOURCE_TYPE_ID),
            99,
            lkp_OMS_CREATED_SOURCE_TYPE_ID
          )
        )
        OR (IFF(ISNULL(DSG_CARRIER_ID), 99, DSG_CARRIER_ID)) != (
          IFF(
            ISNULL(lkp_OMS_DSG_CARRIER_ID),
            99,
            lkp_OMS_DSG_CARRIER_ID
          )
        )
        OR (
          IFF(
            ISNULL(PURCHASE_ORDERS_LINE_STATUS),
            99,
            PURCHASE_ORDERS_LINE_STATUS
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_PURCHASE_ORDERS_LINE_STATUS_ID),
            99,
            lkp_OMS_PURCHASE_ORDERS_LINE_STATUS_ID
          )
        )
        OR (
          IFF(
            ISNULL(PARENT_PO_LINE_ITEM_ID),
            99,
            PARENT_PO_LINE_ITEM_ID
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_PARENT_PO_LINE_ITEM_ID),
            99,
            lkp_OMS_PARENT_PO_LINE_ITEM_ID
          )
        )
        OR (IFF(ISNULL(ORDER_QTY), 99, ORDER_QTY)) != (IFF(ISNULL(lkp_ORDER_QTY1), 99, lkp_ORDER_QTY1))
        OR (IFF(ISNULL(IS_DO_CREATED), 99, IS_DO_CREATED)) != (
          IFF(
            ISNULL(lkp_DO_CREATED_FLAG),
            99,
            lkp_DO_CREATED_FLAG
          )
        )
        OR (IFF(ISNULL(ORIG_ORDER_QTY), 99, ORIG_ORDER_QTY)) != (
          IFF(
            ISNULL(lkp_ORIG_ORDER_QTY1),
            99,
            lkp_ORIG_ORDER_QTY1
          )
        )
        OR (IFF(ISNULL(RETAIL_PRICE), 99, RETAIL_PRICE)) != (
          IFF(
            ISNULL(lkp_RETAIL_PRICE_AMT),
            99,
            lkp_RETAIL_PRICE_AMT
          )
        )
        OR (IFF(ISNULL(LINE_TOTAL), 99, LINE_TOTAL)) != (
          IFF(ISNULL(lkp_LINE_TOTAL_AMT), 99, lkp_LINE_TOTAL_AMT)
        )
        OR (IFF(ISNULL(REASON_ID), 99, REASON_ID)) != (
          IFF(ISNULL(lkp_OMS_REASON_ID), 99, lkp_OMS_REASON_ID)
        )
        OR (IFF(ISNULL(IS_RETURNABLE), 99, IS_RETURNABLE)) != (
          IFF(
            ISNULL(lkp_RETURNABLE_FLAG),
            99,
            lkp_RETURNABLE_FLAG
          )
        )
        OR (IFF(ISNULL(PRICE_OVERRIDE), 99, PRICE_OVERRIDE)) != (
          IFF(
            ISNULL(lkp_PRICE_OVERRIDE_FLAG),
            99,
            lkp_PRICE_OVERRIDE_FLAG
          )
        )
        OR (IFF(ISNULL(ORIGINAL_PRICE), 99, ORIGINAL_PRICE)) != (
          IFF(
            ISNULL(lkp_ORIGINAL_PRICE_AMT),
            99,
            lkp_ORIGINAL_PRICE_AMT
          )
        )
        OR (
          IFF(
            ISNULL(REASON_CODES_GROUP_ID),
            99,
            REASON_CODES_GROUP_ID
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_REASON_CODES_GROUP_ID),
            99,
            lkp_OMS_REASON_CODES_GROUP_ID
          )
        )
        OR (IFF(ISNULL(IS_EXCHANGEABLE), 99, IS_EXCHANGEABLE)) != (
          IFF(
            ISNULL(lkp_EXCHANGEABLE_FLAG),
            99,
            lkp_EXCHANGEABLE_FLAG
          )
        )
        OR (
          IFF(
            ISNULL(ORIGINAL_PO_LINE_ITEM_ID),
            99,
            ORIGINAL_PO_LINE_ITEM_ID
          )
        ) != (
          IFF(
            ISNULL(lkp_OMS_ORIGINAL_PO_LINE_ITEM_ID),
            99,
            lkp_OMS_ORIGINAL_PO_LINE_ITEM_ID
          )
        )
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(O_FACILITY_ALIAS_ID),
              ' ',
              O_FACILITY_ALIAS_ID
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_OMS_O_FACILITY_ALIAS_ID),
              ' ',
              lkp_OMS_O_FACILITY_ALIAS_ID
            )
          )
        )
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(D_FACILITY_ALIAS_ID),
              ' ',
              D_FACILITY_ALIAS_ID
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_OMS_D_FACILITY_ALIAS_ID),
              ' ',
              lkp_OMS_D_FACILITY_ALIAS_ID
            )
          )
        )
        OR LTRIM(RTRIM(IFF(ISNULL(D_NAME), ' ', D_NAME))) != LTRIM(
          RTRIM(
            IFF(ISNULL(lkp_D_FIRST_NAME), ' ', lkp_D_FIRST_NAME)
          )
        )
        OR LTRIM(RTRIM(IFF(ISNULL(D_LAST_NAME), ' ', D_LAST_NAME))) != LTRIM(
          RTRIM(
            IFF(ISNULL(lkp_D_LAST_NAME1), ' ', lkp_D_LAST_NAME1)
          )
        )
        OR LTRIM(RTRIM(IFF(ISNULL(D_ADDRESS_1), ' ', D_ADDRESS_1))) != LTRIM(
          RTRIM(IFF(ISNULL(lkp_D_ADDR_1), ' ', lkp_D_ADDR_1))
        )
        OR LTRIM(RTRIM(IFF(ISNULL(D_ADDRESS_2), ' ', D_ADDRESS_2))) != LTRIM(
          RTRIM(IFF(ISNULL(lkp_D_ADDR_2), ' ', lkp_D_ADDR_2))
        )
        OR LTRIM(RTRIM(IFF(ISNULL(D_ADDRESS_3), ' ', D_ADDRESS_3))) != LTRIM(
          RTRIM(IFF(ISNULL(lkp_D_ADDR_3), ' ', lkp_D_ADDR_3))
        )
        OR LTRIM(RTRIM(IFF(ISNULL(D_CITY), ' ', D_CITY))) != LTRIM(RTRIM(IFF(ISNULL(lkp_D_CITY1), ' ', lkp_D_CITY1)))
        OR LTRIM(
          RTRIM(IFF(ISNULL(D_STATE_PROV), ' ', D_STATE_PROV))
        ) != LTRIM(
          RTRIM(
            IFF(ISNULL(lkp_D_STATE_PROV1), ' ', lkp_D_STATE_PROV1)
          )
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(D_POSTAL_CODE), ' ', D_POSTAL_CODE))
        ) != LTRIM(
          RTRIM(IFF(ISNULL(lkp_D_POSTAL_CD), ' ', lkp_D_POSTAL_CD))
        )
        OR LTRIM(RTRIM(IFF(ISNULL(D_COUNTY), ' ', D_COUNTY))) != LTRIM(
          RTRIM(IFF(ISNULL(lkp_D_COUNTY1), ' ', lkp_D_COUNTY1))
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(D_COUNTRY_CODE), ' ', D_COUNTRY_CODE))
        ) != LTRIM(
          RTRIM(
            IFF(ISNULL(lkp_D_COUNTRY_CD), ' ', lkp_D_COUNTRY_CD)
          )
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(D_PHONE_NUMBER), ' ', D_PHONE_NUMBER))
        ) != LTRIM(
          RTRIM(IFF(ISNULL(lkp_D_PHONE_NBR), ' ', lkp_D_PHONE_NBR))
        )
        OR LTRIM(RTRIM(IFF(ISNULL(D_EMAIL), ' ', D_EMAIL))) != LTRIM(
          RTRIM(IFF(ISNULL(lkp_D_EMAIL1), ' ', lkp_D_EMAIL1))
        )
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(BILL_FACILITY_ALIAS_ID),
              ' ',
              BILL_FACILITY_ALIAS_ID
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_OMS_BILL_FACILITY_ALIAS_ID),
              ' ',
              lkp_OMS_BILL_FACILITY_ALIAS_ID
            )
          )
        )
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(STORE_FACILITY_ALIAS_ID),
              ' ',
              STORE_FACILITY_ALIAS_ID
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_OMS_STORE_FACILITY_ALIAS_ID),
              ' ',
              lkp_OMS_STORE_FACILITY_ALIAS_ID
            )
          )
        )
        OR LTRIM(RTRIM(IFF(ISNULL(SKU), ' ', SKU))) != LTRIM(RTRIM(IFF(ISNULL(lkp_SKU1), ' ', lkp_SKU1)))
        OR LTRIM(
          RTRIM(
            IFF(ISNULL(MV_CURRENCY_CODE), ' ', MV_CURRENCY_CODE)
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_MV_CURRENCY_CD),
              ' ',
              lkp_MV_CURRENCY_CD
            )
          )
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(CREATED_SOURCE), ' ', CREATED_SOURCE))
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_OMS_CREATED_SOURCE),
              ' ',
              lkp_OMS_CREATED_SOURCE
            )
          )
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(TC_PO_LINE_ID), ' ', TC_PO_LINE_ID))
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_OMS_TC_PO_LINE_ID),
              ' ',
              lkp_OMS_TC_PO_LINE_ID
            )
          )
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(ALLOC_FINALIZER), ' ', ALLOC_FINALIZER))
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_OMS_ALLOC_FINALIZER),
              ' ',
              lkp_OMS_ALLOC_FINALIZER
            )
          )
        )
        OR LTRIM(RTRIM(IFF(ISNULL(CUST_SKU), ' ', CUST_SKU))) != LTRIM(
          RTRIM(IFF(ISNULL(lkp_CUST_SKU1), ' ', lkp_CUST_SKU1))
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(DSG_SHIP_VIA), ' ', DSG_SHIP_VIA))
        ) != LTRIM(
          RTRIM(
            IFF(ISNULL(lkp_DSG_SHIP_VIA1), ' ', lkp_DSG_SHIP_VIA1)
          )
        )
        OR LTRIM(RTRIM(IFF(ISNULL(ADDR_VALID), ' ', ADDR_VALID))) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_ADDR_VALID_FLAG),
              ' ',
              lkp_ADDR_VALID_FLAG
            )
          )
        )
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(ORDER_FULFILLMENT_OPTION),
              ' ',
              ORDER_FULFILLMENT_OPTION
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_ORDER_FULFILLMENT_OPTION_ID),
              ' ',
              lkp_ORDER_FULFILLMENT_OPTION_ID
            )
          )
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(BACK_ORD_REASON), ' ', BACK_ORD_REASON))
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_OMS_BACK_ORD_REASON_ID),
              ' ',
              lkp_OMS_BACK_ORD_REASON_ID
            )
          )
        )
      ),
      'UPDATE',
      'REJECT'
    )
  ) AS o_UPDATE_FLAG,
  now() AS o_UPDATE_TSTMP,
  IFF(ISNULL(lkp_LOAD_TSTMP), now(), lkp_LOAD_TSTMP) AS o_LOAD_TSTMP,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  JNR_OMS_PURCHASE_ORDERS_LINE_ITEM_4"""

df_5 = spark.sql(query_5)

df_5.createOrReplaceTempView("EXP_FLAG_5")

# COMMAND ----------
# DBTITLE 1, FIL_FLAG_6


query_6 = f"""SELECT
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  PURCHASE_ORDERS_LINE_ITEM_ID AS PURCHASE_ORDERS_LINE_ITEM_ID,
  O_FACILITY_ID AS O_FACILITY_ID,
  O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  D_FACILITY_ID AS D_FACILITY_ID,
  D_FACILITY_ALIAS_ID AS D_FACILITY_ALIAS_ID,
  D_NAME AS D_NAME,
  D_LAST_NAME AS D_LAST_NAME,
  D_ADDRESS_1 AS D_ADDRESS_1,
  D_ADDRESS_2 AS D_ADDRESS_2,
  D_ADDRESS_3 AS D_ADDRESS_3,
  D_CITY AS D_CITY,
  D_STATE_PROV AS D_STATE_PROV,
  D_POSTAL_CODE AS D_POSTAL_CODE,
  D_COUNTY AS D_COUNTY,
  D_COUNTRY_CODE AS D_COUNTRY_CODE,
  D_PHONE_NUMBER AS D_PHONE_NUMBER,
  D_EMAIL AS D_EMAIL,
  BILL_FACILITY_ALIAS_ID AS BILL_FACILITY_ALIAS_ID,
  BILL_FACILITY_ID AS BILL_FACILITY_ID,
  STORE_FACILITY_ALIAS_ID AS STORE_FACILITY_ALIAS_ID,
  STORE_FACILITY_ID AS STORE_FACILITY_ID,
  SKU AS SKU,
  MV_CURRENCY_CODE AS MV_CURRENCY_CODE,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  UNIT_TAX_AMOUNT AS UNIT_TAX_AMOUNT,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  RELEASED_QTY AS RELEASED_QTY,
  CANCELLED_QTY AS CANCELLED_QTY,
  PPACK_QTY AS PPACK_QTY,
  DELIVERY_TZ AS DELIVERY_TZ,
  PICKUP_TZ AS PICKUP_TZ,
  PICKUP_START_DTTM AS PICKUP_START_DTTM,
  PICKUP_END_DTTM AS PICKUP_END_DTTM,
  DELIVERY_START_DTTM AS DELIVERY_START_DTTM,
  DELIVERY_END_DTTM AS DELIVERY_END_DTTM,
  REQ_DLVR_DTTM AS REQ_DLVR_DTTM,
  MUST_DLVR_DTTM AS MUST_DLVR_DTTM,
  SHIP_BY_DATE AS SHIP_BY_DATE,
  IS_READY_TO_SHIP AS IS_READY_TO_SHIP,
  IS_CANCELLED AS IS_CANCELLED,
  IS_CLOSED AS IS_CLOSED,
  IS_DELETED AS IS_DELETED,
  SHIPPED_QTY AS SHIPPED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  DSG_CARRIER_ID AS DSG_CARRIER_ID,
  PURCHASE_ORDERS_LINE_STATUS AS PURCHASE_ORDERS_LINE_STATUS,
  TC_PO_LINE_ID AS TC_PO_LINE_ID,
  PARENT_PO_LINE_ITEM_ID AS PARENT_PO_LINE_ITEM_ID,
  ORDER_QTY AS ORDER_QTY,
  ALLOC_FINALIZER AS ALLOC_FINALIZER,
  CUST_SKU AS CUST_SKU,
  IS_DO_CREATED AS IS_DO_CREATED,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  RETAIL_PRICE AS RETAIL_PRICE,
  DSG_SHIP_VIA AS DSG_SHIP_VIA,
  LINE_TOTAL AS LINE_TOTAL,
  ADDR_VALID AS ADDR_VALID,
  REASON_ID AS REASON_ID,
  ORDER_FULFILLMENT_OPTION AS ORDER_FULFILLMENT_OPTION,
  IS_RETURNABLE AS IS_RETURNABLE,
  BACK_ORD_REASON AS BACK_ORD_REASON,
  PRICE_OVERRIDE AS PRICE_OVERRIDE,
  ORIGINAL_PRICE AS ORIGINAL_PRICE,
  EXT_CREATED_DTTM AS EXT_CREATED_DTTM,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  IS_EXCHANGEABLE AS IS_EXCHANGEABLE,
  ORIGINAL_PO_LINE_ITEM_ID AS ORIGINAL_PO_LINE_ITEM_ID,
  o_UPDATE_FLAG AS o_UPDATE_FLAG,
  o_UPDATE_TSTMP AS o_UPDATE_TSTMP,
  o_LOAD_TSTMP AS o_LOAD_TSTMP,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  EXP_FLAG_5
WHERE
  IN(o_UPDATE_FLAG, 'INSERT', 'UPDATE')"""

df_6 = spark.sql(query_6)

df_6.createOrReplaceTempView("FIL_FLAG_6")

# COMMAND ----------
# DBTITLE 1, UPD_INSERT_UPDATE_7


query_7 = f"""SELECT
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  PURCHASE_ORDERS_LINE_ITEM_ID AS PURCHASE_ORDERS_LINE_ITEM_ID,
  O_FACILITY_ID AS O_FACILITY_ID,
  O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  D_FACILITY_ID AS D_FACILITY_ID,
  D_FACILITY_ALIAS_ID AS D_FACILITY_ALIAS_ID,
  D_NAME AS D_NAME,
  D_LAST_NAME AS D_LAST_NAME,
  D_ADDRESS_1 AS D_ADDRESS_1,
  D_ADDRESS_2 AS D_ADDRESS_2,
  D_ADDRESS_3 AS D_ADDRESS_3,
  D_CITY AS D_CITY,
  D_STATE_PROV AS D_STATE_PROV,
  D_POSTAL_CODE AS D_POSTAL_CODE,
  D_COUNTY AS D_COUNTY,
  D_COUNTRY_CODE AS D_COUNTRY_CODE,
  D_PHONE_NUMBER AS D_PHONE_NUMBER,
  D_EMAIL AS D_EMAIL,
  BILL_FACILITY_ALIAS_ID AS BILL_FACILITY_ALIAS_ID,
  BILL_FACILITY_ID AS BILL_FACILITY_ID,
  STORE_FACILITY_ALIAS_ID AS STORE_FACILITY_ALIAS_ID,
  STORE_FACILITY_ID AS STORE_FACILITY_ID,
  SKU AS SKU,
  MV_CURRENCY_CODE AS MV_CURRENCY_CODE,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  UNIT_TAX_AMOUNT AS UNIT_TAX_AMOUNT,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  RELEASED_QTY AS RELEASED_QTY,
  CANCELLED_QTY AS CANCELLED_QTY,
  PPACK_QTY AS PPACK_QTY,
  DELIVERY_TZ AS DELIVERY_TZ,
  PICKUP_TZ AS PICKUP_TZ,
  PICKUP_START_DTTM AS PICKUP_START_DTTM,
  PICKUP_END_DTTM AS PICKUP_END_DTTM,
  DELIVERY_START_DTTM AS DELIVERY_START_DTTM,
  DELIVERY_END_DTTM AS DELIVERY_END_DTTM,
  REQ_DLVR_DTTM AS REQ_DLVR_DTTM,
  MUST_DLVR_DTTM AS MUST_DLVR_DTTM,
  SHIP_BY_DATE AS SHIP_BY_DATE,
  IS_READY_TO_SHIP AS IS_READY_TO_SHIP,
  IS_CANCELLED AS IS_CANCELLED,
  IS_CLOSED AS IS_CLOSED,
  IS_DELETED AS IS_DELETED,
  SHIPPED_QTY AS SHIPPED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  DSG_CARRIER_ID AS DSG_CARRIER_ID,
  PURCHASE_ORDERS_LINE_STATUS AS PURCHASE_ORDERS_LINE_STATUS,
  TC_PO_LINE_ID AS TC_PO_LINE_ID,
  PARENT_PO_LINE_ITEM_ID AS PARENT_PO_LINE_ITEM_ID,
  ORDER_QTY AS ORDER_QTY,
  ALLOC_FINALIZER AS ALLOC_FINALIZER,
  CUST_SKU AS CUST_SKU,
  IS_DO_CREATED AS IS_DO_CREATED,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  RETAIL_PRICE AS RETAIL_PRICE,
  DSG_SHIP_VIA AS DSG_SHIP_VIA,
  LINE_TOTAL AS LINE_TOTAL,
  ADDR_VALID AS ADDR_VALID,
  REASON_ID AS REASON_ID,
  ORDER_FULFILLMENT_OPTION AS ORDER_FULFILLMENT_OPTION,
  IS_RETURNABLE AS IS_RETURNABLE,
  BACK_ORD_REASON AS BACK_ORD_REASON,
  PRICE_OVERRIDE AS PRICE_OVERRIDE,
  ORIGINAL_PRICE AS ORIGINAL_PRICE,
  EXT_CREATED_DTTM AS EXT_CREATED_DTTM,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  IS_EXCHANGEABLE AS IS_EXCHANGEABLE,
  ORIGINAL_PO_LINE_ITEM_ID AS ORIGINAL_PO_LINE_ITEM_ID,
  o_UPDATE_FLAG AS o_UPDATE_FLAG,
  o_UPDATE_TSTMP AS o_UPDATE_TSTMP,
  o_LOAD_TSTMP AS o_LOAD_TSTMP,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id,
  IFF(o_UPDATE_FLAG = 'INSERT', 'DD_INSERT', 'DD_UPDATE') AS UPDATE_STRATEGY_FLAG
FROM
  FIL_FLAG_6"""

df_7 = spark.sql(query_7)

df_7.createOrReplaceTempView("UPD_INSERT_UPDATE_7")

# COMMAND ----------
# DBTITLE 1, OMS_PURCHASE_ORDERS_LINE_ITEM


spark.sql("""MERGE INTO OMS_PURCHASE_ORDERS_LINE_ITEM AS TARGET
USING
  UPD_INSERT_UPDATE_7 AS SOURCE ON TARGET.OMS_PURCHASE_ORDERS_LINE_ITEM_ID = SOURCE.PURCHASE_ORDERS_LINE_ITEM_ID
  AND TARGET.OMS_PURCHASE_ORDERS_ID = SOURCE.PURCHASE_ORDERS_ID
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_UPDATE" THEN
UPDATE
SET
  TARGET.OMS_PURCHASE_ORDERS_ID = SOURCE.PURCHASE_ORDERS_ID,
  TARGET.OMS_PURCHASE_ORDERS_LINE_ITEM_ID = SOURCE.PURCHASE_ORDERS_LINE_ITEM_ID,
  TARGET.OMS_TC_PO_LINE_ID = SOURCE.TC_PO_LINE_ID,
  TARGET.OMS_PARENT_PO_LINE_ITEM_ID = SOURCE.PARENT_PO_LINE_ITEM_ID,
  TARGET.OMS_ORIGINAL_PO_LINE_ITEM_ID = SOURCE.ORIGINAL_PO_LINE_ITEM_ID,
  TARGET.OMS_PURCHASE_ORDERS_LINE_STATUS_ID = SOURCE.PURCHASE_ORDERS_LINE_STATUS,
  TARGET.ORDER_FULFILLMENT_OPTION_ID = SOURCE.ORDER_FULFILLMENT_OPTION,
  TARGET.SKU = SOURCE.SKU,
  TARGET.CUST_SKU = SOURCE.CUST_SKU,
  TARGET.OMS_PRODUCT_CLASS_ID = SOURCE.PRODUCT_CLASS_ID,
  TARGET.RETURNABLE_FLAG = SOURCE.IS_RETURNABLE,
  TARGET.EXCHANGEABLE_FLAG = SOURCE.IS_EXCHANGEABLE,
  TARGET.PRICE_OVERRIDE_FLAG = SOURCE.PRICE_OVERRIDE,
  TARGET.OMS_STORE_FACILITY_ALIAS_ID = SOURCE.STORE_FACILITY_ALIAS_ID,
  TARGET.OMS_STORE_FACILITY_ID = SOURCE.STORE_FACILITY_ID,
  TARGET.OMS_O_FACILITY_ID = SOURCE.O_FACILITY_ID,
  TARGET.OMS_O_FACILITY_ALIAS_ID = SOURCE.O_FACILITY_ALIAS_ID,
  TARGET.OMS_BILL_FACILITY_ALIAS_ID = SOURCE.BILL_FACILITY_ALIAS_ID,
  TARGET.OMS_BILL_FACILITY_ID = SOURCE.BILL_FACILITY_ID,
  TARGET.OMS_D_FACILITY_ID = SOURCE.D_FACILITY_ID,
  TARGET.OMS_D_FACILITY_ALIAS_ID = SOURCE.D_FACILITY_ALIAS_ID,
  TARGET.D_FIRST_NAME = SOURCE.D_NAME,
  TARGET.D_LAST_NAME = SOURCE.D_LAST_NAME,
  TARGET.D_ADDR_1 = SOURCE.D_ADDRESS_1,
  TARGET.D_ADDR_2 = SOURCE.D_ADDRESS_2,
  TARGET.D_ADDR_3 = SOURCE.D_ADDRESS_3,
  TARGET.D_CITY = SOURCE.D_CITY,
  TARGET.D_STATE_PROV = SOURCE.D_STATE_PROV,
  TARGET.D_POSTAL_CD = SOURCE.D_POSTAL_CODE,
  TARGET.D_COUNTY = SOURCE.D_COUNTY,
  TARGET.D_COUNTRY_CD = SOURCE.D_COUNTRY_CODE,
  TARGET.D_PHONE_NBR = SOURCE.D_PHONE_NUMBER,
  TARGET.D_EMAIL = SOURCE.D_EMAIL,
  TARGET.ADDR_VALID_FLAG = SOURCE.ADDR_VALID,
  TARGET.OMS_ALLOC_FINALIZER = SOURCE.ALLOC_FINALIZER,
  TARGET.OMS_DSG_CARRIER_ID = SOURCE.DSG_CARRIER_ID,
  TARGET.DSG_SHIP_VIA = SOURCE.DSG_SHIP_VIA,
  TARGET.DO_CREATED_FLAG = SOURCE.IS_DO_CREATED,
  TARGET.READY_TO_SHIP_FLAG = SOURCE.IS_READY_TO_SHIP,
  TARGET.CANCELLED_FLAG = SOURCE.IS_CANCELLED,
  TARGET.CLOSED_FLAG = SOURCE.IS_CLOSED,
  TARGET.DELETED_FLAG = SOURCE.IS_DELETED,
  TARGET.OMS_REASON_ID = SOURCE.REASON_ID,
  TARGET.OMS_REASON_CODES_GROUP_ID = SOURCE.REASON_CODES_GROUP_ID,
  TARGET.OMS_BACK_ORD_REASON_ID = SOURCE.BACK_ORD_REASON,
  TARGET.OMS_PICKUP_START_TSTMP = SOURCE.PICKUP_START_DTTM,
  TARGET.OMS_PICKUP_END_TSTMP = SOURCE.PICKUP_END_DTTM,
  TARGET.OMS_PICKUP_TZ_ID = SOURCE.PICKUP_TZ,
  TARGET.OMS_DELIVERY_START_TSTMP = SOURCE.DELIVERY_START_DTTM,
  TARGET.OMS_DELIVERY_END_TSTMP = SOURCE.DELIVERY_END_DTTM,
  TARGET.OMS_DELIVERY_TZ_ID = SOURCE.DELIVERY_TZ,
  TARGET.OMS_REQ_DLVR_TSTMP = SOURCE.REQ_DLVR_DTTM,
  TARGET.OMS_MUST_DLVR_TSTMP = SOURCE.MUST_DLVR_DTTM,
  TARGET.OMS_SHIP_BY_DT = SOURCE.SHIP_BY_DATE,
  TARGET.ORIG_ORDER_QTY = SOURCE.ORIG_ORDER_QTY,
  TARGET.ORDER_QTY = SOURCE.ORDER_QTY,
  TARGET.CANCELLED_QTY = SOURCE.CANCELLED_QTY,
  TARGET.ALLOCATED_QTY = SOURCE.ALLOCATED_QTY,
  TARGET.RELEASED_QTY = SOURCE.RELEASED_QTY,
  TARGET.RECEIVED_QTY = SOURCE.RECEIVED_QTY,
  TARGET.PPACK_QTY = SOURCE.PPACK_QTY,
  TARGET.SHIPPED_QTY = SOURCE.SHIPPED_QTY,
  TARGET.ORIGINAL_PRICE_AMT = SOURCE.ORIGINAL_PRICE,
  TARGET.RETAIL_PRICE_AMT = SOURCE.RETAIL_PRICE,
  TARGET.UNIT_TAX_AMT = SOURCE.UNIT_TAX_AMOUNT,
  TARGET.LINE_TOTAL_AMT = SOURCE.LINE_TOTAL,
  TARGET.UNIT_MONETARY_VALUE = SOURCE.UNIT_MONETARY_VALUE,
  TARGET.TOTAL_MONETARY_VALUE = SOURCE.TOTAL_MONETARY_VALUE,
  TARGET.MV_CURRENCY_CD = SOURCE.MV_CURRENCY_CODE,
  TARGET.OMS_EXT_CREATED_TSTMP = SOURCE.EXT_CREATED_DTTM,
  TARGET.OMS_CREATED_SOURCE_TYPE_ID = SOURCE.CREATED_SOURCE_TYPE,
  TARGET.OMS_CREATED_SOURCE = SOURCE.CREATED_SOURCE,
  TARGET.OMS_CREATED_TSTMP = SOURCE.CREATED_DTTM,
  TARGET.OMS_LAST_UPDATED_TSTMP = SOURCE.LAST_UPDATED_DTTM,
  TARGET.UPDATE_TSTMP = SOURCE.o_UPDATE_TSTMP,
  TARGET.LOAD_TSTMP = SOURCE.o_LOAD_TSTMP
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_DELETE"
  AND TARGET.OMS_TC_PO_LINE_ID = SOURCE.TC_PO_LINE_ID
  AND TARGET.OMS_PARENT_PO_LINE_ITEM_ID = SOURCE.PARENT_PO_LINE_ITEM_ID
  AND TARGET.OMS_ORIGINAL_PO_LINE_ITEM_ID = SOURCE.ORIGINAL_PO_LINE_ITEM_ID
  AND TARGET.OMS_PURCHASE_ORDERS_LINE_STATUS_ID = SOURCE.PURCHASE_ORDERS_LINE_STATUS
  AND TARGET.ORDER_FULFILLMENT_OPTION_ID = SOURCE.ORDER_FULFILLMENT_OPTION
  AND TARGET.SKU = SOURCE.SKU
  AND TARGET.CUST_SKU = SOURCE.CUST_SKU
  AND TARGET.OMS_PRODUCT_CLASS_ID = SOURCE.PRODUCT_CLASS_ID
  AND TARGET.RETURNABLE_FLAG = SOURCE.IS_RETURNABLE
  AND TARGET.EXCHANGEABLE_FLAG = SOURCE.IS_EXCHANGEABLE
  AND TARGET.PRICE_OVERRIDE_FLAG = SOURCE.PRICE_OVERRIDE
  AND TARGET.OMS_STORE_FACILITY_ALIAS_ID = SOURCE.STORE_FACILITY_ALIAS_ID
  AND TARGET.OMS_STORE_FACILITY_ID = SOURCE.STORE_FACILITY_ID
  AND TARGET.OMS_O_FACILITY_ID = SOURCE.O_FACILITY_ID
  AND TARGET.OMS_O_FACILITY_ALIAS_ID = SOURCE.O_FACILITY_ALIAS_ID
  AND TARGET.OMS_BILL_FACILITY_ALIAS_ID = SOURCE.BILL_FACILITY_ALIAS_ID
  AND TARGET.OMS_BILL_FACILITY_ID = SOURCE.BILL_FACILITY_ID
  AND TARGET.OMS_D_FACILITY_ID = SOURCE.D_FACILITY_ID
  AND TARGET.OMS_D_FACILITY_ALIAS_ID = SOURCE.D_FACILITY_ALIAS_ID
  AND TARGET.D_FIRST_NAME = SOURCE.D_NAME
  AND TARGET.D_LAST_NAME = SOURCE.D_LAST_NAME
  AND TARGET.D_ADDR_1 = SOURCE.D_ADDRESS_1
  AND TARGET.D_ADDR_2 = SOURCE.D_ADDRESS_2
  AND TARGET.D_ADDR_3 = SOURCE.D_ADDRESS_3
  AND TARGET.D_CITY = SOURCE.D_CITY
  AND TARGET.D_STATE_PROV = SOURCE.D_STATE_PROV
  AND TARGET.D_POSTAL_CD = SOURCE.D_POSTAL_CODE
  AND TARGET.D_COUNTY = SOURCE.D_COUNTY
  AND TARGET.D_COUNTRY_CD = SOURCE.D_COUNTRY_CODE
  AND TARGET.D_PHONE_NBR = SOURCE.D_PHONE_NUMBER
  AND TARGET.D_EMAIL = SOURCE.D_EMAIL
  AND TARGET.ADDR_VALID_FLAG = SOURCE.ADDR_VALID
  AND TARGET.OMS_ALLOC_FINALIZER = SOURCE.ALLOC_FINALIZER
  AND TARGET.OMS_DSG_CARRIER_ID = SOURCE.DSG_CARRIER_ID
  AND TARGET.DSG_SHIP_VIA = SOURCE.DSG_SHIP_VIA
  AND TARGET.DO_CREATED_FLAG = SOURCE.IS_DO_CREATED
  AND TARGET.READY_TO_SHIP_FLAG = SOURCE.IS_READY_TO_SHIP
  AND TARGET.CANCELLED_FLAG = SOURCE.IS_CANCELLED
  AND TARGET.CLOSED_FLAG = SOURCE.IS_CLOSED
  AND TARGET.DELETED_FLAG = SOURCE.IS_DELETED
  AND TARGET.OMS_REASON_ID = SOURCE.REASON_ID
  AND TARGET.OMS_REASON_CODES_GROUP_ID = SOURCE.REASON_CODES_GROUP_ID
  AND TARGET.OMS_BACK_ORD_REASON_ID = SOURCE.BACK_ORD_REASON
  AND TARGET.OMS_PICKUP_START_TSTMP = SOURCE.PICKUP_START_DTTM
  AND TARGET.OMS_PICKUP_END_TSTMP = SOURCE.PICKUP_END_DTTM
  AND TARGET.OMS_PICKUP_TZ_ID = SOURCE.PICKUP_TZ
  AND TARGET.OMS_DELIVERY_START_TSTMP = SOURCE.DELIVERY_START_DTTM
  AND TARGET.OMS_DELIVERY_END_TSTMP = SOURCE.DELIVERY_END_DTTM
  AND TARGET.OMS_DELIVERY_TZ_ID = SOURCE.DELIVERY_TZ
  AND TARGET.OMS_REQ_DLVR_TSTMP = SOURCE.REQ_DLVR_DTTM
  AND TARGET.OMS_MUST_DLVR_TSTMP = SOURCE.MUST_DLVR_DTTM
  AND TARGET.OMS_SHIP_BY_DT = SOURCE.SHIP_BY_DATE
  AND TARGET.ORIG_ORDER_QTY = SOURCE.ORIG_ORDER_QTY
  AND TARGET.ORDER_QTY = SOURCE.ORDER_QTY
  AND TARGET.CANCELLED_QTY = SOURCE.CANCELLED_QTY
  AND TARGET.ALLOCATED_QTY = SOURCE.ALLOCATED_QTY
  AND TARGET.RELEASED_QTY = SOURCE.RELEASED_QTY
  AND TARGET.RECEIVED_QTY = SOURCE.RECEIVED_QTY
  AND TARGET.PPACK_QTY = SOURCE.PPACK_QTY
  AND TARGET.SHIPPED_QTY = SOURCE.SHIPPED_QTY
  AND TARGET.ORIGINAL_PRICE_AMT = SOURCE.ORIGINAL_PRICE
  AND TARGET.RETAIL_PRICE_AMT = SOURCE.RETAIL_PRICE
  AND TARGET.UNIT_TAX_AMT = SOURCE.UNIT_TAX_AMOUNT
  AND TARGET.LINE_TOTAL_AMT = SOURCE.LINE_TOTAL
  AND TARGET.UNIT_MONETARY_VALUE = SOURCE.UNIT_MONETARY_VALUE
  AND TARGET.TOTAL_MONETARY_VALUE = SOURCE.TOTAL_MONETARY_VALUE
  AND TARGET.MV_CURRENCY_CD = SOURCE.MV_CURRENCY_CODE
  AND TARGET.OMS_EXT_CREATED_TSTMP = SOURCE.EXT_CREATED_DTTM
  AND TARGET.OMS_CREATED_SOURCE_TYPE_ID = SOURCE.CREATED_SOURCE_TYPE
  AND TARGET.OMS_CREATED_SOURCE = SOURCE.CREATED_SOURCE
  AND TARGET.OMS_CREATED_TSTMP = SOURCE.CREATED_DTTM
  AND TARGET.OMS_LAST_UPDATED_TSTMP = SOURCE.LAST_UPDATED_DTTM
  AND TARGET.UPDATE_TSTMP = SOURCE.o_UPDATE_TSTMP
  AND TARGET.LOAD_TSTMP = SOURCE.o_LOAD_TSTMP THEN DELETE
  WHEN NOT MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_INSERT" THEN
INSERT
  (
    TARGET.OMS_PURCHASE_ORDERS_ID,
    TARGET.OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
    TARGET.OMS_TC_PO_LINE_ID,
    TARGET.OMS_PARENT_PO_LINE_ITEM_ID,
    TARGET.OMS_ORIGINAL_PO_LINE_ITEM_ID,
    TARGET.OMS_PURCHASE_ORDERS_LINE_STATUS_ID,
    TARGET.ORDER_FULFILLMENT_OPTION_ID,
    TARGET.SKU,
    TARGET.CUST_SKU,
    TARGET.OMS_PRODUCT_CLASS_ID,
    TARGET.RETURNABLE_FLAG,
    TARGET.EXCHANGEABLE_FLAG,
    TARGET.PRICE_OVERRIDE_FLAG,
    TARGET.OMS_STORE_FACILITY_ALIAS_ID,
    TARGET.OMS_STORE_FACILITY_ID,
    TARGET.OMS_O_FACILITY_ID,
    TARGET.OMS_O_FACILITY_ALIAS_ID,
    TARGET.OMS_BILL_FACILITY_ALIAS_ID,
    TARGET.OMS_BILL_FACILITY_ID,
    TARGET.OMS_D_FACILITY_ID,
    TARGET.OMS_D_FACILITY_ALIAS_ID,
    TARGET.D_FIRST_NAME,
    TARGET.D_LAST_NAME,
    TARGET.D_ADDR_1,
    TARGET.D_ADDR_2,
    TARGET.D_ADDR_3,
    TARGET.D_CITY,
    TARGET.D_STATE_PROV,
    TARGET.D_POSTAL_CD,
    TARGET.D_COUNTY,
    TARGET.D_COUNTRY_CD,
    TARGET.D_PHONE_NBR,
    TARGET.D_EMAIL,
    TARGET.ADDR_VALID_FLAG,
    TARGET.OMS_ALLOC_FINALIZER,
    TARGET.OMS_DSG_CARRIER_ID,
    TARGET.DSG_SHIP_VIA,
    TARGET.DO_CREATED_FLAG,
    TARGET.READY_TO_SHIP_FLAG,
    TARGET.CANCELLED_FLAG,
    TARGET.CLOSED_FLAG,
    TARGET.DELETED_FLAG,
    TARGET.OMS_REASON_ID,
    TARGET.OMS_REASON_CODES_GROUP_ID,
    TARGET.OMS_BACK_ORD_REASON_ID,
    TARGET.OMS_PICKUP_START_TSTMP,
    TARGET.OMS_PICKUP_END_TSTMP,
    TARGET.OMS_PICKUP_TZ_ID,
    TARGET.OMS_DELIVERY_START_TSTMP,
    TARGET.OMS_DELIVERY_END_TSTMP,
    TARGET.OMS_DELIVERY_TZ_ID,
    TARGET.OMS_REQ_DLVR_TSTMP,
    TARGET.OMS_MUST_DLVR_TSTMP,
    TARGET.OMS_SHIP_BY_DT,
    TARGET.ORIG_ORDER_QTY,
    TARGET.ORDER_QTY,
    TARGET.CANCELLED_QTY,
    TARGET.ALLOCATED_QTY,
    TARGET.RELEASED_QTY,
    TARGET.RECEIVED_QTY,
    TARGET.PPACK_QTY,
    TARGET.SHIPPED_QTY,
    TARGET.ORIGINAL_PRICE_AMT,
    TARGET.RETAIL_PRICE_AMT,
    TARGET.UNIT_TAX_AMT,
    TARGET.LINE_TOTAL_AMT,
    TARGET.UNIT_MONETARY_VALUE,
    TARGET.TOTAL_MONETARY_VALUE,
    TARGET.MV_CURRENCY_CD,
    TARGET.OMS_EXT_CREATED_TSTMP,
    TARGET.OMS_CREATED_SOURCE_TYPE_ID,
    TARGET.OMS_CREATED_SOURCE,
    TARGET.OMS_CREATED_TSTMP,
    TARGET.OMS_LAST_UPDATED_TSTMP,
    TARGET.UPDATE_TSTMP,
    TARGET.LOAD_TSTMP
  )
VALUES
  (
    SOURCE.PURCHASE_ORDERS_ID,
    SOURCE.PURCHASE_ORDERS_LINE_ITEM_ID,
    SOURCE.TC_PO_LINE_ID,
    SOURCE.PARENT_PO_LINE_ITEM_ID,
    SOURCE.ORIGINAL_PO_LINE_ITEM_ID,
    SOURCE.PURCHASE_ORDERS_LINE_STATUS,
    SOURCE.ORDER_FULFILLMENT_OPTION,
    SOURCE.SKU,
    SOURCE.CUST_SKU,
    SOURCE.PRODUCT_CLASS_ID,
    SOURCE.IS_RETURNABLE,
    SOURCE.IS_EXCHANGEABLE,
    SOURCE.PRICE_OVERRIDE,
    SOURCE.STORE_FACILITY_ALIAS_ID,
    SOURCE.STORE_FACILITY_ID,
    SOURCE.O_FACILITY_ID,
    SOURCE.O_FACILITY_ALIAS_ID,
    SOURCE.BILL_FACILITY_ALIAS_ID,
    SOURCE.BILL_FACILITY_ID,
    SOURCE.D_FACILITY_ID,
    SOURCE.D_FACILITY_ALIAS_ID,
    SOURCE.D_NAME,
    SOURCE.D_LAST_NAME,
    SOURCE.D_ADDRESS_1,
    SOURCE.D_ADDRESS_2,
    SOURCE.D_ADDRESS_3,
    SOURCE.D_CITY,
    SOURCE.D_STATE_PROV,
    SOURCE.D_POSTAL_CODE,
    SOURCE.D_COUNTY,
    SOURCE.D_COUNTRY_CODE,
    SOURCE.D_PHONE_NUMBER,
    SOURCE.D_EMAIL,
    SOURCE.ADDR_VALID,
    SOURCE.ALLOC_FINALIZER,
    SOURCE.DSG_CARRIER_ID,
    SOURCE.DSG_SHIP_VIA,
    SOURCE.IS_DO_CREATED,
    SOURCE.IS_READY_TO_SHIP,
    SOURCE.IS_CANCELLED,
    SOURCE.IS_CLOSED,
    SOURCE.IS_DELETED,
    SOURCE.REASON_ID,
    SOURCE.REASON_CODES_GROUP_ID,
    SOURCE.BACK_ORD_REASON,
    SOURCE.PICKUP_START_DTTM,
    SOURCE.PICKUP_END_DTTM,
    SOURCE.PICKUP_TZ,
    SOURCE.DELIVERY_START_DTTM,
    SOURCE.DELIVERY_END_DTTM,
    SOURCE.DELIVERY_TZ,
    SOURCE.REQ_DLVR_DTTM,
    SOURCE.MUST_DLVR_DTTM,
    SOURCE.SHIP_BY_DATE,
    SOURCE.ORIG_ORDER_QTY,
    SOURCE.ORDER_QTY,
    SOURCE.CANCELLED_QTY,
    SOURCE.ALLOCATED_QTY,
    SOURCE.RELEASED_QTY,
    SOURCE.RECEIVED_QTY,
    SOURCE.PPACK_QTY,
    SOURCE.SHIPPED_QTY,
    SOURCE.ORIGINAL_PRICE,
    SOURCE.RETAIL_PRICE,
    SOURCE.UNIT_TAX_AMOUNT,
    SOURCE.LINE_TOTAL,
    SOURCE.UNIT_MONETARY_VALUE,
    SOURCE.TOTAL_MONETARY_VALUE,
    SOURCE.MV_CURRENCY_CODE,
    SOURCE.EXT_CREATED_DTTM,
    SOURCE.CREATED_SOURCE_TYPE,
    SOURCE.CREATED_SOURCE,
    SOURCE.CREATED_DTTM,
    SOURCE.LAST_UPDATED_DTTM,
    SOURCE.o_UPDATE_TSTMP,
    SOURCE.o_LOAD_TSTMP
  )""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_Purchase_Orders_Line_Item")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_DDS_OMS_Purchase_Orders_Line_Item", mainWorkflowId, parentName)
