# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ../WorkflowUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_Lpn_Pre")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_DDS_OMS_Lpn_Pre", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_ORDER_LOAD_CTRL_0


query_0 = f"""SELECT
  ORDER_ID AS ORDER_ID,
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID
FROM
  OMS_ORDER_LOAD_CTRL"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_OMS_ORDER_LOAD_CTRL_0")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_LPN_1


query_1 = f"""SELECT
  LPN_ID AS LPN_ID,
  TC_LPN_ID AS TC_LPN_ID,
  BUSINESS_PARTNER_ID AS BUSINESS_PARTNER_ID,
  TC_COMPANY_ID AS TC_COMPANY_ID,
  PARENT_LPN_ID AS PARENT_LPN_ID,
  TC_PARENT_LPN_ID AS TC_PARENT_LPN_ID,
  LPN_TYPE AS LPN_TYPE,
  VERSION_NBR AS VERSION_NBR,
  LPN_MONETARY_VALUE AS LPN_MONETARY_VALUE,
  LPN_MONETARY_VALUE_CURR_CODE AS LPN_MONETARY_VALUE_CURR_CODE,
  TIER_QTY AS TIER_QTY,
  STD_LPN_QTY AS STD_LPN_QTY,
  C_FACILITY_ID AS C_FACILITY_ID,
  O_FACILITY_ID AS O_FACILITY_ID,
  O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  FINAL_DEST_FACILITY_ALIAS_ID AS FINAL_DEST_FACILITY_ALIAS_ID,
  FINAL_DEST_FACILITY_ID AS FINAL_DEST_FACILITY_ID,
  LPN_STATUS AS LPN_STATUS,
  LPN_STATUS_UPDATED_DTTM AS LPN_STATUS_UPDATED_DTTM,
  LPN_FACILITY_STATUS AS LPN_FACILITY_STATUS,
  TC_REFERENCE_LPN_ID AS TC_REFERENCE_LPN_ID,
  TC_ORDER_ID AS TC_ORDER_ID,
  ORIGINAL_TC_SHIPMENT_ID AS ORIGINAL_TC_SHIPMENT_ID,
  PARCEL_SHIPMENT_NBR AS PARCEL_SHIPMENT_NBR,
  TRACKING_NBR AS TRACKING_NBR,
  MANIFEST_NBR AS MANIFEST_NBR,
  SHIP_VIA AS SHIP_VIA,
  MASTER_BOL_NBR AS MASTER_BOL_NBR,
  BOL_NBR AS BOL_NBR,
  INIT_SHIP_VIA AS INIT_SHIP_VIA,
  PATH_ID AS PATH_ID,
  ROUTE_RULE_ID AS ROUTE_RULE_ID,
  IDEAL_PICK_DTTM AS IDEAL_PICK_DTTM,
  REPRINT_COUNT AS REPRINT_COUNT,
  LAST_FROZEN_DTTM AS LAST_FROZEN_DTTM,
  LAST_COUNTED_DTTM AS LAST_COUNTED_DTTM,
  BASE_CHARGE AS BASE_CHARGE,
  BASE_CHARGE_CURR_CODE AS BASE_CHARGE_CURR_CODE,
  ADDNL_OPTION_CHARGE AS ADDNL_OPTION_CHARGE,
  ADDNL_OPTION_CHARGE_CURR_CODE AS ADDNL_OPTION_CHARGE_CURR_CODE,
  INSUR_CHARGE AS INSUR_CHARGE,
  INSUR_CHARGE_CURR_CODE AS INSUR_CHARGE_CURR_CODE,
  ACTUAL_CHARGE AS ACTUAL_CHARGE,
  ACTUAL_CHARGE_CURR_CODE AS ACTUAL_CHARGE_CURR_CODE,
  PRE_BULK_BASE_CHARGE AS PRE_BULK_BASE_CHARGE,
  PRE_BULK_BASE_CHARGE_CURR_CODE AS PRE_BULK_BASE_CHARGE_CURR_CODE,
  PRE_BULK_ADD_OPT_CHR AS PRE_BULK_ADD_OPT_CHR,
  PRE_BULK_ADD_OPT_CHR_CURR_CODE AS PRE_BULK_ADD_OPT_CHR_CURR_CODE,
  DIST_CHARGE AS DIST_CHARGE,
  DIST_CHARGE_CURR_CODE AS DIST_CHARGE_CURR_CODE,
  FREIGHT_CHARGE AS FREIGHT_CHARGE,
  FREIGHT_CHARGE_CURR_CODE AS FREIGHT_CHARGE_CURR_CODE,
  RECEIVED_TC_SHIPMENT_ID AS RECEIVED_TC_SHIPMENT_ID,
  MANUFACTURED_DTTM AS MANUFACTURED_DTTM,
  MANUFACT_PLANT_FACILITY_ALIAS AS MANUFACT_PLANT_FACILITY_ALIAS,
  RCVD_DTTM AS RCVD_DTTM,
  TC_PURCHASE_ORDERS_ID AS TC_PURCHASE_ORDERS_ID,
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  TC_SHIPMENT_ID AS TC_SHIPMENT_ID,
  SHIPMENT_ID AS SHIPMENT_ID,
  TC_ASN_ID AS TC_ASN_ID,
  ASN_ID AS ASN_ID,
  RECEIPT_VARIANCE_INDICATOR AS RECEIPT_VARIANCE_INDICATOR,
  ESTIMATED_VOLUME AS ESTIMATED_VOLUME,
  WEIGHT AS WEIGHT,
  ACTUAL_VOLUME AS ACTUAL_VOLUME,
  LPN_LABEL_TYPE AS LPN_LABEL_TYPE,
  PACKAGE_TYPE_ID AS PACKAGE_TYPE_ID,
  MISC_INSTR_CODE_1 AS MISC_INSTR_CODE_1,
  MISC_INSTR_CODE_2 AS MISC_INSTR_CODE_2,
  MISC_INSTR_CODE_3 AS MISC_INSTR_CODE_3,
  MISC_INSTR_CODE_4 AS MISC_INSTR_CODE_4,
  MISC_INSTR_CODE_5 AS MISC_INSTR_CODE_5,
  MISC_NUM_1 AS MISC_NUM_1,
  MISC_NUM_2 AS MISC_NUM_2,
  HIBERNATE_VERSION AS HIBERNATE_VERSION,
  CUBE_UOM AS CUBE_UOM,
  ERROR_INDICATOR AS ERROR_INDICATOR,
  WARNING_INDICATOR AS WARNING_INDICATOR,
  QA_FLAG AS QA_FLAG,
  PALLET_OPEN_FLAG AS PALLET_OPEN_FLAG,
  QTY_UOM_ID_BASE AS QTY_UOM_ID_BASE,
  WEIGHT_UOM_ID_BASE AS WEIGHT_UOM_ID_BASE,
  VOLUME_UOM_ID_BASE AS VOLUME_UOM_ID_BASE,
  SPLIT_LPN_ID AS SPLIT_LPN_ID,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_DTTM AS CREATED_DTTM,
  EXT_CREATED_DTTM AS EXT_CREATED_DTTM,
  LAST_UPDATED_SOURCE_TYPE AS LAST_UPDATED_SOURCE_TYPE,
  LAST_UPDATED_SOURCE AS LAST_UPDATED_SOURCE,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  CONVEYABLE_LPN_FLAG AS CONVEYABLE_LPN_FLAG,
  ACTIVE_LPN_FLAG AS ACTIVE_LPN_FLAG,
  LPN_SHIPPED_FLAG AS LPN_SHIPPED_FLAG,
  STD_QTY_FLAG AS STD_QTY_FLAG,
  C_FACILITY_ALIAS_ID AS C_FACILITY_ALIAS_ID,
  PALLET_MASTER_LPN_FLAG AS PALLET_MASTER_LPN_FLAG,
  MASTER_LPN_FLAG AS MASTER_LPN_FLAG,
  LPN_SIZE_TYPE_ID AS LPN_SIZE_TYPE_ID,
  PICK_SUB_LOCN_ID AS PICK_SUB_LOCN_ID,
  CURR_SUB_LOCN_ID AS CURR_SUB_LOCN_ID,
  PREV_SUB_LOCN_ID AS PREV_SUB_LOCN_ID,
  DEST_SUB_LOCN_ID AS DEST_SUB_LOCN_ID,
  INBOUND_OUTBOUND_INDICATOR AS INBOUND_OUTBOUND_INDICATOR,
  WORK_ORD_NBR AS WORK_ORD_NBR,
  INTERNAL_ORDER_ID AS INTERNAL_ORDER_ID,
  SHIPPED_DTTM AS SHIPPED_DTTM,
  TRAILER_STOP_SEQ_NBR AS TRAILER_STOP_SEQ_NBR,
  PACK_WAVE_NBR AS PACK_WAVE_NBR,
  WAVE_NBR AS WAVE_NBR,
  WAVE_SEQ_NBR AS WAVE_SEQ_NBR,
  WAVE_STAT_CODE AS WAVE_STAT_CODE,
  DIRECTED_QTY AS DIRECTED_QTY,
  TRANSITIONAL_INVENTORY_TYPE AS TRANSITIONAL_INVENTORY_TYPE,
  PICKER_USERID AS PICKER_USERID,
  PACKER_USERID AS PACKER_USERID,
  CHUTE_ID AS CHUTE_ID,
  CHUTE_ASSIGN_TYPE AS CHUTE_ASSIGN_TYPE,
  STAGE_INDICATOR AS STAGE_INDICATOR,
  OUT_OF_ZONE_INDICATOR AS OUT_OF_ZONE_INDICATOR,
  LABEL_PRINT_REQD AS LABEL_PRINT_REQD,
  CONSUMPTION_SEQUENCE AS CONSUMPTION_SEQUENCE,
  CONSUMPTION_PRIORITY AS CONSUMPTION_PRIORITY,
  CONSUMPTION_PRIORITY_DTTM AS CONSUMPTION_PRIORITY_DTTM,
  PUTAWAY_TYPE AS PUTAWAY_TYPE,
  RETURN_DISPOSITION_CODE AS RETURN_DISPOSITION_CODE,
  FINAL_DISPOSITION_CODE AS FINAL_DISPOSITION_CODE,
  LOADED_DTTM AS LOADED_DTTM,
  LOADER_USERID AS LOADER_USERID,
  LOADED_POSN AS LOADED_POSN,
  SHIP_BY_DATE AS SHIP_BY_DATE,
  PICK_DELIVERY_DURATION AS PICK_DELIVERY_DURATION,
  LPN_BREAK_ATTR AS LPN_BREAK_ATTR,
  LPN_PRINT_GROUP_CODE AS LPN_PRINT_GROUP_CODE,
  SEQ_RULE_PRIORITY AS SEQ_RULE_PRIORITY,
  SPUR_LANE AS SPUR_LANE,
  SPUR_POSITION AS SPUR_POSITION,
  FIRST_ZONE AS FIRST_ZONE,
  LAST_ZONE AS LAST_ZONE,
  NBR_OF_ZONES AS NBR_OF_ZONES,
  LPN_DIVERT_CODE AS LPN_DIVERT_CODE,
  INTERNAL_ORDER_CONSOL_ATTR AS INTERNAL_ORDER_CONSOL_ATTR,
  WHSE_INTERNAL_EVENT_CODE AS WHSE_INTERNAL_EVENT_CODE,
  SELECTION_RULE_ID AS SELECTION_RULE_ID,
  VOCO_INTRN_REVERSE_ID AS VOCO_INTRN_REVERSE_ID,
  VOCO_INTRN_REVERSE_PALLET_ID AS VOCO_INTRN_REVERSE_PALLET_ID,
  LPN_CREATION_CODE AS LPN_CREATION_CODE,
  PALLET_X_OF_Y AS PALLET_X_OF_Y,
  INCUBATION_DATE AS INCUBATION_DATE,
  CONTAINER_TYPE AS CONTAINER_TYPE,
  CONTAINER_SIZE AS CONTAINER_SIZE,
  LPN_NBR_X_OF_Y AS LPN_NBR_X_OF_Y,
  LOAD_SEQUENCE AS LOAD_SEQUENCE,
  MASTER_PACK_ID AS MASTER_PACK_ID,
  SINGLE_LINE_LPN AS SINGLE_LINE_LPN,
  NON_INVENTORY_LPN_FLAG AS NON_INVENTORY_LPN_FLAG,
  EPC_MATCH_FLAG AS EPC_MATCH_FLAG,
  AUDITOR_USERID AS AUDITOR_USERID,
  PRINTING_RULE_ID AS PRINTING_RULE_ID,
  EXPIRATION_DATE AS EXPIRATION_DATE,
  QUAL_AUD_STAT_CODE AS QUAL_AUD_STAT_CODE,
  DELVRECIPIENTNAME AS DELVRECIPIENTNAME,
  DELVRECEIPTDATETIME AS DELVRECEIPTDATETIME,
  DELVONTIMEFLAG AS DELVONTIMEFLAG,
  DELVCOMPLFLAG AS DELVCOMPLFLAG,
  ITEM_ID AS ITEM_ID,
  LPN_FACILITY_STAT_UPDATED_DTTM AS LPN_FACILITY_STAT_UPDATED_DTTM,
  LPN_DISP_STATUS AS LPN_DISP_STATUS,
  OVERSIZE_LENGTH AS OVERSIZE_LENGTH,
  BILLING_METHOD AS BILLING_METHOD,
  CUSTOMER_ID AS CUSTOMER_ID,
  IS_ZONE_SKIPPED AS IS_ZONE_SKIPPED,
  ZONESKIP_HUB_FACILITY_ALIAS_ID AS ZONESKIP_HUB_FACILITY_ALIAS_ID,
  ZONESKIP_HUB_FACILITY_ID AS ZONESKIP_HUB_FACILITY_ID,
  PLANING_DEST_FACILITY_ALIAS_ID AS PLANING_DEST_FACILITY_ALIAS_ID,
  PLANING_DEST_FACILITY_ID AS PLANING_DEST_FACILITY_ID,
  SCHED_SHIP_DTTM AS SCHED_SHIP_DTTM,
  DISTRIBUTION_LEG_CARRIER_ID AS DISTRIBUTION_LEG_CARRIER_ID,
  DISTRIBUTION_LEG_MODE_ID AS DISTRIBUTION_LEG_MODE_ID,
  DISTRIBUTION_LEV_SVCE_LEVEL_ID AS DISTRIBUTION_LEV_SVCE_LEVEL_ID,
  SERVICE_LEVEL_INDICATOR AS SERVICE_LEVEL_INDICATOR,
  COD_FLAG AS COD_FLAG,
  COD_AMOUNT AS COD_AMOUNT,
  COD_PAYMENT_METHOD AS COD_PAYMENT_METHOD,
  RATED_WEIGHT AS RATED_WEIGHT,
  RATE_WEIGHT_TYPE AS RATE_WEIGHT_TYPE,
  RATE_ZONE AS RATE_ZONE,
  FRT_FORWARDER_ACCT_NBR AS FRT_FORWARDER_ACCT_NBR,
  INTL_GOODS_DESC AS INTL_GOODS_DESC,
  SHIPMENT_PRINT_SED AS SHIPMENT_PRINT_SED,
  EXPORT_LICENSE_NUMBER AS EXPORT_LICENSE_NUMBER,
  EXPORT_LICENSE_SYMBOL AS EXPORT_LICENSE_SYMBOL,
  EXPORT_INFO_CODE AS EXPORT_INFO_CODE,
  REPRINT_SHIPPING_LABEL AS REPRINT_SHIPPING_LABEL,
  PLAN_LOAD_ID AS PLAN_LOAD_ID,
  DOCUMENTS_ONLY AS DOCUMENTS_ONLY,
  SCHEDULED_DELIVERY_DTTM AS SCHEDULED_DELIVERY_DTTM,
  NON_MACHINEABLE AS NON_MACHINEABLE,
  D_FACILITY_ID AS D_FACILITY_ID,
  D_FACILITY_ALIAS_ID AS D_FACILITY_ALIAS_ID,
  VENDOR_LPN_NBR AS VENDOR_LPN_NBR,
  PLANNED_TC_ASN_ID AS PLANNED_TC_ASN_ID,
  ESTIMATED_WEIGHT AS ESTIMATED_WEIGHT,
  ORDER_ID AS ORDER_ID,
  MARK_FOR AS MARK_FOR,
  PRE_RECEIPT_STATUS AS PRE_RECEIPT_STATUS,
  CROSSDOCK_TC_ORDER_ID AS CROSSDOCK_TC_ORDER_ID,
  PHYSICAL_ENTITY_CODE AS PHYSICAL_ENTITY_CODE,
  PROCESS_IMMEDIATE_NEEDS AS PROCESS_IMMEDIATE_NEEDS,
  LENGTH AS LENGTH,
  WIDTH AS WIDTH,
  HEIGHT AS HEIGHT,
  TOTAL_LPN_QTY AS TOTAL_LPN_QTY,
  STATIC_ROUTE_ID AS STATIC_ROUTE_ID,
  HAS_ALERTS AS HAS_ALERTS,
  ORDER_SPLIT_ID AS ORDER_SPLIT_ID,
  MHE_LOADED AS MHE_LOADED,
  ITEM_NAME AS ITEM_NAME,
  ALT_TRACKING_NBR AS ALT_TRACKING_NBR,
  RECEIPT_TYPE AS RECEIPT_TYPE,
  VARIANCE_TYPE AS VARIANCE_TYPE,
  RETURN_TRACKING_NBR AS RETURN_TRACKING_NBR,
  CONTAINS_DRY_ICE AS CONTAINS_DRY_ICE,
  RETURN_REFERENCE_NUMBER AS RETURN_REFERENCE_NUMBER,
  HAS_NOTES AS HAS_NOTES,
  RETURN_TRACKING_NBR_2 AS RETURN_TRACKING_NBR_2,
  DELIVERY_TYPE AS DELIVERY_TYPE,
  REF_FIELD_1 AS REF_FIELD_1,
  REF_FIELD_2 AS REF_FIELD_2,
  REF_FIELD_3 AS REF_FIELD_3,
  REF_FIELD_4 AS REF_FIELD_4,
  REF_FIELD_5 AS REF_FIELD_5,
  REF_FIELD_6 AS REF_FIELD_6,
  REF_FIELD_7 AS REF_FIELD_7,
  REF_FIELD_8 AS REF_FIELD_8,
  REF_FIELD_9 AS REF_FIELD_9,
  REF_FIELD_10 AS REF_FIELD_10,
  REF_NUM1 AS REF_NUM1,
  REF_NUM2 AS REF_NUM2,
  REF_NUM3 AS REF_NUM3,
  REF_NUM4 AS REF_NUM4,
  REF_NUM5 AS REF_NUM5,
  REGULATION_SET AS REGULATION_SET,
  DRY_ICE_WT AS DRY_ICE_WT,
  OVERPACK AS OVERPACK,
  SALVAGE_PACK AS SALVAGE_PACK,
  SALVAGE_PACK_QTY AS SALVAGE_PACK_QTY,
  Q_VALUE AS Q_VALUE,
  ALL_PAKD_IN_ONE AS ALL_PAKD_IN_ONE,
  SPECIAL_PERMITS AS SPECIAL_PERMITS,
  CN22_NBR AS CN22_NBR,
  DISPOSITION_TYPE AS DISPOSITION_TYPE,
  DISPOSITION_SOURCE_ID AS DISPOSITION_SOURCE_ID,
  END_OLPN_DTTM AS END_OLPN_DTTM,
  VOCOLLECT_ASSIGN_ID AS VOCOLLECT_ASSIGN_ID,
  CALCULATED_CUT_OFF_DTTM AS CALCULATED_CUT_OFF_DTTM,
  FAILED_GUARANTEED_DELIVERY AS FAILED_GUARANTEED_DELIVERY,
  EPI_PACKAGE_ID AS EPI_PACKAGE_ID,
  EPI_SHIPMENT_ID AS EPI_SHIPMENT_ID,
  EPI_MANIFEST_ID AS EPI_MANIFEST_ID,
  EPI_PACKAGE_STATUS AS EPI_PACKAGE_STATUS,
  XREF_OLPN AS XREF_OLPN
FROM
  LPN"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("Shortcut_to_LPN_1")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_LPN_2


query_2 = f"""SELECT
  Shortcut_to_LPN_1.LPN_ID AS LPN_ID,
  Shortcut_to_LPN_1.TC_LPN_ID AS TC_LPN_ID,
  Shortcut_to_LPN_1.PARENT_LPN_ID AS PARENT_LPN_ID,
  Shortcut_to_LPN_1.LPN_TYPE AS LPN_TYPE,
  Shortcut_to_LPN_1.FINAL_DEST_FACILITY_ALIAS_ID AS FINAL_DEST_FACILITY_ALIAS_ID,
  Shortcut_to_LPN_1.LPN_STATUS AS LPN_STATUS,
  Shortcut_to_LPN_1.LPN_STATUS_UPDATED_DTTM AS LPN_STATUS_UPDATED_DTTM,
  Shortcut_to_LPN_1.TRACKING_NBR AS TRACKING_NBR,
  Shortcut_to_LPN_1.BASE_CHARGE AS BASE_CHARGE,
  Shortcut_to_LPN_1.BASE_CHARGE_CURR_CODE AS BASE_CHARGE_CURR_CODE,
  Shortcut_to_LPN_1.ADDNL_OPTION_CHARGE AS ADDNL_OPTION_CHARGE,
  Shortcut_to_LPN_1.ADDNL_OPTION_CHARGE_CURR_CODE AS ADDNL_OPTION_CHARGE_CURR_CODE,
  Shortcut_to_LPN_1.ACTUAL_CHARGE AS ACTUAL_CHARGE,
  Shortcut_to_LPN_1.ACTUAL_CHARGE_CURR_CODE AS ACTUAL_CHARGE_CURR_CODE,
  Shortcut_to_LPN_1.DIST_CHARGE AS DIST_CHARGE,
  Shortcut_to_LPN_1.DIST_CHARGE_CURR_CODE AS DIST_CHARGE_CURR_CODE,
  Shortcut_to_LPN_1.FREIGHT_CHARGE AS FREIGHT_CHARGE,
  Shortcut_to_LPN_1.FREIGHT_CHARGE_CURR_CODE AS FREIGHT_CHARGE_CURR_CODE,
  Shortcut_to_LPN_1.SHIPMENT_ID AS SHIPMENT_ID,
  Shortcut_to_LPN_1.TC_ASN_ID AS TC_ASN_ID,
  Shortcut_to_LPN_1.ASN_ID AS ASN_ID,
  Shortcut_to_LPN_1.CREATED_DTTM AS CREATED_DTTM,
  Shortcut_to_LPN_1.LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  Shortcut_to_LPN_1.ORDER_ID AS ORDER_ID,
  Shortcut_to_OMS_ORDER_LOAD_CTRL_0.ORDER_ID AS ORDER_ID1,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_ORDER_LOAD_CTRL_0,
  Shortcut_to_LPN_1
WHERE
  Shortcut_to_LPN_1.ORDER_ID = Shortcut_to_OMS_ORDER_LOAD_CTRL_0.ORDER_ID"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("SQ_Shortcut_to_LPN_2")

# COMMAND ----------
# DBTITLE 1, EXP_LOAD_TSTMP_3


query_3 = f"""SELECT
  LPN_ID AS LPN_ID,
  TC_LPN_ID AS TC_LPN_ID,
  PARENT_LPN_ID AS PARENT_LPN_ID,
  LPN_TYPE AS LPN_TYPE,
  FINAL_DEST_FACILITY_ALIAS_ID AS FINAL_DEST_FACILITY_ALIAS_ID,
  LPN_STATUS AS LPN_STATUS,
  LPN_STATUS_UPDATED_DTTM AS LPN_STATUS_UPDATED_DTTM,
  TRACKING_NBR AS TRACKING_NBR,
  BASE_CHARGE AS BASE_CHARGE,
  BASE_CHARGE_CURR_CODE AS BASE_CHARGE_CURR_CODE,
  ADDNL_OPTION_CHARGE AS ADDNL_OPTION_CHARGE,
  ADDNL_OPTION_CHARGE_CURR_CODE AS ADDNL_OPTION_CHARGE_CURR_CODE,
  ACTUAL_CHARGE AS ACTUAL_CHARGE,
  ACTUAL_CHARGE_CURR_CODE AS ACTUAL_CHARGE_CURR_CODE,
  DIST_CHARGE AS DIST_CHARGE,
  DIST_CHARGE_CURR_CODE AS DIST_CHARGE_CURR_CODE,
  FREIGHT_CHARGE AS FREIGHT_CHARGE,
  FREIGHT_CHARGE_CURR_CODE AS FREIGHT_CHARGE_CURR_CODE,
  SHIPMENT_ID AS SHIPMENT_ID,
  TC_ASN_ID AS TC_ASN_ID,
  ASN_ID AS ASN_ID,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  ORDER_ID AS ORDER_ID,
  now() AS o_LOAD_TSTMP,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_LPN_2"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("EXP_LOAD_TSTMP_3")

# COMMAND ----------
# DBTITLE 1, OMS_LPN_PRE


spark.sql("""INSERT INTO
  OMS_LPN_PRE
SELECT
  LPN_ID AS LPN_ID,
  TC_LPN_ID AS TC_LPN_ID,
  PARENT_LPN_ID AS PARENT_LPN_ID,
  LPN_TYPE AS LPN_TYPE,
  FINAL_DEST_FACILITY_ALIAS_ID AS FINAL_DEST_FACILITY_ALIAS_ID,
  LPN_STATUS AS LPN_STATUS,
  LPN_STATUS_UPDATED_DTTM AS LPN_STATUS_UPDATED_DTTM,
  TRACKING_NBR AS TRACKING_NBR,
  BASE_CHARGE AS BASE_CHARGE,
  BASE_CHARGE_CURR_CODE AS BASE_CHARGE_CURR_CODE,
  ADDNL_OPTION_CHARGE AS ADDNL_OPTION_CHARGE,
  ADDNL_OPTION_CHARGE_CURR_CODE AS ADDNL_OPTION_CHARGE_CURR_CODE,
  ACTUAL_CHARGE AS ACTUAL_CHARGE,
  ACTUAL_CHARGE_CURR_CODE AS ACTUAL_CHARGE_CURR_CODE,
  DIST_CHARGE AS DIST_CHARGE,
  DIST_CHARGE_CURR_CODE AS DIST_CHARGE_CURR_CODE,
  FREIGHT_CHARGE AS FREIGHT_CHARGE,
  FREIGHT_CHARGE_CURR_CODE AS FREIGHT_CHARGE_CURR_CODE,
  SHIPMENT_ID AS SHIPMENT_ID,
  TC_ASN_ID AS TC_ASN_ID,
  ASN_ID AS ASN_ID,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  ORDER_ID AS ORDER_ID,
  o_LOAD_TSTMP AS LOAD_TSTMP
FROM
  EXP_LOAD_TSTMP_3""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_Lpn_Pre")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_DDS_OMS_Lpn_Pre", mainWorkflowId, parentName)
