# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ../WorkflowUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_Purchase_Orders")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_DDS_OMS_Purchase_Orders", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_PURCHASE_ORDERS_PRE_0


query_0 = f"""SELECT
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  TC_COMPANY_ID AS TC_COMPANY_ID,
  CREATION_TYPE AS CREATION_TYPE,
  PURCHASE_ORDERS_TYPE AS PURCHASE_ORDERS_TYPE,
  PURCHASE_ORDERS_STATUS AS PURCHASE_ORDERS_STATUS,
  TC_PURCHASE_ORDERS_ID AS TC_PURCHASE_ORDERS_ID,
  PARENT_PURCHASE_ORDERS_ID AS PARENT_PURCHASE_ORDERS_ID,
  O_FACILITY_ID AS O_FACILITY_ID,
  O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  O_DOCK_ID AS O_DOCK_ID,
  D_FACILITY_ID AS D_FACILITY_ID,
  D_FACILITY_ALIAS_ID AS D_FACILITY_ALIAS_ID,
  BILL_FACILITY_ID AS BILL_FACILITY_ID,
  BILL_FACILITY_ALIAS_ID AS BILL_FACILITY_ALIAS_ID,
  ORG_SHIP_VIA_FACILITY_ALIAS_ID AS ORG_SHIP_VIA_FACILITY_ALIAS_ID,
  ORG_SHIP_VIA_FACILITY_ID AS ORG_SHIP_VIA_FACILITY_ID,
  DES_SHIP_VIA_FACILITY_ALIAS_ID AS DES_SHIP_VIA_FACILITY_ALIAS_ID,
  DES_SHIP_VIA_FACILITY_ID AS DES_SHIP_VIA_FACILITY_ID,
  PICKUP_TZ AS PICKUP_TZ,
  DELIVERY_TZ AS DELIVERY_TZ,
  PICKUP_START_DTTM AS PICKUP_START_DTTM,
  PICKUP_END_DTTM AS PICKUP_END_DTTM,
  DELIVERY_START_DTTM AS DELIVERY_START_DTTM,
  DELIVERY_END_DTTM AS DELIVERY_END_DTTM,
  REQUESTED_DLVR_DTTM AS REQUESTED_DLVR_DTTM,
  MUST_DLVR_DTTM AS MUST_DLVR_DTTM,
  PROMISED_DLVR_DTTM AS PROMISED_DLVR_DTTM,
  DUE_DT AS DUE_DT,
  CANCEL_DT AS CANCEL_DT,
  PURCHASE_ORDERS_DATE_DTTM AS PURCHASE_ORDERS_DATE_DTTM,
  RELEASE_DTTM AS RELEASE_DTTM,
  FIRST_RCPT_DTTM AS FIRST_RCPT_DTTM,
  LAST_RCPT_DTTM AS LAST_RCPT_DTTM,
  PAYMENT_MODE AS PAYMENT_MODE,
  MV_CURRENCY_CODE AS MV_CURRENCY_CODE,
  MONETARY_VALUE AS MONETARY_VALUE,
  CURRENCY_CODE AS CURRENCY_CODE,
  ORIG_BUDG_COST AS ORIG_BUDG_COST,
  BUDG_COST_CURRENCY_CODE AS BUDG_COST_CURRENCY_CODE,
  BUDG_COST AS BUDG_COST,
  TAX_CHARGES AS TAX_CHARGES,
  MISC_CHARGES AS MISC_CHARGES,
  IS_CANCELLED AS IS_CANCELLED,
  IS_IMPORTED AS IS_IMPORTED,
  HAS_ALERTS AS HAS_ALERTS,
  IS_PURCHASE_ORDERS_RECONCILED AS IS_PURCHASE_ORDERS_RECONCILED,
  IS_READY_TO_SHIP AS IS_READY_TO_SHIP,
  IS_CUSTOMER_PICKUP AS IS_CUSTOMER_PICKUP,
  IS_DIRECT_ALLOWED AS IS_DIRECT_ALLOWED,
  IS_PARTIALLY_PLANNED AS IS_PARTIALLY_PLANNED,
  ON_HOLD AS ON_HOLD,
  BILL_OF_LADING_NUMBER AS BILL_OF_LADING_NUMBER,
  TRANS_RESP_CODE AS TRANS_RESP_CODE,
  COMMODITY_CODE_ID AS COMMODITY_CODE_ID,
  CARRIER_ID AS CARRIER_ID,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  PROTECTION_LEVEL_ID AS PROTECTION_LEVEL_ID,
  DECLINE_REASON_ID AS DECLINE_REASON_ID,
  CHANNEL_TYPE AS CHANNEL_TYPE,
  CUSTOMER_CODE AS CUSTOMER_CODE,
  CUSTOMER_FIRSTNAME AS CUSTOMER_FIRSTNAME,
  CUSTOMER_LASTNAME AS CUSTOMER_LASTNAME,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  IS_CLOSED AS IS_CLOSED,
  GRAND_TOTAL AS GRAND_TOTAL,
  EXT_PURCHASE_ORDERS_ID AS EXT_PURCHASE_ORDERS_ID,
  ORDER_CATEGORY AS ORDER_CATEGORY,
  CHANNEL_ID AS CHANNEL_ID,
  FULFILL_MODE AS FULFILL_MODE,
  ENTERED_BY AS ENTERED_BY,
  ENTRY_CODE AS ENTRY_CODE,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  CUSTOMER_PHONE AS CUSTOMER_PHONE,
  PAYMENT_STATUS AS PAYMENT_STATUS,
  REASON_ID AS REASON_ID,
  ORDER_RECEIVED AS ORDER_RECEIVED,
  FREIGHT_REVENUE AS FREIGHT_REVENUE,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  RETURN_REFERENCE_NUMBER AS RETURN_REFERENCE_NUMBER,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_PURCHASE_ORDERS_PRE"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_OMS_PURCHASE_ORDERS_PRE_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_PURCHASE_ORDERS_PRE_1


query_1 = f"""SELECT
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  TC_COMPANY_ID AS TC_COMPANY_ID,
  CREATION_TYPE AS CREATION_TYPE,
  PURCHASE_ORDERS_TYPE AS PURCHASE_ORDERS_TYPE,
  PURCHASE_ORDERS_STATUS AS PURCHASE_ORDERS_STATUS,
  TC_PURCHASE_ORDERS_ID AS TC_PURCHASE_ORDERS_ID,
  PARENT_PURCHASE_ORDERS_ID AS PARENT_PURCHASE_ORDERS_ID,
  O_FACILITY_ID AS O_FACILITY_ID,
  O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  O_DOCK_ID AS O_DOCK_ID,
  D_FACILITY_ID AS D_FACILITY_ID,
  D_FACILITY_ALIAS_ID AS D_FACILITY_ALIAS_ID,
  BILL_FACILITY_ID AS BILL_FACILITY_ID,
  BILL_FACILITY_ALIAS_ID AS BILL_FACILITY_ALIAS_ID,
  ORG_SHIP_VIA_FACILITY_ALIAS_ID AS ORG_SHIP_VIA_FACILITY_ALIAS_ID,
  ORG_SHIP_VIA_FACILITY_ID AS ORG_SHIP_VIA_FACILITY_ID,
  DES_SHIP_VIA_FACILITY_ALIAS_ID AS DES_SHIP_VIA_FACILITY_ALIAS_ID,
  DES_SHIP_VIA_FACILITY_ID AS DES_SHIP_VIA_FACILITY_ID,
  PICKUP_TZ AS PICKUP_TZ,
  DELIVERY_TZ AS DELIVERY_TZ,
  PICKUP_START_DTTM AS PICKUP_START_DTTM,
  PICKUP_END_DTTM AS PICKUP_END_DTTM,
  DELIVERY_START_DTTM AS DELIVERY_START_DTTM,
  DELIVERY_END_DTTM AS DELIVERY_END_DTTM,
  REQUESTED_DLVR_DTTM AS REQUESTED_DLVR_DTTM,
  MUST_DLVR_DTTM AS MUST_DLVR_DTTM,
  PROMISED_DLVR_DTTM AS PROMISED_DLVR_DTTM,
  DUE_DT AS DUE_DT,
  CANCEL_DT AS CANCEL_DT,
  PURCHASE_ORDERS_DATE_DTTM AS PURCHASE_ORDERS_DATE_DTTM,
  RELEASE_DTTM AS RELEASE_DTTM,
  FIRST_RCPT_DTTM AS FIRST_RCPT_DTTM,
  LAST_RCPT_DTTM AS LAST_RCPT_DTTM,
  PAYMENT_MODE AS PAYMENT_MODE,
  MV_CURRENCY_CODE AS MV_CURRENCY_CODE,
  MONETARY_VALUE AS MONETARY_VALUE,
  CURRENCY_CODE AS CURRENCY_CODE,
  ORIG_BUDG_COST AS ORIG_BUDG_COST,
  BUDG_COST_CURRENCY_CODE AS BUDG_COST_CURRENCY_CODE,
  BUDG_COST AS BUDG_COST,
  TAX_CHARGES AS TAX_CHARGES,
  MISC_CHARGES AS MISC_CHARGES,
  IS_CANCELLED AS IS_CANCELLED,
  IS_IMPORTED AS IS_IMPORTED,
  HAS_ALERTS AS HAS_ALERTS,
  IS_PURCHASE_ORDERS_RECONCILED AS IS_PURCHASE_ORDERS_RECONCILED,
  IS_READY_TO_SHIP AS IS_READY_TO_SHIP,
  IS_CUSTOMER_PICKUP AS IS_CUSTOMER_PICKUP,
  IS_DIRECT_ALLOWED AS IS_DIRECT_ALLOWED,
  IS_PARTIALLY_PLANNED AS IS_PARTIALLY_PLANNED,
  ON_HOLD AS ON_HOLD,
  BILL_OF_LADING_NUMBER AS BILL_OF_LADING_NUMBER,
  TRANS_RESP_CODE AS TRANS_RESP_CODE,
  COMMODITY_CODE_ID AS COMMODITY_CODE_ID,
  CARRIER_ID AS CARRIER_ID,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  PROTECTION_LEVEL_ID AS PROTECTION_LEVEL_ID,
  DECLINE_REASON_ID AS DECLINE_REASON_ID,
  CHANNEL_TYPE AS CHANNEL_TYPE,
  CUSTOMER_CODE AS CUSTOMER_CODE,
  CUSTOMER_FIRSTNAME AS CUSTOMER_FIRSTNAME,
  CUSTOMER_LASTNAME AS CUSTOMER_LASTNAME,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  IS_CLOSED AS IS_CLOSED,
  GRAND_TOTAL AS GRAND_TOTAL,
  EXT_PURCHASE_ORDERS_ID AS EXT_PURCHASE_ORDERS_ID,
  ORDER_CATEGORY AS ORDER_CATEGORY,
  CHANNEL_ID AS CHANNEL_ID,
  FULFILL_MODE AS FULFILL_MODE,
  ENTERED_BY AS ENTERED_BY,
  ENTRY_CODE AS ENTRY_CODE,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  CUSTOMER_PHONE AS CUSTOMER_PHONE,
  PAYMENT_STATUS AS PAYMENT_STATUS,
  REASON_ID AS REASON_ID,
  ORDER_RECEIVED AS ORDER_RECEIVED,
  FREIGHT_REVENUE AS FREIGHT_REVENUE,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  RETURN_REFERENCE_NUMBER AS RETURN_REFERENCE_NUMBER,
  LOAD_TSTMP AS LOAD_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_PURCHASE_ORDERS_PRE_0"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("SQ_Shortcut_to_OMS_PURCHASE_ORDERS_PRE_1")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_PURCHASE_ORDERS_2


query_2 = f"""SELECT
  OMS_PURCHASE_ORDERS_ID AS OMS_PURCHASE_ORDERS_ID,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  OMS_EXT_PURCHASE_ORDERS_ID AS OMS_EXT_PURCHASE_ORDERS_ID,
  OMS_PARENT_PURCHASE_ORDERS_ID AS OMS_PARENT_PURCHASE_ORDERS_ID,
  OMS_PURCHASE_ORDERS_TYPE_ID AS OMS_PURCHASE_ORDERS_TYPE_ID,
  OMS_PURCHASE_ORDERS_STATUS_ID AS OMS_PURCHASE_ORDERS_STATUS_ID,
  OMS_ORDER_CATEGORY_ID AS OMS_ORDER_CATEGORY_ID,
  OMS_O_FACILITY_ID AS OMS_O_FACILITY_ID,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  OMS_D_FACILITY_ID AS OMS_D_FACILITY_ID,
  OMS_D_FACILITY_ALIAS_ID AS OMS_D_FACILITY_ALIAS_ID,
  OMS_BILL_FACILITY_ID AS OMS_BILL_FACILITY_ID,
  OMS_BILL_FACILITY_ALIAS_ID AS OMS_BILL_FACILITY_ALIAS_ID,
  OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID AS OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID,
  OMS_ORIGIN_SHIP_VIA_FACILITY_ID AS OMS_ORIGIN_SHIP_VIA_FACILITY_ID,
  OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID AS OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID,
  OMS_DES_SHIP_VIA_FACILITY_ID AS OMS_DES_SHIP_VIA_FACILITY_ID,
  OMS_CUSTOMER_CD AS OMS_CUSTOMER_CD,
  CUSTOMER_FIRST_NAME AS CUSTOMER_FIRST_NAME,
  CUSTOMER_LAST_NAME AS CUSTOMER_LAST_NAME,
  CUSTOMER_PHONE_NBR AS CUSTOMER_PHONE_NBR,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  OMS_RETURN_REFERENCE_NBR AS OMS_RETURN_REFERENCE_NBR,
  OMS_BILL_OF_LADING_NBR AS OMS_BILL_OF_LADING_NBR,
  OMS_TRANS_RESP_CD AS OMS_TRANS_RESP_CD,
  OMS_COMMODITY_CODE_ID AS OMS_COMMODITY_CODE_ID,
  OMS_CARRIER_ID AS OMS_CARRIER_ID,
  OMS_PRODUCT_CLASS_ID AS OMS_PRODUCT_CLASS_ID,
  OMS_PROTECTION_LEVEL_ID AS OMS_PROTECTION_LEVEL_ID,
  OMS_CREATION_TYPE_ID AS OMS_CREATION_TYPE_ID,
  OMS_CHANNEL_TYPE_ID AS OMS_CHANNEL_TYPE_ID,
  OMS_CHANNEL_ID AS OMS_CHANNEL_ID,
  OMS_FULFILL_MODE_ID AS OMS_FULFILL_MODE_ID,
  OMS_ENTERED_BY AS OMS_ENTERED_BY,
  OMS_ENTRY_CD AS OMS_ENTRY_CD,
  OMS_PAYMENT_MODE_ID AS OMS_PAYMENT_MODE_ID,
  OMS_PAYMENT_STATUS_ID AS OMS_PAYMENT_STATUS_ID,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  ORDER_RECEIVED_FLAG AS ORDER_RECEIVED_FLAG,
  ON_HOLD_FLAG AS ON_HOLD_FLAG,
  HAS_ALERTS_FLAG AS HAS_ALERTS_FLAG,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  CLOSED_FLAG AS CLOSED_FLAG,
  OMS_REASON_ID AS OMS_REASON_ID,
  OMS_DECLINE_REASON_ID AS OMS_DECLINE_REASON_ID,
  OMS_REASON_CODES_GROUP_ID AS OMS_REASON_CODES_GROUP_ID,
  IMPORTED_FLAG AS IMPORTED_FLAG,
  PURCHASE_ORDERS_RECONCILED_FLAG AS PURCHASE_ORDERS_RECONCILED_FLAG,
  READY_TO_SHIP_FLAG AS READY_TO_SHIP_FLAG,
  CUSTOMER_PICKUP_FLAG AS CUSTOMER_PICKUP_FLAG,
  DIRECT_ALLOWED_FLAG AS DIRECT_ALLOWED_FLAG,
  PARTIALLY_PLANNED_FLAG AS PARTIALLY_PLANNED_FLAG,
  OMS_PURCHASE_ORDERS_DT_TSTMP AS OMS_PURCHASE_ORDERS_DT_TSTMP,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PICKUP_TZ_ID AS OMS_PICKUP_TZ_ID,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_DELIVERY_TZ_ID AS OMS_DELIVERY_TZ_ID,
  OMS_REQUESTED_DLVR_TSTMP AS OMS_REQUESTED_DLVR_TSTMP,
  OMS_MUST_DLVR_TSTMP AS OMS_MUST_DLVR_TSTMP,
  OMS_PROMISED_DLVR_TSTMP AS OMS_PROMISED_DLVR_TSTMP,
  OMS_DUE_DT AS OMS_DUE_DT,
  OMS_CANCEL_DT AS OMS_CANCEL_DT,
  OMS_RELEASE_TSTMP AS OMS_RELEASE_TSTMP,
  OMS_FIRST_RCPT_TSTMP AS OMS_FIRST_RCPT_TSTMP,
  OMS_LAST_RCPT_TSTMP AS OMS_LAST_RCPT_TSTMP,
  MONETARY_VALUE AS MONETARY_VALUE,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  ORIG_BUDG_COST AS ORIG_BUDG_COST,
  BUDG_COST AS BUDG_COST,
  BUDG_COST_CURRENCY_CD AS BUDG_COST_CURRENCY_CD,
  TAX_CHARGES_AMT AS TAX_CHARGES_AMT,
  MISC_CHARGES_AMT AS MISC_CHARGES_AMT,
  GRAND_TOTAL_AMT AS GRAND_TOTAL_AMT,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  CURRENCY_CD AS CURRENCY_CD,
  OMS_CREATED_SOURCE_TYPE_ID AS OMS_CREATED_SOURCE_TYPE_ID,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_PURCHASE_ORDERS"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("Shortcut_to_OMS_PURCHASE_ORDERS_2")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_PURCHASE_ORDERS_3


query_3 = f"""SELECT
  OMS_PURCHASE_ORDERS_ID AS OMS_PURCHASE_ORDERS_ID,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  OMS_EXT_PURCHASE_ORDERS_ID AS OMS_EXT_PURCHASE_ORDERS_ID,
  OMS_PARENT_PURCHASE_ORDERS_ID AS OMS_PARENT_PURCHASE_ORDERS_ID,
  OMS_PURCHASE_ORDERS_TYPE_ID AS OMS_PURCHASE_ORDERS_TYPE_ID,
  OMS_PURCHASE_ORDERS_STATUS_ID AS OMS_PURCHASE_ORDERS_STATUS_ID,
  OMS_ORDER_CATEGORY_ID AS OMS_ORDER_CATEGORY_ID,
  OMS_O_FACILITY_ID AS OMS_O_FACILITY_ID,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  OMS_D_FACILITY_ID AS OMS_D_FACILITY_ID,
  OMS_D_FACILITY_ALIAS_ID AS OMS_D_FACILITY_ALIAS_ID,
  OMS_BILL_FACILITY_ID AS OMS_BILL_FACILITY_ID,
  OMS_BILL_FACILITY_ALIAS_ID AS OMS_BILL_FACILITY_ALIAS_ID,
  OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID AS OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID,
  OMS_ORIGIN_SHIP_VIA_FACILITY_ID AS OMS_ORIGIN_SHIP_VIA_FACILITY_ID,
  OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID AS OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID,
  OMS_DES_SHIP_VIA_FACILITY_ID AS OMS_DES_SHIP_VIA_FACILITY_ID,
  OMS_CUSTOMER_CD AS OMS_CUSTOMER_CD,
  CUSTOMER_FIRST_NAME AS CUSTOMER_FIRST_NAME,
  CUSTOMER_LAST_NAME AS CUSTOMER_LAST_NAME,
  CUSTOMER_PHONE_NBR AS CUSTOMER_PHONE_NBR,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  OMS_RETURN_REFERENCE_NBR AS OMS_RETURN_REFERENCE_NBR,
  OMS_BILL_OF_LADING_NBR AS OMS_BILL_OF_LADING_NBR,
  OMS_TRANS_RESP_CD AS OMS_TRANS_RESP_CD,
  OMS_COMMODITY_CODE_ID AS OMS_COMMODITY_CODE_ID,
  OMS_CARRIER_ID AS OMS_CARRIER_ID,
  OMS_PRODUCT_CLASS_ID AS OMS_PRODUCT_CLASS_ID,
  OMS_PROTECTION_LEVEL_ID AS OMS_PROTECTION_LEVEL_ID,
  OMS_CREATION_TYPE_ID AS OMS_CREATION_TYPE_ID,
  OMS_CHANNEL_TYPE_ID AS OMS_CHANNEL_TYPE_ID,
  OMS_CHANNEL_ID AS OMS_CHANNEL_ID,
  OMS_FULFILL_MODE_ID AS OMS_FULFILL_MODE_ID,
  OMS_ENTERED_BY AS OMS_ENTERED_BY,
  OMS_ENTRY_CD AS OMS_ENTRY_CD,
  OMS_PAYMENT_MODE_ID AS OMS_PAYMENT_MODE_ID,
  OMS_PAYMENT_STATUS_ID AS OMS_PAYMENT_STATUS_ID,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  ORDER_RECEIVED_FLAG AS ORDER_RECEIVED_FLAG,
  ON_HOLD_FLAG AS ON_HOLD_FLAG,
  HAS_ALERTS_FLAG AS HAS_ALERTS_FLAG,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  CLOSED_FLAG AS CLOSED_FLAG,
  OMS_REASON_ID AS OMS_REASON_ID,
  OMS_DECLINE_REASON_ID AS OMS_DECLINE_REASON_ID,
  OMS_REASON_CODES_GROUP_ID AS OMS_REASON_CODES_GROUP_ID,
  IMPORTED_FLAG AS IMPORTED_FLAG,
  PURCHASE_ORDERS_RECONCILED_FLAG AS PURCHASE_ORDERS_RECONCILED_FLAG,
  READY_TO_SHIP_FLAG AS READY_TO_SHIP_FLAG,
  CUSTOMER_PICKUP_FLAG AS CUSTOMER_PICKUP_FLAG,
  DIRECT_ALLOWED_FLAG AS DIRECT_ALLOWED_FLAG,
  PARTIALLY_PLANNED_FLAG AS PARTIALLY_PLANNED_FLAG,
  OMS_PURCHASE_ORDERS_DT_TSTMP AS OMS_PURCHASE_ORDERS_DT_TSTMP,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PICKUP_TZ_ID AS OMS_PICKUP_TZ_ID,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_DELIVERY_TZ_ID AS OMS_DELIVERY_TZ_ID,
  OMS_REQUESTED_DLVR_TSTMP AS OMS_REQUESTED_DLVR_TSTMP,
  OMS_MUST_DLVR_TSTMP AS OMS_MUST_DLVR_TSTMP,
  OMS_PROMISED_DLVR_TSTMP AS OMS_PROMISED_DLVR_TSTMP,
  OMS_DUE_DT AS OMS_DUE_DT,
  OMS_CANCEL_DT AS OMS_CANCEL_DT,
  OMS_RELEASE_TSTMP AS OMS_RELEASE_TSTMP,
  OMS_FIRST_RCPT_TSTMP AS OMS_FIRST_RCPT_TSTMP,
  OMS_LAST_RCPT_TSTMP AS OMS_LAST_RCPT_TSTMP,
  MONETARY_VALUE AS MONETARY_VALUE,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  ORIG_BUDG_COST AS ORIG_BUDG_COST,
  BUDG_COST AS BUDG_COST,
  BUDG_COST_CURRENCY_CD AS BUDG_COST_CURRENCY_CD,
  TAX_CHARGES_AMT AS TAX_CHARGES_AMT,
  MISC_CHARGES_AMT AS MISC_CHARGES_AMT,
  GRAND_TOTAL_AMT AS GRAND_TOTAL_AMT,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  CURRENCY_CD AS CURRENCY_CD,
  OMS_CREATED_SOURCE_TYPE_ID AS OMS_CREATED_SOURCE_TYPE_ID,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_PURCHASE_ORDERS_2"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("SQ_Shortcut_to_OMS_PURCHASE_ORDERS_3")

# COMMAND ----------
# DBTITLE 1, JNR_OMS_PURCHASE_ORDERS_4


query_4 = f"""SELECT
  DETAIL.PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  DETAIL.TC_COMPANY_ID AS TC_COMPANY_ID,
  DETAIL.CREATION_TYPE AS CREATION_TYPE,
  DETAIL.PURCHASE_ORDERS_TYPE AS PURCHASE_ORDERS_TYPE,
  DETAIL.PURCHASE_ORDERS_STATUS AS PURCHASE_ORDERS_STATUS,
  DETAIL.TC_PURCHASE_ORDERS_ID AS TC_PURCHASE_ORDERS_ID,
  DETAIL.PARENT_PURCHASE_ORDERS_ID AS PARENT_PURCHASE_ORDERS_ID,
  DETAIL.O_FACILITY_ID AS O_FACILITY_ID,
  DETAIL.O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  DETAIL.O_DOCK_ID AS O_DOCK_ID,
  DETAIL.D_FACILITY_ID AS D_FACILITY_ID,
  DETAIL.D_FACILITY_ALIAS_ID AS D_FACILITY_ALIAS_ID,
  DETAIL.BILL_FACILITY_ID AS BILL_FACILITY_ID,
  DETAIL.BILL_FACILITY_ALIAS_ID AS BILL_FACILITY_ALIAS_ID,
  DETAIL.ORG_SHIP_VIA_FACILITY_ALIAS_ID AS ORG_SHIP_VIA_FACILITY_ALIAS_ID,
  DETAIL.ORG_SHIP_VIA_FACILITY_ID AS ORG_SHIP_VIA_FACILITY_ID,
  DETAIL.DES_SHIP_VIA_FACILITY_ALIAS_ID AS DES_SHIP_VIA_FACILITY_ALIAS_ID,
  DETAIL.DES_SHIP_VIA_FACILITY_ID AS DES_SHIP_VIA_FACILITY_ID,
  DETAIL.PICKUP_TZ AS PICKUP_TZ,
  DETAIL.DELIVERY_TZ AS DELIVERY_TZ,
  DETAIL.PICKUP_START_DTTM AS PICKUP_START_DTTM,
  DETAIL.PICKUP_END_DTTM AS PICKUP_END_DTTM,
  DETAIL.DELIVERY_START_DTTM AS DELIVERY_START_DTTM,
  DETAIL.DELIVERY_END_DTTM AS DELIVERY_END_DTTM,
  DETAIL.REQUESTED_DLVR_DTTM AS REQUESTED_DLVR_DTTM,
  DETAIL.MUST_DLVR_DTTM AS MUST_DLVR_DTTM,
  DETAIL.PROMISED_DLVR_DTTM AS PROMISED_DLVR_DTTM,
  DETAIL.DUE_DT AS DUE_DT,
  DETAIL.CANCEL_DT AS CANCEL_DT,
  DETAIL.PURCHASE_ORDERS_DATE_DTTM AS PURCHASE_ORDERS_DATE_DTTM,
  DETAIL.RELEASE_DTTM AS RELEASE_DTTM,
  DETAIL.FIRST_RCPT_DTTM AS FIRST_RCPT_DTTM,
  DETAIL.LAST_RCPT_DTTM AS LAST_RCPT_DTTM,
  DETAIL.PAYMENT_MODE AS PAYMENT_MODE,
  DETAIL.MV_CURRENCY_CODE AS MV_CURRENCY_CODE,
  DETAIL.MONETARY_VALUE AS MONETARY_VALUE,
  DETAIL.CURRENCY_CODE AS CURRENCY_CODE,
  DETAIL.ORIG_BUDG_COST AS ORIG_BUDG_COST,
  DETAIL.BUDG_COST_CURRENCY_CODE AS BUDG_COST_CURRENCY_CODE,
  DETAIL.BUDG_COST AS BUDG_COST,
  DETAIL.TAX_CHARGES AS TAX_CHARGES,
  DETAIL.MISC_CHARGES AS MISC_CHARGES,
  DETAIL.IS_CANCELLED AS IS_CANCELLED,
  DETAIL.IS_IMPORTED AS IS_IMPORTED,
  DETAIL.IS_PURCHASE_ORDERS_RECONCILED AS IS_PURCHASE_ORDERS_RECONCILED,
  DETAIL.IS_READY_TO_SHIP AS IS_READY_TO_SHIP,
  DETAIL.IS_CUSTOMER_PICKUP AS IS_CUSTOMER_PICKUP,
  DETAIL.IS_DIRECT_ALLOWED AS IS_DIRECT_ALLOWED,
  DETAIL.IS_PARTIALLY_PLANNED AS IS_PARTIALLY_PLANNED,
  DETAIL.ON_HOLD AS ON_HOLD,
  DETAIL.BILL_OF_LADING_NUMBER AS BILL_OF_LADING_NUMBER,
  DETAIL.TRANS_RESP_CODE AS TRANS_RESP_CODE,
  DETAIL.COMMODITY_CODE_ID AS COMMODITY_CODE_ID,
  DETAIL.CARRIER_ID AS CARRIER_ID,
  DETAIL.PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  DETAIL.PROTECTION_LEVEL_ID AS PROTECTION_LEVEL_ID,
  DETAIL.DECLINE_REASON_ID AS DECLINE_REASON_ID,
  DETAIL.CHANNEL_TYPE AS CHANNEL_TYPE,
  DETAIL.CUSTOMER_CODE AS CUSTOMER_CODE,
  DETAIL.CUSTOMER_FIRSTNAME AS CUSTOMER_FIRSTNAME,
  DETAIL.CUSTOMER_LASTNAME AS CUSTOMER_LASTNAME,
  DETAIL.CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  DETAIL.CREATED_SOURCE AS CREATED_SOURCE,
  DETAIL.CREATED_DTTM AS CREATED_DTTM,
  DETAIL.LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  DETAIL.DROPOFF_PICKUP AS DROPOFF_PICKUP,
  DETAIL.IS_CLOSED AS IS_CLOSED,
  DETAIL.GRAND_TOTAL AS GRAND_TOTAL,
  DETAIL.EXT_PURCHASE_ORDERS_ID AS EXT_PURCHASE_ORDERS_ID,
  DETAIL.ORDER_CATEGORY AS ORDER_CATEGORY,
  DETAIL.CHANNEL_ID AS CHANNEL_ID,
  DETAIL.FULFILL_MODE AS FULFILL_MODE,
  DETAIL.ENTERED_BY AS ENTERED_BY,
  DETAIL.ENTRY_CODE AS ENTRY_CODE,
  DETAIL.CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  DETAIL.CUSTOMER_PHONE AS CUSTOMER_PHONE,
  DETAIL.PAYMENT_STATUS AS PAYMENT_STATUS,
  DETAIL.REASON_ID AS REASON_ID,
  DETAIL.ORDER_RECEIVED AS ORDER_RECEIVED,
  DETAIL.FREIGHT_REVENUE AS FREIGHT_REVENUE,
  DETAIL.REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  DETAIL.RETURN_REFERENCE_NUMBER AS RETURN_REFERENCE_NUMBER,
  MASTER.OMS_PURCHASE_ORDERS_ID AS OMS_PURCHASE_ORDERS_ID,
  MASTER.OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  MASTER.OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  MASTER.OMS_EXT_PURCHASE_ORDERS_ID AS OMS_EXT_PURCHASE_ORDERS_ID,
  MASTER.OMS_PARENT_PURCHASE_ORDERS_ID AS OMS_PARENT_PURCHASE_ORDERS_ID,
  MASTER.OMS_PURCHASE_ORDERS_TYPE_ID AS OMS_PURCHASE_ORDERS_TYPE_ID,
  MASTER.OMS_PURCHASE_ORDERS_STATUS_ID AS OMS_PURCHASE_ORDERS_STATUS_ID,
  MASTER.OMS_ORDER_CATEGORY_ID AS OMS_ORDER_CATEGORY_ID,
  MASTER.OMS_O_FACILITY_ID AS OMS_O_FACILITY_ID,
  MASTER.OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  MASTER.OMS_D_FACILITY_ID AS OMS_D_FACILITY_ID,
  MASTER.OMS_D_FACILITY_ALIAS_ID AS OMS_D_FACILITY_ALIAS_ID,
  MASTER.OMS_BILL_FACILITY_ID AS OMS_BILL_FACILITY_ID,
  MASTER.OMS_BILL_FACILITY_ALIAS_ID AS OMS_BILL_FACILITY_ALIAS_ID,
  MASTER.OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID AS OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID,
  MASTER.OMS_ORIGIN_SHIP_VIA_FACILITY_ID AS OMS_ORIGIN_SHIP_VIA_FACILITY_ID,
  MASTER.OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID AS OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID,
  MASTER.OMS_DES_SHIP_VIA_FACILITY_ID AS OMS_DES_SHIP_VIA_FACILITY_ID,
  MASTER.OMS_CUSTOMER_CD AS OMS_CUSTOMER_CD,
  MASTER.CUSTOMER_FIRST_NAME AS lkp_CUSTOMER_FIRST_NAME,
  MASTER.CUSTOMER_LAST_NAME AS lkp_CUSTOMER_LAST_NAME,
  MASTER.CUSTOMER_PHONE_NBR AS lkp_CUSTOMER_PHONE_NBR,
  MASTER.CUSTOMER_EMAIL AS lkp_CUSTOMER_EMAIL,
  MASTER.OMS_RETURN_REFERENCE_NBR AS OMS_RETURN_REFERENCE_NBR,
  MASTER.OMS_BILL_OF_LADING_NBR AS OMS_BILL_OF_LADING_NBR,
  MASTER.OMS_TRANS_RESP_CD AS OMS_TRANS_RESP_CD,
  MASTER.OMS_COMMODITY_CODE_ID AS OMS_COMMODITY_CODE_ID,
  MASTER.OMS_CARRIER_ID AS OMS_CARRIER_ID,
  MASTER.OMS_PRODUCT_CLASS_ID AS OMS_PRODUCT_CLASS_ID,
  MASTER.OMS_PROTECTION_LEVEL_ID AS OMS_PROTECTION_LEVEL_ID,
  MASTER.OMS_CREATION_TYPE_ID AS OMS_CREATION_TYPE_ID,
  MASTER.OMS_CHANNEL_TYPE_ID AS OMS_CHANNEL_TYPE_ID,
  MASTER.OMS_CHANNEL_ID AS OMS_CHANNEL_ID,
  MASTER.OMS_FULFILL_MODE_ID AS OMS_FULFILL_MODE_ID,
  MASTER.OMS_ENTERED_BY AS OMS_ENTERED_BY,
  MASTER.OMS_ENTRY_CD AS OMS_ENTRY_CD,
  MASTER.OMS_PAYMENT_MODE_ID AS OMS_PAYMENT_MODE_ID,
  MASTER.OMS_PAYMENT_STATUS_ID AS OMS_PAYMENT_STATUS_ID,
  MASTER.DROPOFF_PICKUP AS lkp_DROPOFF_PICKUP,
  MASTER.ORDER_RECEIVED_FLAG AS lkp_ORDER_RECEIVED_FLAG,
  MASTER.ON_HOLD_FLAG AS lkp_ON_HOLD_FLAG,
  MASTER.CANCELLED_FLAG AS lkp_CANCELLED_FLAG,
  MASTER.CLOSED_FLAG AS lkp_CLOSED_FLAG,
  MASTER.OMS_REASON_ID AS OMS_REASON_ID,
  MASTER.OMS_DECLINE_REASON_ID AS OMS_DECLINE_REASON_ID,
  MASTER.OMS_REASON_CODES_GROUP_ID AS OMS_REASON_CODES_GROUP_ID,
  MASTER.IMPORTED_FLAG AS lkp_IMPORTED_FLAG,
  MASTER.PURCHASE_ORDERS_RECONCILED_FLAG AS lkp_PURCHASE_ORDERS_RECONCILED_FLAG,
  MASTER.READY_TO_SHIP_FLAG AS lkp_READY_TO_SHIP_FLAG,
  MASTER.CUSTOMER_PICKUP_FLAG AS lkp_CUSTOMER_PICKUP_FLAG,
  MASTER.DIRECT_ALLOWED_FLAG AS lkp_DIRECT_ALLOWED_FLAG,
  MASTER.PARTIALLY_PLANNED_FLAG AS lkp_PARTIALLY_PLANNED_FLAG,
  MASTER.OMS_PURCHASE_ORDERS_DT_TSTMP AS OMS_PURCHASE_ORDERS_DT_TSTMP,
  MASTER.OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  MASTER.OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  MASTER.OMS_PICKUP_TZ_ID AS OMS_PICKUP_TZ_ID,
  MASTER.OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  MASTER.OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  MASTER.OMS_DELIVERY_TZ_ID AS OMS_DELIVERY_TZ_ID,
  MASTER.OMS_REQUESTED_DLVR_TSTMP AS OMS_REQUESTED_DLVR_TSTMP,
  MASTER.OMS_MUST_DLVR_TSTMP AS OMS_MUST_DLVR_TSTMP,
  MASTER.OMS_PROMISED_DLVR_TSTMP AS OMS_PROMISED_DLVR_TSTMP,
  MASTER.OMS_DUE_DT AS OMS_DUE_DT,
  MASTER.OMS_CANCEL_DT AS OMS_CANCEL_DT,
  MASTER.OMS_RELEASE_TSTMP AS OMS_RELEASE_TSTMP,
  MASTER.OMS_FIRST_RCPT_TSTMP AS OMS_FIRST_RCPT_TSTMP,
  MASTER.OMS_LAST_RCPT_TSTMP AS OMS_LAST_RCPT_TSTMP,
  MASTER.MONETARY_VALUE AS lkp_MONETARY_VALUE,
  MASTER.MV_CURRENCY_CD AS lkp_MV_CURRENCY_CD,
  MASTER.ORIG_BUDG_COST AS lkp_ORIG_BUDG_COST,
  MASTER.BUDG_COST AS lkp_BUDG_COST,
  MASTER.BUDG_COST_CURRENCY_CD AS lkp_BUDG_COST_CURRENCY_CD,
  MASTER.TAX_CHARGES_AMT AS lkp_TAX_CHARGES_AMT,
  MASTER.MISC_CHARGES_AMT AS lkp_MISC_CHARGES_AMT,
  MASTER.GRAND_TOTAL_AMT AS lkp_GRAND_TOTAL_AMT,
  MASTER.FREIGHT_REVENUE_AMT AS lkp_FREIGHT_REVENUE_AMT,
  MASTER.CURRENCY_CD AS lkp_CURRENCY_CD,
  MASTER.OMS_CREATED_SOURCE_TYPE_ID AS OMS_CREATED_SOURCE_TYPE_ID,
  MASTER.OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  MASTER.OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  MASTER.OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  MASTER.LOAD_TSTMP AS lkp_LOAD_TSTMP,
  MASTER.HAS_ALERTS_FLAG AS lkp_HAS_ALERTS_FLAG,
  DETAIL.HAS_ALERTS AS HAS_ALERTS,
  DETAIL.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_PURCHASE_ORDERS_3 MASTER
  RIGHT JOIN SQ_Shortcut_to_OMS_PURCHASE_ORDERS_PRE_1 DETAIL ON MASTER.OMS_PURCHASE_ORDERS_ID = DETAIL.PURCHASE_ORDERS_ID"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("JNR_OMS_PURCHASE_ORDERS_4")

# COMMAND ----------
# DBTITLE 1, EXP_UPD_VALIDATOR_5


query_5 = f"""SELECT
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  TC_COMPANY_ID AS TC_COMPANY_ID,
  CREATION_TYPE AS CREATION_TYPE,
  PURCHASE_ORDERS_TYPE AS PURCHASE_ORDERS_TYPE,
  PURCHASE_ORDERS_STATUS AS PURCHASE_ORDERS_STATUS,
  TC_PURCHASE_ORDERS_ID AS TC_PURCHASE_ORDERS_ID,
  PARENT_PURCHASE_ORDERS_ID AS PARENT_PURCHASE_ORDERS_ID,
  O_FACILITY_ID AS O_FACILITY_ID,
  O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  O_DOCK_ID AS O_DOCK_ID,
  D_FACILITY_ID AS D_FACILITY_ID,
  D_FACILITY_ALIAS_ID AS D_FACILITY_ALIAS_ID,
  BILL_FACILITY_ID AS BILL_FACILITY_ID,
  BILL_FACILITY_ALIAS_ID AS BILL_FACILITY_ALIAS_ID,
  ORG_SHIP_VIA_FACILITY_ALIAS_ID AS ORG_SHIP_VIA_FACILITY_ALIAS_ID,
  ORG_SHIP_VIA_FACILITY_ID AS ORG_SHIP_VIA_FACILITY_ID,
  DES_SHIP_VIA_FACILITY_ALIAS_ID AS DES_SHIP_VIA_FACILITY_ALIAS_ID,
  DES_SHIP_VIA_FACILITY_ID AS DES_SHIP_VIA_FACILITY_ID,
  PICKUP_TZ AS PICKUP_TZ,
  DELIVERY_TZ AS DELIVERY_TZ,
  PICKUP_START_DTTM AS PICKUP_START_DTTM,
  PICKUP_END_DTTM AS PICKUP_END_DTTM,
  DELIVERY_START_DTTM AS DELIVERY_START_DTTM,
  DELIVERY_END_DTTM AS DELIVERY_END_DTTM,
  REQUESTED_DLVR_DTTM AS REQUESTED_DLVR_DTTM,
  MUST_DLVR_DTTM AS MUST_DLVR_DTTM,
  PROMISED_DLVR_DTTM AS PROMISED_DLVR_DTTM,
  DUE_DT AS DUE_DT,
  CANCEL_DT AS CANCEL_DT,
  PURCHASE_ORDERS_DATE_DTTM AS PURCHASE_ORDERS_DATE_DTTM,
  RELEASE_DTTM AS RELEASE_DTTM,
  FIRST_RCPT_DTTM AS FIRST_RCPT_DTTM,
  LAST_RCPT_DTTM AS LAST_RCPT_DTTM,
  PAYMENT_MODE AS PAYMENT_MODE,
  MV_CURRENCY_CODE AS MV_CURRENCY_CODE,
  MONETARY_VALUE AS MONETARY_VALUE,
  CURRENCY_CODE AS CURRENCY_CODE,
  ORIG_BUDG_COST AS ORIG_BUDG_COST,
  BUDG_COST_CURRENCY_CODE AS BUDG_COST_CURRENCY_CODE,
  BUDG_COST AS BUDG_COST,
  TAX_CHARGES AS TAX_CHARGES,
  MISC_CHARGES AS MISC_CHARGES,
  IS_CANCELLED AS IS_CANCELLED,
  IS_IMPORTED AS IS_IMPORTED,
  IS_PURCHASE_ORDERS_RECONCILED AS IS_PURCHASE_ORDERS_RECONCILED,
  IS_READY_TO_SHIP AS IS_READY_TO_SHIP,
  IS_CUSTOMER_PICKUP AS IS_CUSTOMER_PICKUP,
  IS_DIRECT_ALLOWED AS IS_DIRECT_ALLOWED,
  IS_PARTIALLY_PLANNED AS IS_PARTIALLY_PLANNED,
  ON_HOLD AS ON_HOLD,
  BILL_OF_LADING_NUMBER AS BILL_OF_LADING_NUMBER,
  TRANS_RESP_CODE AS TRANS_RESP_CODE,
  COMMODITY_CODE_ID AS COMMODITY_CODE_ID,
  CARRIER_ID AS CARRIER_ID,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  PROTECTION_LEVEL_ID AS PROTECTION_LEVEL_ID,
  DECLINE_REASON_ID AS DECLINE_REASON_ID,
  CHANNEL_TYPE AS CHANNEL_TYPE,
  CUSTOMER_CODE AS CUSTOMER_CODE,
  CUSTOMER_FIRSTNAME AS CUSTOMER_FIRSTNAME,
  CUSTOMER_LASTNAME AS CUSTOMER_LASTNAME,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  IS_CLOSED AS IS_CLOSED,
  GRAND_TOTAL AS GRAND_TOTAL,
  EXT_PURCHASE_ORDERS_ID AS EXT_PURCHASE_ORDERS_ID,
  ORDER_CATEGORY AS ORDER_CATEGORY,
  CHANNEL_ID AS CHANNEL_ID,
  FULFILL_MODE AS FULFILL_MODE,
  ENTERED_BY AS ENTERED_BY,
  ENTRY_CODE AS ENTRY_CODE,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  CUSTOMER_PHONE AS CUSTOMER_PHONE,
  PAYMENT_STATUS AS PAYMENT_STATUS,
  REASON_ID AS REASON_ID,
  ORDER_RECEIVED AS ORDER_RECEIVED,
  FREIGHT_REVENUE AS FREIGHT_REVENUE,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  RETURN_REFERENCE_NUMBER AS RETURN_REFERENCE_NUMBER,
  OMS_PURCHASE_ORDERS_ID AS OMS_PURCHASE_ORDERS_ID,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  OMS_EXT_PURCHASE_ORDERS_ID AS OMS_EXT_PURCHASE_ORDERS_ID,
  OMS_PARENT_PURCHASE_ORDERS_ID AS OMS_PARENT_PURCHASE_ORDERS_ID,
  OMS_PURCHASE_ORDERS_TYPE_ID AS OMS_PURCHASE_ORDERS_TYPE_ID,
  OMS_PURCHASE_ORDERS_STATUS_ID AS OMS_PURCHASE_ORDERS_STATUS_ID,
  OMS_ORDER_CATEGORY_ID AS OMS_ORDER_CATEGORY_ID,
  OMS_O_FACILITY_ID AS OMS_O_FACILITY_ID,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  OMS_D_FACILITY_ID AS OMS_D_FACILITY_ID,
  OMS_D_FACILITY_ALIAS_ID AS OMS_D_FACILITY_ALIAS_ID,
  OMS_BILL_FACILITY_ID AS OMS_BILL_FACILITY_ID,
  OMS_BILL_FACILITY_ALIAS_ID AS OMS_BILL_FACILITY_ALIAS_ID,
  OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID AS OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID,
  OMS_ORIGIN_SHIP_VIA_FACILITY_ID AS OMS_ORIGIN_SHIP_VIA_FACILITY_ID,
  OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID AS OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID,
  OMS_DES_SHIP_VIA_FACILITY_ID AS OMS_DES_SHIP_VIA_FACILITY_ID,
  OMS_CUSTOMER_CD AS OMS_CUSTOMER_CD,
  lkp_CUSTOMER_FIRST_NAME AS lkp_CUSTOMER_FIRST_NAME,
  lkp_CUSTOMER_LAST_NAME AS lkp_CUSTOMER_LAST_NAME,
  lkp_CUSTOMER_PHONE_NBR AS lkp_CUSTOMER_PHONE_NBR,
  lkp_CUSTOMER_EMAIL AS lkp_CUSTOMER_EMAIL,
  OMS_RETURN_REFERENCE_NBR AS OMS_RETURN_REFERENCE_NBR,
  OMS_BILL_OF_LADING_NBR AS OMS_BILL_OF_LADING_NBR,
  OMS_TRANS_RESP_CD AS OMS_TRANS_RESP_CD,
  OMS_COMMODITY_CODE_ID AS OMS_COMMODITY_CODE_ID,
  OMS_CARRIER_ID AS OMS_CARRIER_ID,
  OMS_PRODUCT_CLASS_ID AS OMS_PRODUCT_CLASS_ID,
  OMS_PROTECTION_LEVEL_ID AS OMS_PROTECTION_LEVEL_ID,
  OMS_CREATION_TYPE_ID AS OMS_CREATION_TYPE_ID,
  OMS_CHANNEL_TYPE_ID AS OMS_CHANNEL_TYPE_ID,
  OMS_CHANNEL_ID AS OMS_CHANNEL_ID,
  OMS_FULFILL_MODE_ID AS OMS_FULFILL_MODE_ID,
  OMS_ENTERED_BY AS OMS_ENTERED_BY,
  OMS_ENTRY_CD AS OMS_ENTRY_CD,
  OMS_PAYMENT_MODE_ID AS OMS_PAYMENT_MODE_ID,
  OMS_PAYMENT_STATUS_ID AS OMS_PAYMENT_STATUS_ID,
  lkp_DROPOFF_PICKUP AS lkp_DROPOFF_PICKUP,
  lkp_ORDER_RECEIVED_FLAG AS lkp_ORDER_RECEIVED_FLAG,
  lkp_ON_HOLD_FLAG AS lkp_ON_HOLD_FLAG,
  lkp_CANCELLED_FLAG AS lkp_CANCELLED_FLAG,
  lkp_CLOSED_FLAG AS lkp_CLOSED_FLAG,
  OMS_REASON_ID AS OMS_REASON_ID,
  OMS_DECLINE_REASON_ID AS OMS_DECLINE_REASON_ID,
  OMS_REASON_CODES_GROUP_ID AS OMS_REASON_CODES_GROUP_ID,
  lkp_IMPORTED_FLAG AS lkp_IMPORTED_FLAG,
  lkp_PURCHASE_ORDERS_RECONCILED_FLAG AS lkp_PURCHASE_ORDERS_RECONCILED_FLAG,
  lkp_READY_TO_SHIP_FLAG AS lkp_READY_TO_SHIP_FLAG,
  lkp_CUSTOMER_PICKUP_FLAG AS lkp_CUSTOMER_PICKUP_FLAG,
  lkp_DIRECT_ALLOWED_FLAG AS lkp_DIRECT_ALLOWED_FLAG,
  lkp_PARTIALLY_PLANNED_FLAG AS lkp_PARTIALLY_PLANNED_FLAG,
  OMS_PURCHASE_ORDERS_DT_TSTMP AS OMS_PURCHASE_ORDERS_DT_TSTMP,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PICKUP_TZ_ID AS OMS_PICKUP_TZ_ID,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_DELIVERY_TZ_ID AS OMS_DELIVERY_TZ_ID,
  OMS_REQUESTED_DLVR_TSTMP AS OMS_REQUESTED_DLVR_TSTMP,
  OMS_MUST_DLVR_TSTMP AS OMS_MUST_DLVR_TSTMP,
  OMS_PROMISED_DLVR_TSTMP AS OMS_PROMISED_DLVR_TSTMP,
  OMS_DUE_DT AS OMS_DUE_DT,
  OMS_CANCEL_DT AS OMS_CANCEL_DT,
  OMS_RELEASE_TSTMP AS OMS_RELEASE_TSTMP,
  OMS_FIRST_RCPT_TSTMP AS OMS_FIRST_RCPT_TSTMP,
  OMS_LAST_RCPT_TSTMP AS OMS_LAST_RCPT_TSTMP,
  lkp_MONETARY_VALUE AS lkp_MONETARY_VALUE,
  lkp_MV_CURRENCY_CD AS lkp_MV_CURRENCY_CD,
  lkp_ORIG_BUDG_COST AS lkp_ORIG_BUDG_COST,
  lkp_BUDG_COST AS lkp_BUDG_COST,
  lkp_BUDG_COST_CURRENCY_CD AS lkp_BUDG_COST_CURRENCY_CD,
  lkp_TAX_CHARGES_AMT AS lkp_TAX_CHARGES_AMT,
  lkp_MISC_CHARGES_AMT AS lkp_MISC_CHARGES_AMT,
  lkp_GRAND_TOTAL_AMT AS lkp_GRAND_TOTAL_AMT,
  lkp_FREIGHT_REVENUE_AMT AS lkp_FREIGHT_REVENUE_AMT,
  lkp_CURRENCY_CD AS lkp_CURRENCY_CD,
  OMS_CREATED_SOURCE_TYPE_ID AS OMS_CREATED_SOURCE_TYPE_ID,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  lkp_LOAD_TSTMP AS lkp_LOAD_TSTMP,
  now() AS UPDATE_TSTMP_exp,
  IFF(ISNULL(lkp_LOAD_TSTMP), now(), lkp_LOAD_TSTMP) AS LOAD_TSTMP_exp,
  IFF(
    ISNULL(OMS_PURCHASE_ORDERS_ID),
    'INSERT',
    IFF(
      (
        IFF(ISNULL(TC_COMPANY_ID), 99, TC_COMPANY_ID) <> IFF(ISNULL(OMS_TC_COMPANY_ID), 99, OMS_TC_COMPANY_ID)
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(TC_PURCHASE_ORDERS_ID),
              '',
              TC_PURCHASE_ORDERS_ID
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(OMS_TC_PURCHASE_ORDERS_ID),
              '',
              OMS_TC_PURCHASE_ORDERS_ID
            )
          )
        )
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(EXT_PURCHASE_ORDERS_ID),
              '',
              EXT_PURCHASE_ORDERS_ID
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(OMS_EXT_PURCHASE_ORDERS_ID),
              '',
              OMS_EXT_PURCHASE_ORDERS_ID
            )
          )
        )
        OR IFF(
          ISNULL(PARENT_PURCHASE_ORDERS_ID),
          99,
          PARENT_PURCHASE_ORDERS_ID
        ) != IFF(
          ISNULL(OMS_PARENT_PURCHASE_ORDERS_ID),
          99,
          OMS_PARENT_PURCHASE_ORDERS_ID
        )
        OR IFF(
          ISNULL(PURCHASE_ORDERS_TYPE),
          99,
          PURCHASE_ORDERS_TYPE
        ) != IFF(
          ISNULL(OMS_PURCHASE_ORDERS_TYPE_ID),
          99,
          OMS_PURCHASE_ORDERS_TYPE_ID
        )
        OR IFF(
          ISNULL(PURCHASE_ORDERS_STATUS),
          99,
          PURCHASE_ORDERS_STATUS
        ) != IFF(
          ISNULL(OMS_PURCHASE_ORDERS_STATUS_ID),
          99,
          OMS_PURCHASE_ORDERS_STATUS_ID
        )
        OR IFF(ISNULL(ORDER_CATEGORY), 99, ORDER_CATEGORY) != IFF(
          ISNULL(OMS_ORDER_CATEGORY_ID),
          99,
          OMS_ORDER_CATEGORY_ID
        )
        OR IFF(ISNULL(O_FACILITY_ID), 99, O_FACILITY_ID) != IFF(ISNULL(OMS_O_FACILITY_ID), 99, OMS_O_FACILITY_ID)
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(O_FACILITY_ALIAS_ID),
              '',
              O_FACILITY_ALIAS_ID
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(OMS_O_FACILITY_ALIAS_ID),
              '',
              OMS_O_FACILITY_ALIAS_ID
            )
          )
        )
        OR IFF(ISNULL(D_FACILITY_ID), 99, D_FACILITY_ID) != IFF(ISNULL(OMS_D_FACILITY_ID), 99, OMS_D_FACILITY_ID)
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(D_FACILITY_ALIAS_ID),
              '',
              D_FACILITY_ALIAS_ID
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(OMS_D_FACILITY_ALIAS_ID),
              '',
              OMS_D_FACILITY_ALIAS_ID
            )
          )
        )
        OR IFF(ISNULL(BILL_FACILITY_ID), 99, BILL_FACILITY_ID) != IFF(
          ISNULL(OMS_BILL_FACILITY_ID),
          99,
          OMS_BILL_FACILITY_ID
        )
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(BILL_FACILITY_ALIAS_ID),
              '',
              BILL_FACILITY_ALIAS_ID
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(OMS_BILL_FACILITY_ALIAS_ID),
              '',
              OMS_BILL_FACILITY_ALIAS_ID
            )
          )
        )
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(ORG_SHIP_VIA_FACILITY_ALIAS_ID),
              '',
              ORG_SHIP_VIA_FACILITY_ALIAS_ID
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID),
              '',
              OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID
            )
          )
        )
        OR IFF(
          ISNULL(ORG_SHIP_VIA_FACILITY_ID),
          99,
          ORG_SHIP_VIA_FACILITY_ID
        ) != IFF(
          ISNULL(OMS_ORIGIN_SHIP_VIA_FACILITY_ID),
          99,
          OMS_ORIGIN_SHIP_VIA_FACILITY_ID
        )
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(DES_SHIP_VIA_FACILITY_ALIAS_ID),
              '',
              DES_SHIP_VIA_FACILITY_ALIAS_ID
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID),
              '',
              OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID
            )
          )
        )
        OR IFF(
          ISNULL(DES_SHIP_VIA_FACILITY_ID),
          99,
          DES_SHIP_VIA_FACILITY_ID
        ) != IFF(
          ISNULL(OMS_DES_SHIP_VIA_FACILITY_ID),
          99,
          OMS_DES_SHIP_VIA_FACILITY_ID
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(CUSTOMER_CODE), '', CUSTOMER_CODE))
        ) != LTRIM(
          RTRIM(IFF(ISNULL(OMS_CUSTOMER_CD), '', OMS_CUSTOMER_CD))
        )
        OR LTRIM(
          RTRIM(
            IFF(ISNULL(CUSTOMER_FIRSTNAME), '', CUSTOMER_FIRSTNAME)
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_CUSTOMER_FIRST_NAME),
              '',
              lkp_CUSTOMER_FIRST_NAME
            )
          )
        )
        OR LTRIM(
          RTRIM(
            IFF(ISNULL(CUSTOMER_LASTNAME), '', CUSTOMER_LASTNAME)
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_CUSTOMER_LAST_NAME),
              '',
              lkp_CUSTOMER_LAST_NAME
            )
          )
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(CUSTOMER_PHONE), '', CUSTOMER_PHONE))
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_CUSTOMER_PHONE_NBR),
              '',
              lkp_CUSTOMER_PHONE_NBR
            )
          )
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(CUSTOMER_EMAIL), '', CUSTOMER_EMAIL))
        ) != LTRIM(
          RTRIM(
            IFF(ISNULL(lkp_CUSTOMER_EMAIL), '', lkp_CUSTOMER_EMAIL)
          )
        )
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(RETURN_REFERENCE_NUMBER),
              '',
              RETURN_REFERENCE_NUMBER
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(OMS_RETURN_REFERENCE_NBR),
              '',
              OMS_RETURN_REFERENCE_NBR
            )
          )
        )
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(BILL_OF_LADING_NUMBER),
              '',
              BILL_OF_LADING_NUMBER
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(OMS_BILL_OF_LADING_NBR),
              '',
              OMS_BILL_OF_LADING_NBR
            )
          )
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(TRANS_RESP_CODE), '', TRANS_RESP_CODE))
        ) != LTRIM(
          RTRIM(
            IFF(ISNULL(OMS_TRANS_RESP_CD), '', OMS_TRANS_RESP_CD)
          )
        )
        OR IFF(ISNULL(COMMODITY_CODE_ID), 99, COMMODITY_CODE_ID) != IFF(
          ISNULL(OMS_COMMODITY_CODE_ID),
          99,
          OMS_COMMODITY_CODE_ID
        )
        OR IFF(ISNULL(CARRIER_ID), 99, CARRIER_ID) != IFF(ISNULL(OMS_CARRIER_ID), 99, OMS_CARRIER_ID)
        OR IFF(ISNULL(PRODUCT_CLASS_ID), 99, PRODUCT_CLASS_ID) != IFF(
          ISNULL(OMS_PRODUCT_CLASS_ID),
          99,
          OMS_PRODUCT_CLASS_ID
        )
        OR IFF(
          ISNULL(PROTECTION_LEVEL_ID),
          99,
          PROTECTION_LEVEL_ID
        ) != IFF(
          ISNULL(OMS_PROTECTION_LEVEL_ID),
          99,
          OMS_PROTECTION_LEVEL_ID
        )
        OR IFF(ISNULL(CREATION_TYPE), 99, CREATION_TYPE) != IFF(
          ISNULL(OMS_CREATION_TYPE_ID),
          99,
          OMS_CREATION_TYPE_ID
        )
        OR IFF(ISNULL(CHANNEL_TYPE), 99, CHANNEL_TYPE) != IFF(
          ISNULL(OMS_CHANNEL_TYPE_ID),
          99,
          OMS_CHANNEL_TYPE_ID
        )
        OR IFF(ISNULL(CHANNEL_ID), 99, CHANNEL_ID) != IFF(ISNULL(OMS_CHANNEL_ID), 99, OMS_CHANNEL_ID)
        OR IFF(ISNULL(FULFILL_MODE), 99, FULFILL_MODE) != IFF(
          ISNULL(OMS_FULFILL_MODE_ID),
          99,
          OMS_FULFILL_MODE_ID
        )
        OR LTRIM(RTRIM(IFF(ISNULL(ENTERED_BY), '', ENTERED_BY))) != LTRIM(
          RTRIM(IFF(ISNULL(OMS_ENTERED_BY), '', OMS_ENTERED_BY))
        )
        OR LTRIM(RTRIM(IFF(ISNULL(ENTRY_CODE), '', ENTRY_CODE))) != LTRIM(RTRIM(IFF(ISNULL(OMS_ENTRY_CD), '', OMS_ENTRY_CD)))
        OR IFF(ISNULL(PAYMENT_MODE), 99, PAYMENT_MODE) != IFF(
          ISNULL(OMS_PAYMENT_MODE_ID),
          99,
          OMS_PAYMENT_MODE_ID
        )
        OR IFF(ISNULL(PAYMENT_STATUS), 99, PAYMENT_STATUS) != IFF(
          ISNULL(OMS_PAYMENT_STATUS_ID),
          99,
          OMS_PAYMENT_STATUS_ID
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(DROPOFF_PICKUP), '', DROPOFF_PICKUP))
        ) != LTRIM(
          RTRIM(
            IFF(ISNULL(lkp_DROPOFF_PICKUP), '', lkp_DROPOFF_PICKUP)
          )
        )
        OR IFF(ISNULL(ORDER_RECEIVED), 99, ORDER_RECEIVED) != IFF(
          ISNULL(lkp_ORDER_RECEIVED_FLAG),
          99,
          lkp_ORDER_RECEIVED_FLAG
        )
        OR IFF(ISNULL(ON_HOLD), 99, ON_HOLD) != IFF(ISNULL(lkp_ON_HOLD_FLAG), 99, lkp_ON_HOLD_FLAG)
        OR IFF(ISNULL(IS_CANCELLED), 99, IS_CANCELLED) != IFF(ISNULL(lkp_CANCELLED_FLAG), 99, lkp_CANCELLED_FLAG)
        OR IFF(ISNULL(IS_CLOSED), 99, IS_CLOSED) != IFF(ISNULL(lkp_CLOSED_FLAG), 99, lkp_CLOSED_FLAG)
        OR IFF(ISNULL(REASON_ID), 99, REASON_ID) != IFF(ISNULL(OMS_REASON_ID), 99, OMS_REASON_ID)
        OR IFF(ISNULL(DECLINE_REASON_ID), 99, DECLINE_REASON_ID) != IFF(
          ISNULL(OMS_DECLINE_REASON_ID),
          99,
          OMS_DECLINE_REASON_ID
        )
        OR IFF(
          ISNULL(REASON_CODES_GROUP_ID),
          99,
          REASON_CODES_GROUP_ID
        ) != IFF(
          ISNULL(OMS_REASON_CODES_GROUP_ID),
          99,
          OMS_REASON_CODES_GROUP_ID
        )
        OR IFF(ISNULL(IS_IMPORTED), 99, IS_IMPORTED) != IFF(ISNULL(lkp_IMPORTED_FLAG), 99, lkp_IMPORTED_FLAG)
        OR IFF(
          ISNULL(IS_PURCHASE_ORDERS_RECONCILED),
          99,
          IS_PURCHASE_ORDERS_RECONCILED
        ) != IFF(
          ISNULL(lkp_PURCHASE_ORDERS_RECONCILED_FLAG),
          99,
          lkp_PURCHASE_ORDERS_RECONCILED_FLAG
        )
        OR IFF(ISNULL(IS_READY_TO_SHIP), 99, IS_READY_TO_SHIP) != IFF(
          ISNULL(lkp_READY_TO_SHIP_FLAG),
          99,
          lkp_READY_TO_SHIP_FLAG
        )
        OR IFF(ISNULL(IS_CUSTOMER_PICKUP), 99, IS_CUSTOMER_PICKUP) != IFF(
          ISNULL(lkp_CUSTOMER_PICKUP_FLAG),
          99,
          lkp_CUSTOMER_PICKUP_FLAG
        )
        OR IFF(ISNULL(IS_DIRECT_ALLOWED), 99, IS_DIRECT_ALLOWED) != IFF(
          ISNULL(lkp_DIRECT_ALLOWED_FLAG),
          99,
          lkp_DIRECT_ALLOWED_FLAG
        )
        OR IFF(
          ISNULL(IS_PARTIALLY_PLANNED),
          99,
          IS_PARTIALLY_PLANNED
        ) != IFF(
          ISNULL(lkp_PARTIALLY_PLANNED_FLAG),
          99,
          lkp_PARTIALLY_PLANNED_FLAG
        )
        OR IFF(ISNULL(HAS_ALERTS), 99, HAS_ALERTS) != IFF(
          ISNULL(lkp_HAS_ALERTS_FLAG),
          99,
          lkp_HAS_ALERTS_FLAG
        )
        OR (
          IFF(
            ISNULL(PURCHASE_ORDERS_DATE_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            PURCHASE_ORDERS_DATE_DTTM
          )
        ) != (
          IFF(
            ISNULL(OMS_PURCHASE_ORDERS_DT_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_PURCHASE_ORDERS_DT_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(PICKUP_START_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            PICKUP_START_DTTM
          )
        ) != (
          IFF(
            ISNULL(OMS_PICKUP_START_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_PICKUP_START_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(PICKUP_END_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            PICKUP_END_DTTM
          )
        ) != (
          IFF(
            ISNULL(OMS_PICKUP_END_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_PICKUP_END_TSTMP
          )
        )
        OR IFF(ISNULL(PICKUP_TZ), 99, PICKUP_TZ) != IFF(ISNULL(OMS_PICKUP_TZ_ID), 99, OMS_PICKUP_TZ_ID)
        OR (
          IFF(
            ISNULL(DELIVERY_START_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            DELIVERY_START_DTTM
          )
        ) != (
          IFF(
            ISNULL(OMS_DELIVERY_START_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_DELIVERY_START_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(DELIVERY_END_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            DELIVERY_END_DTTM
          )
        ) != (
          IFF(
            ISNULL(OMS_DELIVERY_END_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_DELIVERY_END_TSTMP
          )
        )
        OR IFF(ISNULL(DELIVERY_TZ), 99, DELIVERY_TZ) != IFF(ISNULL(OMS_DELIVERY_TZ_ID), 99, OMS_DELIVERY_TZ_ID)
        OR (
          IFF(
            ISNULL(REQUESTED_DLVR_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            REQUESTED_DLVR_DTTM
          )
        ) != (
          IFF(
            ISNULL(OMS_REQUESTED_DLVR_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_REQUESTED_DLVR_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(MUST_DLVR_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            MUST_DLVR_DTTM
          )
        ) != (
          IFF(
            ISNULL(OMS_MUST_DLVR_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_MUST_DLVR_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(PROMISED_DLVR_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            PROMISED_DLVR_DTTM
          )
        ) != (
          IFF(
            ISNULL(OMS_PROMISED_DLVR_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_PROMISED_DLVR_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(DUE_DT),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            DUE_DT
          )
        ) != (
          IFF(
            ISNULL(OMS_DUE_DT),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_DUE_DT
          )
        )
        OR (
          IFF(
            ISNULL(CANCEL_DT),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            CANCEL_DT
          )
        ) != (
          IFF(
            ISNULL(OMS_CANCEL_DT),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_CANCEL_DT
          )
        )
        OR (
          IFF(
            ISNULL(RELEASE_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            RELEASE_DTTM
          )
        ) != (
          IFF(
            ISNULL(OMS_RELEASE_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_RELEASE_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(FIRST_RCPT_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            FIRST_RCPT_DTTM
          )
        ) != (
          IFF(
            ISNULL(OMS_FIRST_RCPT_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_FIRST_RCPT_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(LAST_RCPT_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            LAST_RCPT_DTTM
          )
        ) != (
          IFF(
            ISNULL(OMS_LAST_RCPT_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_LAST_RCPT_TSTMP
          )
        )
        OR IFF(ISNULL(MONETARY_VALUE), 99, MONETARY_VALUE) != IFF(ISNULL(lkp_MONETARY_VALUE), 99, lkp_MONETARY_VALUE)
        OR LTRIM(
          RTRIM(
            IFF(ISNULL(MV_CURRENCY_CODE), '', MV_CURRENCY_CODE)
          )
        ) != LTRIM(
          RTRIM(
            IFF(ISNULL(lkp_MV_CURRENCY_CD), '', lkp_MV_CURRENCY_CD)
          )
        )
        OR IFF(ISNULL(ORIG_BUDG_COST), 99, ORIG_BUDG_COST) != IFF(ISNULL(lkp_ORIG_BUDG_COST), 99, lkp_ORIG_BUDG_COST)
        OR IFF(ISNULL(BUDG_COST), 99, BUDG_COST) != IFF(ISNULL(lkp_BUDG_COST), 99, lkp_BUDG_COST)
        OR LTRIM(
          RTRIM(
            IFF(
              ISNULL(BUDG_COST_CURRENCY_CODE),
              '',
              BUDG_COST_CURRENCY_CODE
            )
          )
        ) != LTRIM(
          RTRIM(
            IFF(
              ISNULL(lkp_BUDG_COST_CURRENCY_CD),
              '',
              lkp_BUDG_COST_CURRENCY_CD
            )
          )
        )
        OR IFF(ISNULL(TAX_CHARGES), 99, TAX_CHARGES) != IFF(
          ISNULL(lkp_TAX_CHARGES_AMT),
          99,
          lkp_TAX_CHARGES_AMT
        )
        OR IFF(ISNULL(MISC_CHARGES), 99, MISC_CHARGES) != IFF(
          ISNULL(lkp_MISC_CHARGES_AMT),
          99,
          lkp_MISC_CHARGES_AMT
        )
        OR IFF(ISNULL(GRAND_TOTAL), 99, GRAND_TOTAL) != IFF(
          ISNULL(lkp_GRAND_TOTAL_AMT),
          99,
          lkp_GRAND_TOTAL_AMT
        )
        OR IFF(ISNULL(FREIGHT_REVENUE), 99, FREIGHT_REVENUE) != IFF(
          ISNULL(lkp_FREIGHT_REVENUE_AMT),
          99,
          lkp_FREIGHT_REVENUE_AMT
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(CURRENCY_CODE), '', CURRENCY_CODE))
        ) != LTRIM(
          RTRIM(IFF(ISNULL(lkp_CURRENCY_CD), '', lkp_CURRENCY_CD))
        )
        OR LTRIM(
          RTRIM(IFF(ISNULL(CREATED_SOURCE), '', CREATED_SOURCE))
        ) != LTRIM(
          RTRIM(
            IFF(ISNULL(OMS_CREATED_SOURCE), '', OMS_CREATED_SOURCE)
          )
        )
        OR IFF(
          ISNULL(CREATED_SOURCE_TYPE),
          99,
          CREATED_SOURCE_TYPE
        ) != IFF(
          ISNULL(OMS_CREATED_SOURCE_TYPE_ID),
          99,
          OMS_CREATED_SOURCE_TYPE_ID
        )
        OR (
          IFF(
            ISNULL(CREATED_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            CREATED_DTTM
          )
        ) != (
          IFF(
            ISNULL(OMS_CREATED_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_CREATED_TSTMP
          )
        )
        OR (
          IFF(
            ISNULL(LAST_UPDATED_DTTM),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            LAST_UPDATED_DTTM
          )
        ) != (
          IFF(
            ISNULL(OMS_LAST_UPDATED_TSTMP),
            To_DATE('9999-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            OMS_LAST_UPDATED_TSTMP
          )
        )
      ),
      'UPDATE',
      'REJECT'
    )
  ) AS O_VALID_UPDATOR,
  lkp_HAS_ALERTS_FLAG AS lkp_HAS_ALERTS_FLAG,
  HAS_ALERTS AS HAS_ALERTS,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  JNR_OMS_PURCHASE_ORDERS_4"""

df_5 = spark.sql(query_5)

df_5.createOrReplaceTempView("EXP_UPD_VALIDATOR_5")

# COMMAND ----------
# DBTITLE 1, FTR_UNCHANGED_REC_6


query_6 = f"""SELECT
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  TC_COMPANY_ID AS TC_COMPANY_ID,
  CREATION_TYPE AS CREATION_TYPE,
  PURCHASE_ORDERS_TYPE AS PURCHASE_ORDERS_TYPE,
  PURCHASE_ORDERS_STATUS AS PURCHASE_ORDERS_STATUS,
  TC_PURCHASE_ORDERS_ID AS TC_PURCHASE_ORDERS_ID,
  PARENT_PURCHASE_ORDERS_ID AS PARENT_PURCHASE_ORDERS_ID,
  O_FACILITY_ID AS O_FACILITY_ID,
  O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  O_DOCK_ID AS O_DOCK_ID,
  D_FACILITY_ID AS D_FACILITY_ID,
  D_FACILITY_ALIAS_ID AS D_FACILITY_ALIAS_ID,
  BILL_FACILITY_ID AS BILL_FACILITY_ID,
  BILL_FACILITY_ALIAS_ID AS BILL_FACILITY_ALIAS_ID,
  ORG_SHIP_VIA_FACILITY_ALIAS_ID AS ORG_SHIP_VIA_FACILITY_ALIAS_ID,
  ORG_SHIP_VIA_FACILITY_ID AS ORG_SHIP_VIA_FACILITY_ID,
  DES_SHIP_VIA_FACILITY_ALIAS_ID AS DES_SHIP_VIA_FACILITY_ALIAS_ID,
  DES_SHIP_VIA_FACILITY_ID AS DES_SHIP_VIA_FACILITY_ID,
  PICKUP_TZ AS PICKUP_TZ,
  DELIVERY_TZ AS DELIVERY_TZ,
  PICKUP_START_DTTM AS PICKUP_START_DTTM,
  PICKUP_END_DTTM AS PICKUP_END_DTTM,
  DELIVERY_START_DTTM AS DELIVERY_START_DTTM,
  DELIVERY_END_DTTM AS DELIVERY_END_DTTM,
  REQUESTED_DLVR_DTTM AS REQUESTED_DLVR_DTTM,
  MUST_DLVR_DTTM AS MUST_DLVR_DTTM,
  PROMISED_DLVR_DTTM AS PROMISED_DLVR_DTTM,
  DUE_DT AS DUE_DT,
  CANCEL_DT AS CANCEL_DT,
  PURCHASE_ORDERS_DATE_DTTM AS PURCHASE_ORDERS_DATE_DTTM,
  RELEASE_DTTM AS RELEASE_DTTM,
  FIRST_RCPT_DTTM AS FIRST_RCPT_DTTM,
  LAST_RCPT_DTTM AS LAST_RCPT_DTTM,
  PAYMENT_MODE AS PAYMENT_MODE,
  MV_CURRENCY_CODE AS MV_CURRENCY_CODE,
  MONETARY_VALUE AS MONETARY_VALUE,
  CURRENCY_CODE AS CURRENCY_CODE,
  ORIG_BUDG_COST AS ORIG_BUDG_COST,
  BUDG_COST_CURRENCY_CODE AS BUDG_COST_CURRENCY_CODE,
  BUDG_COST AS BUDG_COST,
  TAX_CHARGES AS TAX_CHARGES,
  MISC_CHARGES AS MISC_CHARGES,
  IS_CANCELLED AS IS_CANCELLED,
  IS_IMPORTED AS IS_IMPORTED,
  IS_PURCHASE_ORDERS_RECONCILED AS IS_PURCHASE_ORDERS_RECONCILED,
  IS_READY_TO_SHIP AS IS_READY_TO_SHIP,
  IS_CUSTOMER_PICKUP AS IS_CUSTOMER_PICKUP,
  IS_DIRECT_ALLOWED AS IS_DIRECT_ALLOWED,
  IS_PARTIALLY_PLANNED AS IS_PARTIALLY_PLANNED,
  ON_HOLD AS ON_HOLD,
  BILL_OF_LADING_NUMBER AS BILL_OF_LADING_NUMBER,
  TRANS_RESP_CODE AS TRANS_RESP_CODE,
  COMMODITY_CODE_ID AS COMMODITY_CODE_ID,
  CARRIER_ID AS CARRIER_ID,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  PROTECTION_LEVEL_ID AS PROTECTION_LEVEL_ID,
  DECLINE_REASON_ID AS DECLINE_REASON_ID,
  CHANNEL_TYPE AS CHANNEL_TYPE,
  CUSTOMER_CODE AS CUSTOMER_CODE,
  CUSTOMER_FIRSTNAME AS CUSTOMER_FIRSTNAME,
  CUSTOMER_LASTNAME AS CUSTOMER_LASTNAME,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  IS_CLOSED AS IS_CLOSED,
  GRAND_TOTAL AS GRAND_TOTAL,
  EXT_PURCHASE_ORDERS_ID AS EXT_PURCHASE_ORDERS_ID,
  ORDER_CATEGORY AS ORDER_CATEGORY,
  CHANNEL_ID AS CHANNEL_ID,
  FULFILL_MODE AS FULFILL_MODE,
  ENTERED_BY AS ENTERED_BY,
  ENTRY_CODE AS ENTRY_CODE,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  CUSTOMER_PHONE AS CUSTOMER_PHONE,
  PAYMENT_STATUS AS PAYMENT_STATUS,
  REASON_ID AS REASON_ID,
  ORDER_RECEIVED AS ORDER_RECEIVED,
  FREIGHT_REVENUE AS FREIGHT_REVENUE,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  RETURN_REFERENCE_NUMBER AS RETURN_REFERENCE_NUMBER,
  UPDATE_TSTMP_exp AS UPDATE_TSTMP_exp,
  LOAD_TSTMP_exp AS LOAD_TSTMP_exp,
  O_VALID_UPDATOR AS O_VALID_UPDATOR,
  HAS_ALERTS AS HAS_ALERTS,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  EXP_UPD_VALIDATOR_5
WHERE
  IN(O_VALID_UPDATOR, 'INSERT', 'UPDATE')"""

df_6 = spark.sql(query_6)

df_6.createOrReplaceTempView("FTR_UNCHANGED_REC_6")

# COMMAND ----------
# DBTITLE 1, UPD_INS_UPD_7


query_7 = f"""SELECT
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  TC_COMPANY_ID AS TC_COMPANY_ID,
  TC_PURCHASE_ORDERS_ID AS TC_PURCHASE_ORDERS_ID,
  EXT_PURCHASE_ORDERS_ID AS EXT_PURCHASE_ORDERS_ID,
  PARENT_PURCHASE_ORDERS_ID AS PARENT_PURCHASE_ORDERS_ID,
  PURCHASE_ORDERS_TYPE AS PURCHASE_ORDERS_TYPE,
  PURCHASE_ORDERS_STATUS AS PURCHASE_ORDERS_STATUS,
  ORDER_CATEGORY AS ORDER_CATEGORY,
  O_FACILITY_ID AS O_FACILITY_ID,
  O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  O_DOCK_ID AS O_DOCK_ID,
  D_FACILITY_ID AS D_FACILITY_ID,
  D_FACILITY_ALIAS_ID AS D_FACILITY_ALIAS_ID,
  BILL_FACILITY_ID AS BILL_FACILITY_ID,
  BILL_FACILITY_ALIAS_ID AS BILL_FACILITY_ALIAS_ID,
  ORG_SHIP_VIA_FACILITY_ALIAS_ID AS ORG_SHIP_VIA_FACILITY_ALIAS_ID,
  ORG_SHIP_VIA_FACILITY_ID AS ORG_SHIP_VIA_FACILITY_ID,
  DES_SHIP_VIA_FACILITY_ALIAS_ID AS DES_SHIP_VIA_FACILITY_ALIAS_ID,
  DES_SHIP_VIA_FACILITY_ID AS DES_SHIP_VIA_FACILITY_ID,
  CUSTOMER_CODE AS CUSTOMER_CODE,
  CUSTOMER_FIRSTNAME AS CUSTOMER_FIRSTNAME,
  CUSTOMER_LASTNAME AS CUSTOMER_LASTNAME,
  CUSTOMER_PHONE AS CUSTOMER_PHONE,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  RETURN_REFERENCE_NUMBER AS RETURN_REFERENCE_NUMBER,
  BILL_OF_LADING_NUMBER AS BILL_OF_LADING_NUMBER,
  TRANS_RESP_CODE AS TRANS_RESP_CODE,
  COMMODITY_CODE_ID AS COMMODITY_CODE_ID,
  CARRIER_ID AS CARRIER_ID,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  PROTECTION_LEVEL_ID AS PROTECTION_LEVEL_ID,
  CREATION_TYPE AS CREATION_TYPE,
  CHANNEL_TYPE AS CHANNEL_TYPE,
  CHANNEL_ID AS CHANNEL_ID,
  FULFILL_MODE AS FULFILL_MODE,
  ENTERED_BY AS ENTERED_BY,
  ENTRY_CODE AS ENTRY_CODE,
  PAYMENT_MODE AS PAYMENT_MODE,
  PAYMENT_STATUS AS PAYMENT_STATUS,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  ORDER_RECEIVED AS ORDER_RECEIVED,
  ON_HOLD AS ON_HOLD,
  IS_CANCELLED AS IS_CANCELLED,
  IS_CLOSED AS IS_CLOSED,
  REASON_ID AS REASON_ID,
  DECLINE_REASON_ID AS DECLINE_REASON_ID,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  IS_IMPORTED AS IS_IMPORTED,
  IS_PURCHASE_ORDERS_RECONCILED AS IS_PURCHASE_ORDERS_RECONCILED,
  IS_READY_TO_SHIP AS IS_READY_TO_SHIP,
  IS_CUSTOMER_PICKUP AS IS_CUSTOMER_PICKUP,
  IS_DIRECT_ALLOWED AS IS_DIRECT_ALLOWED,
  IS_PARTIALLY_PLANNED AS IS_PARTIALLY_PLANNED,
  PURCHASE_ORDERS_DATE_DTTM AS PURCHASE_ORDERS_DATE_DTTM,
  PICKUP_START_DTTM AS PICKUP_START_DTTM,
  PICKUP_END_DTTM AS PICKUP_END_DTTM,
  PICKUP_TZ AS PICKUP_TZ,
  DELIVERY_START_DTTM AS DELIVERY_START_DTTM,
  DELIVERY_END_DTTM AS DELIVERY_END_DTTM,
  DELIVERY_TZ AS DELIVERY_TZ,
  REQUESTED_DLVR_DTTM AS REQUESTED_DLVR_DTTM,
  MUST_DLVR_DTTM AS MUST_DLVR_DTTM,
  PROMISED_DLVR_DTTM AS PROMISED_DLVR_DTTM,
  DUE_DT AS DUE_DT,
  CANCEL_DT AS CANCEL_DT,
  RELEASE_DTTM AS RELEASE_DTTM,
  FIRST_RCPT_DTTM AS FIRST_RCPT_DTTM,
  LAST_RCPT_DTTM AS LAST_RCPT_DTTM,
  MONETARY_VALUE AS MONETARY_VALUE,
  MV_CURRENCY_CODE AS MV_CURRENCY_CODE,
  ORIG_BUDG_COST AS ORIG_BUDG_COST,
  BUDG_COST AS BUDG_COST,
  BUDG_COST_CURRENCY_CODE AS BUDG_COST_CURRENCY_CODE,
  TAX_CHARGES AS TAX_CHARGES,
  MISC_CHARGES AS MISC_CHARGES,
  GRAND_TOTAL AS GRAND_TOTAL,
  FREIGHT_REVENUE AS FREIGHT_REVENUE,
  CURRENCY_CODE AS CURRENCY_CODE,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  UPDATE_TSTMP_exp AS UPDATE_TSTMP_exp,
  LOAD_TSTMP_exp AS LOAD_TSTMP_exp,
  O_VALID_UPDATOR AS O_VALID_UPDATOR,
  HAS_ALERTS AS HAS_ALERTS,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id,
  IFF(O_VALID_UPDATOR = 'INSERT', 'DD_INSERT', 'DD_UPDATE') AS UPDATE_STRATEGY_FLAG
FROM
  FTR_UNCHANGED_REC_6"""

df_7 = spark.sql(query_7)

df_7.createOrReplaceTempView("UPD_INS_UPD_7")

# COMMAND ----------
# DBTITLE 1, OMS_PURCHASE_ORDERS


spark.sql("""MERGE INTO OMS_PURCHASE_ORDERS AS TARGET
USING
  UPD_INS_UPD_7 AS SOURCE ON TARGET.OMS_PURCHASE_ORDERS_ID = SOURCE.PURCHASE_ORDERS_ID
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_UPDATE" THEN
UPDATE
SET
  TARGET.OMS_PURCHASE_ORDERS_ID = SOURCE.PURCHASE_ORDERS_ID,
  TARGET.OMS_TC_COMPANY_ID = SOURCE.TC_COMPANY_ID,
  TARGET.OMS_TC_PURCHASE_ORDERS_ID = SOURCE.TC_PURCHASE_ORDERS_ID,
  TARGET.OMS_EXT_PURCHASE_ORDERS_ID = SOURCE.EXT_PURCHASE_ORDERS_ID,
  TARGET.OMS_PARENT_PURCHASE_ORDERS_ID = SOURCE.PARENT_PURCHASE_ORDERS_ID,
  TARGET.OMS_PURCHASE_ORDERS_TYPE_ID = SOURCE.PURCHASE_ORDERS_TYPE,
  TARGET.OMS_PURCHASE_ORDERS_STATUS_ID = SOURCE.PURCHASE_ORDERS_STATUS,
  TARGET.OMS_ORDER_CATEGORY_ID = SOURCE.ORDER_CATEGORY,
  TARGET.OMS_O_FACILITY_ID = SOURCE.O_FACILITY_ID,
  TARGET.OMS_O_FACILITY_ALIAS_ID = SOURCE.O_FACILITY_ALIAS_ID,
  TARGET.OMS_D_FACILITY_ID = SOURCE.D_FACILITY_ID,
  TARGET.OMS_D_FACILITY_ALIAS_ID = SOURCE.D_FACILITY_ALIAS_ID,
  TARGET.OMS_BILL_FACILITY_ID = SOURCE.BILL_FACILITY_ID,
  TARGET.OMS_BILL_FACILITY_ALIAS_ID = SOURCE.BILL_FACILITY_ALIAS_ID,
  TARGET.OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID = SOURCE.ORG_SHIP_VIA_FACILITY_ALIAS_ID,
  TARGET.OMS_ORIGIN_SHIP_VIA_FACILITY_ID = SOURCE.ORG_SHIP_VIA_FACILITY_ID,
  TARGET.OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID = SOURCE.DES_SHIP_VIA_FACILITY_ALIAS_ID,
  TARGET.OMS_DES_SHIP_VIA_FACILITY_ID = SOURCE.DES_SHIP_VIA_FACILITY_ID,
  TARGET.OMS_CUSTOMER_CD = SOURCE.CUSTOMER_CODE,
  TARGET.CUSTOMER_FIRST_NAME = SOURCE.CUSTOMER_FIRSTNAME,
  TARGET.CUSTOMER_LAST_NAME = SOURCE.CUSTOMER_LASTNAME,
  TARGET.CUSTOMER_PHONE_NBR = SOURCE.CUSTOMER_PHONE,
  TARGET.CUSTOMER_EMAIL = SOURCE.CUSTOMER_EMAIL,
  TARGET.OMS_RETURN_REFERENCE_NBR = SOURCE.RETURN_REFERENCE_NUMBER,
  TARGET.OMS_BILL_OF_LADING_NBR = SOURCE.BILL_OF_LADING_NUMBER,
  TARGET.OMS_TRANS_RESP_CD = SOURCE.TRANS_RESP_CODE,
  TARGET.OMS_COMMODITY_CODE_ID = SOURCE.COMMODITY_CODE_ID,
  TARGET.OMS_CARRIER_ID = SOURCE.CARRIER_ID,
  TARGET.OMS_PRODUCT_CLASS_ID = SOURCE.PRODUCT_CLASS_ID,
  TARGET.OMS_PROTECTION_LEVEL_ID = SOURCE.PROTECTION_LEVEL_ID,
  TARGET.OMS_CREATION_TYPE_ID = SOURCE.CREATION_TYPE,
  TARGET.OMS_CHANNEL_TYPE_ID = SOURCE.CHANNEL_TYPE,
  TARGET.OMS_CHANNEL_ID = SOURCE.CHANNEL_ID,
  TARGET.OMS_FULFILL_MODE_ID = SOURCE.FULFILL_MODE,
  TARGET.OMS_ENTERED_BY = SOURCE.ENTERED_BY,
  TARGET.OMS_ENTRY_CD = SOURCE.ENTRY_CODE,
  TARGET.OMS_PAYMENT_MODE_ID = SOURCE.PAYMENT_MODE,
  TARGET.OMS_PAYMENT_STATUS_ID = SOURCE.PAYMENT_STATUS,
  TARGET.DROPOFF_PICKUP = SOURCE.DROPOFF_PICKUP,
  TARGET.ORDER_RECEIVED_FLAG = SOURCE.ORDER_RECEIVED,
  TARGET.ON_HOLD_FLAG = SOURCE.ON_HOLD,
  TARGET.HAS_ALERTS_FLAG = SOURCE.HAS_ALERTS,
  TARGET.CANCELLED_FLAG = SOURCE.IS_CANCELLED,
  TARGET.CLOSED_FLAG = SOURCE.IS_CLOSED,
  TARGET.OMS_REASON_ID = SOURCE.REASON_ID,
  TARGET.OMS_DECLINE_REASON_ID = SOURCE.DECLINE_REASON_ID,
  TARGET.OMS_REASON_CODES_GROUP_ID = SOURCE.REASON_CODES_GROUP_ID,
  TARGET.IMPORTED_FLAG = SOURCE.IS_IMPORTED,
  TARGET.PURCHASE_ORDERS_RECONCILED_FLAG = SOURCE.IS_PURCHASE_ORDERS_RECONCILED,
  TARGET.READY_TO_SHIP_FLAG = SOURCE.IS_READY_TO_SHIP,
  TARGET.CUSTOMER_PICKUP_FLAG = SOURCE.IS_CUSTOMER_PICKUP,
  TARGET.DIRECT_ALLOWED_FLAG = SOURCE.IS_DIRECT_ALLOWED,
  TARGET.PARTIALLY_PLANNED_FLAG = SOURCE.IS_PARTIALLY_PLANNED,
  TARGET.OMS_PURCHASE_ORDERS_DT_TSTMP = SOURCE.PURCHASE_ORDERS_DATE_DTTM,
  TARGET.OMS_PICKUP_START_TSTMP = SOURCE.PICKUP_START_DTTM,
  TARGET.OMS_PICKUP_END_TSTMP = SOURCE.PICKUP_END_DTTM,
  TARGET.OMS_PICKUP_TZ_ID = SOURCE.PICKUP_TZ,
  TARGET.OMS_DELIVERY_START_TSTMP = SOURCE.DELIVERY_START_DTTM,
  TARGET.OMS_DELIVERY_END_TSTMP = SOURCE.DELIVERY_END_DTTM,
  TARGET.OMS_DELIVERY_TZ_ID = SOURCE.DELIVERY_TZ,
  TARGET.OMS_REQUESTED_DLVR_TSTMP = SOURCE.REQUESTED_DLVR_DTTM,
  TARGET.OMS_MUST_DLVR_TSTMP = SOURCE.MUST_DLVR_DTTM,
  TARGET.OMS_PROMISED_DLVR_TSTMP = SOURCE.PROMISED_DLVR_DTTM,
  TARGET.OMS_DUE_DT = SOURCE.DUE_DT,
  TARGET.OMS_CANCEL_DT = SOURCE.CANCEL_DT,
  TARGET.OMS_RELEASE_TSTMP = SOURCE.RELEASE_DTTM,
  TARGET.OMS_FIRST_RCPT_TSTMP = SOURCE.FIRST_RCPT_DTTM,
  TARGET.OMS_LAST_RCPT_TSTMP = SOURCE.LAST_RCPT_DTTM,
  TARGET.MONETARY_VALUE = SOURCE.MONETARY_VALUE,
  TARGET.MV_CURRENCY_CD = SOURCE.MV_CURRENCY_CODE,
  TARGET.ORIG_BUDG_COST = SOURCE.ORIG_BUDG_COST,
  TARGET.BUDG_COST = SOURCE.BUDG_COST,
  TARGET.BUDG_COST_CURRENCY_CD = SOURCE.BUDG_COST_CURRENCY_CODE,
  TARGET.TAX_CHARGES_AMT = SOURCE.TAX_CHARGES,
  TARGET.MISC_CHARGES_AMT = SOURCE.MISC_CHARGES,
  TARGET.GRAND_TOTAL_AMT = SOURCE.GRAND_TOTAL,
  TARGET.FREIGHT_REVENUE_AMT = SOURCE.FREIGHT_REVENUE,
  TARGET.CURRENCY_CD = SOURCE.CURRENCY_CODE,
  TARGET.OMS_CREATED_SOURCE_TYPE_ID = SOURCE.CREATED_SOURCE_TYPE,
  TARGET.OMS_CREATED_SOURCE = SOURCE.CREATED_SOURCE,
  TARGET.OMS_CREATED_TSTMP = SOURCE.CREATED_DTTM,
  TARGET.OMS_LAST_UPDATED_TSTMP = SOURCE.LAST_UPDATED_DTTM,
  TARGET.UPDATE_TSTMP = SOURCE.UPDATE_TSTMP_exp,
  TARGET.LOAD_TSTMP = SOURCE.LOAD_TSTMP_exp
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_DELETE"
  AND TARGET.OMS_TC_COMPANY_ID = SOURCE.TC_COMPANY_ID
  AND TARGET.OMS_TC_PURCHASE_ORDERS_ID = SOURCE.TC_PURCHASE_ORDERS_ID
  AND TARGET.OMS_EXT_PURCHASE_ORDERS_ID = SOURCE.EXT_PURCHASE_ORDERS_ID
  AND TARGET.OMS_PARENT_PURCHASE_ORDERS_ID = SOURCE.PARENT_PURCHASE_ORDERS_ID
  AND TARGET.OMS_PURCHASE_ORDERS_TYPE_ID = SOURCE.PURCHASE_ORDERS_TYPE
  AND TARGET.OMS_PURCHASE_ORDERS_STATUS_ID = SOURCE.PURCHASE_ORDERS_STATUS
  AND TARGET.OMS_ORDER_CATEGORY_ID = SOURCE.ORDER_CATEGORY
  AND TARGET.OMS_O_FACILITY_ID = SOURCE.O_FACILITY_ID
  AND TARGET.OMS_O_FACILITY_ALIAS_ID = SOURCE.O_FACILITY_ALIAS_ID
  AND TARGET.OMS_D_FACILITY_ID = SOURCE.D_FACILITY_ID
  AND TARGET.OMS_D_FACILITY_ALIAS_ID = SOURCE.D_FACILITY_ALIAS_ID
  AND TARGET.OMS_BILL_FACILITY_ID = SOURCE.BILL_FACILITY_ID
  AND TARGET.OMS_BILL_FACILITY_ALIAS_ID = SOURCE.BILL_FACILITY_ALIAS_ID
  AND TARGET.OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID = SOURCE.ORG_SHIP_VIA_FACILITY_ALIAS_ID
  AND TARGET.OMS_ORIGIN_SHIP_VIA_FACILITY_ID = SOURCE.ORG_SHIP_VIA_FACILITY_ID
  AND TARGET.OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID = SOURCE.DES_SHIP_VIA_FACILITY_ALIAS_ID
  AND TARGET.OMS_DES_SHIP_VIA_FACILITY_ID = SOURCE.DES_SHIP_VIA_FACILITY_ID
  AND TARGET.OMS_CUSTOMER_CD = SOURCE.CUSTOMER_CODE
  AND TARGET.CUSTOMER_FIRST_NAME = SOURCE.CUSTOMER_FIRSTNAME
  AND TARGET.CUSTOMER_LAST_NAME = SOURCE.CUSTOMER_LASTNAME
  AND TARGET.CUSTOMER_PHONE_NBR = SOURCE.CUSTOMER_PHONE
  AND TARGET.CUSTOMER_EMAIL = SOURCE.CUSTOMER_EMAIL
  AND TARGET.OMS_RETURN_REFERENCE_NBR = SOURCE.RETURN_REFERENCE_NUMBER
  AND TARGET.OMS_BILL_OF_LADING_NBR = SOURCE.BILL_OF_LADING_NUMBER
  AND TARGET.OMS_TRANS_RESP_CD = SOURCE.TRANS_RESP_CODE
  AND TARGET.OMS_COMMODITY_CODE_ID = SOURCE.COMMODITY_CODE_ID
  AND TARGET.OMS_CARRIER_ID = SOURCE.CARRIER_ID
  AND TARGET.OMS_PRODUCT_CLASS_ID = SOURCE.PRODUCT_CLASS_ID
  AND TARGET.OMS_PROTECTION_LEVEL_ID = SOURCE.PROTECTION_LEVEL_ID
  AND TARGET.OMS_CREATION_TYPE_ID = SOURCE.CREATION_TYPE
  AND TARGET.OMS_CHANNEL_TYPE_ID = SOURCE.CHANNEL_TYPE
  AND TARGET.OMS_CHANNEL_ID = SOURCE.CHANNEL_ID
  AND TARGET.OMS_FULFILL_MODE_ID = SOURCE.FULFILL_MODE
  AND TARGET.OMS_ENTERED_BY = SOURCE.ENTERED_BY
  AND TARGET.OMS_ENTRY_CD = SOURCE.ENTRY_CODE
  AND TARGET.OMS_PAYMENT_MODE_ID = SOURCE.PAYMENT_MODE
  AND TARGET.OMS_PAYMENT_STATUS_ID = SOURCE.PAYMENT_STATUS
  AND TARGET.DROPOFF_PICKUP = SOURCE.DROPOFF_PICKUP
  AND TARGET.ORDER_RECEIVED_FLAG = SOURCE.ORDER_RECEIVED
  AND TARGET.ON_HOLD_FLAG = SOURCE.ON_HOLD
  AND TARGET.HAS_ALERTS_FLAG = SOURCE.HAS_ALERTS
  AND TARGET.CANCELLED_FLAG = SOURCE.IS_CANCELLED
  AND TARGET.CLOSED_FLAG = SOURCE.IS_CLOSED
  AND TARGET.OMS_REASON_ID = SOURCE.REASON_ID
  AND TARGET.OMS_DECLINE_REASON_ID = SOURCE.DECLINE_REASON_ID
  AND TARGET.OMS_REASON_CODES_GROUP_ID = SOURCE.REASON_CODES_GROUP_ID
  AND TARGET.IMPORTED_FLAG = SOURCE.IS_IMPORTED
  AND TARGET.PURCHASE_ORDERS_RECONCILED_FLAG = SOURCE.IS_PURCHASE_ORDERS_RECONCILED
  AND TARGET.READY_TO_SHIP_FLAG = SOURCE.IS_READY_TO_SHIP
  AND TARGET.CUSTOMER_PICKUP_FLAG = SOURCE.IS_CUSTOMER_PICKUP
  AND TARGET.DIRECT_ALLOWED_FLAG = SOURCE.IS_DIRECT_ALLOWED
  AND TARGET.PARTIALLY_PLANNED_FLAG = SOURCE.IS_PARTIALLY_PLANNED
  AND TARGET.OMS_PURCHASE_ORDERS_DT_TSTMP = SOURCE.PURCHASE_ORDERS_DATE_DTTM
  AND TARGET.OMS_PICKUP_START_TSTMP = SOURCE.PICKUP_START_DTTM
  AND TARGET.OMS_PICKUP_END_TSTMP = SOURCE.PICKUP_END_DTTM
  AND TARGET.OMS_PICKUP_TZ_ID = SOURCE.PICKUP_TZ
  AND TARGET.OMS_DELIVERY_START_TSTMP = SOURCE.DELIVERY_START_DTTM
  AND TARGET.OMS_DELIVERY_END_TSTMP = SOURCE.DELIVERY_END_DTTM
  AND TARGET.OMS_DELIVERY_TZ_ID = SOURCE.DELIVERY_TZ
  AND TARGET.OMS_REQUESTED_DLVR_TSTMP = SOURCE.REQUESTED_DLVR_DTTM
  AND TARGET.OMS_MUST_DLVR_TSTMP = SOURCE.MUST_DLVR_DTTM
  AND TARGET.OMS_PROMISED_DLVR_TSTMP = SOURCE.PROMISED_DLVR_DTTM
  AND TARGET.OMS_DUE_DT = SOURCE.DUE_DT
  AND TARGET.OMS_CANCEL_DT = SOURCE.CANCEL_DT
  AND TARGET.OMS_RELEASE_TSTMP = SOURCE.RELEASE_DTTM
  AND TARGET.OMS_FIRST_RCPT_TSTMP = SOURCE.FIRST_RCPT_DTTM
  AND TARGET.OMS_LAST_RCPT_TSTMP = SOURCE.LAST_RCPT_DTTM
  AND TARGET.MONETARY_VALUE = SOURCE.MONETARY_VALUE
  AND TARGET.MV_CURRENCY_CD = SOURCE.MV_CURRENCY_CODE
  AND TARGET.ORIG_BUDG_COST = SOURCE.ORIG_BUDG_COST
  AND TARGET.BUDG_COST = SOURCE.BUDG_COST
  AND TARGET.BUDG_COST_CURRENCY_CD = SOURCE.BUDG_COST_CURRENCY_CODE
  AND TARGET.TAX_CHARGES_AMT = SOURCE.TAX_CHARGES
  AND TARGET.MISC_CHARGES_AMT = SOURCE.MISC_CHARGES
  AND TARGET.GRAND_TOTAL_AMT = SOURCE.GRAND_TOTAL
  AND TARGET.FREIGHT_REVENUE_AMT = SOURCE.FREIGHT_REVENUE
  AND TARGET.CURRENCY_CD = SOURCE.CURRENCY_CODE
  AND TARGET.OMS_CREATED_SOURCE_TYPE_ID = SOURCE.CREATED_SOURCE_TYPE
  AND TARGET.OMS_CREATED_SOURCE = SOURCE.CREATED_SOURCE
  AND TARGET.OMS_CREATED_TSTMP = SOURCE.CREATED_DTTM
  AND TARGET.OMS_LAST_UPDATED_TSTMP = SOURCE.LAST_UPDATED_DTTM
  AND TARGET.UPDATE_TSTMP = SOURCE.UPDATE_TSTMP_exp
  AND TARGET.LOAD_TSTMP = SOURCE.LOAD_TSTMP_exp THEN DELETE
  WHEN NOT MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_INSERT" THEN
INSERT
  (
    TARGET.OMS_PURCHASE_ORDERS_ID,
    TARGET.OMS_TC_COMPANY_ID,
    TARGET.OMS_TC_PURCHASE_ORDERS_ID,
    TARGET.OMS_EXT_PURCHASE_ORDERS_ID,
    TARGET.OMS_PARENT_PURCHASE_ORDERS_ID,
    TARGET.OMS_PURCHASE_ORDERS_TYPE_ID,
    TARGET.OMS_PURCHASE_ORDERS_STATUS_ID,
    TARGET.OMS_ORDER_CATEGORY_ID,
    TARGET.OMS_O_FACILITY_ID,
    TARGET.OMS_O_FACILITY_ALIAS_ID,
    TARGET.OMS_D_FACILITY_ID,
    TARGET.OMS_D_FACILITY_ALIAS_ID,
    TARGET.OMS_BILL_FACILITY_ID,
    TARGET.OMS_BILL_FACILITY_ALIAS_ID,
    TARGET.OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID,
    TARGET.OMS_ORIGIN_SHIP_VIA_FACILITY_ID,
    TARGET.OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID,
    TARGET.OMS_DES_SHIP_VIA_FACILITY_ID,
    TARGET.OMS_CUSTOMER_CD,
    TARGET.CUSTOMER_FIRST_NAME,
    TARGET.CUSTOMER_LAST_NAME,
    TARGET.CUSTOMER_PHONE_NBR,
    TARGET.CUSTOMER_EMAIL,
    TARGET.OMS_RETURN_REFERENCE_NBR,
    TARGET.OMS_BILL_OF_LADING_NBR,
    TARGET.OMS_TRANS_RESP_CD,
    TARGET.OMS_COMMODITY_CODE_ID,
    TARGET.OMS_CARRIER_ID,
    TARGET.OMS_PRODUCT_CLASS_ID,
    TARGET.OMS_PROTECTION_LEVEL_ID,
    TARGET.OMS_CREATION_TYPE_ID,
    TARGET.OMS_CHANNEL_TYPE_ID,
    TARGET.OMS_CHANNEL_ID,
    TARGET.OMS_FULFILL_MODE_ID,
    TARGET.OMS_ENTERED_BY,
    TARGET.OMS_ENTRY_CD,
    TARGET.OMS_PAYMENT_MODE_ID,
    TARGET.OMS_PAYMENT_STATUS_ID,
    TARGET.DROPOFF_PICKUP,
    TARGET.ORDER_RECEIVED_FLAG,
    TARGET.ON_HOLD_FLAG,
    TARGET.HAS_ALERTS_FLAG,
    TARGET.CANCELLED_FLAG,
    TARGET.CLOSED_FLAG,
    TARGET.OMS_REASON_ID,
    TARGET.OMS_DECLINE_REASON_ID,
    TARGET.OMS_REASON_CODES_GROUP_ID,
    TARGET.IMPORTED_FLAG,
    TARGET.PURCHASE_ORDERS_RECONCILED_FLAG,
    TARGET.READY_TO_SHIP_FLAG,
    TARGET.CUSTOMER_PICKUP_FLAG,
    TARGET.DIRECT_ALLOWED_FLAG,
    TARGET.PARTIALLY_PLANNED_FLAG,
    TARGET.OMS_PURCHASE_ORDERS_DT_TSTMP,
    TARGET.OMS_PICKUP_START_TSTMP,
    TARGET.OMS_PICKUP_END_TSTMP,
    TARGET.OMS_PICKUP_TZ_ID,
    TARGET.OMS_DELIVERY_START_TSTMP,
    TARGET.OMS_DELIVERY_END_TSTMP,
    TARGET.OMS_DELIVERY_TZ_ID,
    TARGET.OMS_REQUESTED_DLVR_TSTMP,
    TARGET.OMS_MUST_DLVR_TSTMP,
    TARGET.OMS_PROMISED_DLVR_TSTMP,
    TARGET.OMS_DUE_DT,
    TARGET.OMS_CANCEL_DT,
    TARGET.OMS_RELEASE_TSTMP,
    TARGET.OMS_FIRST_RCPT_TSTMP,
    TARGET.OMS_LAST_RCPT_TSTMP,
    TARGET.MONETARY_VALUE,
    TARGET.MV_CURRENCY_CD,
    TARGET.ORIG_BUDG_COST,
    TARGET.BUDG_COST,
    TARGET.BUDG_COST_CURRENCY_CD,
    TARGET.TAX_CHARGES_AMT,
    TARGET.MISC_CHARGES_AMT,
    TARGET.GRAND_TOTAL_AMT,
    TARGET.FREIGHT_REVENUE_AMT,
    TARGET.CURRENCY_CD,
    TARGET.OMS_CREATED_SOURCE_TYPE_ID,
    TARGET.OMS_CREATED_SOURCE,
    TARGET.OMS_CREATED_TSTMP,
    TARGET.OMS_LAST_UPDATED_TSTMP,
    TARGET.UPDATE_TSTMP,
    TARGET.LOAD_TSTMP
  )
VALUES
  (
    SOURCE.PURCHASE_ORDERS_ID,
    SOURCE.TC_COMPANY_ID,
    SOURCE.TC_PURCHASE_ORDERS_ID,
    SOURCE.EXT_PURCHASE_ORDERS_ID,
    SOURCE.PARENT_PURCHASE_ORDERS_ID,
    SOURCE.PURCHASE_ORDERS_TYPE,
    SOURCE.PURCHASE_ORDERS_STATUS,
    SOURCE.ORDER_CATEGORY,
    SOURCE.O_FACILITY_ID,
    SOURCE.O_FACILITY_ALIAS_ID,
    SOURCE.D_FACILITY_ID,
    SOURCE.D_FACILITY_ALIAS_ID,
    SOURCE.BILL_FACILITY_ID,
    SOURCE.BILL_FACILITY_ALIAS_ID,
    SOURCE.ORG_SHIP_VIA_FACILITY_ALIAS_ID,
    SOURCE.ORG_SHIP_VIA_FACILITY_ID,
    SOURCE.DES_SHIP_VIA_FACILITY_ALIAS_ID,
    SOURCE.DES_SHIP_VIA_FACILITY_ID,
    SOURCE.CUSTOMER_CODE,
    SOURCE.CUSTOMER_FIRSTNAME,
    SOURCE.CUSTOMER_LASTNAME,
    SOURCE.CUSTOMER_PHONE,
    SOURCE.CUSTOMER_EMAIL,
    SOURCE.RETURN_REFERENCE_NUMBER,
    SOURCE.BILL_OF_LADING_NUMBER,
    SOURCE.TRANS_RESP_CODE,
    SOURCE.COMMODITY_CODE_ID,
    SOURCE.CARRIER_ID,
    SOURCE.PRODUCT_CLASS_ID,
    SOURCE.PROTECTION_LEVEL_ID,
    SOURCE.CREATION_TYPE,
    SOURCE.CHANNEL_TYPE,
    SOURCE.CHANNEL_ID,
    SOURCE.FULFILL_MODE,
    SOURCE.ENTERED_BY,
    SOURCE.ENTRY_CODE,
    SOURCE.PAYMENT_MODE,
    SOURCE.PAYMENT_STATUS,
    SOURCE.DROPOFF_PICKUP,
    SOURCE.ORDER_RECEIVED,
    SOURCE.ON_HOLD,
    SOURCE.HAS_ALERTS,
    SOURCE.IS_CANCELLED,
    SOURCE.IS_CLOSED,
    SOURCE.REASON_ID,
    SOURCE.DECLINE_REASON_ID,
    SOURCE.REASON_CODES_GROUP_ID,
    SOURCE.IS_IMPORTED,
    SOURCE.IS_PURCHASE_ORDERS_RECONCILED,
    SOURCE.IS_READY_TO_SHIP,
    SOURCE.IS_CUSTOMER_PICKUP,
    SOURCE.IS_DIRECT_ALLOWED,
    SOURCE.IS_PARTIALLY_PLANNED,
    SOURCE.PURCHASE_ORDERS_DATE_DTTM,
    SOURCE.PICKUP_START_DTTM,
    SOURCE.PICKUP_END_DTTM,
    SOURCE.PICKUP_TZ,
    SOURCE.DELIVERY_START_DTTM,
    SOURCE.DELIVERY_END_DTTM,
    SOURCE.DELIVERY_TZ,
    SOURCE.REQUESTED_DLVR_DTTM,
    SOURCE.MUST_DLVR_DTTM,
    SOURCE.PROMISED_DLVR_DTTM,
    SOURCE.DUE_DT,
    SOURCE.CANCEL_DT,
    SOURCE.RELEASE_DTTM,
    SOURCE.FIRST_RCPT_DTTM,
    SOURCE.LAST_RCPT_DTTM,
    SOURCE.MONETARY_VALUE,
    SOURCE.MV_CURRENCY_CODE,
    SOURCE.ORIG_BUDG_COST,
    SOURCE.BUDG_COST,
    SOURCE.BUDG_COST_CURRENCY_CODE,
    SOURCE.TAX_CHARGES,
    SOURCE.MISC_CHARGES,
    SOURCE.GRAND_TOTAL,
    SOURCE.FREIGHT_REVENUE,
    SOURCE.CURRENCY_CODE,
    SOURCE.CREATED_SOURCE_TYPE,
    SOURCE.CREATED_SOURCE,
    SOURCE.CREATED_DTTM,
    SOURCE.LAST_UPDATED_DTTM,
    SOURCE.UPDATE_TSTMP_exp,
    SOURCE.LOAD_TSTMP_exp
  )""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_Purchase_Orders")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_DDS_OMS_Purchase_Orders", mainWorkflowId, parentName)
