# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ../WorkflowUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_A_Charge_Detail")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_DDS_OMS_A_Charge_Detail", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_A_CHARGE_DETAIL_PRE_0


query_0 = f"""SELECT
  CHARGE_DETAIL_ID AS CHARGE_DETAIL_ID,
  ENTITY_TYPE_ID AS ENTITY_TYPE_ID,
  ENTITY_ID AS ENTITY_ID,
  ENTITY_LINE_ID AS ENTITY_LINE_ID,
  CHARGE_CATEGORY AS CHARGE_CATEGORY,
  CHARGE_NAME AS CHARGE_NAME,
  CHARGE_AMOUNT AS CHARGE_AMOUNT,
  MARK_FOR_DELETION AS MARK_FOR_DELETION,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  OVERRIDEN_CHARGE AS OVERRIDEN_CHARGE,
  ORIGINAL_CHARGE_AMOUNT AS ORIGINAL_CHARGE_AMOUNT,
  REASON_CODE_GROUP_ID AS REASON_CODE_GROUP_ID,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_A_CHARGE_DETAIL_PRE"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_OMS_A_CHARGE_DETAIL_PRE_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_A_CHARGE_DETAIL_PRE_1


query_1 = f"""SELECT
  CHARGE_DETAIL_ID AS CHARGE_DETAIL_ID,
  ENTITY_TYPE_ID AS ENTITY_TYPE_ID,
  ENTITY_ID AS ENTITY_ID,
  ENTITY_LINE_ID AS ENTITY_LINE_ID,
  CHARGE_CATEGORY AS CHARGE_CATEGORY,
  CHARGE_AMOUNT AS CHARGE_AMOUNT,
  MARK_FOR_DELETION AS MARK_FOR_DELETION,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  OVERRIDEN_CHARGE AS OVERRIDEN_CHARGE,
  ORIGINAL_CHARGE_AMOUNT AS ORIGINAL_CHARGE_AMOUNT,
  REASON_CODE_GROUP_ID AS REASON_CODE_GROUP_ID,
  LOAD_TSTMP AS LOAD_TSTMP,
  CHARGE_NAME AS CHARGE_NAME,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_A_CHARGE_DETAIL_PRE_0"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("SQ_Shortcut_to_OMS_A_CHARGE_DETAIL_PRE_1")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_A_CHARGE_DETAIL_2


query_2 = f"""SELECT
  OMS_CHARGE_DETAIL_ID AS OMS_CHARGE_DETAIL_ID,
  OMS_ENTITY_TYPE_ID AS OMS_ENTITY_TYPE_ID,
  OMS_ENTITY_ID AS OMS_ENTITY_ID,
  OMS_ENTITY_LINE_ID AS OMS_ENTITY_LINE_ID,
  OMS_CHARGE_NAME AS OMS_CHARGE_NAME,
  OMS_CHARGE_CATEGORY AS OMS_CHARGE_CATEGORY,
  OMS_REASON_CODE_GROUP_ID AS OMS_REASON_CODE_GROUP_ID,
  CHARGE_AMT AS CHARGE_AMT,
  ORIGINAL_CHARGE_AMT AS ORIGINAL_CHARGE_AMT,
  OVERRIDEN_CHARGE_FLAG AS OVERRIDEN_CHARGE_FLAG,
  MARK_FOR_DELETION_FLAG AS MARK_FOR_DELETION_FLAG,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_A_CHARGE_DETAIL"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("Shortcut_to_OMS_A_CHARGE_DETAIL_2")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_A_CHARGE_DETAIL_3


query_3 = f"""SELECT
  OMS_CHARGE_DETAIL_ID AS OMS_CHARGE_DETAIL_ID,
  OMS_ENTITY_TYPE_ID AS OMS_ENTITY_TYPE_ID,
  OMS_ENTITY_ID AS OMS_ENTITY_ID,
  OMS_ENTITY_LINE_ID AS OMS_ENTITY_LINE_ID,
  OMS_CHARGE_CATEGORY AS OMS_CHARGE_CATEGORY,
  OMS_REASON_CODE_GROUP_ID AS OMS_REASON_CODE_GROUP_ID,
  CHARGE_AMT AS CHARGE_AMT,
  ORIGINAL_CHARGE_AMT AS ORIGINAL_CHARGE_AMT,
  OVERRIDEN_CHARGE_FLAG AS OVERRIDEN_CHARGE_FLAG,
  MARK_FOR_DELETION_FLAG AS MARK_FOR_DELETION_FLAG,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  OMS_CHARGE_NAME AS OMS_CHARGE_NAME,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_A_CHARGE_DETAIL_2"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("SQ_Shortcut_to_OMS_A_CHARGE_DETAIL_3")

# COMMAND ----------
# DBTITLE 1, JNR_OMS_A_CHARGE_DETAIL_4


query_4 = f"""SELECT
  DETAIL.CHARGE_DETAIL_ID AS CHARGE_DETAIL_ID,
  DETAIL.ENTITY_TYPE_ID AS ENTITY_TYPE_ID,
  DETAIL.ENTITY_ID AS ENTITY_ID,
  DETAIL.ENTITY_LINE_ID AS ENTITY_LINE_ID,
  DETAIL.CHARGE_CATEGORY AS CHARGE_CATEGORY,
  DETAIL.CHARGE_NAME AS CHARGE_NAME,
  DETAIL.CHARGE_AMOUNT AS CHARGE_AMOUNT,
  DETAIL.MARK_FOR_DELETION AS MARK_FOR_DELETION,
  DETAIL.CREATED_DTTM AS CREATED_DTTM,
  DETAIL.LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  DETAIL.OVERRIDEN_CHARGE AS OVERRIDEN_CHARGE,
  DETAIL.ORIGINAL_CHARGE_AMOUNT AS ORIGINAL_CHARGE_AMOUNT,
  DETAIL.REASON_CODE_GROUP_ID AS REASON_CODE_GROUP_ID,
  MASTER.OMS_CHARGE_DETAIL_ID AS lkp_OMS_CHARGE_DETAIL_ID,
  MASTER.OMS_ENTITY_TYPE_ID AS lkp_OMS_ENTITY_TYPE_ID,
  MASTER.OMS_ENTITY_ID AS lkp_OMS_ENTITY_ID,
  MASTER.OMS_ENTITY_LINE_ID AS lkp_OMS_ENTITY_LINE_ID,
  MASTER.OMS_CHARGE_CATEGORY AS lkp_OMS_CHARGE_CATEGORY,
  MASTER.OMS_REASON_CODE_GROUP_ID AS lkp_OMS_REASON_CODE_GROUP_ID,
  MASTER.OMS_CHARGE_NAME AS lkp_CHARGE_NAME,
  MASTER.CHARGE_AMT AS lkp_CHARGE_AMT,
  MASTER.ORIGINAL_CHARGE_AMT AS lkp_ORIGINAL_CHARGE_AMT,
  MASTER.OVERRIDEN_CHARGE_FLAG AS lkp_OVERRIDEN_CHARGE_FLAG,
  MASTER.MARK_FOR_DELETION_FLAG AS lkp_MARK_FOR_DELETION_FLAG,
  MASTER.OMS_CREATED_TSTMP AS lkp_OMS_CREATED_TSTMP,
  MASTER.OMS_LAST_UPDATED_TSTMP AS lkp_OMS_LAST_UPDATED_TSTMP,
  MASTER.LOAD_TSTMP AS lkp_LOAD_TSTMP,
  DETAIL.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_A_CHARGE_DETAIL_3 MASTER
  RIGHT JOIN SQ_Shortcut_to_OMS_A_CHARGE_DETAIL_PRE_1 DETAIL ON MASTER.OMS_CHARGE_DETAIL_ID = DETAIL.CHARGE_DETAIL_ID"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("JNR_OMS_A_CHARGE_DETAIL_4")

# COMMAND ----------
# DBTITLE 1, FIL_UNCHANGED_RECORDS_5


query_5 = f"""SELECT
  CHARGE_DETAIL_ID AS CHARGE_DETAIL_ID,
  ENTITY_TYPE_ID AS ENTITY_TYPE_ID,
  ENTITY_ID AS ENTITY_ID,
  ENTITY_LINE_ID AS ENTITY_LINE_ID,
  CHARGE_CATEGORY AS CHARGE_CATEGORY,
  CHARGE_AMOUNT AS CHARGE_AMOUNT,
  MARK_FOR_DELETION AS MARK_FOR_DELETION,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  OVERRIDEN_CHARGE AS OVERRIDEN_CHARGE,
  ORIGINAL_CHARGE_AMOUNT AS ORIGINAL_CHARGE_AMOUNT,
  REASON_CODE_GROUP_ID AS REASON_CODE_GROUP_ID,
  lkp_OMS_CHARGE_DETAIL_ID AS lkp_OMS_CHARGE_DETAIL_ID,
  lkp_OMS_ENTITY_TYPE_ID AS lkp_OMS_ENTITY_TYPE_ID,
  lkp_OMS_ENTITY_ID AS lkp_OMS_ENTITY_ID,
  lkp_OMS_ENTITY_LINE_ID AS lkp_OMS_ENTITY_LINE_ID,
  lkp_OMS_CHARGE_CATEGORY AS lkp_OMS_CHARGE_CATEGORY,
  lkp_OMS_REASON_CODE_GROUP_ID AS lkp_OMS_REASON_CODE_GROUP_ID,
  lkp_CHARGE_AMT AS lkp_CHARGE_AMT,
  lkp_ORIGINAL_CHARGE_AMT AS lkp_ORIGINAL_CHARGE_AMT,
  lkp_OVERRIDEN_CHARGE_FLAG AS lkp_OVERRIDEN_CHARGE_FLAG,
  lkp_MARK_FOR_DELETION_FLAG AS lkp_MARK_FOR_DELETION_FLAG,
  lkp_OMS_CREATED_TSTMP AS lkp_OMS_CREATED_TSTMP,
  lkp_OMS_LAST_UPDATED_TSTMP AS lkp_OMS_LAST_UPDATED_TSTMP,
  lkp_LOAD_TSTMP AS lkp_LOAD_TSTMP,
  lkp_CHARGE_NAME AS lkp_CHARGE_NAME,
  CHARGE_NAME AS CHARGE_NAME,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  JNR_OMS_A_CHARGE_DETAIL_4
WHERE
  ISNULL(lkp_OMS_CHARGE_DETAIL_ID)
  OR (
    NOT ISNULL(lkp_OMS_CHARGE_DETAIL_ID)
    AND (
      IFF(ISNULL(ENTITY_TYPE_ID), 99, ENTITY_TYPE_ID) <> IFF(
        ISNULL(lkp_OMS_ENTITY_TYPE_ID),
        99,
        lkp_OMS_ENTITY_TYPE_ID
      )
      OR IFF(ISNULL(ENTITY_ID), 9999999999, ENTITY_ID) <> IFF(
        ISNULL(lkp_OMS_ENTITY_ID),
        9999999999,
        lkp_OMS_ENTITY_ID
      )
      OR IFF(ISNULL(ENTITY_LINE_ID), 9999999999, ENTITY_LINE_ID) <> IFF(
        ISNULL(lkp_OMS_ENTITY_LINE_ID),
        9999999999,
        lkp_OMS_ENTITY_LINE_ID
      )
      OR IFF(ISNULL(CHARGE_NAME), ' ', CHARGE_NAME) <> IFF(ISNULL(lkp_CHARGE_NAME), ' ', lkp_CHARGE_NAME)
      OR IFF(ISNULL(CHARGE_CATEGORY), 99999999, CHARGE_CATEGORY) <> IFF(
        ISNULL(lkp_OMS_CHARGE_CATEGORY),
        99999999,
        lkp_OMS_CHARGE_CATEGORY
      )
      OR IFF(
        ISNULL(REASON_CODE_GROUP_ID),
        9999999999,
        REASON_CODE_GROUP_ID
      ) <> IFF(
        ISNULL(lkp_OMS_REASON_CODE_GROUP_ID),
        9999999999,
        lkp_OMS_REASON_CODE_GROUP_ID
      )
      OR IFF(ISNULL(CHARGE_AMOUNT), 9999999999, CHARGE_AMOUNT) <> IFF(ISNULL(lkp_CHARGE_AMT), 9999999999, lkp_CHARGE_AMT)
      OR IFF(
        ISNULL(ORIGINAL_CHARGE_AMOUNT),
        9999999999,
        ORIGINAL_CHARGE_AMOUNT
      ) <> IFF(
        ISNULL(lkp_ORIGINAL_CHARGE_AMT),
        9999999999,
        lkp_ORIGINAL_CHARGE_AMT
      )
      OR IFF(ISNULL(OVERRIDEN_CHARGE), 9, OVERRIDEN_CHARGE) <> IFF(
        ISNULL(lkp_OVERRIDEN_CHARGE_FLAG),
        9,
        lkp_OVERRIDEN_CHARGE_FLAG
      )
      OR IFF(ISNULL(MARK_FOR_DELETION), 9, MARK_FOR_DELETION) <> IFF(
        ISNULL(lkp_MARK_FOR_DELETION_FLAG),
        9,
        lkp_MARK_FOR_DELETION_FLAG
      )
      OR IFF(
        ISNULL(CREATED_DTTM),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        CREATED_DTTM
      ) <> IFF(
        ISNULL(lkp_OMS_CREATED_TSTMP),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        lkp_OMS_CREATED_TSTMP
      )
      OR IFF(
        ISNULL(LAST_UPDATED_DTTM),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        LAST_UPDATED_DTTM
      ) <> IFF(
        ISNULL(lkp_OMS_LAST_UPDATED_TSTMP),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        lkp_OMS_LAST_UPDATED_TSTMP
      )
    )
  )"""

df_5 = spark.sql(query_5)

df_5.createOrReplaceTempView("FIL_UNCHANGED_RECORDS_5")

# COMMAND ----------
# DBTITLE 1, EXP_UPDATE_FLAG_6


query_6 = f"""SELECT
  CHARGE_DETAIL_ID AS CHARGE_DETAIL_ID,
  ENTITY_TYPE_ID AS ENTITY_TYPE_ID,
  ENTITY_ID AS ENTITY_ID,
  ENTITY_LINE_ID AS ENTITY_LINE_ID,
  CHARGE_CATEGORY AS CHARGE_CATEGORY,
  CHARGE_AMOUNT AS CHARGE_AMOUNT,
  MARK_FOR_DELETION AS MARK_FOR_DELETION,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  OVERRIDEN_CHARGE AS OVERRIDEN_CHARGE,
  ORIGINAL_CHARGE_AMOUNT AS ORIGINAL_CHARGE_AMOUNT,
  REASON_CODE_GROUP_ID AS REASON_CODE_GROUP_ID,
  now() AS o_UPDATE_TSTMP,
  IFF(ISNULL(lkp_LOAD_TSTMP), now(), lkp_LOAD_TSTMP) AS o_LOAD_TSTMP,
  IFF(ISNULL(lkp_OMS_CHARGE_DETAIL_ID), 1, 2) AS o_UPDATE_FLAG,
  CHARGE_NAME AS CHARGE_NAME,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  FIL_UNCHANGED_RECORDS_5"""

df_6 = spark.sql(query_6)

df_6.createOrReplaceTempView("EXP_UPDATE_FLAG_6")

# COMMAND ----------
# DBTITLE 1, UPD_INSERT_UPDATE_7


query_7 = f"""SELECT
  CHARGE_DETAIL_ID AS CHARGE_DETAIL_ID,
  ENTITY_TYPE_ID AS ENTITY_TYPE_ID,
  ENTITY_ID AS ENTITY_ID,
  ENTITY_LINE_ID AS ENTITY_LINE_ID,
  CHARGE_CATEGORY AS CHARGE_CATEGORY,
  CHARGE_AMOUNT AS CHARGE_AMOUNT,
  MARK_FOR_DELETION AS MARK_FOR_DELETION,
  CREATED_DTTM AS CREATED_DTTM,
  LAST_UPDATED_DTTM AS LAST_UPDATED_DTTM,
  OVERRIDEN_CHARGE AS OVERRIDEN_CHARGE,
  ORIGINAL_CHARGE_AMOUNT AS ORIGINAL_CHARGE_AMOUNT,
  REASON_CODE_GROUP_ID AS REASON_CODE_GROUP_ID,
  o_UPDATE_TSTMP AS o_UPDATE_TSTMP,
  o_LOAD_TSTMP AS o_LOAD_TSTMP,
  o_UPDATE_FLAG AS o_UPDATE_FLAG,
  CHARGE_NAME AS CHARGE_NAME,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id,
  DECODE(o_UPDATE_FLAG, 1, 'DD_INSERT', 2, 'DD_UPDATE') AS UPDATE_STRATEGY_FLAG
FROM
  EXP_UPDATE_FLAG_6"""

df_7 = spark.sql(query_7)

df_7.createOrReplaceTempView("UPD_INSERT_UPDATE_7")

# COMMAND ----------
# DBTITLE 1, OMS_A_CHARGE_DETAIL


spark.sql("""MERGE INTO OMS_A_CHARGE_DETAIL AS TARGET
USING
  UPD_INSERT_UPDATE_7 AS SOURCE ON TARGET.OMS_CHARGE_DETAIL_ID = SOURCE.CHARGE_DETAIL_ID
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_UPDATE" THEN
UPDATE
SET
  TARGET.OMS_CHARGE_DETAIL_ID = SOURCE.CHARGE_DETAIL_ID,
  TARGET.OMS_ENTITY_TYPE_ID = SOURCE.ENTITY_TYPE_ID,
  TARGET.OMS_ENTITY_ID = SOURCE.ENTITY_ID,
  TARGET.OMS_ENTITY_LINE_ID = SOURCE.ENTITY_LINE_ID,
  TARGET.OMS_CHARGE_NAME = SOURCE.CHARGE_NAME,
  TARGET.OMS_CHARGE_CATEGORY = SOURCE.CHARGE_CATEGORY,
  TARGET.OMS_REASON_CODE_GROUP_ID = SOURCE.REASON_CODE_GROUP_ID,
  TARGET.CHARGE_AMT = SOURCE.CHARGE_AMOUNT,
  TARGET.ORIGINAL_CHARGE_AMT = SOURCE.ORIGINAL_CHARGE_AMOUNT,
  TARGET.OVERRIDEN_CHARGE_FLAG = SOURCE.OVERRIDEN_CHARGE,
  TARGET.MARK_FOR_DELETION_FLAG = SOURCE.MARK_FOR_DELETION,
  TARGET.OMS_CREATED_TSTMP = SOURCE.CREATED_DTTM,
  TARGET.OMS_LAST_UPDATED_TSTMP = SOURCE.LAST_UPDATED_DTTM,
  TARGET.UPDATE_TSTMP = SOURCE.o_UPDATE_TSTMP,
  TARGET.LOAD_TSTMP = SOURCE.o_LOAD_TSTMP
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_DELETE"
  AND TARGET.OMS_ENTITY_TYPE_ID = SOURCE.ENTITY_TYPE_ID
  AND TARGET.OMS_ENTITY_ID = SOURCE.ENTITY_ID
  AND TARGET.OMS_ENTITY_LINE_ID = SOURCE.ENTITY_LINE_ID
  AND TARGET.OMS_CHARGE_NAME = SOURCE.CHARGE_NAME
  AND TARGET.OMS_CHARGE_CATEGORY = SOURCE.CHARGE_CATEGORY
  AND TARGET.OMS_REASON_CODE_GROUP_ID = SOURCE.REASON_CODE_GROUP_ID
  AND TARGET.CHARGE_AMT = SOURCE.CHARGE_AMOUNT
  AND TARGET.ORIGINAL_CHARGE_AMT = SOURCE.ORIGINAL_CHARGE_AMOUNT
  AND TARGET.OVERRIDEN_CHARGE_FLAG = SOURCE.OVERRIDEN_CHARGE
  AND TARGET.MARK_FOR_DELETION_FLAG = SOURCE.MARK_FOR_DELETION
  AND TARGET.OMS_CREATED_TSTMP = SOURCE.CREATED_DTTM
  AND TARGET.OMS_LAST_UPDATED_TSTMP = SOURCE.LAST_UPDATED_DTTM
  AND TARGET.UPDATE_TSTMP = SOURCE.o_UPDATE_TSTMP
  AND TARGET.LOAD_TSTMP = SOURCE.o_LOAD_TSTMP THEN DELETE
  WHEN NOT MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_INSERT" THEN
INSERT
  (
    TARGET.OMS_CHARGE_DETAIL_ID,
    TARGET.OMS_ENTITY_TYPE_ID,
    TARGET.OMS_ENTITY_ID,
    TARGET.OMS_ENTITY_LINE_ID,
    TARGET.OMS_CHARGE_NAME,
    TARGET.OMS_CHARGE_CATEGORY,
    TARGET.OMS_REASON_CODE_GROUP_ID,
    TARGET.CHARGE_AMT,
    TARGET.ORIGINAL_CHARGE_AMT,
    TARGET.OVERRIDEN_CHARGE_FLAG,
    TARGET.MARK_FOR_DELETION_FLAG,
    TARGET.OMS_CREATED_TSTMP,
    TARGET.OMS_LAST_UPDATED_TSTMP,
    TARGET.UPDATE_TSTMP,
    TARGET.LOAD_TSTMP
  )
VALUES
  (
    SOURCE.CHARGE_DETAIL_ID,
    SOURCE.ENTITY_TYPE_ID,
    SOURCE.ENTITY_ID,
    SOURCE.ENTITY_LINE_ID,
    SOURCE.CHARGE_NAME,
    SOURCE.CHARGE_CATEGORY,
    SOURCE.REASON_CODE_GROUP_ID,
    SOURCE.CHARGE_AMOUNT,
    SOURCE.ORIGINAL_CHARGE_AMOUNT,
    SOURCE.OVERRIDEN_CHARGE,
    SOURCE.MARK_FOR_DELETION,
    SOURCE.CREATED_DTTM,
    SOURCE.LAST_UPDATED_DTTM,
    SOURCE.o_UPDATE_TSTMP,
    SOURCE.o_LOAD_TSTMP
  )""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_A_Charge_Detail")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_DDS_OMS_A_Charge_Detail", mainWorkflowId, parentName)
