# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ../WorkflowUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_PO_Line_Item_Ref_Fields")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_DDS_OMS_PO_Line_Item_Ref_Fields", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_PRE_0


query_0 = f"""SELECT
  PURCHASE_ORDERS_LINE_ITEM_ID AS PURCHASE_ORDERS_LINE_ITEM_ID,
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  REF_FIELD1 AS REF_FIELD1,
  REF_FIELD2 AS REF_FIELD2,
  REF_FIELD3 AS REF_FIELD3,
  REF_FIELD4 AS REF_FIELD4,
  REF_FIELD5 AS REF_FIELD5,
  REF_FIELD6 AS REF_FIELD6,
  REF_FIELD7 AS REF_FIELD7,
  REF_FIELD8 AS REF_FIELD8,
  REF_FIELD9 AS REF_FIELD9,
  REF_FIELD10 AS REF_FIELD10,
  REF_NUM1 AS REF_NUM1,
  REF_NUM2 AS REF_NUM2,
  REF_NUM3 AS REF_NUM3,
  REF_NUM4 AS REF_NUM4,
  REF_NUM5 AS REF_NUM5,
  RX_STATUS AS RX_STATUS,
  RX_ASSIGNED_TO AS RX_ASSIGNED_TO,
  RX_ASSIGNED_DTTM AS RX_ASSIGNED_DTTM,
  RX_VET_INQUIRY AS RX_VET_INQUIRY,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_PO_LINE_ITEM_REF_FIELDS_PRE"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_PRE_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_PRE_1


query_1 = f"""SELECT
  PURCHASE_ORDERS_LINE_ITEM_ID AS PURCHASE_ORDERS_LINE_ITEM_ID,
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  REF_FIELD1 AS REF_FIELD1,
  REF_FIELD2 AS REF_FIELD2,
  REF_FIELD3 AS REF_FIELD3,
  REF_FIELD4 AS REF_FIELD4,
  REF_FIELD5 AS REF_FIELD5,
  REF_FIELD6 AS REF_FIELD6,
  REF_FIELD7 AS REF_FIELD7,
  REF_FIELD8 AS REF_FIELD8,
  REF_FIELD9 AS REF_FIELD9,
  REF_FIELD10 AS REF_FIELD10,
  REF_NUM1 AS REF_NUM1,
  REF_NUM2 AS REF_NUM2,
  REF_NUM3 AS REF_NUM3,
  REF_NUM4 AS REF_NUM4,
  REF_NUM5 AS REF_NUM5,
  RX_STATUS AS RX_STATUS,
  RX_ASSIGNED_TO AS RX_ASSIGNED_TO,
  NULL AS RX_ASSIGNED_DTTM,
  RX_VET_INQUIRY AS RX_VET_INQUIRY,
  LOAD_TSTMP AS LOAD_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_PRE_0"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("SQ_Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_PRE_1")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_2


query_2 = f"""SELECT
  OMS_PURCHASE_ORDERS_LINE_ITEM_ID AS OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
  OMS_PURCHASE_ORDERS_ID AS OMS_PURCHASE_ORDERS_ID,
  REF_FIELD1 AS REF_FIELD1,
  REF_FIELD2 AS REF_FIELD2,
  REF_FIELD3 AS REF_FIELD3,
  REF_FIELD4 AS REF_FIELD4,
  REF_FIELD5 AS REF_FIELD5,
  REF_FIELD6 AS REF_FIELD6,
  REF_FIELD7 AS REF_FIELD7,
  REF_FIELD8 AS REF_FIELD8,
  REF_FIELD9 AS REF_FIELD9,
  REF_FIELD10 AS REF_FIELD10,
  REF_NUM1 AS REF_NUM1,
  REF_NUM2 AS REF_NUM2,
  REF_NUM3 AS REF_NUM3,
  REF_NUM4 AS REF_NUM4,
  REF_NUM5 AS REF_NUM5,
  RX_STATUS AS RX_STATUS,
  RX_ASSIGNED_TO AS RX_ASSIGNED_TO,
  RX_ASSIGNED_TSTMP AS RX_ASSIGNED_TSTMP,
  RX_VET_INQUIRY AS RX_VET_INQUIRY,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_PO_LINE_ITEM_REF_FIELDS"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_2")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_3


query_3 = f"""SELECT
  OMS_PURCHASE_ORDERS_LINE_ITEM_ID AS OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
  OMS_PURCHASE_ORDERS_ID AS OMS_PURCHASE_ORDERS_ID,
  REF_FIELD1 AS REF_FIELD1,
  REF_FIELD2 AS REF_FIELD2,
  REF_FIELD3 AS REF_FIELD3,
  REF_FIELD4 AS REF_FIELD4,
  REF_FIELD5 AS REF_FIELD5,
  REF_FIELD6 AS REF_FIELD6,
  REF_FIELD7 AS REF_FIELD7,
  REF_FIELD8 AS REF_FIELD8,
  REF_FIELD9 AS REF_FIELD9,
  REF_FIELD10 AS REF_FIELD10,
  REF_NUM1 AS REF_NUM1,
  REF_NUM2 AS REF_NUM2,
  REF_NUM3 AS REF_NUM3,
  REF_NUM4 AS REF_NUM4,
  REF_NUM5 AS REF_NUM5,
  RX_STATUS AS RX_STATUS,
  RX_ASSIGNED_TO AS RX_ASSIGNED_TO,
  RX_ASSIGNED_TSTMP AS RX_ASSIGNED_TSTMP,
  RX_VET_INQUIRY AS RX_VET_INQUIRY,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_2"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("SQ_Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_3")

# COMMAND ----------
# DBTITLE 1, JNR_OMS_PO_LINE_ITEM_REF_FIELDS_4


query_4 = f"""SELECT
  DETAIL.PURCHASE_ORDERS_LINE_ITEM_ID AS PURCHASE_ORDERS_LINE_ITEM_ID,
  DETAIL.PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  DETAIL.REF_FIELD1 AS REF_FIELD1,
  DETAIL.REF_FIELD2 AS REF_FIELD2,
  DETAIL.REF_FIELD3 AS REF_FIELD3,
  DETAIL.REF_FIELD4 AS REF_FIELD4,
  DETAIL.REF_FIELD5 AS REF_FIELD5,
  DETAIL.REF_FIELD6 AS REF_FIELD6,
  DETAIL.REF_FIELD7 AS REF_FIELD7,
  DETAIL.REF_FIELD8 AS REF_FIELD8,
  DETAIL.REF_FIELD9 AS REF_FIELD9,
  DETAIL.REF_FIELD10 AS REF_FIELD10,
  DETAIL.REF_NUM1 AS REF_NUM1,
  DETAIL.REF_NUM2 AS REF_NUM2,
  DETAIL.REF_NUM3 AS REF_NUM3,
  DETAIL.REF_NUM4 AS REF_NUM4,
  DETAIL.REF_NUM5 AS REF_NUM5,
  DETAIL.RX_STATUS AS RX_STATUS,
  DETAIL.RX_ASSIGNED_TO AS RX_ASSIGNED_TO,
  DETAIL.RX_ASSIGNED_DTTM AS RX_ASSIGNED_DTTM,
  DETAIL.RX_VET_INQUIRY AS RX_VET_INQUIRY,
  MASTER.OMS_PURCHASE_ORDERS_LINE_ITEM_ID AS lkp_OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
  MASTER.OMS_PURCHASE_ORDERS_ID AS lkp_OMS_PURCHASE_ORDERS_ID,
  MASTER.REF_FIELD1 AS lkp_REF_FIELD11,
  MASTER.REF_FIELD2 AS lkp_REF_FIELD21,
  MASTER.REF_FIELD3 AS lkp_REF_FIELD31,
  MASTER.REF_FIELD4 AS lkp_REF_FIELD41,
  MASTER.REF_FIELD5 AS lkp_REF_FIELD51,
  MASTER.REF_FIELD6 AS lkp_REF_FIELD61,
  MASTER.REF_FIELD7 AS lkp_REF_FIELD71,
  MASTER.REF_FIELD8 AS lkp_REF_FIELD81,
  MASTER.REF_FIELD9 AS lkp_REF_FIELD91,
  MASTER.REF_FIELD10 AS lkp_REF_FIELD101,
  MASTER.REF_NUM1 AS lkp_REF_NUM11,
  MASTER.REF_NUM2 AS lkp_REF_NUM21,
  MASTER.REF_NUM3 AS lkp_REF_NUM31,
  MASTER.REF_NUM4 AS lkp_REF_NUM41,
  MASTER.REF_NUM5 AS lkp_REF_NUM51,
  MASTER.RX_STATUS AS lkp_RX_STATUS1,
  MASTER.RX_ASSIGNED_TO AS lkp_RX_ASSIGNED_TO1,
  MASTER.RX_ASSIGNED_TSTMP AS lkp_RX_ASSIGNED_TSTMP,
  MASTER.RX_VET_INQUIRY AS lkp_RX_VET_INQUIRY1,
  MASTER.LOAD_TSTMP AS lkp_LOAD_TSTMP,
  DETAIL.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_3 MASTER
  RIGHT JOIN SQ_Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_PRE_1 DETAIL ON MASTER.OMS_PURCHASE_ORDERS_LINE_ITEM_ID = DETAIL.PURCHASE_ORDERS_LINE_ITEM_ID"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("JNR_OMS_PO_LINE_ITEM_REF_FIELDS_4")

# COMMAND ----------
# DBTITLE 1, FIL_UNCHANGED_RECORDS_5


query_5 = f"""SELECT
  PURCHASE_ORDERS_LINE_ITEM_ID AS PURCHASE_ORDERS_LINE_ITEM_ID,
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  REF_FIELD1 AS REF_FIELD1,
  REF_FIELD2 AS REF_FIELD2,
  REF_FIELD3 AS REF_FIELD3,
  REF_FIELD4 AS REF_FIELD4,
  REF_FIELD5 AS REF_FIELD5,
  REF_FIELD6 AS REF_FIELD6,
  REF_FIELD7 AS REF_FIELD7,
  REF_FIELD8 AS REF_FIELD8,
  REF_FIELD9 AS REF_FIELD9,
  REF_FIELD10 AS REF_FIELD10,
  REF_NUM1 AS REF_NUM1,
  REF_NUM2 AS REF_NUM2,
  REF_NUM3 AS REF_NUM3,
  REF_NUM4 AS REF_NUM4,
  REF_NUM5 AS REF_NUM5,
  RX_STATUS AS RX_STATUS,
  RX_ASSIGNED_TO AS RX_ASSIGNED_TO,
  RX_ASSIGNED_DTTM AS RX_ASSIGNED_DTTM,
  RX_VET_INQUIRY AS RX_VET_INQUIRY,
  lkp_OMS_PURCHASE_ORDERS_LINE_ITEM_ID AS lkp_OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
  lkp_OMS_PURCHASE_ORDERS_ID AS lkp_OMS_PURCHASE_ORDERS_ID,
  lkp_REF_FIELD11 AS lkp_REF_FIELD11,
  lkp_REF_FIELD21 AS lkp_REF_FIELD21,
  lkp_REF_FIELD31 AS lkp_REF_FIELD31,
  lkp_REF_FIELD41 AS lkp_REF_FIELD41,
  lkp_REF_FIELD51 AS lkp_REF_FIELD51,
  lkp_REF_FIELD61 AS lkp_REF_FIELD61,
  lkp_REF_FIELD71 AS lkp_REF_FIELD71,
  lkp_REF_FIELD81 AS lkp_REF_FIELD81,
  lkp_REF_FIELD91 AS lkp_REF_FIELD91,
  lkp_REF_FIELD101 AS lkp_REF_FIELD101,
  lkp_REF_NUM11 AS lkp_REF_NUM11,
  lkp_REF_NUM21 AS lkp_REF_NUM21,
  lkp_REF_NUM31 AS lkp_REF_NUM31,
  lkp_REF_NUM41 AS lkp_REF_NUM41,
  lkp_REF_NUM51 AS lkp_REF_NUM51,
  lkp_RX_STATUS1 AS lkp_RX_STATUS1,
  lkp_RX_ASSIGNED_TO1 AS lkp_RX_ASSIGNED_TO1,
  lkp_RX_ASSIGNED_TSTMP AS lkp_RX_ASSIGNED_TSTMP,
  lkp_RX_VET_INQUIRY1 AS lkp_RX_VET_INQUIRY1,
  lkp_LOAD_TSTMP AS lkp_LOAD_TSTMP,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  JNR_OMS_PO_LINE_ITEM_REF_FIELDS_4
WHERE
  ISNULL(lkp_OMS_PURCHASE_ORDERS_LINE_ITEM_ID)
  OR (
    NOT ISNULL(lkp_OMS_PURCHASE_ORDERS_LINE_ITEM_ID)
    AND (
      IFF(
        ISNULL(PURCHASE_ORDERS_ID),
        9999999999,
        PURCHASE_ORDERS_ID
      ) <> IFF(
        ISNULL(lkp_OMS_PURCHASE_ORDERS_ID),
        9999999999,
        lkp_OMS_PURCHASE_ORDERS_ID
      )
      OR IFF(
        ISNULL(LTRIM(RTRIM(REF_FIELD1))),
        ' ',
        LTRIM(RTRIM(REF_FIELD1))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_REF_FIELD11))),
        ' ',
        LTRIM(RTRIM(lkp_REF_FIELD11))
      )
      OR IFF(
        ISNULL(LTRIM(RTRIM(REF_FIELD2))),
        ' ',
        LTRIM(RTRIM(REF_FIELD2))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_REF_FIELD21))),
        ' ',
        LTRIM(RTRIM(lkp_REF_FIELD21))
      )
      OR IFF(
        ISNULL(LTRIM(RTRIM(REF_FIELD3))),
        ' ',
        LTRIM(RTRIM(REF_FIELD3))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_REF_FIELD31))),
        ' ',
        LTRIM(RTRIM(lkp_REF_FIELD31))
      )
      OR IFF(
        ISNULL(LTRIM(RTRIM(REF_FIELD4))),
        ' ',
        LTRIM(RTRIM(REF_FIELD4))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_REF_FIELD41))),
        ' ',
        LTRIM(RTRIM(lkp_REF_FIELD41))
      )
      OR IFF(
        ISNULL(LTRIM(RTRIM(REF_FIELD5))),
        ' ',
        LTRIM(RTRIM(REF_FIELD5))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_REF_FIELD51))),
        ' ',
        LTRIM(RTRIM(lkp_REF_FIELD51))
      )
      OR IFF(
        ISNULL(LTRIM(RTRIM(REF_FIELD6))),
        ' ',
        LTRIM(RTRIM(REF_FIELD6))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_REF_FIELD61))),
        ' ',
        LTRIM(RTRIM(lkp_REF_FIELD61))
      )
      OR IFF(
        ISNULL(LTRIM(RTRIM(REF_FIELD7))),
        ' ',
        LTRIM(RTRIM(REF_FIELD7))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_REF_FIELD71))),
        ' ',
        LTRIM(RTRIM(lkp_REF_FIELD71))
      )
      OR IFF(
        ISNULL(LTRIM(RTRIM(REF_FIELD8))),
        ' ',
        LTRIM(RTRIM(REF_FIELD8))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_REF_FIELD81))),
        ' ',
        LTRIM(RTRIM(lkp_REF_FIELD81))
      )
      OR IFF(
        ISNULL(LTRIM(RTRIM(REF_FIELD9))),
        ' ',
        LTRIM(RTRIM(REF_FIELD9))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_REF_FIELD91))),
        ' ',
        LTRIM(RTRIM(lkp_REF_FIELD91))
      )
      OR IFF(
        ISNULL(LTRIM(RTRIM(REF_FIELD10))),
        ' ',
        LTRIM(RTRIM(REF_FIELD10))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_REF_FIELD101))),
        ' ',
        LTRIM(RTRIM(lkp_REF_FIELD101))
      )
      OR IFF(ISNULL(REF_NUM1), 9999999999, REF_NUM1) <> IFF(ISNULL(lkp_REF_NUM11), 9999999999, lkp_REF_NUM11)
      OR IFF(ISNULL(REF_NUM2), 9999999999, REF_NUM2) <> IFF(ISNULL(lkp_REF_NUM21), 9999999999, lkp_REF_NUM21)
      OR IFF(ISNULL(REF_NUM3), 9999999999, REF_NUM3) <> IFF(ISNULL(lkp_REF_NUM31), 9999999999, lkp_REF_NUM31)
      OR IFF(ISNULL(REF_NUM4), 9999999999, REF_NUM4) <> IFF(ISNULL(lkp_REF_NUM41), 9999999999, lkp_REF_NUM41)
      OR IFF(ISNULL(REF_NUM5), 9999999999, REF_NUM5) <> IFF(ISNULL(lkp_REF_NUM51), 9999999999, lkp_REF_NUM51)
      OR IFF(
        ISNULL(LTRIM(RTRIM(RX_STATUS))),
        ' ',
        LTRIM(RTRIM(RX_STATUS))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_RX_STATUS1))),
        ' ',
        LTRIM(RTRIM(lkp_RX_STATUS1))
      )
      OR IFF(
        ISNULL(LTRIM(RTRIM(RX_ASSIGNED_TO))),
        ' ',
        LTRIM(RTRIM(RX_ASSIGNED_TO))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_RX_ASSIGNED_TO1))),
        ' ',
        LTRIM(RTRIM(lkp_RX_ASSIGNED_TO1))
      )
      OR IFF(
        ISNULL(RX_ASSIGNED_DTTM),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        RX_ASSIGNED_DTTM
      ) <> IFF(
        ISNULL(lkp_RX_ASSIGNED_TSTMP),
        To_DATE('12-31-9999', 'MM-DD-YYYY'),
        lkp_RX_ASSIGNED_TSTMP
      )
      OR IFF(
        ISNULL(LTRIM(RTRIM(RX_VET_INQUIRY))),
        ' ',
        LTRIM(RTRIM(RX_VET_INQUIRY))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(lkp_RX_VET_INQUIRY1))),
        ' ',
        LTRIM(RTRIM(lkp_RX_VET_INQUIRY1))
      )
    )
  )"""

df_5 = spark.sql(query_5)

df_5.createOrReplaceTempView("FIL_UNCHANGED_RECORDS_5")

# COMMAND ----------
# DBTITLE 1, EXP_UPDATE_FLAG_6


query_6 = f"""SELECT
  PURCHASE_ORDERS_LINE_ITEM_ID AS PURCHASE_ORDERS_LINE_ITEM_ID,
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  REF_FIELD1 AS REF_FIELD1,
  REF_FIELD2 AS REF_FIELD2,
  REF_FIELD3 AS REF_FIELD3,
  REF_FIELD4 AS REF_FIELD4,
  REF_FIELD5 AS REF_FIELD5,
  REF_FIELD6 AS REF_FIELD6,
  REF_FIELD7 AS REF_FIELD7,
  REF_FIELD8 AS REF_FIELD8,
  REF_FIELD9 AS REF_FIELD9,
  REF_FIELD10 AS REF_FIELD10,
  REF_NUM1 AS REF_NUM1,
  REF_NUM2 AS REF_NUM2,
  REF_NUM3 AS REF_NUM3,
  REF_NUM4 AS REF_NUM4,
  REF_NUM5 AS REF_NUM5,
  RX_STATUS AS RX_STATUS,
  RX_ASSIGNED_TO AS RX_ASSIGNED_TO,
  RX_ASSIGNED_DTTM AS RX_ASSIGNED_DTTM,
  RX_VET_INQUIRY AS RX_VET_INQUIRY,
  now() AS o_UPDATE_TSTMP,
  IFF(ISNULL(lkp_LOAD_TSTMP), now(), lkp_LOAD_TSTMP) AS o_LOAD_TSTMP,
  IFF(ISNULL(lkp_OMS_PURCHASE_ORDERS_LINE_ITEM_ID), 1, 2) AS o_UPDATE_FLAG,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  FIL_UNCHANGED_RECORDS_5"""

df_6 = spark.sql(query_6)

df_6.createOrReplaceTempView("EXP_UPDATE_FLAG_6")

# COMMAND ----------
# DBTITLE 1, UPD_INSERT_UPDATE_7


query_7 = f"""SELECT
  PURCHASE_ORDERS_LINE_ITEM_ID AS PURCHASE_ORDERS_LINE_ITEM_ID,
  PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  REF_FIELD1 AS REF_FIELD1,
  REF_FIELD2 AS REF_FIELD2,
  REF_FIELD3 AS REF_FIELD3,
  REF_FIELD4 AS REF_FIELD4,
  REF_FIELD5 AS REF_FIELD5,
  REF_FIELD6 AS REF_FIELD6,
  REF_FIELD7 AS REF_FIELD7,
  REF_FIELD8 AS REF_FIELD8,
  REF_FIELD9 AS REF_FIELD9,
  REF_FIELD10 AS REF_FIELD10,
  REF_NUM1 AS REF_NUM1,
  REF_NUM2 AS REF_NUM2,
  REF_NUM3 AS REF_NUM3,
  REF_NUM4 AS REF_NUM4,
  REF_NUM5 AS REF_NUM5,
  RX_STATUS AS RX_STATUS,
  RX_ASSIGNED_TO AS RX_ASSIGNED_TO,
  RX_ASSIGNED_DTTM AS RX_ASSIGNED_DTTM,
  RX_VET_INQUIRY AS RX_VET_INQUIRY,
  o_UPDATE_TSTMP AS o_UPDATE_TSTMP,
  o_LOAD_TSTMP AS o_LOAD_TSTMP,
  o_UPDATE_FLAG AS o_UPDATE_FLAG,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id,
  DECODE(o_UPDATE_FLAG, 1, 'DD_INSERT', 2, 'DD_UPDATE') AS UPDATE_STRATEGY_FLAG
FROM
  EXP_UPDATE_FLAG_6"""

df_7 = spark.sql(query_7)

df_7.createOrReplaceTempView("UPD_INSERT_UPDATE_7")

# COMMAND ----------
# DBTITLE 1, OMS_PO_LINE_ITEM_REF_FIELDS


spark.sql("""MERGE INTO OMS_PO_LINE_ITEM_REF_FIELDS AS TARGET
USING
  UPD_INSERT_UPDATE_7 AS SOURCE ON TARGET.OMS_PURCHASE_ORDERS_LINE_ITEM_ID = SOURCE.PURCHASE_ORDERS_LINE_ITEM_ID
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_UPDATE" THEN
UPDATE
SET
  TARGET.OMS_PURCHASE_ORDERS_LINE_ITEM_ID = SOURCE.PURCHASE_ORDERS_LINE_ITEM_ID,
  TARGET.OMS_PURCHASE_ORDERS_ID = SOURCE.PURCHASE_ORDERS_ID,
  TARGET.REF_FIELD1 = SOURCE.REF_FIELD1,
  TARGET.REF_FIELD2 = SOURCE.REF_FIELD2,
  TARGET.REF_FIELD3 = SOURCE.REF_FIELD3,
  TARGET.REF_FIELD4 = SOURCE.REF_FIELD4,
  TARGET.REF_FIELD5 = SOURCE.REF_FIELD5,
  TARGET.REF_FIELD6 = SOURCE.REF_FIELD6,
  TARGET.REF_FIELD7 = SOURCE.REF_FIELD7,
  TARGET.REF_FIELD8 = SOURCE.REF_FIELD8,
  TARGET.REF_FIELD9 = SOURCE.REF_FIELD9,
  TARGET.REF_FIELD10 = SOURCE.REF_FIELD10,
  TARGET.REF_NUM1 = SOURCE.REF_NUM1,
  TARGET.REF_NUM2 = SOURCE.REF_NUM2,
  TARGET.REF_NUM3 = SOURCE.REF_NUM3,
  TARGET.REF_NUM4 = SOURCE.REF_NUM4,
  TARGET.REF_NUM5 = SOURCE.REF_NUM5,
  TARGET.RX_STATUS = SOURCE.RX_STATUS,
  TARGET.RX_ASSIGNED_TO = SOURCE.RX_ASSIGNED_TO,
  TARGET.RX_ASSIGNED_TSTMP = SOURCE.RX_ASSIGNED_DTTM,
  TARGET.RX_VET_INQUIRY = SOURCE.RX_VET_INQUIRY,
  TARGET.UPDATE_TSTMP = SOURCE.o_UPDATE_TSTMP,
  TARGET.LOAD_TSTMP = SOURCE.o_LOAD_TSTMP
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_DELETE"
  AND TARGET.OMS_PURCHASE_ORDERS_ID = SOURCE.PURCHASE_ORDERS_ID
  AND TARGET.REF_FIELD1 = SOURCE.REF_FIELD1
  AND TARGET.REF_FIELD2 = SOURCE.REF_FIELD2
  AND TARGET.REF_FIELD3 = SOURCE.REF_FIELD3
  AND TARGET.REF_FIELD4 = SOURCE.REF_FIELD4
  AND TARGET.REF_FIELD5 = SOURCE.REF_FIELD5
  AND TARGET.REF_FIELD6 = SOURCE.REF_FIELD6
  AND TARGET.REF_FIELD7 = SOURCE.REF_FIELD7
  AND TARGET.REF_FIELD8 = SOURCE.REF_FIELD8
  AND TARGET.REF_FIELD9 = SOURCE.REF_FIELD9
  AND TARGET.REF_FIELD10 = SOURCE.REF_FIELD10
  AND TARGET.REF_NUM1 = SOURCE.REF_NUM1
  AND TARGET.REF_NUM2 = SOURCE.REF_NUM2
  AND TARGET.REF_NUM3 = SOURCE.REF_NUM3
  AND TARGET.REF_NUM4 = SOURCE.REF_NUM4
  AND TARGET.REF_NUM5 = SOURCE.REF_NUM5
  AND TARGET.RX_STATUS = SOURCE.RX_STATUS
  AND TARGET.RX_ASSIGNED_TO = SOURCE.RX_ASSIGNED_TO
  AND TARGET.RX_ASSIGNED_TSTMP = SOURCE.RX_ASSIGNED_DTTM
  AND TARGET.RX_VET_INQUIRY = SOURCE.RX_VET_INQUIRY
  AND TARGET.UPDATE_TSTMP = SOURCE.o_UPDATE_TSTMP
  AND TARGET.LOAD_TSTMP = SOURCE.o_LOAD_TSTMP THEN DELETE
  WHEN NOT MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_INSERT" THEN
INSERT
  (
    TARGET.OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
    TARGET.OMS_PURCHASE_ORDERS_ID,
    TARGET.REF_FIELD1,
    TARGET.REF_FIELD2,
    TARGET.REF_FIELD3,
    TARGET.REF_FIELD4,
    TARGET.REF_FIELD5,
    TARGET.REF_FIELD6,
    TARGET.REF_FIELD7,
    TARGET.REF_FIELD8,
    TARGET.REF_FIELD9,
    TARGET.REF_FIELD10,
    TARGET.REF_NUM1,
    TARGET.REF_NUM2,
    TARGET.REF_NUM3,
    TARGET.REF_NUM4,
    TARGET.REF_NUM5,
    TARGET.RX_STATUS,
    TARGET.RX_ASSIGNED_TO,
    TARGET.RX_ASSIGNED_TSTMP,
    TARGET.RX_VET_INQUIRY,
    TARGET.UPDATE_TSTMP,
    TARGET.LOAD_TSTMP
  )
VALUES
  (
    SOURCE.PURCHASE_ORDERS_LINE_ITEM_ID,
    SOURCE.PURCHASE_ORDERS_ID,
    SOURCE.REF_FIELD1,
    SOURCE.REF_FIELD2,
    SOURCE.REF_FIELD3,
    SOURCE.REF_FIELD4,
    SOURCE.REF_FIELD5,
    SOURCE.REF_FIELD6,
    SOURCE.REF_FIELD7,
    SOURCE.REF_FIELD8,
    SOURCE.REF_FIELD9,
    SOURCE.REF_FIELD10,
    SOURCE.REF_NUM1,
    SOURCE.REF_NUM2,
    SOURCE.REF_NUM3,
    SOURCE.REF_NUM4,
    SOURCE.REF_NUM5,
    SOURCE.RX_STATUS,
    SOURCE.RX_ASSIGNED_TO,
    SOURCE.RX_ASSIGNED_DTTM,
    SOURCE.RX_VET_INQUIRY,
    SOURCE.o_UPDATE_TSTMP,
    SOURCE.o_LOAD_TSTMP
  )""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_DDS_OMS_PO_Line_Item_Ref_Fields")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_DDS_OMS_PO_Line_Item_Ref_Fields", mainWorkflowId, parentName)
