# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ../WorkflowUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_OMS_LPN")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_OMS_LPN", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_FACILITY_0


query_0 = f"""SELECT
  OMS_FACILITY_ID AS OMS_FACILITY_ID,
  FACILITY_TYPE_BITS AS FACILITY_TYPE_BITS,
  MARK_FOR_DELETION_FLAG AS MARK_FOR_DELETION_FLAG,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_FACILITY"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_OMS_FACILITY_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_FACILITY_1


query_1 = f"""SELECT
  OMS_FACILITY_ID AS FACILITY_ID,
  FACILITY_TYPE_BITS AS FACILITY_TYPE_BITS,
  OMS_LAST_UPDATED_TSTMP AS f_OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP_OMS_FACILITY,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_FACILITY_0"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("SQ_Shortcut_to_OMS_FACILITY_1")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_LPN_DETAIL_2


query_2 = f"""SELECT
  OMS_LPN_ID AS OMS_LPN_ID,
  OMS_LPN_DETAIL_ID AS OMS_LPN_DETAIL_ID,
  OMS_ASN_DTL_ID AS OMS_ASN_DTL_ID,
  OMS_DISTRIBUTION_ORDER_DTL_ID AS OMS_DISTRIBUTION_ORDER_DTL_ID,
  OMS_ITEM_ID AS OMS_ITEM_ID,
  OMS_ITEM_NAME AS OMS_ITEM_NAME,
  SHIPPED_QTY AS SHIPPED_QTY,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_LPN_DETAIL"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("Shortcut_to_OMS_LPN_DETAIL_2")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_LPN_DETAIL_3


query_3 = f"""SELECT
  OMS_LPN_ID AS LPN_ID,
  OMS_LPN_DETAIL_ID AS LPN_DETAIL_ID,
  OMS_DISTRIBUTION_ORDER_DTL_ID AS DISTRIBUTION_ORDER_DTL_ID,
  SHIPPED_QTY AS SHIPPED_QTY,
  OMS_ITEM_NAME AS ITEM_NAME,
  OMS_LAST_UPDATED_TSTMP AS ld_OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_LPN_DETAIL_2"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("SQ_Shortcut_to_OMS_LPN_DETAIL_3")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_ORDERS_4


query_4 = f"""SELECT
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  OMS_TC_ORDER_ID AS OMS_TC_ORDER_ID,
  OMS_PURCHASE_ORDER_ID AS OMS_PURCHASE_ORDER_ID,
  OMS_PURCHASE_ORDER_NBR AS OMS_PURCHASE_ORDER_NBR,
  OMS_EXT_PURCHASE_ORDER AS OMS_EXT_PURCHASE_ORDER,
  OMS_ORDER_TYPE AS OMS_ORDER_TYPE,
  OMS_ORDER_STATUS_ID AS OMS_ORDER_STATUS_ID,
  OMS_DO_TYPE_ID AS OMS_DO_TYPE_ID,
  OMS_DO_STATUS_ID AS OMS_DO_STATUS_ID,
  OMS_SHIPMENT_ID AS OMS_SHIPMENT_ID,
  OMS_CREATION_TYPE_ID AS OMS_CREATION_TYPE_ID,
  OMS_BILLING_METHOD_ID AS OMS_BILLING_METHOD_ID,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  OMS_DELIVERY_OPTIONS_ID AS OMS_DELIVERY_OPTIONS_ID,
  CUSTOMER_PICKUP_FLAG AS CUSTOMER_PICKUP_FLAG,
  PARTIALLY_PLANNED_FLAG AS PARTIALLY_PLANNED_FLAG,
  PARTIAL_SHIP_CONFIRMATION_FLAG AS PARTIAL_SHIP_CONFIRMATION_FLAG,
  PARTIAL_SHIP_CONFIRMATION_STATUS AS PARTIAL_SHIP_CONFIRMATION_STATUS,
  HAS_ALERTS_FLAG AS HAS_ALERTS_FLAG,
  HAS_SPLIT_FLAG AS HAS_SPLIT_FLAG,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  BACK_ORDERED_FLAG AS BACK_ORDERED_FLAG,
  OMS_INBOUND_REGION_ID AS OMS_INBOUND_REGION_ID,
  OMS_OUTBOUND_REGION_ID AS OMS_OUTBOUND_REGION_ID,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  OMS_O_FACILITY_ID AS OMS_O_FACILITY_ID,
  OMS_D_FACILITY_ALIAS_ID AS OMS_D_FACILITY_ALIAS_ID,
  OMS_D_FACILITY_ID AS OMS_D_FACILITY_ID,
  OMS_BILL_FACILITY_ALIAS_ID AS OMS_BILL_FACILITY_ALIAS_ID,
  OMS_BILL_FACILITY_ID AS OMS_BILL_FACILITY_ID,
  OMS_CUSTOMER_ID AS OMS_CUSTOMER_ID,
  ADDR_VALID_FLAG AS ADDR_VALID_FLAG,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PICKUP_TZ_ID AS OMS_PICKUP_TZ_ID,
  OMS_DELIVERY_TZ_ID AS OMS_DELIVERY_TZ_ID,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_ORDER_DT_TSTMP AS OMS_ORDER_DT_TSTMP,
  OMS_ORDER_RECON_TSTMP AS OMS_ORDER_RECON_TSTMP,
  OMS_SCHED_PICKUP_TSTMP AS OMS_SCHED_PICKUP_TSTMP,
  OMS_SCHED_DELIVERY_TSTMP AS OMS_SCHED_DELIVERY_TSTMP,
  OMS_ACTUAL_SHIPPED_TSTMP AS OMS_ACTUAL_SHIPPED_TSTMP,
  TOTAL_NBR_OF_UNITS AS TOTAL_NBR_OF_UNITS,
  BASELINE_COST AS BASELINE_COST,
  ACTUAL_COST AS ACTUAL_COST,
  MONETARY_VALUE AS MONETARY_VALUE,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  REF_NUM1 AS REF_NUM1,
  OMS_CREATED_SOURCE_TYPE_ID AS OMS_CREATED_SOURCE_TYPE_ID,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_ORDERS"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("Shortcut_to_OMS_ORDERS_4")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_ORDERS_5


query_5 = f"""SELECT
  OMS_ORDER_ID AS ORDER_ID,
  OMS_O_FACILITY_ALIAS_ID AS O_FACILITY_ALIAS_ID,
  OMS_O_FACILITY_ID AS O_FACILITY_ID,
  OMS_LAST_UPDATED_TSTMP AS o_OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_ORDERS_4"""

df_5 = spark.sql(query_5)

df_5.createOrReplaceTempView("SQ_Shortcut_to_OMS_ORDERS_5")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_LPN_DDS_6


query_6 = f"""SELECT
  OMS_LPN_ID AS OMS_LPN_ID,
  OMS_TC_LPN_ID AS OMS_TC_LPN_ID,
  OMS_PARENT_LPN_ID AS OMS_PARENT_LPN_ID,
  OMS_LPN_TYPE_ID AS OMS_LPN_TYPE_ID,
  OMS_LPN_STATUS_ID AS OMS_LPN_STATUS_ID,
  OMS_LPN_STATUS_UPDATED_TSTMP AS OMS_LPN_STATUS_UPDATED_TSTMP,
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_SHIPMENT_ID AS OMS_SHIPMENT_ID,
  OMS_ASN_ID AS OMS_ASN_ID,
  OMS_TC_ASN_ID AS OMS_TC_ASN_ID,
  OMS_FINAL_DEST_FACILITY_ALIAS_ID AS OMS_FINAL_DEST_FACILITY_ALIAS_ID,
  OMS_TRACKING_NBR AS OMS_TRACKING_NBR,
  BASE_CHARGE_AMT AS BASE_CHARGE_AMT,
  BASE_CHARGE_CURRENCY_CD AS BASE_CHARGE_CURRENCY_CD,
  ADDL_OPTION_CHARGE_AMT AS ADDL_OPTION_CHARGE_AMT,
  ADDL_OPTION_CHARGE_CURRENCY_CD AS ADDL_OPTION_CHARGE_CURRENCY_CD,
  ACTUAL_CHARGE_AMT AS ACTUAL_CHARGE_AMT,
  ACTUAL_CHARGE_CURRENCY_CD AS ACTUAL_CHARGE_CURRENCY_CD,
  DIST_CHARGE_AMT AS DIST_CHARGE_AMT,
  DIST_CHARGE_CURRENCY_CD AS DIST_CHARGE_CURRENCY_CD,
  FREIGHT_CHARGE_AMT AS FREIGHT_CHARGE_AMT,
  FREIGHT_CHARGE_CURRENCY_CD AS FREIGHT_CHARGE_CURRENCY_CD,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_LPN_DDS"""

df_6 = spark.sql(query_6)

df_6.createOrReplaceTempView("Shortcut_to_OMS_LPN_DDS_6")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_LPN_DDS_7


query_7 = f"""SELECT
  OMS_LPN_ID AS LPN_ID,
  OMS_TC_LPN_ID AS TC_LPN_ID,
  OMS_PARENT_LPN_ID AS PARENT_LPN_ID,
  OMS_LPN_TYPE_ID AS LPN_TYPE,
  OMS_LPN_STATUS_ID AS LPN_STATUS,
  OMS_TRACKING_NBR AS TRACKING_NBR,
  BASE_CHARGE_AMT AS BASE_CHARGE,
  DIST_CHARGE_AMT AS DIST_CHARGE,
  FREIGHT_CHARGE_AMT AS FREIGHT_CHARGE,
  OMS_TC_ASN_ID AS TC_ASN_ID,
  OMS_ASN_ID AS ASN_ID,
  OMS_CREATED_TSTMP AS CREATED_DTTM,
  OMS_LAST_UPDATED_TSTMP AS LAST_UPDATED_DTTM,
  OMS_ORDER_ID AS ORDER_ID,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_LPN_DDS_6"""

df_7 = spark.sql(query_7)

df_7.createOrReplaceTempView("SQ_Shortcut_to_OMS_LPN_DDS_7")

# COMMAND ----------
# DBTITLE 1, JNR_LPN_DETAIL_8


query_8 = f"""SELECT
  DETAIL.LPN_ID AS LPN_ID,
  DETAIL.TC_LPN_ID AS TC_LPN_ID,
  DETAIL.PARENT_LPN_ID AS PARENT_LPN_ID,
  DETAIL.LPN_TYPE AS LPN_TYPE,
  DETAIL.LPN_STATUS AS LPN_STATUS,
  DETAIL.TRACKING_NBR AS TRACKING_NBR,
  DETAIL.BASE_CHARGE AS BASE_CHARGE,
  DETAIL.DIST_CHARGE AS DIST_CHARGE,
  DETAIL.FREIGHT_CHARGE AS FREIGHT_CHARGE,
  DETAIL.TC_ASN_ID AS TC_ASN_ID,
  DETAIL.ASN_ID AS ASN_ID,
  DETAIL.CREATED_DTTM AS CREATED_DTTM,
  DETAIL.LAST_UPDATED_DTTM AS lpn_LAST_UPDATED_DTTM,
  DETAIL.ORDER_ID AS lpn_ORDER_ID,
  MASTER.LPN_ID AS LPN_ID1,
  MASTER.LPN_DETAIL_ID AS LPN_DETAIL_ID,
  MASTER.DISTRIBUTION_ORDER_DTL_ID AS DISTRIBUTION_ORDER_DTL_ID,
  MASTER.SHIPPED_QTY AS SHIPPED_QTY,
  MASTER.ITEM_NAME AS ITEM_NAME,
  DETAIL.UPDATE_TSTMP AS UPDATE_TSTMP_OMS_LPN_DDS,
  MASTER.UPDATE_TSTMP AS UPDATE_TSTMP_OMS_LPN_DETAIL,
  MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_LPN_DETAIL_3 MASTER
  INNER JOIN SQ_Shortcut_to_OMS_LPN_DDS_7 DETAIL ON MASTER.LPN_ID = DETAIL.LPN_ID"""

df_8 = spark.sql(query_8)

df_8.createOrReplaceTempView("JNR_LPN_DETAIL_8")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_9


query_9 = f"""SELECT
  OMS_PURCHASE_ORDERS_ID AS OMS_PURCHASE_ORDERS_ID,
  OMS_PURCHASE_ORDERS_LINE_ITEM_ID AS OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
  OMS_TC_PO_LINE_ID AS OMS_TC_PO_LINE_ID,
  OMS_PARENT_PO_LINE_ITEM_ID AS OMS_PARENT_PO_LINE_ITEM_ID,
  OMS_ORIGINAL_PO_LINE_ITEM_ID AS OMS_ORIGINAL_PO_LINE_ITEM_ID,
  OMS_PURCHASE_ORDERS_LINE_STATUS_ID AS OMS_PURCHASE_ORDERS_LINE_STATUS_ID,
  ORDER_FULFILLMENT_OPTION_ID AS ORDER_FULFILLMENT_OPTION_ID,
  SKU AS SKU,
  CUST_SKU AS CUST_SKU,
  OMS_PRODUCT_CLASS_ID AS OMS_PRODUCT_CLASS_ID,
  RETURNABLE_FLAG AS RETURNABLE_FLAG,
  EXCHANGEABLE_FLAG AS EXCHANGEABLE_FLAG,
  PRICE_OVERRIDE_FLAG AS PRICE_OVERRIDE_FLAG,
  OMS_STORE_FACILITY_ALIAS_ID AS OMS_STORE_FACILITY_ALIAS_ID,
  OMS_STORE_FACILITY_ID AS OMS_STORE_FACILITY_ID,
  OMS_O_FACILITY_ID AS OMS_O_FACILITY_ID,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  OMS_BILL_FACILITY_ALIAS_ID AS OMS_BILL_FACILITY_ALIAS_ID,
  OMS_BILL_FACILITY_ID AS OMS_BILL_FACILITY_ID,
  OMS_D_FACILITY_ID AS OMS_D_FACILITY_ID,
  OMS_D_FACILITY_ALIAS_ID AS OMS_D_FACILITY_ALIAS_ID,
  D_FIRST_NAME AS D_FIRST_NAME,
  D_LAST_NAME AS D_LAST_NAME,
  D_ADDR_1 AS D_ADDR_1,
  D_ADDR_2 AS D_ADDR_2,
  D_ADDR_3 AS D_ADDR_3,
  D_CITY AS D_CITY,
  D_STATE_PROV AS D_STATE_PROV,
  D_POSTAL_CD AS D_POSTAL_CD,
  D_COUNTY AS D_COUNTY,
  D_COUNTRY_CD AS D_COUNTRY_CD,
  D_PHONE_NBR AS D_PHONE_NBR,
  D_EMAIL AS D_EMAIL,
  ADDR_VALID_FLAG AS ADDR_VALID_FLAG,
  OMS_ALLOC_FINALIZER AS OMS_ALLOC_FINALIZER,
  OMS_DSG_CARRIER_ID AS OMS_DSG_CARRIER_ID,
  DSG_SHIP_VIA AS DSG_SHIP_VIA,
  DO_CREATED_FLAG AS DO_CREATED_FLAG,
  READY_TO_SHIP_FLAG AS READY_TO_SHIP_FLAG,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  CLOSED_FLAG AS CLOSED_FLAG,
  DELETED_FLAG AS DELETED_FLAG,
  OMS_REASON_ID AS OMS_REASON_ID,
  OMS_REASON_CODES_GROUP_ID AS OMS_REASON_CODES_GROUP_ID,
  OMS_BACK_ORD_REASON_ID AS OMS_BACK_ORD_REASON_ID,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PICKUP_TZ_ID AS OMS_PICKUP_TZ_ID,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_DELIVERY_TZ_ID AS OMS_DELIVERY_TZ_ID,
  OMS_REQ_DLVR_TSTMP AS OMS_REQ_DLVR_TSTMP,
  OMS_MUST_DLVR_TSTMP AS OMS_MUST_DLVR_TSTMP,
  OMS_SHIP_BY_DT AS OMS_SHIP_BY_DT,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  ORDER_QTY AS ORDER_QTY,
  CANCELLED_QTY AS CANCELLED_QTY,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  RELEASED_QTY AS RELEASED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  PPACK_QTY AS PPACK_QTY,
  SHIPPED_QTY AS SHIPPED_QTY,
  ORIGINAL_PRICE_AMT AS ORIGINAL_PRICE_AMT,
  RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  UNIT_TAX_AMT AS UNIT_TAX_AMT,
  LINE_TOTAL_AMT AS LINE_TOTAL_AMT,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  OMS_EXT_CREATED_TSTMP AS OMS_EXT_CREATED_TSTMP,
  OMS_CREATED_SOURCE_TYPE_ID AS OMS_CREATED_SOURCE_TYPE_ID,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_PURCHASE_ORDERS_LINE_ITEM"""

df_9 = spark.sql(query_9)

df_9.createOrReplaceTempView("Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_9")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_10


query_10 = f"""SELECT
  OMS_PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  OMS_PURCHASE_ORDERS_LINE_ITEM_ID AS PURCHASE_ORDERS_LINE_ITEM_ID,
  OMS_LAST_UPDATED_TSTMP AS poli_OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_9"""

df_10 = spark.sql(query_10)

df_10.createOrReplaceTempView("SQ_Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_10")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_PURCHASE_ORDERS_11


query_11 = f"""SELECT
  OMS_PURCHASE_ORDERS_ID AS OMS_PURCHASE_ORDERS_ID,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  OMS_EXT_PURCHASE_ORDERS_ID AS OMS_EXT_PURCHASE_ORDERS_ID,
  OMS_PARENT_PURCHASE_ORDERS_ID AS OMS_PARENT_PURCHASE_ORDERS_ID,
  OMS_PURCHASE_ORDERS_TYPE_ID AS OMS_PURCHASE_ORDERS_TYPE_ID,
  OMS_PURCHASE_ORDERS_STATUS_ID AS OMS_PURCHASE_ORDERS_STATUS_ID,
  OMS_ORDER_CATEGORY_ID AS OMS_ORDER_CATEGORY_ID,
  OMS_O_FACILITY_ID AS OMS_O_FACILITY_ID,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  OMS_D_FACILITY_ID AS OMS_D_FACILITY_ID,
  OMS_D_FACILITY_ALIAS_ID AS OMS_D_FACILITY_ALIAS_ID,
  OMS_BILL_FACILITY_ID AS OMS_BILL_FACILITY_ID,
  OMS_BILL_FACILITY_ALIAS_ID AS OMS_BILL_FACILITY_ALIAS_ID,
  OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID AS OMS_ORIGIN_SHIP_VIA_FACILITY_ALIAS_ID,
  OMS_ORIGIN_SHIP_VIA_FACILITY_ID AS OMS_ORIGIN_SHIP_VIA_FACILITY_ID,
  OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID AS OMS_DES_SHIP_VIA_FACILITY_ALIAS_ID,
  OMS_DES_SHIP_VIA_FACILITY_ID AS OMS_DES_SHIP_VIA_FACILITY_ID,
  OMS_CUSTOMER_CD AS OMS_CUSTOMER_CD,
  CUSTOMER_FIRST_NAME AS CUSTOMER_FIRST_NAME,
  CUSTOMER_LAST_NAME AS CUSTOMER_LAST_NAME,
  CUSTOMER_PHONE_NBR AS CUSTOMER_PHONE_NBR,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  OMS_RETURN_REFERENCE_NBR AS OMS_RETURN_REFERENCE_NBR,
  OMS_BILL_OF_LADING_NBR AS OMS_BILL_OF_LADING_NBR,
  OMS_TRANS_RESP_CD AS OMS_TRANS_RESP_CD,
  OMS_COMMODITY_CODE_ID AS OMS_COMMODITY_CODE_ID,
  OMS_CARRIER_ID AS OMS_CARRIER_ID,
  OMS_PRODUCT_CLASS_ID AS OMS_PRODUCT_CLASS_ID,
  OMS_PROTECTION_LEVEL_ID AS OMS_PROTECTION_LEVEL_ID,
  OMS_CREATION_TYPE_ID AS OMS_CREATION_TYPE_ID,
  OMS_CHANNEL_TYPE_ID AS OMS_CHANNEL_TYPE_ID,
  OMS_CHANNEL_ID AS OMS_CHANNEL_ID,
  OMS_FULFILL_MODE_ID AS OMS_FULFILL_MODE_ID,
  OMS_ENTERED_BY AS OMS_ENTERED_BY,
  OMS_ENTRY_CD AS OMS_ENTRY_CD,
  OMS_PAYMENT_MODE_ID AS OMS_PAYMENT_MODE_ID,
  OMS_PAYMENT_STATUS_ID AS OMS_PAYMENT_STATUS_ID,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  ORDER_RECEIVED_FLAG AS ORDER_RECEIVED_FLAG,
  ON_HOLD_FLAG AS ON_HOLD_FLAG,
  HAS_ALERTS_FLAG AS HAS_ALERTS_FLAG,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  CLOSED_FLAG AS CLOSED_FLAG,
  OMS_REASON_ID AS OMS_REASON_ID,
  OMS_DECLINE_REASON_ID AS OMS_DECLINE_REASON_ID,
  OMS_REASON_CODES_GROUP_ID AS OMS_REASON_CODES_GROUP_ID,
  IMPORTED_FLAG AS IMPORTED_FLAG,
  PURCHASE_ORDERS_RECONCILED_FLAG AS PURCHASE_ORDERS_RECONCILED_FLAG,
  READY_TO_SHIP_FLAG AS READY_TO_SHIP_FLAG,
  CUSTOMER_PICKUP_FLAG AS CUSTOMER_PICKUP_FLAG,
  DIRECT_ALLOWED_FLAG AS DIRECT_ALLOWED_FLAG,
  PARTIALLY_PLANNED_FLAG AS PARTIALLY_PLANNED_FLAG,
  OMS_PURCHASE_ORDERS_DT_TSTMP AS OMS_PURCHASE_ORDERS_DT_TSTMP,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PICKUP_TZ_ID AS OMS_PICKUP_TZ_ID,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_DELIVERY_TZ_ID AS OMS_DELIVERY_TZ_ID,
  OMS_REQUESTED_DLVR_TSTMP AS OMS_REQUESTED_DLVR_TSTMP,
  OMS_MUST_DLVR_TSTMP AS OMS_MUST_DLVR_TSTMP,
  OMS_PROMISED_DLVR_TSTMP AS OMS_PROMISED_DLVR_TSTMP,
  OMS_DUE_DT AS OMS_DUE_DT,
  OMS_CANCEL_DT AS OMS_CANCEL_DT,
  OMS_RELEASE_TSTMP AS OMS_RELEASE_TSTMP,
  OMS_FIRST_RCPT_TSTMP AS OMS_FIRST_RCPT_TSTMP,
  OMS_LAST_RCPT_TSTMP AS OMS_LAST_RCPT_TSTMP,
  MONETARY_VALUE AS MONETARY_VALUE,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  ORIG_BUDG_COST AS ORIG_BUDG_COST,
  BUDG_COST AS BUDG_COST,
  BUDG_COST_CURRENCY_CD AS BUDG_COST_CURRENCY_CD,
  TAX_CHARGES_AMT AS TAX_CHARGES_AMT,
  MISC_CHARGES_AMT AS MISC_CHARGES_AMT,
  GRAND_TOTAL_AMT AS GRAND_TOTAL_AMT,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  CURRENCY_CD AS CURRENCY_CD,
  OMS_CREATED_SOURCE_TYPE_ID AS OMS_CREATED_SOURCE_TYPE_ID,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_PURCHASE_ORDERS"""

df_11 = spark.sql(query_11)

df_11.createOrReplaceTempView("Shortcut_to_OMS_PURCHASE_ORDERS_11")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_PURCHASE_ORDERS_12


query_12 = f"""SELECT
  OMS_PURCHASE_ORDERS_ID AS PURCHASE_ORDERS_ID,
  OMS_CREATED_TSTMP AS CREATED_DTTM,
  OMS_LAST_UPDATED_TSTMP AS po_OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_PURCHASE_ORDERS_11"""

df_12 = spark.sql(query_12)

df_12.createOrReplaceTempView("SQ_Shortcut_to_OMS_PURCHASE_ORDERS_12")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_ORDER_LINE_ITEM_13


query_13 = f"""SELECT
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  OMS_MASTER_ORDER_ID AS OMS_MASTER_ORDER_ID,
  OMS_MO_LINE_ITEM_ID AS OMS_MO_LINE_ITEM_ID,
  OMS_TC_ORDER_LINE_ID AS OMS_TC_ORDER_LINE_ID,
  OMS_PURCHASE_ORDER_NBR AS OMS_PURCHASE_ORDER_NBR,
  OMS_PURCHASE_ORDER_LINE_NBR AS OMS_PURCHASE_ORDER_LINE_NBR,
  OMS_ITEM_ID AS OMS_ITEM_ID,
  OMS_ITEM_NAME AS OMS_ITEM_NAME,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_ACTUAL_SHIPPED_TSTMP AS OMS_ACTUAL_SHIPPED_TSTMP,
  OMS_DO_DTL_STATUS_ID AS OMS_DO_DTL_STATUS_ID,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  OMS_EVENT_CD AS OMS_EVENT_CD,
  OMS_REASON_CD AS OMS_REASON_CD,
  OMS_EXP_INFO_CD AS OMS_EXP_INFO_CD,
  PARTIAL_FILL_FLAG AS PARTIAL_FILL_FLAG,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  USER_CANCELED_QTY AS USER_CANCELED_QTY,
  ORDER_QTY AS ORDER_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  SHIPPED_QTY AS SHIPPED_QTY,
  RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  UNIT_COST_AMT AS UNIT_COST_AMT,
  UNIT_TAX_AMT AS UNIT_TAX_AMT,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_ORDER_LINE_ITEM"""

df_13 = spark.sql(query_13)

df_13.createOrReplaceTempView("Shortcut_to_OMS_ORDER_LINE_ITEM_13")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_ORDER_LINE_ITEM_14


query_14 = f"""SELECT
  OMS_ORDER_ID AS ORDER_ID,
  OMS_LINE_ITEM_ID AS LINE_ITEM_ID,
  OMS_MASTER_ORDER_ID AS MASTER_ORDER_ID,
  OMS_MO_LINE_ITEM_ID AS MO_LINE_ITEM_ID,
  OMS_LAST_UPDATED_TSTMP AS oli_LAST_UPDATED_DTTM,
  OMS_ITEM_NAME AS ITEM_NAME,
  OMS_TC_COMPANY_ID AS TC_COMPANY_ID,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_ORDER_LINE_ITEM_13"""

df_14 = spark.sql(query_14)

df_14.createOrReplaceTempView("SQ_Shortcut_to_OMS_ORDER_LINE_ITEM_14")

# COMMAND ----------
# DBTITLE 1, JNR_ORDER_LINE_ITEM_15


query_15 = f"""SELECT
  DETAIL.LPN_ID AS LPN_ID,
  DETAIL.TC_LPN_ID AS TC_LPN_ID,
  DETAIL.PARENT_LPN_ID AS PARENT_LPN_ID,
  DETAIL.LPN_TYPE AS LPN_TYPE,
  DETAIL.LPN_STATUS AS LPN_STATUS,
  DETAIL.TRACKING_NBR AS TRACKING_NBR,
  DETAIL.BASE_CHARGE AS BASE_CHARGE,
  DETAIL.DIST_CHARGE AS DIST_CHARGE,
  DETAIL.FREIGHT_CHARGE AS FREIGHT_CHARGE,
  DETAIL.TC_ASN_ID AS TC_ASN_ID,
  DETAIL.ASN_ID AS ASN_ID,
  DETAIL.CREATED_DTTM AS CREATED_DTTM,
  DETAIL.lpn_LAST_UPDATED_DTTM AS lpn_LAST_UPDATED_DTTM,
  DETAIL.lpn_ORDER_ID AS lpn_ORDER_ID,
  DETAIL.LPN_DETAIL_ID AS LPN_DETAIL_ID,
  DETAIL.DISTRIBUTION_ORDER_DTL_ID AS DISTRIBUTION_ORDER_DTL_ID,
  DETAIL.SHIPPED_QTY AS SHIPPED_QTY,
  MASTER.ORDER_ID AS dol_ORDER_ID,
  MASTER.LINE_ITEM_ID AS dol_LINE_ITEM_ID,
  MASTER.MASTER_ORDER_ID AS dol_MASTER_ORDER_ID,
  MASTER.MO_LINE_ITEM_ID AS dol_MO_LINE_ITEM_ID,
  MASTER.oli_LAST_UPDATED_DTTM AS dol_LAST_UPDATED_DTTM,
  MASTER.ITEM_NAME AS dol_ITEM_NAME,
  DETAIL.ITEM_NAME AS ITEM_NAME,
  MASTER.TC_COMPANY_ID AS TC_COMPANY_ID,
  DETAIL.UPDATE_TSTMP_OMS_LPN_DDS AS UPDATE_TSTMP_OMS_LPN_DDS,
  DETAIL.UPDATE_TSTMP_OMS_LPN_DETAIL AS UPDATE_TSTMP_OMS_LPN_DETAIL,
  MASTER.UPDATE_TSTMP AS UPDATE_TSTMP_OMS_ORDER_LINE_ITEM,
  MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_ORDER_LINE_ITEM_14 MASTER
  INNER JOIN JNR_LPN_DETAIL_8 DETAIL ON MASTER.LINE_ITEM_ID = DETAIL.DISTRIBUTION_ORDER_DTL_ID
  AND MASTER.ORDER_ID = DETAIL.lpn_ORDER_ID"""

df_15 = spark.sql(query_15)

df_15.createOrReplaceTempView("JNR_ORDER_LINE_ITEM_15")

# COMMAND ----------
# DBTITLE 1, Jnr_ORDER_16


query_16 = f"""SELECT
  DETAIL.LPN_ID AS LPN_ID,
  DETAIL.TC_LPN_ID AS TC_LPN_ID,
  DETAIL.PARENT_LPN_ID AS PARENT_LPN_ID,
  DETAIL.LPN_TYPE AS LPN_TYPE,
  DETAIL.LPN_STATUS AS LPN_STATUS,
  DETAIL.TRACKING_NBR AS TRACKING_NBR,
  DETAIL.BASE_CHARGE AS BASE_CHARGE,
  DETAIL.DIST_CHARGE AS DIST_CHARGE,
  DETAIL.FREIGHT_CHARGE AS FREIGHT_CHARGE,
  DETAIL.TC_ASN_ID AS TC_ASN_ID,
  DETAIL.ASN_ID AS ASN_ID,
  DETAIL.CREATED_DTTM AS CREATED_DTTM,
  DETAIL.lpn_LAST_UPDATED_DTTM AS lpn_LAST_UPDATED_DTTM,
  DETAIL.lpn_ORDER_ID AS lpn_ORDER_ID,
  DETAIL.LPN_DETAIL_ID AS LPN_DETAIL_ID,
  DETAIL.DISTRIBUTION_ORDER_DTL_ID AS DISTRIBUTION_ORDER_DTL_ID,
  DETAIL.SHIPPED_QTY AS SHIPPED_QTY,
  DETAIL.dol_ORDER_ID AS dol_ORDER_ID,
  DETAIL.dol_LINE_ITEM_ID AS dol_LINE_ITEM_ID,
  DETAIL.dol_MASTER_ORDER_ID AS dol_MASTER_ORDER_ID,
  DETAIL.dol_MO_LINE_ITEM_ID AS dol_MO_LINE_ITEM_ID,
  MASTER.ORDER_ID AS do_ORDER_ID,
  MASTER.O_FACILITY_ALIAS_ID AS do_O_FACILITY_ALIAS_ID,
  DETAIL.dol_ITEM_NAME AS dol_ITEM_NAME,
  DETAIL.ITEM_NAME AS ITEM_NAME,
  DETAIL.TC_COMPANY_ID AS TC_COMPANY_ID,
  MASTER.O_FACILITY_ID AS O_FACILITY_ID,
  DETAIL.UPDATE_TSTMP_OMS_LPN_DDS AS UPDATE_TSTMP_OMS_LPN_DDS,
  DETAIL.UPDATE_TSTMP_OMS_LPN_DETAIL AS UPDATE_TSTMP_OMS_LPN_DETAIL,
  DETAIL.UPDATE_TSTMP_OMS_ORDER_LINE_ITEM AS UPDATE_TSTMP_OMS_ORDER_LINE_ITEM,
  MASTER.UPDATE_TSTMP AS UPDATE_TSTMP_OMS_ORDERS,
  MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_ORDERS_5 MASTER
  INNER JOIN JNR_ORDER_LINE_ITEM_15 DETAIL ON MASTER.ORDER_ID = DETAIL.dol_ORDER_ID"""

df_16 = spark.sql(query_16)

df_16.createOrReplaceTempView("Jnr_ORDER_16")

# COMMAND ----------
# DBTITLE 1, JJnr_Facility_17


query_17 = f"""SELECT
  DETAIL.LPN_ID AS LPN_ID,
  DETAIL.TC_LPN_ID AS TC_LPN_ID,
  DETAIL.PARENT_LPN_ID AS PARENT_LPN_ID,
  DETAIL.LPN_TYPE AS LPN_TYPE,
  DETAIL.LPN_STATUS AS LPN_STATUS,
  DETAIL.TRACKING_NBR AS TRACKING_NBR,
  DETAIL.BASE_CHARGE AS BASE_CHARGE,
  DETAIL.DIST_CHARGE AS DIST_CHARGE,
  DETAIL.FREIGHT_CHARGE AS FREIGHT_CHARGE,
  DETAIL.TC_ASN_ID AS TC_ASN_ID,
  DETAIL.ASN_ID AS ASN_ID,
  DETAIL.CREATED_DTTM AS CREATED_DTTM,
  DETAIL.lpn_LAST_UPDATED_DTTM AS lpn_LAST_UPDATED_DTTM,
  DETAIL.LPN_DETAIL_ID AS LPN_DETAIL_ID,
  DETAIL.DISTRIBUTION_ORDER_DTL_ID AS DISTRIBUTION_ORDER_DTL_ID,
  DETAIL.SHIPPED_QTY AS SHIPPED_QTY,
  DETAIL.dol_LINE_ITEM_ID AS dol_LINE_ITEM_ID,
  DETAIL.dol_MASTER_ORDER_ID AS dol_MASTER_ORDER_ID,
  DETAIL.dol_MO_LINE_ITEM_ID AS dol_MO_LINE_ITEM_ID,
  DETAIL.do_ORDER_ID AS do_ORDER_ID,
  DETAIL.do_O_FACILITY_ALIAS_ID AS do_O_FACILITY_ALIAS_ID,
  DETAIL.dol_ITEM_NAME AS dol_ITEM_NAME,
  DETAIL.ITEM_NAME AS ITEM_NAME,
  DETAIL.TC_COMPANY_ID AS TC_COMPANY_ID,
  DETAIL.O_FACILITY_ID AS O_FACILITY_ID,
  MASTER.FACILITY_ID AS FACILITY_ID,
  MASTER.FACILITY_TYPE_BITS AS FACILITY_TYPE_BITS,
  DETAIL.UPDATE_TSTMP_OMS_LPN_DDS AS UPDATE_TSTMP_OMS_LPN_DDS,
  DETAIL.UPDATE_TSTMP_OMS_LPN_DETAIL AS UPDATE_TSTMP_OMS_LPN_DETAIL,
  DETAIL.UPDATE_TSTMP_OMS_ORDER_LINE_ITEM AS UPDATE_TSTMP_OMS_ORDER_LINE_ITEM,
  DETAIL.UPDATE_TSTMP_OMS_ORDERS AS UPDATE_TSTMP_OMS_ORDERS,
  MASTER.UPDATE_TSTMP_OMS_FACILITY AS UPDATE_TSTMP_OMS_FACILITY,
  DETAIL.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_FACILITY_1 MASTER
  RIGHT JOIN Jnr_ORDER_16 DETAIL ON MASTER.FACILITY_ID = DETAIL.O_FACILITY_ID"""

df_17 = spark.sql(query_17)

df_17.createOrReplaceTempView("JJnr_Facility_17")

# COMMAND ----------
# DBTITLE 1, JNR_POL_18


query_18 = f"""SELECT
  DETAIL.LPN_ID AS LPN_ID,
  DETAIL.TC_LPN_ID AS TC_LPN_ID,
  DETAIL.PARENT_LPN_ID AS PARENT_LPN_ID,
  DETAIL.LPN_TYPE AS LPN_TYPE,
  DETAIL.LPN_STATUS AS LPN_STATUS,
  DETAIL.TRACKING_NBR AS TRACKING_NBR,
  DETAIL.BASE_CHARGE AS BASE_CHARGE,
  DETAIL.DIST_CHARGE AS DIST_CHARGE,
  DETAIL.FREIGHT_CHARGE AS FREIGHT_CHARGE,
  DETAIL.TC_ASN_ID AS TC_ASN_ID,
  DETAIL.ASN_ID AS ASN_ID,
  DETAIL.CREATED_DTTM AS CREATED_DTTM,
  DETAIL.lpn_LAST_UPDATED_DTTM AS lpn_LAST_UPDATED_DTTM,
  DETAIL.LPN_DETAIL_ID AS LPN_DETAIL_ID,
  DETAIL.DISTRIBUTION_ORDER_DTL_ID AS DISTRIBUTION_ORDER_DTL_ID,
  DETAIL.SHIPPED_QTY AS SHIPPED_QTY,
  DETAIL.dol_ITEM_NAME AS dol_ITEM_NAME,
  DETAIL.dol_LINE_ITEM_ID AS dol_LINE_ITEM_ID,
  DETAIL.dol_MASTER_ORDER_ID AS dol_MASTER_ORDER_ID,
  DETAIL.dol_MO_LINE_ITEM_ID AS dol_MO_LINE_ITEM_ID,
  DETAIL.do_ORDER_ID AS do_ORDER_ID,
  DETAIL.do_O_FACILITY_ALIAS_ID AS do_O_FACILITY_ALIAS_ID,
  MASTER.PURCHASE_ORDERS_ID AS pol_PURCHASE_ORDERS_ID,
  MASTER.PURCHASE_ORDERS_LINE_ITEM_ID AS pol_PURCHASE_ORDERS_LINE_ITEM_ID,
  DETAIL.ITEM_NAME AS ITEM_NAME,
  DETAIL.TC_COMPANY_ID AS TC_COMPANY_ID,
  DETAIL.FACILITY_TYPE_BITS AS FACILITY_TYPE_BITS,
  MASTER.UPDATE_TSTMP AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM,
  DETAIL.UPDATE_TSTMP_OMS_LPN_DDS AS UPDATE_TSTMP_OMS_LPN_DDS,
  DETAIL.UPDATE_TSTMP_OMS_LPN_DETAIL AS UPDATE_TSTMP_OMS_LPN_DETAIL,
  DETAIL.UPDATE_TSTMP_OMS_ORDER_LINE_ITEM AS UPDATE_TSTMP_OMS_ORDER_LINE_ITEM,
  DETAIL.UPDATE_TSTMP_OMS_ORDERS AS UPDATE_TSTMP_OMS_ORDERS,
  DETAIL.UPDATE_TSTMP_OMS_FACILITY AS UPDATE_TSTMP_OMS_FACILITY,
  MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_PURCHASE_ORDERS_LINE_ITEM_10 MASTER
  INNER JOIN JJnr_Facility_17 DETAIL ON MASTER.PURCHASE_ORDERS_ID = DETAIL.dol_MASTER_ORDER_ID
  AND MASTER.PURCHASE_ORDERS_LINE_ITEM_ID = DETAIL.dol_MO_LINE_ITEM_ID"""

df_18 = spark.sql(query_18)

df_18.createOrReplaceTempView("JNR_POL_18")

# COMMAND ----------
# DBTITLE 1, JNR_PO_19


query_19 = f"""SELECT
  DETAIL.LPN_ID AS LPN_ID,
  DETAIL.TC_LPN_ID AS TC_LPN_ID,
  DETAIL.PARENT_LPN_ID AS PARENT_LPN_ID,
  DETAIL.LPN_TYPE AS LPN_TYPE,
  DETAIL.LPN_STATUS AS LPN_STATUS,
  DETAIL.TRACKING_NBR AS TRACKING_NBR,
  DETAIL.BASE_CHARGE AS BASE_CHARGE,
  DETAIL.DIST_CHARGE AS DIST_CHARGE,
  DETAIL.FREIGHT_CHARGE AS FREIGHT_CHARGE,
  DETAIL.TC_ASN_ID AS TC_ASN_ID,
  DETAIL.ASN_ID AS ASN_ID,
  DETAIL.CREATED_DTTM AS CREATED_DTTM,
  DETAIL.lpn_LAST_UPDATED_DTTM AS lpn_LAST_UPDATED_DTTM,
  DETAIL.LPN_DETAIL_ID AS LPN_DETAIL_ID,
  DETAIL.DISTRIBUTION_ORDER_DTL_ID AS DISTRIBUTION_ORDER_DTL_ID,
  DETAIL.SHIPPED_QTY AS SHIPPED_QTY,
  DETAIL.dol_ITEM_NAME AS dol_ITEM_NAME,
  DETAIL.dol_LINE_ITEM_ID AS dol_LINE_ITEM_ID,
  DETAIL.dol_MASTER_ORDER_ID AS dol_MASTER_ORDER_ID,
  DETAIL.dol_MO_LINE_ITEM_ID AS dol_MO_LINE_ITEM_ID,
  DETAIL.do_ORDER_ID AS do_ORDER_ID,
  DETAIL.do_O_FACILITY_ALIAS_ID AS do_O_FACILITY_ALIAS_ID,
  DETAIL.pol_PURCHASE_ORDERS_ID AS pol_PURCHASE_ORDERS_ID,
  DETAIL.pol_PURCHASE_ORDERS_LINE_ITEM_ID AS pol_PURCHASE_ORDERS_LINE_ITEM_ID,
  MASTER.PURCHASE_ORDERS_ID AS po_PURCHASE_ORDERS_ID,
  MASTER.CREATED_DTTM AS po_CREATED_DTTM,
  DETAIL.ITEM_NAME AS ITEM_NAME,
  DETAIL.TC_COMPANY_ID AS TC_COMPANY_ID,
  DETAIL.FACILITY_TYPE_BITS AS FACILITY_TYPE_BITS,
  DETAIL.UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM,
  DETAIL.UPDATE_TSTMP_OMS_LPN_DDS AS UPDATE_TSTMP_OMS_LPN_DDS,
  DETAIL.UPDATE_TSTMP_OMS_LPN_DETAIL AS UPDATE_TSTMP_OMS_LPN_DETAIL,
  DETAIL.UPDATE_TSTMP_OMS_ORDER_LINE_ITEM AS UPDATE_TSTMP_OMS_ORDER_LINE_ITEM,
  DETAIL.UPDATE_TSTMP_OMS_ORDERS AS UPDATE_TSTMP_OMS_ORDERS,
  DETAIL.UPDATE_TSTMP_OMS_FACILITY AS UPDATE_TSTMP_OMS_FACILITY,
  MASTER.UPDATE_TSTMP AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS,
  MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_PURCHASE_ORDERS_12 MASTER
  INNER JOIN JNR_POL_18 DETAIL ON MASTER.PURCHASE_ORDERS_ID = DETAIL.pol_PURCHASE_ORDERS_ID"""

df_19 = spark.sql(query_19)

df_19.createOrReplaceTempView("JNR_PO_19")

# COMMAND ----------
# DBTITLE 1, EXP_CONV_20


query_20 = f"""SELECT
  LPN_ID AS src_LPN_ID,
  TC_LPN_ID AS src_TC_LPN_ID,
  PARENT_LPN_ID AS src_PARENT_LPN_ID,
  LPN_TYPE AS src_LPN_TYPE,
  LPN_STATUS AS src_LPN_STATUS,
  TRACKING_NBR AS src_TRACKING_NBR,
  BASE_CHARGE AS src_BASE_CHARGE,
  DIST_CHARGE AS src_DIST_CHARGE,
  FREIGHT_CHARGE AS src_FREIGHT_CHARGE,
  TC_ASN_ID AS src_TC_ASN_ID,
  ASN_ID AS src_ASN_ID,
  CREATED_DTTM AS src_CREATED_DTTM,
  lpn_LAST_UPDATED_DTTM AS src_lpn_LAST_UPDATED_DTTM,
  LPN_DETAIL_ID AS src_LPN_DETAIL_ID,
  do_ORDER_ID AS src_do_ORDER_ID,
  dol_MASTER_ORDER_ID AS src_dol_MASTER_ORDER_ID,
  dol_LINE_ITEM_ID AS src_dol_LINE_ITEM_ID,
  DISTRIBUTION_ORDER_DTL_ID AS src_DISTRIBUTION_ORDER_DTL_ID,
  dol_ITEM_NAME AS src_dol_ITEM_NAME,
  SHIPPED_QTY AS src_SHIPPED_QTY,
  do_O_FACILITY_ALIAS_ID AS src_do_O_FACILITY_ALIAS_ID,
  po_CREATED_DTTM AS src_po_CREATED_DTTM,
  TO_DATE(
    TO_CHAR(po_CREATED_DTTM, 'YYYY-MM-DD'),
    'YYYY-MM-DD'
  ) AS join_Date,
  ITEM_NAME AS src_ITEM_NAME,
  TO_INTEGER(ITEM_NAME) AS src_ITEM_NAME_exp,
  TC_COMPANY_ID AS src_TC_COMPANY_ID,
  DECODE(FACILITY_TYPE_BITS, 64, 8, 545, 6, 33, 6, 9, 19, 8) AS src_FACILITY_TYPE_ID,
  UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM,
  UPDATE_TSTMP_OMS_LPN_DDS AS UPDATE_TSTMP_OMS_LPN_DDS,
  UPDATE_TSTMP_OMS_LPN_DETAIL AS UPDATE_TSTMP_OMS_LPN_DETAIL,
  UPDATE_TSTMP_OMS_ORDER_LINE_ITEM AS UPDATE_TSTMP_OMS_ORDER_LINE_ITEM,
  UPDATE_TSTMP_OMS_ORDERS AS UPDATE_TSTMP_OMS_ORDERS,
  UPDATE_TSTMP_OMS_FACILITY AS UPDATE_TSTMP_OMS_FACILITY,
  UPDATE_TSTMP_OMS_PURCHASE_ORDERS AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  JNR_PO_19"""

df_20 = spark.sql(query_20)

df_20.createOrReplaceTempView("EXP_CONV_20")

# COMMAND ----------
# DBTITLE 1, lkp_SKU_Profile_21


query_21 = f"""SELECT
  SP.PRODUCT_ID AS PRODUCT_ID,
  SP.SKU_NBR AS SKU_NBR,
  EC2.src_LPN_ID AS src_LPN_ID,
  EC2.src_TC_LPN_ID AS src_TC_LPN_ID,
  EC2.src_PARENT_LPN_ID AS src_PARENT_LPN_ID,
  EC2.src_LPN_TYPE AS src_LPN_TYPE,
  EC2.src_LPN_STATUS AS src_LPN_STATUS,
  EC2.src_TRACKING_NBR AS src_TRACKING_NBR,
  EC2.src_BASE_CHARGE AS src_BASE_CHARGE,
  EC2.src_DIST_CHARGE AS src_DIST_CHARGE,
  EC2.src_FREIGHT_CHARGE AS src_FREIGHT_CHARGE,
  EC2.src_TC_ASN_ID AS src_TC_ASN_ID,
  EC2.src_ASN_ID AS src_ASN_ID,
  EC2.src_CREATED_DTTM AS src_CREATED_DTTM,
  EC2.src_lpn_LAST_UPDATED_DTTM AS src_lpn_LAST_UPDATED_DTTM,
  EC2.src_LPN_DETAIL_ID AS src_LPN_DETAIL_ID,
  EC2.src_do_ORDER_ID AS src_do_ORDER_ID,
  EC2.src_dol_MASTER_ORDER_ID AS src_dol_MASTER_ORDER_ID,
  EC2.src_dol_LINE_ITEM_ID AS src_dol_LINE_ITEM_ID,
  EC2.src_DISTRIBUTION_ORDER_DTL_ID AS src_DISTRIBUTION_ORDER_DTL_ID,
  EC2.src_dol_ITEM_NAME AS src_dol_ITEM_NAME,
  EC2.src_SHIPPED_QTY AS src_SHIPPED_QTY,
  EC2.src_do_O_FACILITY_ALIAS_ID AS src_do_O_FACILITY_ALIAS_ID,
  EC2.join_Date AS src_po_CREATED_DTTM,
  EC2.src_ITEM_NAME AS src_ITEM_NAME,
  EC2.src_ITEM_NAME_exp AS src_ITEM_NAME_exp,
  EC2.src_TC_COMPANY_ID AS src_TC_COMPANY_ID,
  EC2.src_FACILITY_TYPE_ID AS src_FACILITY_TYPE_ID,
  EC2.UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM,
  EC2.UPDATE_TSTMP_OMS_LPN_DDS AS UPDATE_TSTMP_OMS_LPN_DDS,
  EC2.UPDATE_TSTMP_OMS_LPN_DETAIL AS UPDATE_TSTMP_OMS_LPN_DETAIL,
  EC2.UPDATE_TSTMP_OMS_ORDER_LINE_ITEM AS UPDATE_TSTMP_OMS_ORDER_LINE_ITEM,
  EC2.UPDATE_TSTMP_OMS_ORDERS AS UPDATE_TSTMP_OMS_ORDERS,
  EC2.UPDATE_TSTMP_OMS_FACILITY AS UPDATE_TSTMP_OMS_FACILITY,
  EC2.UPDATE_TSTMP_OMS_PURCHASE_ORDERS AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS,
  EC2.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  EXP_CONV_20 EC2
  LEFT JOIN SKU_PROFILE SP ON SP.SKU_NBR = EC2.src_ITEM_NAME_exp"""

df_21 = spark.sql(query_21)

df_21.createOrReplaceTempView("lkp_SKU_Profile_21")

# COMMAND ----------
# DBTITLE 1, lkp_Site_Profile_22


query_22 = f"""SELECT
  SP.LOCATION_ID AS LOCATION_ID,
  SP.LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
  SP.LOCATION_NBR AS LOCATION_NBR,
  lSP2.PRODUCT_ID AS PRODUCT_ID,
  lSP2.SKU_NBR AS SKU_NBR,
  lSP2.src_LPN_ID AS src_LPN_ID,
  lSP2.src_TC_LPN_ID AS src_TC_LPN_ID,
  lSP2.src_PARENT_LPN_ID AS src_PARENT_LPN_ID,
  lSP2.src_LPN_TYPE AS src_LPN_TYPE,
  lSP2.src_LPN_STATUS AS src_LPN_STATUS,
  lSP2.src_TRACKING_NBR AS src_TRACKING_NBR,
  lSP2.src_BASE_CHARGE AS src_BASE_CHARGE,
  lSP2.src_DIST_CHARGE AS src_DIST_CHARGE,
  lSP2.src_FREIGHT_CHARGE AS src_FREIGHT_CHARGE,
  lSP2.src_TC_ASN_ID AS src_TC_ASN_ID,
  lSP2.src_ASN_ID AS src_ASN_ID,
  lSP2.src_CREATED_DTTM AS src_CREATED_DTTM,
  lSP2.src_lpn_LAST_UPDATED_DTTM AS src_lpn_LAST_UPDATED_DTTM,
  lSP2.src_LPN_DETAIL_ID AS src_LPN_DETAIL_ID,
  lSP2.src_do_ORDER_ID AS src_do_ORDER_ID,
  lSP2.src_dol_MASTER_ORDER_ID AS src_dol_MASTER_ORDER_ID,
  lSP2.src_dol_LINE_ITEM_ID AS src_dol_LINE_ITEM_ID,
  lSP2.src_DISTRIBUTION_ORDER_DTL_ID AS src_DISTRIBUTION_ORDER_DTL_ID,
  lSP2.src_dol_ITEM_NAME AS src_dol_ITEM_NAME,
  lSP2.src_SHIPPED_QTY AS src_SHIPPED_QTY,
  lSP2.src_do_O_FACILITY_ALIAS_ID AS src_do_O_FACILITY_ALIAS_ID,
  lSP2.src_po_CREATED_DTTM AS src_po_CREATED_DTTM,
  lSP2.src_ITEM_NAME AS src_ITEM_NAME,
  lSP2.src_ITEM_NAME_exp AS src_ITEM_NAME_exp,
  lSP2.src_TC_COMPANY_ID AS src_TC_COMPANY_ID,
  lSP2.src_FACILITY_TYPE_ID AS src_FACILITY_TYPE_ID,
  lSP2.UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM,
  lSP2.UPDATE_TSTMP_OMS_LPN_DDS AS UPDATE_TSTMP_OMS_LPN_DDS,
  lSP2.UPDATE_TSTMP_OMS_LPN_DETAIL AS UPDATE_TSTMP_OMS_LPN_DETAIL,
  lSP2.UPDATE_TSTMP_OMS_ORDER_LINE_ITEM AS UPDATE_TSTMP_OMS_ORDER_LINE_ITEM,
  lSP2.UPDATE_TSTMP_OMS_ORDERS AS UPDATE_TSTMP_OMS_ORDERS,
  lSP2.UPDATE_TSTMP_OMS_FACILITY AS UPDATE_TSTMP_OMS_FACILITY,
  lSP2.UPDATE_TSTMP_OMS_PURCHASE_ORDERS AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS,
  lSP2.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  lkp_SKU_Profile_21 lSP2
  LEFT JOIN SITE_PROFILE SP ON SP.LOCATION_TYPE_ID = lSP2.src_FACILITY_TYPE_ID
  AND SP.LOCATION_NBR = lSP2.src_do_O_FACILITY_ALIAS_ID"""

df_22 = spark.sql(query_22)

df_22.createOrReplaceTempView("lkp_Site_Profile_22")

# COMMAND ----------
# DBTITLE 1, lkp_Currency_Day_23


query_23 = f"""SELECT
  CD.DAY_DT AS DAY_DT,
  CD.EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  lSP2.LOCATION_ID AS LOCATION_ID,
  lSP2.LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
  lSP2.LOCATION_NBR AS LOCATION_NBR,
  lSP2.PRODUCT_ID AS PRODUCT_ID,
  lSP2.SKU_NBR AS SKU_NBR,
  lSP2.src_LPN_ID AS src_LPN_ID,
  lSP2.src_TC_LPN_ID AS src_TC_LPN_ID,
  lSP2.src_PARENT_LPN_ID AS src_PARENT_LPN_ID,
  lSP2.src_LPN_TYPE AS src_LPN_TYPE,
  lSP2.src_LPN_STATUS AS src_LPN_STATUS,
  lSP2.src_TRACKING_NBR AS src_TRACKING_NBR,
  lSP2.src_BASE_CHARGE AS src_BASE_CHARGE,
  lSP2.src_DIST_CHARGE AS src_DIST_CHARGE,
  lSP2.src_FREIGHT_CHARGE AS src_FREIGHT_CHARGE,
  lSP2.src_TC_ASN_ID AS src_TC_ASN_ID,
  lSP2.src_ASN_ID AS src_ASN_ID,
  lSP2.src_CREATED_DTTM AS src_CREATED_DTTM,
  lSP2.src_lpn_LAST_UPDATED_DTTM AS src_lpn_LAST_UPDATED_DTTM,
  lSP2.src_LPN_DETAIL_ID AS src_LPN_DETAIL_ID,
  lSP2.src_do_ORDER_ID AS src_do_ORDER_ID,
  lSP2.src_dol_MASTER_ORDER_ID AS src_dol_MASTER_ORDER_ID,
  lSP2.src_dol_LINE_ITEM_ID AS src_dol_LINE_ITEM_ID,
  lSP2.src_DISTRIBUTION_ORDER_DTL_ID AS src_DISTRIBUTION_ORDER_DTL_ID,
  lSP2.src_dol_ITEM_NAME AS src_dol_ITEM_NAME,
  lSP2.src_SHIPPED_QTY AS src_SHIPPED_QTY,
  lSP2.src_do_O_FACILITY_ALIAS_ID AS src_do_O_FACILITY_ALIAS_ID,
  lSP2.src_po_CREATED_DTTM AS src_po_CREATED_DTTM,
  lSP2.src_ITEM_NAME AS src_ITEM_NAME,
  lSP2.src_ITEM_NAME_exp AS src_ITEM_NAME_exp,
  lSP2.src_TC_COMPANY_ID AS src_TC_COMPANY_ID,
  lSP2.src_FACILITY_TYPE_ID AS src_FACILITY_TYPE_ID,
  lSP2.UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM,
  lSP2.UPDATE_TSTMP_OMS_LPN_DDS AS UPDATE_TSTMP_OMS_LPN_DDS,
  lSP2.UPDATE_TSTMP_OMS_LPN_DETAIL AS UPDATE_TSTMP_OMS_LPN_DETAIL,
  lSP2.UPDATE_TSTMP_OMS_ORDER_LINE_ITEM AS UPDATE_TSTMP_OMS_ORDER_LINE_ITEM,
  lSP2.UPDATE_TSTMP_OMS_ORDERS AS UPDATE_TSTMP_OMS_ORDERS,
  lSP2.UPDATE_TSTMP_OMS_FACILITY AS UPDATE_TSTMP_OMS_FACILITY,
  lSP2.UPDATE_TSTMP_OMS_PURCHASE_ORDERS AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS,
  lSP2.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  lkp_Site_Profile_22 lSP2
  LEFT JOIN CURRENCY_DAY CD ON CD.DAY_DT = lSP2.src_po_CREATED_DTTM"""

df_23 = spark.sql(query_23)

df_23.createOrReplaceTempView("lkp_Currency_Day_23")

# COMMAND ----------
# DBTITLE 1, EXP_PRE_24


query_24 = f"""SELECT
  src_LPN_ID AS src_LPN_ID,
  PRODUCT_ID AS src_PRODUCT_ID,
  src_TC_LPN_ID AS src_TC_LPN_ID,
  src_PARENT_LPN_ID AS src_PARENT_LPN_ID,
  src_LPN_TYPE AS src_LPN_TYPE,
  src_LPN_STATUS AS src_LPN_STATUS,
  src_TRACKING_NBR AS src_TRACKING_NBR,
  src_BASE_CHARGE AS src_BASE_CHARGE,
  src_DIST_CHARGE AS src_DIST_CHARGE,
  src_FREIGHT_CHARGE AS src_FREIGHT_CHARGE,
  src_TC_ASN_ID AS src_TC_ASN_ID,
  src_ASN_ID AS src_ASN_ID,
  src_CREATED_DTTM AS src_CREATED_DTTM,
  src_lpn_LAST_UPDATED_DTTM AS src_lpn_LAST_UPDATED_DTTM,
  src_LPN_DETAIL_ID AS src_LPN_DETAIL_ID,
  src_do_ORDER_ID AS src_do_ORDER_ID,
  src_dol_MASTER_ORDER_ID AS src_dol_MASTER_ORDER_ID,
  src_dol_LINE_ITEM_ID AS src_dol_LINE_ITEM_ID,
  src_DISTRIBUTION_ORDER_DTL_ID AS src_DISTRIBUTION_ORDER_DTL_ID,
  src_dol_ITEM_NAME AS src_dol_ITEM_NAME,
  src_SHIPPED_QTY AS src_SHIPPED_QTY,
  src_do_O_FACILITY_ALIAS_ID AS src_do_O_FACILITY_ALIAS_ID,
  TO_INTEGER(src_do_O_FACILITY_ALIAS_ID) AS src_do_O_FACILITY_ALIAS_ID_exp,
  src_po_CREATED_DTTM AS src_po_CREATED_DTTM,
  src_ITEM_NAME AS src_ITEM_NAME,
  src_ITEM_NAME_exp AS src_ITEM_NAME_exp,
  src_TC_COMPANY_ID AS src_TC_COMPANY_ID,
  IFF(src_TC_COMPANY_ID = 8840, 1, EXCHANGE_RATE_PCNT) AS src_EXCHANGE_RATE_PCNT,
  src_FACILITY_TYPE_ID AS src_FACILITY_TYPE_ID,
  LOCATION_ID AS LOCATION_ID,
  IFF(NOT ISNULL(src_FACILITY_TYPE_ID), LOCATION_ID, NULL) AS o_ORIG_LOCATION_ID,
  UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM,
  UPDATE_TSTMP_OMS_LPN_DDS AS UPDATE_TSTMP_OMS_LPN_DDS,
  UPDATE_TSTMP_OMS_LPN_DETAIL AS UPDATE_TSTMP_OMS_LPN_DETAIL,
  UPDATE_TSTMP_OMS_ORDER_LINE_ITEM AS UPDATE_TSTMP_OMS_ORDER_LINE_ITEM,
  UPDATE_TSTMP_OMS_ORDERS AS UPDATE_TSTMP_OMS_ORDERS,
  UPDATE_TSTMP_OMS_FACILITY AS UPDATE_TSTMP_OMS_FACILITY,
  UPDATE_TSTMP_OMS_PURCHASE_ORDERS AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  lkp_Currency_Day_23"""

df_24 = spark.sql(query_24)

df_24.createOrReplaceTempView("EXP_PRE_24")

# COMMAND ----------
# DBTITLE 1, FLT_UPDATE_TSTMP_25


query_25 = f"""SELECT
  src_LPN_ID AS src_LPN_ID,
  src_PRODUCT_ID AS src_PRODUCT_ID,
  src_TC_LPN_ID AS src_TC_LPN_ID,
  src_PARENT_LPN_ID AS src_PARENT_LPN_ID,
  src_LPN_TYPE AS src_LPN_TYPE,
  src_LPN_STATUS AS src_LPN_STATUS,
  src_TRACKING_NBR AS src_TRACKING_NBR,
  src_BASE_CHARGE AS src_BASE_CHARGE,
  src_DIST_CHARGE AS src_DIST_CHARGE,
  src_FREIGHT_CHARGE AS src_FREIGHT_CHARGE,
  src_TC_ASN_ID AS src_TC_ASN_ID,
  src_ASN_ID AS src_ASN_ID,
  src_CREATED_DTTM AS src_CREATED_DTTM,
  src_lpn_LAST_UPDATED_DTTM AS src_lpn_LAST_UPDATED_DTTM,
  src_LPN_DETAIL_ID AS src_LPN_DETAIL_ID,
  src_do_ORDER_ID AS src_do_ORDER_ID,
  src_dol_MASTER_ORDER_ID AS src_dol_MASTER_ORDER_ID,
  src_dol_LINE_ITEM_ID AS src_dol_LINE_ITEM_ID,
  src_DISTRIBUTION_ORDER_DTL_ID AS src_DISTRIBUTION_ORDER_DTL_ID,
  src_dol_ITEM_NAME AS src_dol_ITEM_NAME,
  src_SHIPPED_QTY AS src_SHIPPED_QTY,
  src_do_O_FACILITY_ALIAS_ID AS src_do_O_FACILITY_ALIAS_ID,
  src_do_O_FACILITY_ALIAS_ID_exp AS src_do_O_FACILITY_ALIAS_ID_exp,
  src_po_CREATED_DTTM AS src_po_CREATED_DTTM,
  src_ITEM_NAME AS src_ITEM_NAME,
  src_ITEM_NAME_exp AS src_ITEM_NAME_exp,
  src_TC_COMPANY_ID AS src_TC_COMPANY_ID,
  src_EXCHANGE_RATE_PCNT AS src_EXCHANGE_RATE_PCNT,
  o_ORIG_LOCATION_ID AS o_ORIG_LOCATION_ID,
  UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM,
  UPDATE_TSTMP_OMS_LPN_DDS AS UPDATE_TSTMP_OMS_LPN_DDS,
  UPDATE_TSTMP_OMS_LPN_DETAIL AS UPDATE_TSTMP_OMS_LPN_DETAIL,
  UPDATE_TSTMP_OMS_ORDER_LINE_ITEM AS UPDATE_TSTMP_OMS_ORDER_LINE_ITEM,
  UPDATE_TSTMP_OMS_ORDERS AS UPDATE_TSTMP_OMS_ORDERS,
  UPDATE_TSTMP_OMS_FACILITY AS UPDATE_TSTMP_OMS_FACILITY,
  UPDATE_TSTMP_OMS_PURCHASE_ORDERS AS UPDATE_TSTMP_OMS_PURCHASE_ORDERS,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  EXP_PRE_24
WHERE
  UPDATE_TSTMP_OMS_PURCHASE_ORDERS_LINE_ITEM > TRUNC(now())
  OR UPDATE_TSTMP_OMS_LPN_DDS > TRUNC(now())
  OR UPDATE_TSTMP_OMS_LPN_DETAIL > TRUNC(now())
  OR UPDATE_TSTMP_OMS_ORDER_LINE_ITEM > TRUNC(now())
  OR UPDATE_TSTMP_OMS_ORDERS > TRUNC(now())
  OR UPDATE_TSTMP_OMS_FACILITY > TRUNC(now())
  OR UPDATE_TSTMP_OMS_PURCHASE_ORDERS > TRUNC(now())"""

df_25 = spark.sql(query_25)

df_25.createOrReplaceTempView("FLT_UPDATE_TSTMP_25")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_LPN_26


query_26 = f"""SELECT
  OMS_LPN_ID AS OMS_LPN_ID,
  OMS_LPN_LN_ID AS OMS_LPN_LN_ID,
  OMS_LPN_NBR AS OMS_LPN_NBR,
  OMS_PARENT_LPN_ID AS OMS_PARENT_LPN_ID,
  LPN_TYPE_ID AS LPN_TYPE_ID,
  LPN_STATUS_ID AS LPN_STATUS_ID,
  OMS_TRACKING_NBR AS OMS_TRACKING_NBR,
  BASE_CHARGE_AMT AS BASE_CHARGE_AMT,
  DIST_CHARGE_AMT AS DIST_CHARGE_AMT,
  FREIGHT_CHARGE_AMT AS FREIGHT_CHARGE_AMT,
  OMS_ASN AS OMS_ASN,
  OMS_ASN_ID AS OMS_ASN_ID,
  CREATED_TSTMP AS CREATED_TSTMP,
  LAST_UPDATED_TSTMP AS LAST_UPDATED_TSTMP,
  OMS_DIST_ORDER_ID AS OMS_DIST_ORDER_ID,
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_DIST_ORDER_LN_ID AS OMS_DIST_ORDER_LN_ID,
  OMS_DIST_ORDER_DTL_ID AS OMS_DIST_ORDER_DTL_ID,
  PRODUCT_ID AS PRODUCT_ID,
  ORIGINAL_PRODUCT_ID AS ORIGINAL_PRODUCT_ID,
  SHIPPED_QTY AS SHIPPED_QTY,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  OMS_COMPANY_ID AS OMS_COMPANY_ID,
  EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_LPN"""

df_26 = spark.sql(query_26)

df_26.createOrReplaceTempView("Shortcut_to_OMS_LPN_26")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_LPN_27


query_27 = f"""SELECT
  OMS_LPN_ID AS OMS_LPN_ID,
  OMS_LPN_LN_ID AS OMS_LPN_LN_ID,
  OMS_LPN_NBR AS OMS_LPN_NBR,
  OMS_PARENT_LPN_ID AS OMS_PARENT_LPN_ID,
  LPN_TYPE_ID AS LPN_TYPE_ID,
  LPN_STATUS_ID AS LPN_STATUS_ID,
  OMS_TRACKING_NBR AS OMS_TRACKING_NBR,
  BASE_CHARGE_AMT AS BASE_CHARGE_AMT,
  DIST_CHARGE_AMT AS DIST_CHARGE_AMT,
  FREIGHT_CHARGE_AMT AS FREIGHT_CHARGE_AMT,
  OMS_ASN AS OMS_ASN,
  OMS_ASN_ID AS OMS_ASN_ID,
  CREATED_TSTMP AS CREATED_TSTMP,
  LAST_UPDATED_TSTMP AS LAST_UPDATED_TSTMP,
  OMS_DIST_ORDER_ID AS OMS_DIST_ORDER_ID,
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_DIST_ORDER_LN_ID AS OMS_DIST_ORDER_LN_ID,
  OMS_DIST_ORDER_DTL_ID AS OMS_DIST_ORDER_DTL_ID,
  PRODUCT_ID AS PRODUCT_ID,
  ORIGINAL_PRODUCT_ID AS ORIGINAL_PRODUCT_ID,
  SHIPPED_QTY AS SHIPPED_QTY,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  OMS_COMPANY_ID AS OMS_COMPANY_ID,
  EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_LPN_26"""

df_27 = spark.sql(query_27)

df_27.createOrReplaceTempView("SQ_Shortcut_to_OMS_LPN_27")

# COMMAND ----------
# DBTITLE 1, JNR_OMS_LPN_tgt_28


query_28 = f"""SELECT
  DETAIL.src_PRODUCT_ID AS src_PRODUCT_ID,
  DETAIL.src_LPN_ID AS src_LPN_ID,
  DETAIL.src_TC_LPN_ID AS src_TC_LPN_ID,
  DETAIL.src_PARENT_LPN_ID AS src_PARENT_LPN_ID,
  DETAIL.src_LPN_TYPE AS src_LPN_TYPE,
  DETAIL.src_LPN_STATUS AS src_LPN_STATUS,
  DETAIL.src_TRACKING_NBR AS src_TRACKING_NBR,
  DETAIL.src_BASE_CHARGE AS src_BASE_CHARGE,
  DETAIL.src_DIST_CHARGE AS src_DIST_CHARGE,
  DETAIL.src_FREIGHT_CHARGE AS src_FREIGHT_CHARGE,
  DETAIL.src_TC_ASN_ID AS src_TC_ASN_ID,
  DETAIL.src_ASN_ID AS src_ASN_ID,
  DETAIL.src_CREATED_DTTM AS src_CREATED_DTTM,
  DETAIL.src_lpn_LAST_UPDATED_DTTM AS src_lpn_LAST_UPDATED_DTTM,
  DETAIL.src_LPN_DETAIL_ID AS src_LPN_DETAIL_ID,
  DETAIL.src_do_ORDER_ID AS src_do_ORDER_ID,
  DETAIL.src_dol_MASTER_ORDER_ID AS src_dol_MASTER_ORDER_ID,
  DETAIL.src_dol_LINE_ITEM_ID AS src_dol_LINE_ITEM_ID,
  DETAIL.src_DISTRIBUTION_ORDER_DTL_ID AS src_DISTRIBUTION_ORDER_DTL_ID,
  DETAIL.src_dol_ITEM_NAME AS src_dol_ITEM_NAME,
  DETAIL.src_SHIPPED_QTY AS src_SHIPPED_QTY,
  DETAIL.src_do_O_FACILITY_ALIAS_ID AS src_do_O_FACILITY_ALIAS_ID,
  DETAIL.src_po_CREATED_DTTM AS src_po_CREATED_DTTM,
  DETAIL.src_ITEM_NAME AS src_ITEM_NAME,
  DETAIL.src_ITEM_NAME_exp AS src_ITEM_NAME_exp,
  DETAIL.src_TC_COMPANY_ID AS src_TC_COMPANY_ID,
  DETAIL.o_ORIG_LOCATION_ID AS src_FACILITY_TYPE_ID,
  DETAIL.src_EXCHANGE_RATE_PCNT AS src_EXCHANGE_RATE_PCNT,
  MASTER.OMS_LPN_ID AS OMS_LPN_ID,
  MASTER.OMS_LPN_LN_ID AS OMS_LPN_LN_ID,
  MASTER.OMS_LPN_NBR AS OMS_LPN_NBR,
  MASTER.OMS_PARENT_LPN_ID AS OMS_PARENT_LPN_ID,
  MASTER.LPN_TYPE_ID AS LPN_TYPE_ID,
  MASTER.LPN_STATUS_ID AS LPN_STATUS_ID,
  MASTER.OMS_TRACKING_NBR AS OMS_TRACKING_NBR,
  MASTER.BASE_CHARGE_AMT AS BASE_CHARGE_AMT,
  MASTER.DIST_CHARGE_AMT AS DIST_CHARGE_AMT,
  MASTER.FREIGHT_CHARGE_AMT AS FREIGHT_CHARGE_AMT,
  MASTER.OMS_ASN AS OMS_ASN,
  MASTER.OMS_ASN_ID AS OMS_ASN_ID,
  MASTER.CREATED_TSTMP AS CREATED_TSTMP,
  MASTER.LAST_UPDATED_TSTMP AS LAST_UPDATED_TSTMP,
  MASTER.OMS_DIST_ORDER_ID AS OMS_DIST_ORDER_ID,
  MASTER.OMS_ORDER_ID AS OMS_ORDER_ID,
  MASTER.OMS_DIST_ORDER_LN_ID AS OMS_DIST_ORDER_LN_ID,
  MASTER.OMS_DIST_ORDER_DTL_ID AS OMS_DIST_ORDER_DTL_ID,
  MASTER.PRODUCT_ID AS PRODUCT_ID,
  MASTER.ORIGINAL_PRODUCT_ID AS ORIGINAL_PRODUCT_ID,
  MASTER.SHIPPED_QTY AS SHIPPED_QTY,
  MASTER.ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  MASTER.OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  MASTER.OMS_COMPANY_ID AS OMS_COMPANY_ID,
  MASTER.EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT1,
  MASTER.UPDATE_TSTMP AS UPDATE_TSTMP,
  MASTER.LOAD_TSTMP AS LOAD_TSTMP,
  DETAIL.src_do_O_FACILITY_ALIAS_ID_exp AS src_do_O_FACILITY_ALIAS_ID_exp,
  DETAIL.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_LPN_27 MASTER
  RIGHT JOIN FLT_UPDATE_TSTMP_25 DETAIL ON MASTER.OMS_LPN_ID = DETAIL.src_LPN_ID
  AND MASTER.OMS_LPN_LN_ID = DETAIL.src_LPN_DETAIL_ID"""

df_28 = spark.sql(query_28)

df_28.createOrReplaceTempView("JNR_OMS_LPN_tgt_28")

# COMMAND ----------
# DBTITLE 1, FIL_UNCHANGED_REC_29


query_29 = f"""SELECT
  src_PRODUCT_ID AS src_PRODUCT_ID,
  src_LPN_ID AS src_LPN_ID,
  src_TC_LPN_ID AS src_TC_LPN_ID,
  src_PARENT_LPN_ID AS src_PARENT_LPN_ID,
  src_LPN_TYPE AS src_LPN_TYPE,
  src_LPN_STATUS AS src_LPN_STATUS,
  src_TRACKING_NBR AS src_TRACKING_NBR,
  src_BASE_CHARGE AS src_BASE_CHARGE,
  src_DIST_CHARGE AS src_DIST_CHARGE,
  src_FREIGHT_CHARGE AS src_FREIGHT_CHARGE,
  src_TC_ASN_ID AS src_TC_ASN_ID,
  src_ASN_ID AS src_ASN_ID,
  src_CREATED_DTTM AS src_CREATED_DTTM,
  src_lpn_LAST_UPDATED_DTTM AS src_lpn_LAST_UPDATED_DTTM,
  src_LPN_DETAIL_ID AS src_LPN_DETAIL_ID,
  src_do_ORDER_ID AS src_do_ORDER_ID,
  src_dol_MASTER_ORDER_ID AS src_dol_MASTER_ORDER_ID,
  src_dol_LINE_ITEM_ID AS src_dol_LINE_ITEM_ID,
  src_DISTRIBUTION_ORDER_DTL_ID AS src_DISTRIBUTION_ORDER_DTL_ID,
  src_dol_ITEM_NAME AS src_dol_ITEM_NAME,
  src_SHIPPED_QTY AS src_SHIPPED_QTY,
  src_do_O_FACILITY_ALIAS_ID AS src_do_O_FACILITY_ALIAS_ID,
  src_po_CREATED_DTTM AS src_po_CREATED_DTTM,
  src_ITEM_NAME AS src_ITEM_NAME,
  src_ITEM_NAME_exp AS src_ITEM_NAME_exp,
  src_TC_COMPANY_ID AS src_TC_COMPANY_ID,
  src_FACILITY_TYPE_ID AS src_FACILITY_TYPE_ID,
  NULL AS EXCHANGE_RATE_PCNT,
  src_EXCHANGE_RATE_PCNT AS src_EXCHANGE_RATE_PCNT,
  OMS_LPN_ID AS OMS_LPN_ID,
  OMS_LPN_LN_ID AS OMS_LPN_LN_ID,
  OMS_LPN_NBR AS OMS_LPN_NBR,
  OMS_PARENT_LPN_ID AS OMS_PARENT_LPN_ID,
  LPN_TYPE_ID AS LPN_TYPE_ID,
  LPN_STATUS_ID AS LPN_STATUS_ID,
  OMS_TRACKING_NBR AS OMS_TRACKING_NBR,
  BASE_CHARGE_AMT AS BASE_CHARGE_AMT,
  DIST_CHARGE_AMT AS DIST_CHARGE_AMT,
  FREIGHT_CHARGE_AMT AS FREIGHT_CHARGE_AMT,
  OMS_ASN AS OMS_ASN,
  OMS_ASN_ID AS OMS_ASN_ID,
  CREATED_TSTMP AS CREATED_TSTMP,
  LAST_UPDATED_TSTMP AS LAST_UPDATED_TSTMP,
  OMS_DIST_ORDER_ID AS OMS_DIST_ORDER_ID,
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_DIST_ORDER_LN_ID AS OMS_DIST_ORDER_LN_ID,
  OMS_DIST_ORDER_DTL_ID AS OMS_DIST_ORDER_DTL_ID,
  PRODUCT_ID AS PRODUCT_ID,
  ORIGINAL_PRODUCT_ID AS ORIGINAL_PRODUCT_ID,
  SHIPPED_QTY AS SHIPPED_QTY,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  OMS_COMPANY_ID AS OMS_COMPANY_ID,
  EXCHANGE_RATE_PCNT1 AS EXCHANGE_RATE_PCNT1,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  src_do_O_FACILITY_ALIAS_ID_exp AS src_do_O_FACILITY_ALIAS_ID_exp,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  JNR_OMS_LPN_tgt_28
WHERE
  (
    ISNULL(OMS_LPN_ID)
    AND ISNULL(OMS_LPN_LN_ID)
  )
  OR (
    (
      NOT ISNULL(OMS_LPN_ID)
      AND NOT ISNULL(OMS_LPN_LN_ID)
    )
    AND (
      IFF(
        ISNULL(LTRIM(RTRIM(OMS_LPN_NBR))),
        '',
        LTRIM(RTRIM(OMS_LPN_NBR))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(src_TC_LPN_ID))),
        '',
        LTRIM(RTRIM(src_TC_LPN_ID))
      )
      OR IFF(ISNULL(OMS_PARENT_LPN_ID), 0, OMS_PARENT_LPN_ID) <> IFF(ISNULL(src_PARENT_LPN_ID), 0, src_PARENT_LPN_ID)
      OR IFF(ISNULL(LPN_TYPE_ID), 0, LPN_TYPE_ID) <> IFF(ISNULL(src_LPN_TYPE), 0, src_LPN_TYPE)
      OR IFF(ISNULL(LPN_STATUS_ID), 0, LPN_STATUS_ID) <> IFF(ISNULL(src_LPN_STATUS), 0, src_LPN_STATUS)
      OR IFF(
        ISNULL(LTRIM(RTRIM(OMS_TRACKING_NBR))),
        '',
        LTRIM(RTRIM(OMS_TRACKING_NBR))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(src_TRACKING_NBR))),
        '',
        LTRIM(RTRIM(src_TRACKING_NBR))
      )
      OR IFF(ISNULL(BASE_CHARGE_AMT), 0, BASE_CHARGE_AMT) <> IFF(ISNULL(src_BASE_CHARGE), 0, src_BASE_CHARGE)
      OR IFF(ISNULL(DIST_CHARGE_AMT), 0, DIST_CHARGE_AMT) <> IFF(ISNULL(src_DIST_CHARGE), 0, src_DIST_CHARGE)
      OR IFF(ISNULL(FREIGHT_CHARGE_AMT), 0, FREIGHT_CHARGE_AMT) <> IFF(ISNULL(src_FREIGHT_CHARGE), 0, src_FREIGHT_CHARGE)
      OR IFF(
        ISNULL(LTRIM(RTRIM(OMS_ASN))),
        '',
        LTRIM(RTRIM(OMS_ASN))
      ) <> IFF(
        ISNULL(LTRIM(RTRIM(src_TC_ASN_ID))),
        '',
        LTRIM(RTRIM(src_TC_ASN_ID))
      )
      OR IFF(ISNULL(OMS_ASN_ID), 0, OMS_ASN_ID) <> IFF(ISNULL(src_ASN_ID), 0, src_ASN_ID)
      OR IFF(
        ISNULL(CREATED_TSTMP),
        TO_DATE('1999-01-01', 'YYYY-MM-DD'),
        CREATED_TSTMP
      ) <> IFF(
        ISNULL(src_CREATED_DTTM),
        TO_DATE('1999-01-01', 'YYYY-MM-DD'),
        src_CREATED_DTTM
      )
      OR IFF(
        ISNULL(LAST_UPDATED_TSTMP),
        TO_DATE('1999-01-01', 'YYYY-MM-DD'),
        LAST_UPDATED_TSTMP
      ) <> IFF(
        ISNULL(src_lpn_LAST_UPDATED_DTTM),
        TO_DATE('1999-01-01', 'YYYY-MM-DD'),
        src_lpn_LAST_UPDATED_DTTM
      )
      OR IFF(ISNULL(OMS_DIST_ORDER_ID), 0, OMS_DIST_ORDER_ID) <> IFF(ISNULL(src_do_ORDER_ID), 0, src_do_ORDER_ID)
      OR IFF(
        ISNULL(OMS_DIST_ORDER_LN_ID),
        0,
        OMS_DIST_ORDER_LN_ID
      ) <> IFF(
        ISNULL(src_dol_LINE_ITEM_ID),
        0,
        src_dol_LINE_ITEM_ID
      )
      OR IFF(
        ISNULL(OMS_DIST_ORDER_DTL_ID),
        0,
        OMS_DIST_ORDER_DTL_ID
      ) <> IFF(
        ISNULL(src_DISTRIBUTION_ORDER_DTL_ID),
        0,
        src_DISTRIBUTION_ORDER_DTL_ID
      )
      OR IFF(
        ISNULL(ORIGINAL_PRODUCT_ID),
        0,
        ORIGINAL_PRODUCT_ID
      ) <> IFF(ISNULL(src_ITEM_NAME_exp), 0, src_ITEM_NAME_exp)
      OR IFF(ISNULL(SHIPPED_QTY), 0, SHIPPED_QTY) <> IFF(ISNULL(src_SHIPPED_QTY), 0, src_SHIPPED_QTY)
      OR IFF(ISNULL(ORIG_LOCATION_ID), 0, ORIG_LOCATION_ID) <> IFF(
        ISNULL(src_do_O_FACILITY_ALIAS_ID_exp),
        0,
        src_do_O_FACILITY_ALIAS_ID_exp
      )
      OR IFF(
        ISNULL(OMS_ORDER_CREATED_TSTMP),
        TO_DATE('1999-01-01', 'YYYY-MM-DD'),
        OMS_ORDER_CREATED_TSTMP
      ) <> IFF(
        ISNULL(src_po_CREATED_DTTM),
        TO_DATE('1999-01-01', 'YYYY-MM-DD'),
        src_po_CREATED_DTTM
      )
      OR IFF(
        ISNULL(EXCHANGE_RATE_PCNT1),
        0,
        EXCHANGE_RATE_PCNT1
      ) <> IFF(
        ISNULL(src_EXCHANGE_RATE_PCNT),
        0,
        src_EXCHANGE_RATE_PCNT
      )
    )
  )"""

df_29 = spark.sql(query_29)

df_29.createOrReplaceTempView("FIL_UNCHANGED_REC_29")

# COMMAND ----------
# DBTITLE 1, EXP_VALID_FLAG_30


query_30 = f"""SELECT
  src_PRODUCT_ID AS src_PRODUCT_ID,
  src_LPN_ID AS src_LPN_ID,
  src_TC_LPN_ID AS src_TC_LPN_ID,
  src_PARENT_LPN_ID AS src_PARENT_LPN_ID,
  src_LPN_TYPE AS src_LPN_TYPE,
  src_LPN_STATUS AS src_LPN_STATUS,
  src_TRACKING_NBR AS src_TRACKING_NBR,
  src_BASE_CHARGE AS src_BASE_CHARGE,
  src_DIST_CHARGE AS src_DIST_CHARGE,
  src_FREIGHT_CHARGE AS src_FREIGHT_CHARGE,
  src_TC_ASN_ID AS src_TC_ASN_ID,
  src_ASN_ID AS src_ASN_ID,
  src_CREATED_DTTM AS src_CREATED_DTTM,
  src_lpn_LAST_UPDATED_DTTM AS src_lpn_LAST_UPDATED_DTTM,
  src_LPN_DETAIL_ID AS src_LPN_DETAIL_ID,
  src_do_ORDER_ID AS src_do_ORDER_ID,
  src_dol_MASTER_ORDER_ID AS src_dol_MASTER_ORDER_ID,
  src_dol_LINE_ITEM_ID AS src_dol_LINE_ITEM_ID,
  src_DISTRIBUTION_ORDER_DTL_ID AS src_DISTRIBUTION_ORDER_DTL_ID,
  src_dol_ITEM_NAME AS src_dol_ITEM_NAME,
  src_SHIPPED_QTY AS src_SHIPPED_QTY,
  src_do_O_FACILITY_ALIAS_ID AS src_do_O_FACILITY_ALIAS_ID,
  src_po_CREATED_DTTM AS src_po_CREATED_DTTM,
  src_ITEM_NAME AS src_ITEM_NAME,
  src_ITEM_NAME_exp AS src_ITEM_NAME_exp,
  src_TC_COMPANY_ID AS src_TC_COMPANY_ID,
  src_FACILITY_TYPE_ID AS src_FACILITY_TYPE_ID,
  src_EXCHANGE_RATE_PCNT AS src_EXCHANGE_RATE_PCNT,
  OMS_LPN_ID AS OMS_LPN_ID,
  OMS_LPN_LN_ID AS OMS_LPN_LN_ID,
  LOAD_TSTMP AS lkp_LOAD_TSTMP,
  src_do_O_FACILITY_ALIAS_ID_exp AS src_do_O_FACILITY_ALIAS_ID_exp,
  now() AS UPDATE_TSTMP,
  IFF(ISNULL(LOAD_TSTMP), now(), LOAD_TSTMP) AS LOAD_TSTMP,
  IFF(
    ISNULL(OMS_LPN_ID)
    AND ISNULL(OMS_LPN_LN_ID),
    1,
    2
  ) AS o_VALID_FLAG,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  FIL_UNCHANGED_REC_29"""

df_30 = spark.sql(query_30)

df_30.createOrReplaceTempView("EXP_VALID_FLAG_30")

# COMMAND ----------
# DBTITLE 1, UPD_INSERT_UPD_31


query_31 = f"""SELECT
  src_PRODUCT_ID AS src_PRODUCT_ID,
  src_LPN_ID AS src_LPN_ID,
  src_TC_LPN_ID AS src_TC_LPN_ID,
  src_PARENT_LPN_ID AS src_PARENT_LPN_ID,
  src_LPN_TYPE AS src_LPN_TYPE,
  src_LPN_STATUS AS src_LPN_STATUS,
  src_TRACKING_NBR AS src_TRACKING_NBR,
  src_BASE_CHARGE AS src_BASE_CHARGE,
  src_DIST_CHARGE AS src_DIST_CHARGE,
  src_FREIGHT_CHARGE AS src_FREIGHT_CHARGE,
  src_TC_ASN_ID AS src_TC_ASN_ID,
  src_ASN_ID AS src_ASN_ID,
  src_CREATED_DTTM AS src_CREATED_DTTM,
  src_lpn_LAST_UPDATED_DTTM AS src_lpn_LAST_UPDATED_DTTM,
  src_LPN_DETAIL_ID AS src_LPN_DETAIL_ID,
  src_do_ORDER_ID AS src_do_ORDER_ID,
  src_dol_MASTER_ORDER_ID AS src_dol_MASTER_ORDER_ID,
  src_dol_LINE_ITEM_ID AS src_dol_LINE_ITEM_ID,
  src_DISTRIBUTION_ORDER_DTL_ID AS src_DISTRIBUTION_ORDER_DTL_ID,
  src_dol_ITEM_NAME AS src_dol_ITEM_NAME,
  src_SHIPPED_QTY AS src_SHIPPED_QTY,
  src_do_O_FACILITY_ALIAS_ID AS src_do_O_FACILITY_ALIAS_ID,
  src_po_CREATED_DTTM AS src_po_CREATED_DTTM,
  src_ITEM_NAME AS src_ITEM_NAME,
  NULL AS src_ITEM_NAME_exp,
  src_TC_COMPANY_ID AS src_TC_COMPANY_ID,
  src_FACILITY_TYPE_ID AS src_FACILITY_TYPE_ID,
  src_EXCHANGE_RATE_PCNT AS src_EXCHANGE_RATE_PCNT,
  src_do_O_FACILITY_ALIAS_ID_exp AS src_do_O_FACILITY_ALIAS_ID_exp,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  o_VALID_FLAG AS o_VALID_FLAG,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id,
  DECODE(o_VALID_FLAG, 1, 'DD_INSERT', 2, 'DD_UPDATE') AS UPDATE_STRATEGY_FLAG
FROM
  EXP_VALID_FLAG_30"""

df_31 = spark.sql(query_31)

df_31.createOrReplaceTempView("UPD_INSERT_UPD_31")

# COMMAND ----------
# DBTITLE 1, OMS_LPN


spark.sql("""MERGE INTO OMS_LPN AS TARGET
USING
  UPD_INSERT_UPD_31 AS SOURCE ON TARGET.OMS_LPN_ID = SOURCE.src_LPN_ID
  AND TARGET.OMS_LPN_LN_ID = SOURCE.src_LPN_DETAIL_ID
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_UPDATE" THEN
UPDATE
SET
  TARGET.OMS_LPN_ID = SOURCE.src_LPN_ID,
  TARGET.OMS_LPN_LN_ID = SOURCE.src_LPN_DETAIL_ID,
  TARGET.OMS_LPN_NBR = SOURCE.src_TC_LPN_ID,
  TARGET.OMS_PARENT_LPN_ID = SOURCE.src_PARENT_LPN_ID,
  TARGET.LPN_TYPE_ID = SOURCE.src_LPN_TYPE,
  TARGET.LPN_STATUS_ID = SOURCE.src_LPN_STATUS,
  TARGET.OMS_TRACKING_NBR = SOURCE.src_TRACKING_NBR,
  TARGET.BASE_CHARGE_AMT = SOURCE.src_BASE_CHARGE,
  TARGET.DIST_CHARGE_AMT = SOURCE.src_DIST_CHARGE,
  TARGET.FREIGHT_CHARGE_AMT = SOURCE.src_FREIGHT_CHARGE,
  TARGET.OMS_ASN = SOURCE.src_TC_ASN_ID,
  TARGET.OMS_ASN_ID = SOURCE.src_ASN_ID,
  TARGET.CREATED_TSTMP = SOURCE.src_CREATED_DTTM,
  TARGET.LAST_UPDATED_TSTMP = SOURCE.src_lpn_LAST_UPDATED_DTTM,
  TARGET.OMS_DIST_ORDER_ID = SOURCE.src_do_ORDER_ID,
  TARGET.OMS_ORDER_ID = SOURCE.src_dol_MASTER_ORDER_ID,
  TARGET.OMS_DIST_ORDER_LN_ID = SOURCE.src_dol_LINE_ITEM_ID,
  TARGET.OMS_DIST_ORDER_DTL_ID = SOURCE.src_DISTRIBUTION_ORDER_DTL_ID,
  TARGET.PRODUCT_ID = SOURCE.src_PRODUCT_ID,
  TARGET.ORIGINAL_PRODUCT_ID = SOURCE.src_PRODUCT_ID,
  TARGET.SHIPPED_QTY = SOURCE.src_SHIPPED_QTY,
  TARGET.ORIG_LOCATION_ID = SOURCE.src_FACILITY_TYPE_ID,
  TARGET.OMS_ORDER_CREATED_TSTMP = SOURCE.src_po_CREATED_DTTM,
  TARGET.OMS_COMPANY_ID = SOURCE.src_TC_COMPANY_ID,
  TARGET.EXCHANGE_RATE_PCNT = SOURCE.src_EXCHANGE_RATE_PCNT,
  TARGET.UPDATE_TSTMP = SOURCE.UPDATE_TSTMP,
  TARGET.LOAD_TSTMP = SOURCE.LOAD_TSTMP
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_DELETE"
  AND TARGET.OMS_LPN_NBR = SOURCE.src_TC_LPN_ID
  AND TARGET.OMS_PARENT_LPN_ID = SOURCE.src_PARENT_LPN_ID
  AND TARGET.LPN_TYPE_ID = SOURCE.src_LPN_TYPE
  AND TARGET.LPN_STATUS_ID = SOURCE.src_LPN_STATUS
  AND TARGET.OMS_TRACKING_NBR = SOURCE.src_TRACKING_NBR
  AND TARGET.BASE_CHARGE_AMT = SOURCE.src_BASE_CHARGE
  AND TARGET.DIST_CHARGE_AMT = SOURCE.src_DIST_CHARGE
  AND TARGET.FREIGHT_CHARGE_AMT = SOURCE.src_FREIGHT_CHARGE
  AND TARGET.OMS_ASN = SOURCE.src_TC_ASN_ID
  AND TARGET.OMS_ASN_ID = SOURCE.src_ASN_ID
  AND TARGET.CREATED_TSTMP = SOURCE.src_CREATED_DTTM
  AND TARGET.LAST_UPDATED_TSTMP = SOURCE.src_lpn_LAST_UPDATED_DTTM
  AND TARGET.OMS_DIST_ORDER_ID = SOURCE.src_do_ORDER_ID
  AND TARGET.OMS_ORDER_ID = SOURCE.src_dol_MASTER_ORDER_ID
  AND TARGET.OMS_DIST_ORDER_LN_ID = SOURCE.src_dol_LINE_ITEM_ID
  AND TARGET.OMS_DIST_ORDER_DTL_ID = SOURCE.src_DISTRIBUTION_ORDER_DTL_ID
  AND TARGET.PRODUCT_ID = SOURCE.src_PRODUCT_ID
  AND TARGET.ORIGINAL_PRODUCT_ID = SOURCE.src_PRODUCT_ID
  AND TARGET.SHIPPED_QTY = SOURCE.src_SHIPPED_QTY
  AND TARGET.ORIG_LOCATION_ID = SOURCE.src_FACILITY_TYPE_ID
  AND TARGET.OMS_ORDER_CREATED_TSTMP = SOURCE.src_po_CREATED_DTTM
  AND TARGET.OMS_COMPANY_ID = SOURCE.src_TC_COMPANY_ID
  AND TARGET.EXCHANGE_RATE_PCNT = SOURCE.src_EXCHANGE_RATE_PCNT
  AND TARGET.UPDATE_TSTMP = SOURCE.UPDATE_TSTMP
  AND TARGET.LOAD_TSTMP = SOURCE.LOAD_TSTMP THEN DELETE
  WHEN NOT MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_INSERT" THEN
INSERT
  (
    TARGET.OMS_LPN_ID,
    TARGET.OMS_LPN_LN_ID,
    TARGET.OMS_LPN_NBR,
    TARGET.OMS_PARENT_LPN_ID,
    TARGET.LPN_TYPE_ID,
    TARGET.LPN_STATUS_ID,
    TARGET.OMS_TRACKING_NBR,
    TARGET.BASE_CHARGE_AMT,
    TARGET.DIST_CHARGE_AMT,
    TARGET.FREIGHT_CHARGE_AMT,
    TARGET.OMS_ASN,
    TARGET.OMS_ASN_ID,
    TARGET.CREATED_TSTMP,
    TARGET.LAST_UPDATED_TSTMP,
    TARGET.OMS_DIST_ORDER_ID,
    TARGET.OMS_ORDER_ID,
    TARGET.OMS_DIST_ORDER_LN_ID,
    TARGET.OMS_DIST_ORDER_DTL_ID,
    TARGET.PRODUCT_ID,
    TARGET.ORIGINAL_PRODUCT_ID,
    TARGET.SHIPPED_QTY,
    TARGET.ORIG_LOCATION_ID,
    TARGET.OMS_ORDER_CREATED_TSTMP,
    TARGET.OMS_COMPANY_ID,
    TARGET.EXCHANGE_RATE_PCNT,
    TARGET.UPDATE_TSTMP,
    TARGET.LOAD_TSTMP
  )
VALUES
  (
    SOURCE.src_LPN_ID,
    SOURCE.src_LPN_DETAIL_ID,
    SOURCE.src_TC_LPN_ID,
    SOURCE.src_PARENT_LPN_ID,
    SOURCE.src_LPN_TYPE,
    SOURCE.src_LPN_STATUS,
    SOURCE.src_TRACKING_NBR,
    SOURCE.src_BASE_CHARGE,
    SOURCE.src_DIST_CHARGE,
    SOURCE.src_FREIGHT_CHARGE,
    SOURCE.src_TC_ASN_ID,
    SOURCE.src_ASN_ID,
    SOURCE.src_CREATED_DTTM,
    SOURCE.src_lpn_LAST_UPDATED_DTTM,
    SOURCE.src_do_ORDER_ID,
    SOURCE.src_dol_MASTER_ORDER_ID,
    SOURCE.src_dol_LINE_ITEM_ID,
    SOURCE.src_DISTRIBUTION_ORDER_DTL_ID,
    SOURCE.src_PRODUCT_ID,
    SOURCE.src_PRODUCT_ID,
    SOURCE.src_SHIPPED_QTY,
    SOURCE.src_FACILITY_TYPE_ID,
    SOURCE.src_po_CREATED_DTTM,
    SOURCE.src_TC_COMPANY_ID,
    SOURCE.src_EXCHANGE_RATE_PCNT,
    SOURCE.UPDATE_TSTMP,
    SOURCE.LOAD_TSTMP
  )""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_OMS_LPN")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_OMS_LPN", mainWorkflowId, parentName)
