# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ../WorkflowUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_OMS_Order_Afterpay_FLG_UPD")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_OMS_Order_Afterpay_FLG_UPD", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_A_PAYMENT_DETAIL_0


query_0 = f"""SELECT
  OMS_PAYMENT_DETAIL_ID AS OMS_PAYMENT_DETAIL_ID,
  OMS_ENTITY_TYPE_ID AS OMS_ENTITY_TYPE_ID,
  OMS_ENTITY_ID AS OMS_ENTITY_ID,
  OMS_ENTITY_NBR AS OMS_ENTITY_NBR,
  CARD_NUMBER AS CARD_NUMBER,
  BILL_TO_FIRST_NAME AS BILL_TO_FIRST_NAME,
  BILL_TO_MIDDLE_NAME AS BILL_TO_MIDDLE_NAME,
  BILL_TO_LAST_NAME AS BILL_TO_LAST_NAME,
  BILL_TO_ADDR_LINE1 AS BILL_TO_ADDR_LINE1,
  BILL_TO_ADDR_LINE2 AS BILL_TO_ADDR_LINE2,
  BILL_TO_CITY AS BILL_TO_CITY,
  BILL_TO_STATE_PROV AS BILL_TO_STATE_PROV,
  BILL_TO_POSTAL_CD AS BILL_TO_POSTAL_CD,
  BILL_TO_COUNTRY_CD AS BILL_TO_COUNTRY_CD,
  BILL_TO_PHONE_NBR AS BILL_TO_PHONE_NBR,
  BILL_TO_EMAIL AS BILL_TO_EMAIL,
  OMS_PAYMENT_METHOD_ID AS OMS_PAYMENT_METHOD_ID,
  AFTERPAY_FLG AS AFTERPAY_FLG,
  REQ_AUTH_AMT AS REQ_AUTH_AMT,
  REQ_SETTLEMENT_AMT AS REQ_SETTLEMENT_AMT,
  REQ_REFUND_AMT AS REQ_REFUND_AMT,
  CURRENCY_CD AS CURRENCY_CD,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_A_PAYMENT_DETAIL"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_OMS_A_PAYMENT_DETAIL_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_A_PAYMENT_DETAIL_1


query_1 = f"""SELECT
  OMS_PAYMENT_DETAIL_ID AS OMS_PAYMENT_DETAIL_ID,
  OMS_ENTITY_ID AS OMS_ENTITY_ID,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  AFTERPAY_FLG AS AFTERPAY_FLG,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_A_PAYMENT_DETAIL_0"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("SQ_Shortcut_to_OMS_A_PAYMENT_DETAIL_1")

# COMMAND ----------
# DBTITLE 1, SRT_PD_Entity_ID_2


query_2 = f"""SELECT
  OMS_PAYMENT_DETAIL_ID AS PAYMENT_DETAIL_ID,
  OMS_ENTITY_ID AS ENTITY_ID,
  AFTERPAY_FLG AS AFTERPAY_FLG,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_A_PAYMENT_DETAIL_1
ORDER BY
  ENTITY_ID ASC"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("SRT_PD_Entity_ID_2")

# COMMAND ----------
# DBTITLE 1, AGG_PD_Entity_ID_3


query_3 = f"""SELECT
  ENTITY_ID AS ENTITY_ID,
  MAX(IFF(ISNULL(AFTERPAY_FLG), 0, AFTERPAY_FLG)) AS o_AFTERPAY_FLG,
  last(Monotonically_Increasing_Id) AS Monotonically_Increasing_Id
FROM
  SRT_PD_Entity_ID_2
GROUP BY
  ENTITY_ID"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("AGG_PD_Entity_ID_3")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_ORDER_4


query_4 = f"""SELECT
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_ORDER_NBR AS OMS_ORDER_NBR,
  ORDER_NBR AS ORDER_NBR,
  OMS_PARENT_ORDER_ID AS OMS_PARENT_ORDER_ID,
  OMS_ORDER_DT AS OMS_ORDER_DT,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  CREATION_TYPE AS CREATION_TYPE,
  CREATION_DEVICE_TYPE AS CREATION_DEVICE_TYPE,
  CREATION_DEVICE_WIDTH AS CREATION_DEVICE_WIDTH,
  CHANNEL_TYPE_ID AS CHANNEL_TYPE_ID,
  CHANNEL_ID AS CHANNEL_ID,
  OMS_ORDER_TYPE AS OMS_ORDER_TYPE,
  OMS_ORDER_TYPE_ID AS OMS_ORDER_TYPE_ID,
  ORDER_CATEGORY_ID AS ORDER_CATEGORY_ID,
  SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  CUSTOMER_PICKUP_FLG AS CUSTOMER_PICKUP_FLG,
  OMS_ORDER_STATUS_ID AS OMS_ORDER_STATUS_ID,
  REASON_ID AS REASON_ID,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  ORDER_RECEIVED_FLG AS ORDER_RECEIVED_FLG,
  PARTIALLY_PLANNED_FLG AS PARTIALLY_PLANNED_FLG,
  READY_TO_SHIP_FLG AS READY_TO_SHIP_FLG,
  CLOSED_FLG AS CLOSED_FLG,
  ON_HOLD AS ON_HOLD,
  CANCELLED_FLG AS CANCELLED_FLG,
  CANCELLED_TSTMP AS CANCELLED_TSTMP,
  OMS_CANCELLED_TYPE_ID AS OMS_CANCELLED_TYPE_ID,
  CANCEL_REASON_DESC AS CANCEL_REASON_DESC,
  DECLINE_REASON_ID AS DECLINE_REASON_ID,
  OMS_COMPANY_ID AS OMS_COMPANY_ID,
  BILL_OF_LADING_NBR AS BILL_OF_LADING_NBR,
  RETURN_REFERENCE_NBR AS RETURN_REFERENCE_NBR,
  COMMODITY_CD AS COMMODITY_CD,
  CARRIER_ID AS CARRIER_ID,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  PROTECTION_LEVEL_ID AS PROTECTION_LEVEL_ID,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  ENTRY_CODE AS ENTRY_CODE,
  FULFILL_MODE AS FULFILL_MODE,
  IMPORTED_FLG AS IMPORTED_FLG,
  ALERTS_FLG AS ALERTS_FLG,
  TRANS_RESP_CD AS TRANS_RESP_CD,
  ORIG_LOCATION_NBR AS ORIG_LOCATION_NBR,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  ORIG_SHIP_VIA_LOCATION_ID AS ORIG_SHIP_VIA_LOCATION_ID,
  DEST_LOCATION_NBR AS DEST_LOCATION_NBR,
  DEST_LOCATION_ID AS DEST_LOCATION_ID,
  DEST_SHIP_VIA_LOCATION_ID AS DEST_SHIP_VIA_LOCATION_ID,
  BILL_LOCATION_NBR AS BILL_LOCATION_NBR,
  BILL_LOCATION_ID AS BILL_LOCATION_ID,
  RELEASE_DT AS RELEASE_DT,
  FIRST_RCPT_DT AS FIRST_RCPT_DT,
  LAST_RCPT_DT AS LAST_RCPT_DT,
  DUE_DT AS DUE_DT,
  PICKUP_START_DT AS PICKUP_START_DT,
  PICKUP_END_DT AS PICKUP_END_DT,
  PICKUP_TZ AS PICKUP_TZ,
  REQUESTED_DLVR_DT AS REQUESTED_DLVR_DT,
  PROMISED_DLVR_DT AS PROMISED_DLVR_DT,
  MUST_DLVR_DT AS MUST_DLVR_DT,
  DELIVERY_START_DT AS DELIVERY_START_DT,
  DELIVERY_END_DT AS DELIVERY_END_DT,
  DELIVERY_TZ AS DELIVERY_TZ,
  CUSTOMER_CD AS CUSTOMER_CD,
  CUSTOMER_FIRST_NAME AS CUSTOMER_FIRST_NAME,
  CUSTOMER_LAST_NAME AS CUSTOMER_LAST_NAME,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  CUSTOMER_PHONE AS CUSTOMER_PHONE,
  BILL_FIRST_NAME AS BILL_FIRST_NAME,
  BILL_LAST_NAME AS BILL_LAST_NAME,
  BILL_ADDRESS AS BILL_ADDRESS,
  BILL_CITY AS BILL_CITY,
  BILL_STATE_CD AS BILL_STATE_CD,
  BILL_POSTAL_CD AS BILL_POSTAL_CD,
  BILL_COUNTRY_CD AS BILL_COUNTRY_CD,
  BILL_PHONE AS BILL_PHONE,
  BILL_EMAIL AS BILL_EMAIL,
  AFTERPAY_FLG AS AFTERPAY_FLG,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  MONETARY_VALUE_AMT AS MONETARY_VALUE_AMT,
  ORIG_BUDG_COST_AMT AS ORIG_BUDG_COST_AMT,
  BUDG_COST_AMT AS BUDG_COST_AMT,
  TAX_AMT AS TAX_AMT,
  TAX_CHARGES_AMT AS TAX_CHARGES_AMT,
  MISC_CHARGES_AMT AS MISC_CHARGES_AMT,
  GRAND_TOTAL_AMT AS GRAND_TOTAL_AMT,
  PAYMENT_STATUS AS PAYMENT_STATUS,
  PAYMENT_MODE AS PAYMENT_MODE,
  BUDG_COST_CURRENCY_CD AS BUDG_COST_CURRENCY_CD,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  CURRENCY_CD AS CURRENCY_CD,
  EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_TSTMP AS CREATED_TSTMP,
  LAST_UPDATED_TSTMP AS LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_ORDER"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("Shortcut_to_OMS_ORDER_4")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_ORDER_5


query_5 = f"""SELECT
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_ORDER_NBR AS OMS_ORDER_NBR,
  ORDER_NBR AS ORDER_NBR,
  OMS_PARENT_ORDER_ID AS OMS_PARENT_ORDER_ID,
  OMS_ORDER_DT AS OMS_ORDER_DT,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  CREATION_TYPE AS CREATION_TYPE,
  CREATION_DEVICE_TYPE AS CREATION_DEVICE_TYPE,
  CREATION_DEVICE_WIDTH AS CREATION_DEVICE_WIDTH,
  CHANNEL_TYPE_ID AS CHANNEL_TYPE_ID,
  CHANNEL_ID AS CHANNEL_ID,
  OMS_ORDER_TYPE AS OMS_ORDER_TYPE,
  OMS_ORDER_TYPE_ID AS OMS_ORDER_TYPE_ID,
  ORDER_CATEGORY_ID AS ORDER_CATEGORY_ID,
  SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  CUSTOMER_PICKUP_FLG AS CUSTOMER_PICKUP_FLG,
  OMS_ORDER_STATUS_ID AS OMS_ORDER_STATUS_ID,
  REASON_ID AS REASON_ID,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  ORDER_RECEIVED_FLG AS ORDER_RECEIVED_FLG,
  PARTIALLY_PLANNED_FLG AS PARTIALLY_PLANNED_FLG,
  READY_TO_SHIP_FLG AS READY_TO_SHIP_FLG,
  CLOSED_FLG AS CLOSED_FLG,
  ON_HOLD AS ON_HOLD,
  CANCELLED_FLG AS CANCELLED_FLG,
  CANCELLED_TSTMP AS CANCELLED_TSTMP,
  OMS_CANCELLED_TYPE_ID AS OMS_CANCELLED_TYPE_ID,
  CANCEL_REASON_DESC AS CANCEL_REASON_DESC,
  DECLINE_REASON_ID AS DECLINE_REASON_ID,
  OMS_COMPANY_ID AS OMS_COMPANY_ID,
  BILL_OF_LADING_NBR AS BILL_OF_LADING_NBR,
  RETURN_REFERENCE_NBR AS RETURN_REFERENCE_NBR,
  COMMODITY_CD AS COMMODITY_CD,
  CARRIER_ID AS CARRIER_ID,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  PROTECTION_LEVEL_ID AS PROTECTION_LEVEL_ID,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  ENTRY_CODE AS ENTRY_CODE,
  FULFILL_MODE AS FULFILL_MODE,
  IMPORTED_FLG AS IMPORTED_FLG,
  ALERTS_FLG AS ALERTS_FLG,
  TRANS_RESP_CD AS TRANS_RESP_CD,
  ORIG_LOCATION_NBR AS ORIG_LOCATION_NBR,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  ORIG_SHIP_VIA_LOCATION_ID AS ORIG_SHIP_VIA_LOCATION_ID,
  DEST_LOCATION_NBR AS DEST_LOCATION_NBR,
  DEST_LOCATION_ID AS DEST_LOCATION_ID,
  DEST_SHIP_VIA_LOCATION_ID AS DEST_SHIP_VIA_LOCATION_ID,
  BILL_LOCATION_NBR AS BILL_LOCATION_NBR,
  BILL_LOCATION_ID AS BILL_LOCATION_ID,
  RELEASE_DT AS RELEASE_DT,
  FIRST_RCPT_DT AS FIRST_RCPT_DT,
  LAST_RCPT_DT AS LAST_RCPT_DT,
  DUE_DT AS DUE_DT,
  PICKUP_START_DT AS PICKUP_START_DT,
  PICKUP_END_DT AS PICKUP_END_DT,
  PICKUP_TZ AS PICKUP_TZ,
  REQUESTED_DLVR_DT AS REQUESTED_DLVR_DT,
  PROMISED_DLVR_DT AS PROMISED_DLVR_DT,
  MUST_DLVR_DT AS MUST_DLVR_DT,
  DELIVERY_START_DT AS DELIVERY_START_DT,
  DELIVERY_END_DT AS DELIVERY_END_DT,
  DELIVERY_TZ AS DELIVERY_TZ,
  CUSTOMER_CD AS CUSTOMER_CD,
  CUSTOMER_FIRST_NAME AS CUSTOMER_FIRST_NAME,
  CUSTOMER_LAST_NAME AS CUSTOMER_LAST_NAME,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  CUSTOMER_PHONE AS CUSTOMER_PHONE,
  BILL_FIRST_NAME AS BILL_FIRST_NAME,
  BILL_LAST_NAME AS BILL_LAST_NAME,
  BILL_ADDRESS AS BILL_ADDRESS,
  BILL_CITY AS BILL_CITY,
  BILL_STATE_CD AS BILL_STATE_CD,
  BILL_POSTAL_CD AS BILL_POSTAL_CD,
  BILL_COUNTRY_CD AS BILL_COUNTRY_CD,
  BILL_PHONE AS BILL_PHONE,
  BILL_EMAIL AS BILL_EMAIL,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  MONETARY_VALUE_AMT AS MONETARY_VALUE_AMT,
  ORIG_BUDG_COST_AMT AS ORIG_BUDG_COST_AMT,
  BUDG_COST_AMT AS BUDG_COST_AMT,
  TAX_AMT AS TAX_AMT,
  TAX_CHARGES_AMT AS TAX_CHARGES_AMT,
  MISC_CHARGES_AMT AS MISC_CHARGES_AMT,
  GRAND_TOTAL_AMT AS GRAND_TOTAL_AMT,
  PAYMENT_STATUS AS PAYMENT_STATUS,
  PAYMENT_MODE AS PAYMENT_MODE,
  BUDG_COST_CURRENCY_CD AS BUDG_COST_CURRENCY_CD,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  CURRENCY_CD AS CURRENCY_CD,
  EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_TSTMP AS CREATED_TSTMP,
  LAST_UPDATED_TSTMP AS LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  AFTERPAY_FLG AS AFTERPAY_FLG,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_ORDER_4
WHERE
  (TO_CHAR(OMS_ORDER_DT, 'YYYY-MM-DD') >= '2021-09-14')"""

df_5 = spark.sql(query_5)

df_5.createOrReplaceTempView("SQ_Shortcut_to_OMS_ORDER_5")

# COMMAND ----------
# DBTITLE 1, SRT_OMS_ORDER_6


query_6 = f"""SELECT
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_ORDER_NBR AS OMS_ORDER_NBR,
  ORDER_NBR AS ORDER_NBR,
  OMS_PARENT_ORDER_ID AS OMS_PARENT_ORDER_ID,
  OMS_ORDER_DT AS OMS_ORDER_DT,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  CREATION_TYPE AS CREATION_TYPE,
  CREATION_DEVICE_TYPE AS CREATION_DEVICE_TYPE,
  CREATION_DEVICE_WIDTH AS CREATION_DEVICE_WIDTH,
  CHANNEL_TYPE_ID AS CHANNEL_TYPE_ID,
  CHANNEL_ID AS CHANNEL_ID,
  OMS_ORDER_TYPE AS OMS_ORDER_TYPE,
  OMS_ORDER_TYPE_ID AS OMS_ORDER_TYPE_ID,
  ORDER_CATEGORY_ID AS ORDER_CATEGORY_ID,
  SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  CUSTOMER_PICKUP_FLG AS CUSTOMER_PICKUP_FLG,
  OMS_ORDER_STATUS_ID AS OMS_ORDER_STATUS_ID,
  REASON_ID AS REASON_ID,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  ORDER_RECEIVED_FLG AS ORDER_RECEIVED_FLG,
  PARTIALLY_PLANNED_FLG AS PARTIALLY_PLANNED_FLG,
  READY_TO_SHIP_FLG AS READY_TO_SHIP_FLG,
  CLOSED_FLG AS CLOSED_FLG,
  ON_HOLD AS ON_HOLD,
  CANCELLED_FLG AS CANCELLED_FLG,
  CANCELLED_TSTMP AS CANCELLED_TSTMP,
  OMS_CANCELLED_TYPE_ID AS OMS_CANCELLED_TYPE_ID,
  CANCEL_REASON_DESC AS CANCEL_REASON_DESC,
  DECLINE_REASON_ID AS DECLINE_REASON_ID,
  OMS_COMPANY_ID AS OMS_COMPANY_ID,
  BILL_OF_LADING_NBR AS BILL_OF_LADING_NBR,
  RETURN_REFERENCE_NBR AS RETURN_REFERENCE_NBR,
  COMMODITY_CD AS COMMODITY_CD,
  CARRIER_ID AS CARRIER_ID,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  PROTECTION_LEVEL_ID AS PROTECTION_LEVEL_ID,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  ENTRY_CODE AS ENTRY_CODE,
  FULFILL_MODE AS FULFILL_MODE,
  IMPORTED_FLG AS IMPORTED_FLG,
  ALERTS_FLG AS ALERTS_FLG,
  TRANS_RESP_CD AS TRANS_RESP_CD,
  ORIG_LOCATION_NBR AS ORIG_LOCATION_NBR,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  ORIG_SHIP_VIA_LOCATION_ID AS ORIG_SHIP_VIA_LOCATION_ID,
  DEST_LOCATION_NBR AS DEST_LOCATION_NBR,
  DEST_LOCATION_ID AS DEST_LOCATION_ID,
  DEST_SHIP_VIA_LOCATION_ID AS DEST_SHIP_VIA_LOCATION_ID,
  BILL_LOCATION_NBR AS BILL_LOCATION_NBR,
  BILL_LOCATION_ID AS BILL_LOCATION_ID,
  RELEASE_DT AS RELEASE_DT,
  FIRST_RCPT_DT AS FIRST_RCPT_DT,
  LAST_RCPT_DT AS LAST_RCPT_DT,
  DUE_DT AS DUE_DT,
  PICKUP_START_DT AS PICKUP_START_DT,
  PICKUP_END_DT AS PICKUP_END_DT,
  PICKUP_TZ AS PICKUP_TZ,
  REQUESTED_DLVR_DT AS REQUESTED_DLVR_DT,
  PROMISED_DLVR_DT AS PROMISED_DLVR_DT,
  MUST_DLVR_DT AS MUST_DLVR_DT,
  DELIVERY_START_DT AS DELIVERY_START_DT,
  DELIVERY_END_DT AS DELIVERY_END_DT,
  DELIVERY_TZ AS DELIVERY_TZ,
  CUSTOMER_CD AS CUSTOMER_CD,
  CUSTOMER_FIRST_NAME AS CUSTOMER_FIRST_NAME,
  CUSTOMER_LAST_NAME AS CUSTOMER_LAST_NAME,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  CUSTOMER_PHONE AS CUSTOMER_PHONE,
  BILL_FIRST_NAME AS BILL_FIRST_NAME,
  BILL_LAST_NAME AS BILL_LAST_NAME,
  BILL_ADDRESS AS BILL_ADDRESS,
  BILL_CITY AS BILL_CITY,
  BILL_STATE_CD AS BILL_STATE_CD,
  BILL_POSTAL_CD AS BILL_POSTAL_CD,
  BILL_COUNTRY_CD AS BILL_COUNTRY_CD,
  BILL_PHONE AS BILL_PHONE,
  BILL_EMAIL AS BILL_EMAIL,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  MONETARY_VALUE_AMT AS MONETARY_VALUE_AMT,
  ORIG_BUDG_COST_AMT AS ORIG_BUDG_COST_AMT,
  BUDG_COST_AMT AS BUDG_COST_AMT,
  TAX_AMT AS TAX_AMT,
  TAX_CHARGES_AMT AS TAX_CHARGES_AMT,
  MISC_CHARGES_AMT AS MISC_CHARGES_AMT,
  GRAND_TOTAL_AMT AS GRAND_TOTAL_AMT,
  PAYMENT_STATUS AS PAYMENT_STATUS,
  PAYMENT_MODE AS PAYMENT_MODE,
  BUDG_COST_CURRENCY_CD AS BUDG_COST_CURRENCY_CD,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  CURRENCY_CD AS CURRENCY_CD,
  EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_TSTMP AS CREATED_TSTMP,
  LAST_UPDATED_TSTMP AS LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  AFTERPAY_FLG AS AFTERPAY_FLG,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_OMS_ORDER_5
ORDER BY
  OMS_ORDER_ID ASC"""

df_6 = spark.sql(query_6)

df_6.createOrReplaceTempView("SRT_OMS_ORDER_6")

# COMMAND ----------
# DBTITLE 1, JNR_Payment_Detail_vs_OMS_Order_7


query_7 = f"""SELECT
  DETAIL.ENTITY_ID AS ENTITY_ID,
  DETAIL.o_AFTERPAY_FLG AS o_AFTERPAY_FLG,
  MASTER.OMS_ORDER_ID AS OMS_ORDER_ID,
  MASTER.OMS_ORDER_NBR AS OMS_ORDER_NBR,
  MASTER.ORDER_NBR AS ORDER_NBR,
  MASTER.OMS_PARENT_ORDER_ID AS OMS_PARENT_ORDER_ID,
  MASTER.OMS_ORDER_DT AS OMS_ORDER_DT,
  MASTER.ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  MASTER.CREATION_TYPE AS CREATION_TYPE,
  MASTER.CREATION_DEVICE_TYPE AS CREATION_DEVICE_TYPE,
  MASTER.CREATION_DEVICE_WIDTH AS CREATION_DEVICE_WIDTH,
  MASTER.CHANNEL_TYPE_ID AS CHANNEL_TYPE_ID,
  MASTER.CHANNEL_ID AS CHANNEL_ID,
  MASTER.OMS_ORDER_TYPE AS OMS_ORDER_TYPE,
  MASTER.OMS_ORDER_TYPE_ID AS OMS_ORDER_TYPE_ID,
  MASTER.ORDER_CATEGORY_ID AS ORDER_CATEGORY_ID,
  MASTER.SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  MASTER.SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  MASTER.CUSTOMER_PICKUP_FLG AS CUSTOMER_PICKUP_FLG,
  MASTER.OMS_ORDER_STATUS_ID AS OMS_ORDER_STATUS_ID,
  MASTER.REASON_ID AS REASON_ID,
  MASTER.REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  MASTER.ORDER_RECEIVED_FLG AS ORDER_RECEIVED_FLG,
  MASTER.PARTIALLY_PLANNED_FLG AS PARTIALLY_PLANNED_FLG,
  MASTER.READY_TO_SHIP_FLG AS READY_TO_SHIP_FLG,
  MASTER.CLOSED_FLG AS CLOSED_FLG,
  MASTER.ON_HOLD AS ON_HOLD,
  MASTER.CANCELLED_FLG AS CANCELLED_FLG,
  MASTER.CANCELLED_TSTMP AS CANCELLED_TSTMP,
  MASTER.OMS_CANCELLED_TYPE_ID AS OMS_CANCELLED_TYPE_ID,
  MASTER.CANCEL_REASON_DESC AS CANCEL_REASON_DESC,
  MASTER.DECLINE_REASON_ID AS DECLINE_REASON_ID,
  MASTER.OMS_COMPANY_ID AS OMS_COMPANY_ID,
  MASTER.BILL_OF_LADING_NBR AS BILL_OF_LADING_NBR,
  MASTER.RETURN_REFERENCE_NBR AS RETURN_REFERENCE_NBR,
  MASTER.COMMODITY_CD AS COMMODITY_CD,
  MASTER.CARRIER_ID AS CARRIER_ID,
  MASTER.PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  MASTER.PROTECTION_LEVEL_ID AS PROTECTION_LEVEL_ID,
  MASTER.DROPOFF_PICKUP AS DROPOFF_PICKUP,
  MASTER.ENTRY_CODE AS ENTRY_CODE,
  MASTER.FULFILL_MODE AS FULFILL_MODE,
  MASTER.IMPORTED_FLG AS IMPORTED_FLG,
  MASTER.ALERTS_FLG AS ALERTS_FLG,
  MASTER.TRANS_RESP_CD AS TRANS_RESP_CD,
  MASTER.ORIG_LOCATION_NBR AS ORIG_LOCATION_NBR,
  MASTER.ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  MASTER.ORIG_SHIP_VIA_LOCATION_ID AS ORIG_SHIP_VIA_LOCATION_ID,
  MASTER.DEST_LOCATION_NBR AS DEST_LOCATION_NBR,
  MASTER.DEST_LOCATION_ID AS DEST_LOCATION_ID,
  MASTER.DEST_SHIP_VIA_LOCATION_ID AS DEST_SHIP_VIA_LOCATION_ID,
  MASTER.BILL_LOCATION_NBR AS BILL_LOCATION_NBR,
  MASTER.BILL_LOCATION_ID AS BILL_LOCATION_ID,
  MASTER.RELEASE_DT AS RELEASE_DT,
  MASTER.FIRST_RCPT_DT AS FIRST_RCPT_DT,
  MASTER.LAST_RCPT_DT AS LAST_RCPT_DT,
  MASTER.DUE_DT AS DUE_DT,
  MASTER.PICKUP_START_DT AS PICKUP_START_DT,
  MASTER.PICKUP_END_DT AS PICKUP_END_DT,
  MASTER.PICKUP_TZ AS PICKUP_TZ,
  MASTER.REQUESTED_DLVR_DT AS REQUESTED_DLVR_DT,
  MASTER.PROMISED_DLVR_DT AS PROMISED_DLVR_DT,
  MASTER.MUST_DLVR_DT AS MUST_DLVR_DT,
  MASTER.DELIVERY_START_DT AS DELIVERY_START_DT,
  MASTER.DELIVERY_END_DT AS DELIVERY_END_DT,
  MASTER.DELIVERY_TZ AS DELIVERY_TZ,
  MASTER.CUSTOMER_CD AS CUSTOMER_CD,
  MASTER.CUSTOMER_FIRST_NAME AS CUSTOMER_FIRST_NAME,
  MASTER.CUSTOMER_LAST_NAME AS CUSTOMER_LAST_NAME,
  MASTER.CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  MASTER.CUSTOMER_PHONE AS CUSTOMER_PHONE,
  MASTER.BILL_FIRST_NAME AS BILL_FIRST_NAME,
  MASTER.BILL_LAST_NAME AS BILL_LAST_NAME,
  MASTER.BILL_ADDRESS AS BILL_ADDRESS,
  MASTER.BILL_CITY AS BILL_CITY,
  MASTER.BILL_STATE_CD AS BILL_STATE_CD,
  MASTER.BILL_POSTAL_CD AS BILL_POSTAL_CD,
  MASTER.BILL_COUNTRY_CD AS BILL_COUNTRY_CD,
  MASTER.BILL_PHONE AS BILL_PHONE,
  MASTER.BILL_EMAIL AS BILL_EMAIL,
  MASTER.FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  MASTER.MONETARY_VALUE_AMT AS MONETARY_VALUE_AMT,
  MASTER.ORIG_BUDG_COST_AMT AS ORIG_BUDG_COST_AMT,
  MASTER.BUDG_COST_AMT AS BUDG_COST_AMT,
  MASTER.TAX_AMT AS TAX_AMT,
  MASTER.TAX_CHARGES_AMT AS TAX_CHARGES_AMT,
  MASTER.MISC_CHARGES_AMT AS MISC_CHARGES_AMT,
  MASTER.GRAND_TOTAL_AMT AS GRAND_TOTAL_AMT,
  MASTER.PAYMENT_STATUS AS PAYMENT_STATUS,
  MASTER.PAYMENT_MODE AS PAYMENT_MODE,
  MASTER.BUDG_COST_CURRENCY_CD AS BUDG_COST_CURRENCY_CD,
  MASTER.MV_CURRENCY_CD AS MV_CURRENCY_CD,
  MASTER.CURRENCY_CD AS CURRENCY_CD,
  MASTER.EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  MASTER.CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  MASTER.CREATED_SOURCE AS CREATED_SOURCE,
  MASTER.CREATED_TSTMP AS CREATED_TSTMP,
  MASTER.LAST_UPDATED_TSTMP AS LAST_UPDATED_TSTMP,
  MASTER.UPDATE_TSTMP AS UPDATE_TSTMP,
  MASTER.LOAD_TSTMP AS LOAD_TSTMP,
  MASTER.AFTERPAY_FLG AS AFTERPAY_FLG,
  MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SRT_OMS_ORDER_6 MASTER
  INNER JOIN AGG_PD_Entity_ID_3 DETAIL ON MASTER.OMS_ORDER_ID = DETAIL.ENTITY_ID"""

df_7 = spark.sql(query_7)

df_7.createOrReplaceTempView("JNR_Payment_Detail_vs_OMS_Order_7")

# COMMAND ----------
# DBTITLE 1, FLT_Afterpay_FLG_Data_8


query_8 = f"""SELECT
  ENTITY_ID AS ENTITY_ID,
  o_AFTERPAY_FLG AS o_AFTERPAY_FLG,
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_ORDER_NBR AS OMS_ORDER_NBR,
  ORDER_NBR AS ORDER_NBR,
  OMS_PARENT_ORDER_ID AS OMS_PARENT_ORDER_ID,
  OMS_ORDER_DT AS OMS_ORDER_DT,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  CREATION_TYPE AS CREATION_TYPE,
  CREATION_DEVICE_TYPE AS CREATION_DEVICE_TYPE,
  CREATION_DEVICE_WIDTH AS CREATION_DEVICE_WIDTH,
  CHANNEL_TYPE_ID AS CHANNEL_TYPE_ID,
  CHANNEL_ID AS CHANNEL_ID,
  OMS_ORDER_TYPE AS OMS_ORDER_TYPE,
  OMS_ORDER_TYPE_ID AS OMS_ORDER_TYPE_ID,
  ORDER_CATEGORY_ID AS ORDER_CATEGORY_ID,
  SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  CUSTOMER_PICKUP_FLG AS CUSTOMER_PICKUP_FLG,
  OMS_ORDER_STATUS_ID AS OMS_ORDER_STATUS_ID,
  REASON_ID AS REASON_ID,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  ORDER_RECEIVED_FLG AS ORDER_RECEIVED_FLG,
  PARTIALLY_PLANNED_FLG AS PARTIALLY_PLANNED_FLG,
  READY_TO_SHIP_FLG AS READY_TO_SHIP_FLG,
  CLOSED_FLG AS CLOSED_FLG,
  ON_HOLD AS ON_HOLD,
  CANCELLED_FLG AS CANCELLED_FLG,
  CANCELLED_TSTMP AS CANCELLED_TSTMP,
  OMS_CANCELLED_TYPE_ID AS OMS_CANCELLED_TYPE_ID,
  CANCEL_REASON_DESC AS CANCEL_REASON_DESC,
  DECLINE_REASON_ID AS DECLINE_REASON_ID,
  OMS_COMPANY_ID AS OMS_COMPANY_ID,
  BILL_OF_LADING_NBR AS BILL_OF_LADING_NBR,
  RETURN_REFERENCE_NBR AS RETURN_REFERENCE_NBR,
  COMMODITY_CD AS COMMODITY_CD,
  CARRIER_ID AS CARRIER_ID,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  PROTECTION_LEVEL_ID AS PROTECTION_LEVEL_ID,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  ENTRY_CODE AS ENTRY_CODE,
  FULFILL_MODE AS FULFILL_MODE,
  IMPORTED_FLG AS IMPORTED_FLG,
  ALERTS_FLG AS ALERTS_FLG,
  TRANS_RESP_CD AS TRANS_RESP_CD,
  ORIG_LOCATION_NBR AS ORIG_LOCATION_NBR,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  ORIG_SHIP_VIA_LOCATION_ID AS ORIG_SHIP_VIA_LOCATION_ID,
  DEST_LOCATION_NBR AS DEST_LOCATION_NBR,
  DEST_LOCATION_ID AS DEST_LOCATION_ID,
  DEST_SHIP_VIA_LOCATION_ID AS DEST_SHIP_VIA_LOCATION_ID,
  BILL_LOCATION_NBR AS BILL_LOCATION_NBR,
  BILL_LOCATION_ID AS BILL_LOCATION_ID,
  RELEASE_DT AS RELEASE_DT,
  FIRST_RCPT_DT AS FIRST_RCPT_DT,
  LAST_RCPT_DT AS LAST_RCPT_DT,
  DUE_DT AS DUE_DT,
  PICKUP_START_DT AS PICKUP_START_DT,
  PICKUP_END_DT AS PICKUP_END_DT,
  PICKUP_TZ AS PICKUP_TZ,
  REQUESTED_DLVR_DT AS REQUESTED_DLVR_DT,
  PROMISED_DLVR_DT AS PROMISED_DLVR_DT,
  MUST_DLVR_DT AS MUST_DLVR_DT,
  DELIVERY_START_DT AS DELIVERY_START_DT,
  DELIVERY_END_DT AS DELIVERY_END_DT,
  DELIVERY_TZ AS DELIVERY_TZ,
  CUSTOMER_CD AS CUSTOMER_CD,
  CUSTOMER_FIRST_NAME AS CUSTOMER_FIRST_NAME,
  CUSTOMER_LAST_NAME AS CUSTOMER_LAST_NAME,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  CUSTOMER_PHONE AS CUSTOMER_PHONE,
  BILL_FIRST_NAME AS BILL_FIRST_NAME,
  BILL_LAST_NAME AS BILL_LAST_NAME,
  BILL_ADDRESS AS BILL_ADDRESS,
  BILL_CITY AS BILL_CITY,
  BILL_STATE_CD AS BILL_STATE_CD,
  BILL_POSTAL_CD AS BILL_POSTAL_CD,
  BILL_COUNTRY_CD AS BILL_COUNTRY_CD,
  BILL_PHONE AS BILL_PHONE,
  BILL_EMAIL AS BILL_EMAIL,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  MONETARY_VALUE_AMT AS MONETARY_VALUE_AMT,
  ORIG_BUDG_COST_AMT AS ORIG_BUDG_COST_AMT,
  BUDG_COST_AMT AS BUDG_COST_AMT,
  TAX_AMT AS TAX_AMT,
  TAX_CHARGES_AMT AS TAX_CHARGES_AMT,
  MISC_CHARGES_AMT AS MISC_CHARGES_AMT,
  GRAND_TOTAL_AMT AS GRAND_TOTAL_AMT,
  PAYMENT_STATUS AS PAYMENT_STATUS,
  PAYMENT_MODE AS PAYMENT_MODE,
  BUDG_COST_CURRENCY_CD AS BUDG_COST_CURRENCY_CD,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  CURRENCY_CD AS CURRENCY_CD,
  EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_TSTMP AS CREATED_TSTMP,
  LAST_UPDATED_TSTMP AS LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  AFTERPAY_FLG AS AFTERPAY_FLG,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  JNR_Payment_Detail_vs_OMS_Order_7
WHERE
  o_AFTERPAY_FLG <> IFF(ISNULL(AFTERPAY_FLG), -1, AFTERPAY_FLG)"""

df_8 = spark.sql(query_8)

df_8.createOrReplaceTempView("FLT_Afterpay_FLG_Data_8")

# COMMAND ----------
# DBTITLE 1, EXP_UPDATE_TSTMP_9


query_9 = f"""SELECT
  o_AFTERPAY_FLG AS o_AFTERPAY_FLG,
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_ORDER_NBR AS OMS_ORDER_NBR,
  ORDER_NBR AS ORDER_NBR,
  OMS_PARENT_ORDER_ID AS OMS_PARENT_ORDER_ID,
  OMS_ORDER_DT AS OMS_ORDER_DT,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  CREATION_TYPE AS CREATION_TYPE,
  CREATION_DEVICE_TYPE AS CREATION_DEVICE_TYPE,
  CREATION_DEVICE_WIDTH AS CREATION_DEVICE_WIDTH,
  CHANNEL_TYPE_ID AS CHANNEL_TYPE_ID,
  CHANNEL_ID AS CHANNEL_ID,
  OMS_ORDER_TYPE AS OMS_ORDER_TYPE,
  OMS_ORDER_TYPE_ID AS OMS_ORDER_TYPE_ID,
  ORDER_CATEGORY_ID AS ORDER_CATEGORY_ID,
  SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  CUSTOMER_PICKUP_FLG AS CUSTOMER_PICKUP_FLG,
  OMS_ORDER_STATUS_ID AS OMS_ORDER_STATUS_ID,
  REASON_ID AS REASON_ID,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  ORDER_RECEIVED_FLG AS ORDER_RECEIVED_FLG,
  PARTIALLY_PLANNED_FLG AS PARTIALLY_PLANNED_FLG,
  READY_TO_SHIP_FLG AS READY_TO_SHIP_FLG,
  CLOSED_FLG AS CLOSED_FLG,
  ON_HOLD AS ON_HOLD,
  CANCELLED_FLG AS CANCELLED_FLG,
  CANCELLED_TSTMP AS CANCELLED_TSTMP,
  OMS_CANCELLED_TYPE_ID AS OMS_CANCELLED_TYPE_ID,
  CANCEL_REASON_DESC AS CANCEL_REASON_DESC,
  DECLINE_REASON_ID AS DECLINE_REASON_ID,
  OMS_COMPANY_ID AS OMS_COMPANY_ID,
  BILL_OF_LADING_NBR AS BILL_OF_LADING_NBR,
  RETURN_REFERENCE_NBR AS RETURN_REFERENCE_NBR,
  COMMODITY_CD AS COMMODITY_CD,
  CARRIER_ID AS CARRIER_ID,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  PROTECTION_LEVEL_ID AS PROTECTION_LEVEL_ID,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  ENTRY_CODE AS ENTRY_CODE,
  FULFILL_MODE AS FULFILL_MODE,
  IMPORTED_FLG AS IMPORTED_FLG,
  ALERTS_FLG AS ALERTS_FLG,
  TRANS_RESP_CD AS TRANS_RESP_CD,
  ORIG_LOCATION_NBR AS ORIG_LOCATION_NBR,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  ORIG_SHIP_VIA_LOCATION_ID AS ORIG_SHIP_VIA_LOCATION_ID,
  DEST_LOCATION_NBR AS DEST_LOCATION_NBR,
  DEST_LOCATION_ID AS DEST_LOCATION_ID,
  DEST_SHIP_VIA_LOCATION_ID AS DEST_SHIP_VIA_LOCATION_ID,
  BILL_LOCATION_NBR AS BILL_LOCATION_NBR,
  BILL_LOCATION_ID AS BILL_LOCATION_ID,
  RELEASE_DT AS RELEASE_DT,
  FIRST_RCPT_DT AS FIRST_RCPT_DT,
  LAST_RCPT_DT AS LAST_RCPT_DT,
  DUE_DT AS DUE_DT,
  PICKUP_START_DT AS PICKUP_START_DT,
  PICKUP_END_DT AS PICKUP_END_DT,
  PICKUP_TZ AS PICKUP_TZ,
  REQUESTED_DLVR_DT AS REQUESTED_DLVR_DT,
  PROMISED_DLVR_DT AS PROMISED_DLVR_DT,
  MUST_DLVR_DT AS MUST_DLVR_DT,
  DELIVERY_START_DT AS DELIVERY_START_DT,
  DELIVERY_END_DT AS DELIVERY_END_DT,
  DELIVERY_TZ AS DELIVERY_TZ,
  CUSTOMER_CD AS CUSTOMER_CD,
  CUSTOMER_FIRST_NAME AS CUSTOMER_FIRST_NAME,
  CUSTOMER_LAST_NAME AS CUSTOMER_LAST_NAME,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  CUSTOMER_PHONE AS CUSTOMER_PHONE,
  BILL_FIRST_NAME AS BILL_FIRST_NAME,
  BILL_LAST_NAME AS BILL_LAST_NAME,
  BILL_ADDRESS AS BILL_ADDRESS,
  BILL_CITY AS BILL_CITY,
  BILL_STATE_CD AS BILL_STATE_CD,
  BILL_POSTAL_CD AS BILL_POSTAL_CD,
  BILL_COUNTRY_CD AS BILL_COUNTRY_CD,
  BILL_PHONE AS BILL_PHONE,
  BILL_EMAIL AS BILL_EMAIL,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  MONETARY_VALUE_AMT AS MONETARY_VALUE_AMT,
  ORIG_BUDG_COST_AMT AS ORIG_BUDG_COST_AMT,
  BUDG_COST_AMT AS BUDG_COST_AMT,
  TAX_AMT AS TAX_AMT,
  TAX_CHARGES_AMT AS TAX_CHARGES_AMT,
  MISC_CHARGES_AMT AS MISC_CHARGES_AMT,
  GRAND_TOTAL_AMT AS GRAND_TOTAL_AMT,
  PAYMENT_STATUS AS PAYMENT_STATUS,
  PAYMENT_MODE AS PAYMENT_MODE,
  BUDG_COST_CURRENCY_CD AS BUDG_COST_CURRENCY_CD,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  CURRENCY_CD AS CURRENCY_CD,
  EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_TSTMP AS CREATED_TSTMP,
  LAST_UPDATED_TSTMP AS LAST_UPDATED_TSTMP,
  now() AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  FLT_Afterpay_FLG_Data_8"""

df_9 = spark.sql(query_9)

df_9.createOrReplaceTempView("EXP_UPDATE_TSTMP_9")

# COMMAND ----------
# DBTITLE 1, UPD_Afterpay_FLG_10


query_10 = f"""SELECT
  o_AFTERPAY_FLG AS o_AFTERPAY_FLG,
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_ORDER_NBR AS OMS_ORDER_NBR,
  ORDER_NBR AS ORDER_NBR,
  OMS_PARENT_ORDER_ID AS OMS_PARENT_ORDER_ID,
  OMS_ORDER_DT AS OMS_ORDER_DT,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  CREATION_TYPE AS CREATION_TYPE,
  CREATION_DEVICE_TYPE AS CREATION_DEVICE_TYPE,
  CREATION_DEVICE_WIDTH AS CREATION_DEVICE_WIDTH,
  CHANNEL_TYPE_ID AS CHANNEL_TYPE_ID,
  CHANNEL_ID AS CHANNEL_ID,
  OMS_ORDER_TYPE AS OMS_ORDER_TYPE,
  OMS_ORDER_TYPE_ID AS OMS_ORDER_TYPE_ID,
  ORDER_CATEGORY_ID AS ORDER_CATEGORY_ID,
  SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  CUSTOMER_PICKUP_FLG AS CUSTOMER_PICKUP_FLG,
  OMS_ORDER_STATUS_ID AS OMS_ORDER_STATUS_ID,
  REASON_ID AS REASON_ID,
  REASON_CODES_GROUP_ID AS REASON_CODES_GROUP_ID,
  ORDER_RECEIVED_FLG AS ORDER_RECEIVED_FLG,
  PARTIALLY_PLANNED_FLG AS PARTIALLY_PLANNED_FLG,
  READY_TO_SHIP_FLG AS READY_TO_SHIP_FLG,
  CLOSED_FLG AS CLOSED_FLG,
  ON_HOLD AS ON_HOLD,
  CANCELLED_FLG AS CANCELLED_FLG,
  CANCELLED_TSTMP AS CANCELLED_TSTMP,
  OMS_CANCELLED_TYPE_ID AS OMS_CANCELLED_TYPE_ID,
  CANCEL_REASON_DESC AS CANCEL_REASON_DESC,
  DECLINE_REASON_ID AS DECLINE_REASON_ID,
  OMS_COMPANY_ID AS OMS_COMPANY_ID,
  BILL_OF_LADING_NBR AS BILL_OF_LADING_NBR,
  RETURN_REFERENCE_NBR AS RETURN_REFERENCE_NBR,
  COMMODITY_CD AS COMMODITY_CD,
  CARRIER_ID AS CARRIER_ID,
  PRODUCT_CLASS_ID AS PRODUCT_CLASS_ID,
  PROTECTION_LEVEL_ID AS PROTECTION_LEVEL_ID,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  ENTRY_CODE AS ENTRY_CODE,
  FULFILL_MODE AS FULFILL_MODE,
  IMPORTED_FLG AS IMPORTED_FLG,
  ALERTS_FLG AS ALERTS_FLG,
  TRANS_RESP_CD AS TRANS_RESP_CD,
  ORIG_LOCATION_NBR AS ORIG_LOCATION_NBR,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  ORIG_SHIP_VIA_LOCATION_ID AS ORIG_SHIP_VIA_LOCATION_ID,
  DEST_LOCATION_NBR AS DEST_LOCATION_NBR,
  DEST_LOCATION_ID AS DEST_LOCATION_ID,
  DEST_SHIP_VIA_LOCATION_ID AS DEST_SHIP_VIA_LOCATION_ID,
  BILL_LOCATION_NBR AS BILL_LOCATION_NBR,
  BILL_LOCATION_ID AS BILL_LOCATION_ID,
  RELEASE_DT AS RELEASE_DT,
  FIRST_RCPT_DT AS FIRST_RCPT_DT,
  LAST_RCPT_DT AS LAST_RCPT_DT,
  DUE_DT AS DUE_DT,
  PICKUP_START_DT AS PICKUP_START_DT,
  PICKUP_END_DT AS PICKUP_END_DT,
  PICKUP_TZ AS PICKUP_TZ,
  REQUESTED_DLVR_DT AS REQUESTED_DLVR_DT,
  PROMISED_DLVR_DT AS PROMISED_DLVR_DT,
  MUST_DLVR_DT AS MUST_DLVR_DT,
  DELIVERY_START_DT AS DELIVERY_START_DT,
  DELIVERY_END_DT AS DELIVERY_END_DT,
  DELIVERY_TZ AS DELIVERY_TZ,
  CUSTOMER_CD AS CUSTOMER_CD,
  CUSTOMER_FIRST_NAME AS CUSTOMER_FIRST_NAME,
  CUSTOMER_LAST_NAME AS CUSTOMER_LAST_NAME,
  CUSTOMER_EMAIL AS CUSTOMER_EMAIL,
  CUSTOMER_PHONE AS CUSTOMER_PHONE,
  BILL_FIRST_NAME AS BILL_FIRST_NAME,
  BILL_LAST_NAME AS BILL_LAST_NAME,
  BILL_ADDRESS AS BILL_ADDRESS,
  BILL_CITY AS BILL_CITY,
  BILL_STATE_CD AS BILL_STATE_CD,
  BILL_POSTAL_CD AS BILL_POSTAL_CD,
  BILL_COUNTRY_CD AS BILL_COUNTRY_CD,
  BILL_PHONE AS BILL_PHONE,
  BILL_EMAIL AS BILL_EMAIL,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  MONETARY_VALUE_AMT AS MONETARY_VALUE_AMT,
  ORIG_BUDG_COST_AMT AS ORIG_BUDG_COST_AMT,
  BUDG_COST_AMT AS BUDG_COST_AMT,
  TAX_AMT AS TAX_AMT,
  TAX_CHARGES_AMT AS TAX_CHARGES_AMT,
  MISC_CHARGES_AMT AS MISC_CHARGES_AMT,
  GRAND_TOTAL_AMT AS GRAND_TOTAL_AMT,
  PAYMENT_STATUS AS PAYMENT_STATUS,
  PAYMENT_MODE AS PAYMENT_MODE,
  BUDG_COST_CURRENCY_CD AS BUDG_COST_CURRENCY_CD,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  CURRENCY_CD AS CURRENCY_CD,
  EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  CREATED_SOURCE_TYPE AS CREATED_SOURCE_TYPE,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_TSTMP AS CREATED_TSTMP,
  LAST_UPDATED_TSTMP AS LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  EXP_UPDATE_TSTMP_9"""

df_10 = spark.sql(query_10)

df_10.createOrReplaceTempView("UPD_Afterpay_FLG_10")

# COMMAND ----------
# DBTITLE 1, OMS_ORDER


spark.sql("""MERGE INTO OMS_ORDER AS TARGET
USING
  UPD_Afterpay_FLG_10 AS SOURCE ON TARGET.OMS_ORDER_ID = SOURCE.OMS_ORDER_ID
  WHEN MATCHED THEN
UPDATE
SET
  TARGET.OMS_ORDER_ID = SOURCE.OMS_ORDER_ID,
  TARGET.OMS_ORDER_NBR = SOURCE.OMS_ORDER_NBR,
  TARGET.ORDER_NBR = SOURCE.ORDER_NBR,
  TARGET.OMS_PARENT_ORDER_ID = SOURCE.OMS_PARENT_ORDER_ID,
  TARGET.OMS_ORDER_DT = SOURCE.OMS_ORDER_DT,
  TARGET.ORDER_CREATION_CHANNEL = SOURCE.ORDER_CREATION_CHANNEL,
  TARGET.CREATION_TYPE = SOURCE.CREATION_TYPE,
  TARGET.CREATION_DEVICE_TYPE = SOURCE.CREATION_DEVICE_TYPE,
  TARGET.CREATION_DEVICE_WIDTH = SOURCE.CREATION_DEVICE_WIDTH,
  TARGET.CHANNEL_TYPE_ID = SOURCE.CHANNEL_TYPE_ID,
  TARGET.CHANNEL_ID = SOURCE.CHANNEL_ID,
  TARGET.OMS_ORDER_TYPE = SOURCE.OMS_ORDER_TYPE,
  TARGET.OMS_ORDER_TYPE_ID = SOURCE.OMS_ORDER_TYPE_ID,
  TARGET.ORDER_CATEGORY_ID = SOURCE.ORDER_CATEGORY_ID,
  TARGET.SCHED_DELIVERY_FLG = SOURCE.SCHED_DELIVERY_FLG,
  TARGET.SUBSCRIPTION_ORDER_FLG = SOURCE.SUBSCRIPTION_ORDER_FLG,
  TARGET.CUSTOMER_PICKUP_FLG = SOURCE.CUSTOMER_PICKUP_FLG,
  TARGET.OMS_ORDER_STATUS_ID = SOURCE.OMS_ORDER_STATUS_ID,
  TARGET.REASON_ID = SOURCE.REASON_ID,
  TARGET.REASON_CODES_GROUP_ID = SOURCE.REASON_CODES_GROUP_ID,
  TARGET.ORDER_RECEIVED_FLG = SOURCE.ORDER_RECEIVED_FLG,
  TARGET.PARTIALLY_PLANNED_FLG = SOURCE.PARTIALLY_PLANNED_FLG,
  TARGET.READY_TO_SHIP_FLG = SOURCE.READY_TO_SHIP_FLG,
  TARGET.CLOSED_FLG = SOURCE.CLOSED_FLG,
  TARGET.ON_HOLD = SOURCE.ON_HOLD,
  TARGET.CANCELLED_FLG = SOURCE.CANCELLED_FLG,
  TARGET.CANCELLED_TSTMP = SOURCE.CANCELLED_TSTMP,
  TARGET.OMS_CANCELLED_TYPE_ID = SOURCE.OMS_CANCELLED_TYPE_ID,
  TARGET.CANCEL_REASON_DESC = SOURCE.CANCEL_REASON_DESC,
  TARGET.DECLINE_REASON_ID = SOURCE.DECLINE_REASON_ID,
  TARGET.OMS_COMPANY_ID = SOURCE.OMS_COMPANY_ID,
  TARGET.BILL_OF_LADING_NBR = SOURCE.BILL_OF_LADING_NBR,
  TARGET.RETURN_REFERENCE_NBR = SOURCE.RETURN_REFERENCE_NBR,
  TARGET.COMMODITY_CD = SOURCE.COMMODITY_CD,
  TARGET.CARRIER_ID = SOURCE.CARRIER_ID,
  TARGET.PRODUCT_CLASS_ID = SOURCE.PRODUCT_CLASS_ID,
  TARGET.PROTECTION_LEVEL_ID = SOURCE.PROTECTION_LEVEL_ID,
  TARGET.DROPOFF_PICKUP = SOURCE.DROPOFF_PICKUP,
  TARGET.ENTRY_CODE = SOURCE.ENTRY_CODE,
  TARGET.FULFILL_MODE = SOURCE.FULFILL_MODE,
  TARGET.IMPORTED_FLG = SOURCE.IMPORTED_FLG,
  TARGET.ALERTS_FLG = SOURCE.ALERTS_FLG,
  TARGET.TRANS_RESP_CD = SOURCE.TRANS_RESP_CD,
  TARGET.ORIG_LOCATION_NBR = SOURCE.ORIG_LOCATION_NBR,
  TARGET.ORIG_LOCATION_ID = SOURCE.ORIG_LOCATION_ID,
  TARGET.ORIG_SHIP_VIA_LOCATION_ID = SOURCE.ORIG_SHIP_VIA_LOCATION_ID,
  TARGET.DEST_LOCATION_NBR = SOURCE.DEST_LOCATION_NBR,
  TARGET.DEST_LOCATION_ID = SOURCE.DEST_LOCATION_ID,
  TARGET.DEST_SHIP_VIA_LOCATION_ID = SOURCE.DEST_SHIP_VIA_LOCATION_ID,
  TARGET.BILL_LOCATION_NBR = SOURCE.BILL_LOCATION_NBR,
  TARGET.BILL_LOCATION_ID = SOURCE.BILL_LOCATION_ID,
  TARGET.RELEASE_DT = SOURCE.RELEASE_DT,
  TARGET.FIRST_RCPT_DT = SOURCE.FIRST_RCPT_DT,
  TARGET.LAST_RCPT_DT = SOURCE.LAST_RCPT_DT,
  TARGET.DUE_DT = SOURCE.DUE_DT,
  TARGET.PICKUP_START_DT = SOURCE.PICKUP_START_DT,
  TARGET.PICKUP_END_DT = SOURCE.PICKUP_END_DT,
  TARGET.PICKUP_TZ = SOURCE.PICKUP_TZ,
  TARGET.REQUESTED_DLVR_DT = SOURCE.REQUESTED_DLVR_DT,
  TARGET.PROMISED_DLVR_DT = SOURCE.PROMISED_DLVR_DT,
  TARGET.MUST_DLVR_DT = SOURCE.MUST_DLVR_DT,
  TARGET.DELIVERY_START_DT = SOURCE.DELIVERY_START_DT,
  TARGET.DELIVERY_END_DT = SOURCE.DELIVERY_END_DT,
  TARGET.DELIVERY_TZ = SOURCE.DELIVERY_TZ,
  TARGET.CUSTOMER_CD = SOURCE.CUSTOMER_CD,
  TARGET.CUSTOMER_FIRST_NAME = SOURCE.CUSTOMER_FIRST_NAME,
  TARGET.CUSTOMER_LAST_NAME = SOURCE.CUSTOMER_LAST_NAME,
  TARGET.CUSTOMER_EMAIL = SOURCE.CUSTOMER_EMAIL,
  TARGET.CUSTOMER_PHONE = SOURCE.CUSTOMER_PHONE,
  TARGET.BILL_FIRST_NAME = SOURCE.BILL_FIRST_NAME,
  TARGET.BILL_LAST_NAME = SOURCE.BILL_LAST_NAME,
  TARGET.BILL_ADDRESS = SOURCE.BILL_ADDRESS,
  TARGET.BILL_CITY = SOURCE.BILL_CITY,
  TARGET.BILL_STATE_CD = SOURCE.BILL_STATE_CD,
  TARGET.BILL_POSTAL_CD = SOURCE.BILL_POSTAL_CD,
  TARGET.BILL_COUNTRY_CD = SOURCE.BILL_COUNTRY_CD,
  TARGET.BILL_PHONE = SOURCE.BILL_PHONE,
  TARGET.BILL_EMAIL = SOURCE.BILL_EMAIL,
  TARGET.AFTERPAY_FLG = SOURCE.o_AFTERPAY_FLG,
  TARGET.FREIGHT_REVENUE_AMT = SOURCE.FREIGHT_REVENUE_AMT,
  TARGET.MONETARY_VALUE_AMT = SOURCE.MONETARY_VALUE_AMT,
  TARGET.ORIG_BUDG_COST_AMT = SOURCE.ORIG_BUDG_COST_AMT,
  TARGET.BUDG_COST_AMT = SOURCE.BUDG_COST_AMT,
  TARGET.TAX_AMT = SOURCE.TAX_AMT,
  TARGET.TAX_CHARGES_AMT = SOURCE.TAX_CHARGES_AMT,
  TARGET.MISC_CHARGES_AMT = SOURCE.MISC_CHARGES_AMT,
  TARGET.GRAND_TOTAL_AMT = SOURCE.GRAND_TOTAL_AMT,
  TARGET.PAYMENT_STATUS = SOURCE.PAYMENT_STATUS,
  TARGET.PAYMENT_MODE = SOURCE.PAYMENT_MODE,
  TARGET.BUDG_COST_CURRENCY_CD = SOURCE.BUDG_COST_CURRENCY_CD,
  TARGET.MV_CURRENCY_CD = SOURCE.MV_CURRENCY_CD,
  TARGET.CURRENCY_CD = SOURCE.CURRENCY_CD,
  TARGET.EXCHANGE_RATE_PCNT = SOURCE.EXCHANGE_RATE_PCNT,
  TARGET.CREATED_SOURCE_TYPE = SOURCE.CREATED_SOURCE_TYPE,
  TARGET.CREATED_SOURCE = SOURCE.CREATED_SOURCE,
  TARGET.CREATED_TSTMP = SOURCE.CREATED_TSTMP,
  TARGET.LAST_UPDATED_TSTMP = SOURCE.LAST_UPDATED_TSTMP,
  TARGET.UPDATE_TSTMP = SOURCE.UPDATE_TSTMP,
  TARGET.LOAD_TSTMP = SOURCE.LOAD_TSTMP""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_OMS_Order_Afterpay_FLG_UPD")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_OMS_Order_Afterpay_FLG_UPD", mainWorkflowId, parentName)
