# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ../WorkflowUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_OMS_Dist_Order_LN")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_OMS_Dist_Order_LN", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_FACILITY_0


query_0 = f"""SELECT
  OMS_FACILITY_ID AS OMS_FACILITY_ID,
  FACILITY_TYPE_BITS AS FACILITY_TYPE_BITS,
  MARK_FOR_DELETION_FLAG AS MARK_FOR_DELETION_FLAG,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_FACILITY"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_OMS_FACILITY_0")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_EDW_LOAD_CTRL_PRE_1


query_1 = f"""SELECT
  OMS_PURCHASE_ORDERS_ID AS OMS_PURCHASE_ORDERS_ID,
  OMS_PURCHASE_ORDERS_LINE_ITEM_ID AS OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  ORDER_NBR AS ORDER_NBR,
  OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  OMS_TC_PO_LINE_ID AS OMS_TC_PO_LINE_ID,
  OMS_ORDER_FULFILLMENT_OPTION AS OMS_ORDER_FULFILLMENT_OPTION,
  ORDER_FULFILLMENT_CHANNEL AS ORDER_FULFILLMENT_CHANNEL,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  ORDER_CHANNEL AS ORDER_CHANNEL,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_ENTERED_BY AS OMS_ENTERED_BY,
  OMS_ROLE_NAME AS OMS_ROLE_NAME,
  PO_OMS_CREATED_TSTMP AS PO_OMS_CREATED_TSTMP,
  PO_OMS_LAST_UPDATED_DTTM AS PO_OMS_LAST_UPDATED_DTTM,
  POL_OMS_CREATED_TSTMP AS POL_OMS_CREATED_TSTMP,
  POL_OMS_LAST_UPDATED_TSTMP AS POL_OMS_LAST_UPDATED_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_EDW_LOAD_CTRL_PRE"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("Shortcut_to_OMS_EDW_LOAD_CTRL_PRE_1")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_ORDERS_2


query_2 = f"""SELECT
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  OMS_TC_ORDER_ID AS OMS_TC_ORDER_ID,
  OMS_PURCHASE_ORDER_ID AS OMS_PURCHASE_ORDER_ID,
  OMS_PURCHASE_ORDER_NBR AS OMS_PURCHASE_ORDER_NBR,
  OMS_EXT_PURCHASE_ORDER AS OMS_EXT_PURCHASE_ORDER,
  OMS_ORDER_TYPE AS OMS_ORDER_TYPE,
  OMS_ORDER_STATUS_ID AS OMS_ORDER_STATUS_ID,
  OMS_DO_TYPE_ID AS OMS_DO_TYPE_ID,
  OMS_DO_STATUS_ID AS OMS_DO_STATUS_ID,
  OMS_SHIPMENT_ID AS OMS_SHIPMENT_ID,
  OMS_CREATION_TYPE_ID AS OMS_CREATION_TYPE_ID,
  OMS_BILLING_METHOD_ID AS OMS_BILLING_METHOD_ID,
  DROPOFF_PICKUP AS DROPOFF_PICKUP,
  OMS_DELIVERY_OPTIONS_ID AS OMS_DELIVERY_OPTIONS_ID,
  CUSTOMER_PICKUP_FLAG AS CUSTOMER_PICKUP_FLAG,
  PARTIALLY_PLANNED_FLAG AS PARTIALLY_PLANNED_FLAG,
  PARTIAL_SHIP_CONFIRMATION_FLAG AS PARTIAL_SHIP_CONFIRMATION_FLAG,
  PARTIAL_SHIP_CONFIRMATION_STATUS AS PARTIAL_SHIP_CONFIRMATION_STATUS,
  HAS_ALERTS_FLAG AS HAS_ALERTS_FLAG,
  HAS_SPLIT_FLAG AS HAS_SPLIT_FLAG,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  BACK_ORDERED_FLAG AS BACK_ORDERED_FLAG,
  OMS_INBOUND_REGION_ID AS OMS_INBOUND_REGION_ID,
  OMS_OUTBOUND_REGION_ID AS OMS_OUTBOUND_REGION_ID,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  OMS_O_FACILITY_ID AS OMS_O_FACILITY_ID,
  OMS_D_FACILITY_ALIAS_ID AS OMS_D_FACILITY_ALIAS_ID,
  OMS_D_FACILITY_ID AS OMS_D_FACILITY_ID,
  OMS_BILL_FACILITY_ALIAS_ID AS OMS_BILL_FACILITY_ALIAS_ID,
  OMS_BILL_FACILITY_ID AS OMS_BILL_FACILITY_ID,
  OMS_CUSTOMER_ID AS OMS_CUSTOMER_ID,
  ADDR_VALID_FLAG AS ADDR_VALID_FLAG,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PICKUP_TZ_ID AS OMS_PICKUP_TZ_ID,
  OMS_DELIVERY_TZ_ID AS OMS_DELIVERY_TZ_ID,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_ORDER_DT_TSTMP AS OMS_ORDER_DT_TSTMP,
  OMS_ORDER_RECON_TSTMP AS OMS_ORDER_RECON_TSTMP,
  OMS_SCHED_PICKUP_TSTMP AS OMS_SCHED_PICKUP_TSTMP,
  OMS_SCHED_DELIVERY_TSTMP AS OMS_SCHED_DELIVERY_TSTMP,
  OMS_ACTUAL_SHIPPED_TSTMP AS OMS_ACTUAL_SHIPPED_TSTMP,
  TOTAL_NBR_OF_UNITS AS TOTAL_NBR_OF_UNITS,
  BASELINE_COST AS BASELINE_COST,
  ACTUAL_COST AS ACTUAL_COST,
  MONETARY_VALUE AS MONETARY_VALUE,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  REF_NUM1 AS REF_NUM1,
  OMS_CREATED_SOURCE_TYPE_ID AS OMS_CREATED_SOURCE_TYPE_ID,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_ORDERS"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("Shortcut_to_OMS_ORDERS_2")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS1_3


query_3 = f"""SELECT
  OMS_PURCHASE_ORDERS_LINE_ITEM_ID AS OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
  OMS_PURCHASE_ORDERS_ID AS OMS_PURCHASE_ORDERS_ID,
  REF_FIELD1 AS REF_FIELD1,
  REF_FIELD2 AS REF_FIELD2,
  REF_FIELD3 AS REF_FIELD3,
  REF_FIELD4 AS REF_FIELD4,
  REF_FIELD5 AS REF_FIELD5,
  REF_FIELD6 AS REF_FIELD6,
  REF_FIELD7 AS REF_FIELD7,
  REF_FIELD8 AS REF_FIELD8,
  REF_FIELD9 AS REF_FIELD9,
  REF_FIELD10 AS REF_FIELD10,
  REF_NUM1 AS REF_NUM1,
  REF_NUM2 AS REF_NUM2,
  REF_NUM3 AS REF_NUM3,
  REF_NUM4 AS REF_NUM4,
  REF_NUM5 AS REF_NUM5,
  RX_STATUS AS RX_STATUS,
  RX_ASSIGNED_TO AS RX_ASSIGNED_TO,
  RX_ASSIGNED_TSTMP AS RX_ASSIGNED_TSTMP,
  RX_VET_INQUIRY AS RX_VET_INQUIRY,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_PO_LINE_ITEM_REF_FIELDS"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS1_3")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_4


query_4 = f"""SELECT
  OMS_PURCHASE_ORDERS_LINE_ITEM_ID AS OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
  OMS_PURCHASE_ORDERS_ID AS OMS_PURCHASE_ORDERS_ID,
  REF_FIELD1 AS REF_FIELD1,
  REF_FIELD2 AS REF_FIELD2,
  REF_FIELD3 AS REF_FIELD3,
  REF_FIELD4 AS REF_FIELD4,
  REF_FIELD5 AS REF_FIELD5,
  REF_FIELD6 AS REF_FIELD6,
  REF_FIELD7 AS REF_FIELD7,
  REF_FIELD8 AS REF_FIELD8,
  REF_FIELD9 AS REF_FIELD9,
  REF_FIELD10 AS REF_FIELD10,
  REF_NUM1 AS REF_NUM1,
  REF_NUM2 AS REF_NUM2,
  REF_NUM3 AS REF_NUM3,
  REF_NUM4 AS REF_NUM4,
  REF_NUM5 AS REF_NUM5,
  RX_STATUS AS RX_STATUS,
  RX_ASSIGNED_TO AS RX_ASSIGNED_TO,
  RX_ASSIGNED_TSTMP AS RX_ASSIGNED_TSTMP,
  RX_VET_INQUIRY AS RX_VET_INQUIRY,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_PO_LINE_ITEM_REF_FIELDS"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS_4")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_ORDER_LINE_ITEM_ATTRIBUTE_5


query_5 = f"""SELECT
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  ATTRIBUTE_NAME AS ATTRIBUTE_NAME,
  ATTRIBUTE_SEQ AS ATTRIBUTE_SEQ,
  ATTRIBUTE_VALUE AS ATTRIBUTE_VALUE,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_ORDER_LINE_ITEM_ATTRIBUTE"""

df_5 = spark.sql(query_5)

df_5.createOrReplaceTempView("Shortcut_to_OMS_ORDER_LINE_ITEM_ATTRIBUTE_5")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_ORDER_EVENT_6


query_6 = f"""SELECT
  OMS_ORDER_EVENT_ID AS OMS_ORDER_EVENT_ID,
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  FIELD_NAME AS FIELD_NAME,
  OLD_VALUE AS OLD_VALUE,
  NEW_VALUE AS NEW_VALUE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_ORDER_EVENT"""

df_6 = spark.sql(query_6)

df_6.createOrReplaceTempView("Shortcut_to_OMS_ORDER_EVENT_6")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_ORDER_LINE_ITEM_7


query_7 = f"""SELECT
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  OMS_MASTER_ORDER_ID AS OMS_MASTER_ORDER_ID,
  OMS_MO_LINE_ITEM_ID AS OMS_MO_LINE_ITEM_ID,
  OMS_TC_ORDER_LINE_ID AS OMS_TC_ORDER_LINE_ID,
  OMS_PURCHASE_ORDER_NBR AS OMS_PURCHASE_ORDER_NBR,
  OMS_PURCHASE_ORDER_LINE_NBR AS OMS_PURCHASE_ORDER_LINE_NBR,
  OMS_ITEM_ID AS OMS_ITEM_ID,
  OMS_ITEM_NAME AS OMS_ITEM_NAME,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_ACTUAL_SHIPPED_TSTMP AS OMS_ACTUAL_SHIPPED_TSTMP,
  OMS_DO_DTL_STATUS_ID AS OMS_DO_DTL_STATUS_ID,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  OMS_EVENT_CD AS OMS_EVENT_CD,
  OMS_REASON_CD AS OMS_REASON_CD,
  OMS_EXP_INFO_CD AS OMS_EXP_INFO_CD,
  PARTIAL_FILL_FLAG AS PARTIAL_FILL_FLAG,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  USER_CANCELED_QTY AS USER_CANCELED_QTY,
  ORDER_QTY AS ORDER_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  SHIPPED_QTY AS SHIPPED_QTY,
  RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  UNIT_COST_AMT AS UNIT_COST_AMT,
  UNIT_TAX_AMT AS UNIT_TAX_AMT,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_ORDER_LINE_ITEM"""

df_7 = spark.sql(query_7)

df_7.createOrReplaceTempView("Shortcut_to_OMS_ORDER_LINE_ITEM_7")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_OMS_DIST_ORDER_LN_8


query_8 = f"""SELECT
  OMS_DIST_ORDER_ID AS OMS_DIST_ORDER_ID,
  OMS_DIST_ORDER_LN_ID AS OMS_DIST_ORDER_LN_ID,
  TOTAL_MONETARY_VALUE_AMT AS TOTAL_MONETARY_VALUE_AMT,
  UNIT_MONETARY_VALUE_AMT AS UNIT_MONETARY_VALUE_AMT,
  UNIT_TAX_AMT AS UNIT_TAX_AMT,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  SHIPPED_QTY AS SHIPPED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_TSTMP AS CREATED_TSTMP,
  LAST_UPDATED_TSTMP AS LAST_UPDATED_TSTMP,
  OMS_DIST_ORDER_LN_STATUS_ID AS OMS_DIST_ORDER_LN_STATUS_ID,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  UNIT_COST_AMT AS UNIT_COST_AMT,
  UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  USER_CANCELED_QTY AS USER_CANCELED_QTY,
  DELIVERY_END_DT AS DELIVERY_END_DT,
  DELIVERY_START_DT AS DELIVERY_START_DT,
  EVENT_CD AS EVENT_CD,
  REASON_CODE AS REASON_CODE,
  PARTL_FILL_FLG AS PARTL_FILL_FLG,
  ORDER_QTY AS ORDER_QTY,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  RETAIL_PRICE AS RETAIL_PRICE,
  OMS_DIST_ORDER_LN_NBR AS OMS_DIST_ORDER_LN_NBR,
  PICKUP_END_DTTM AS PICKUP_END_DTTM,
  OMS_ORDER_LN_NBR AS OMS_ORDER_LN_NBR,
  PICKUP_START_DTTM AS PICKUP_START_DTTM,
  CANCELLED_FLG AS CANCELLED_FLG,
  PRODUCT_ID AS PRODUCT_ID,
  OMS_ORDER_NBR AS OMS_ORDER_NBR,
  FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  FREIGHT_REVENUE AS FREIGHT_REVENUE,
  ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  EV_RELEASED_TSTMP AS EV_RELEASED_TSTMP,
  EV_ALLOCATED_TSTMP AS EV_ALLOCATED_TSTMP,
  EV_SHIPPED_TSTMP AS EV_SHIPPED_TSTMP,
  EV_PICKEDUP_TSTMP AS EV_PICKEDUP_TSTMP,
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_ORDER_LN_ID AS OMS_ORDER_LN_ID,
  OMS_DO_CREATED_TSTMP AS OMS_DO_CREATED_TSTMP,
  ORDER_NBR AS ORDER_NBR,
  OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  ORDER_FULFILLMENT_CHANNEL AS ORDER_FULFILLMENT_CHANNEL,
  ORDER_CHANNEL AS ORDER_CHANNEL,
  SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  ADD_ON_FLAG AS ADD_ON_FLAG,
  ISPU_PXY_FIRST_NAME AS ISPU_PXY_FIRST_NAME,
  ISPU_PXY_LAST_NAME AS ISPU_PXY_LAST_NAME,
  ISPU_PXY_ADD_LINE1 AS ISPU_PXY_ADD_LINE1,
  ISPU_PXY_ADD_LINE2 AS ISPU_PXY_ADD_LINE2,
  ISPU_PXY_ADD_LINE3 AS ISPU_PXY_ADD_LINE3,
  ISPU_PXY_CITY AS ISPU_PXY_CITY,
  ISPU_PXY_STATE AS ISPU_PXY_STATE,
  ISPU_PXY_POSTAL_CD AS ISPU_PXY_POSTAL_CD,
  ISPU_PXY_COUNTRY AS ISPU_PXY_COUNTRY,
  ISPU_PXY_EMAIL AS ISPU_PXY_EMAIL,
  ISUP_PXY_PHONE AS ISUP_PXY_PHONE,
  OMS_COMPANY_ID AS OMS_COMPANY_ID,
  EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  RX_ORDER_FLG AS RX_ORDER_FLG,
  CANCEL_TSTMP AS CANCEL_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  OMS_DIST_ORDER_LN"""

df_8 = spark.sql(query_8)

df_8.createOrReplaceTempView("Shortcut_to_OMS_DIST_ORDER_LN_8")

# COMMAND ----------
# DBTITLE 1, SQ_ORDER_LINE_ITEM_9


query_9 = f"""SELECT
  ORDER_LINE_ITEM.OMS_ORDER_ID AS OMS_ORDER_ID,
  ORDER_LINE_ITEM.OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  MAX(ORDER_LINE_ITEM.TOTAL_MONETARY_VALUE) AS TOTAL_MONETARY_VALUE,
  MAX(ORDER_LINE_ITEM.UNIT_MONETARY_VALUE) AS UNIT_MONETARY_VALUE,
  MAX(ORDER_LINE_ITEM.UNIT_TAX_AMT) AS UNIT_TAX_AMT,
  MAX(ORDERS.MV_CURRENCY_CD) AS MV_CURRENCY_CD,
  MAX(ORDER_LINE_ITEM.SHIPPED_QTY) AS SHIPPED_QTY,
  MAX(ORDER_LINE_ITEM.RECEIVED_QTY) AS RECEIVED_QTY,
  MAX(ORDER_LINE_ITEM.OMS_CREATED_SOURCE) AS OMS_CREATED_SOURCE,
  MAX(ORDER_LINE_ITEM.OMS_CREATED_TSTMP) AS OMS_CREATED_TSTMP,
  MAX(ORDER_LINE_ITEM.OMS_LAST_UPDATED_TSTMP) AS OMS_LAST_UPDATED_TSTMP,
  MAX(ORDER_LINE_ITEM.OMS_DO_DTL_STATUS_ID) AS OMS_DO_DTL_STATUS_ID,
  MAX(ORDER_LINE_ITEM.ALLOCATED_QTY) AS ALLOCATED_QTY,
  MAX(ORDER_LINE_ITEM.UNIT_COST_AMT) AS UNIT_COST_AMT,
  MAX(ORDER_LINE_ITEM.UNIT_PRICE_AMT) AS UNIT_PRICE_AMT,
  MAX(ORDER_LINE_ITEM.USER_CANCELED_QTY) AS USER_CANCELED_QTY,
  MAX(ORDER_LINE_ITEM.OMS_DELIVERY_END_TSTMP) AS OMS_DELIVERY_END_TSTMP,
  MAX(ORDER_LINE_ITEM.OMS_DELIVERY_START_TSTMP) AS OMS_DELIVERY_START_TSTMP,
  MAX(ORDER_LINE_ITEM.OMS_EVENT_CD) AS OMS_EVENT_CD,
  MAX(ORDER_LINE_ITEM.OMS_REASON_CD) AS OMS_REASON_CD,
  MAX(ORDER_LINE_ITEM.PARTIAL_FILL_FLAG) AS PARTIAL_FILL_FLAG,
  MAX(ORDER_LINE_ITEM.ORDER_QTY) AS ORDER_QTY,
  MAX(ORDER_LINE_ITEM.ORIG_ORDER_QTY) AS ORIG_ORDER_QTY,
  MAX(ORDER_LINE_ITEM.RETAIL_PRICE_AMT) AS RETAIL_PRICE_AMT,
  MAX(ORDER_LINE_ITEM.OMS_TC_ORDER_LINE_ID) AS OMS_TC_ORDER_LINE_ID,
  MAX(ORDER_LINE_ITEM.OMS_PICKUP_END_TSTMP) AS OMS_PICKUP_END_TSTMP,
  MAX(ORDER_LINE_ITEM.OMS_PURCHASE_ORDER_LINE_NBR) AS OMS_PURCHASE_ORDER_LINE_NBR,
  MAX(ORDER_LINE_ITEM.OMS_PICKUP_START_TSTMP) AS OMS_PICKUP_START_TSTMP,
  MAX(ORDER_LINE_ITEM.CANCELLED_FLAG) AS CANCELLED_FLAG,
  MAX(ORDER_LINE_ITEM.OMS_ITEM_NAME) AS OMS_ITEM_NAME,
  MAX(OMS_MASTER_ORDER.OMS_TC_PURCHASE_ORDERS_ID) AS OMS_TC_PURCHASE_ORDERS_ID,
  MAX(ORDER_LINE_ITEM.FREIGHT_REVENUE_CURRENCY_CD) AS FREIGHT_REVENUE_CURRENCY_CD,
  MAX(ORDER_LINE_ITEM.FREIGHT_REVENUE_AMT) AS FREIGHT_REVENUE_AMT,
  MAX(ORDER_LINE_ITEM.ADJUSTED_ORDER_QTY) AS ADJUSTED_ORDER_QTY,
  MAX(PM_ASARBDBYJMEMGKWZUNLXJPJDMNU.EV_RELEASED_TSTMP) AS EV_RELEASED_TSTMP,
  MAX(
    PM_ASARBDBYJMEMGKWZUNLXJPJDMNU.EV_ALLOCATED_TSTMP
  ) AS EV_ALLOCATED_TSTMP,
  MAX(PM_ASARBDBYJMEMGKWZUNLXJPJDMNU.EV_SHIPPED_TSTMP) AS EV_SHIPPED_TSTMP,
  MAX(ORDER_EVENT.OMS_CREATED_TSTMP) AS EV_PICKEDUP_TSTMP,
  MAX(ORDER_LINE_ITEM.OMS_MASTER_ORDER_ID) AS OMS_MASTER_ORDER_ID,
  MAX(ORDER_LINE_ITEM.OMS_MO_LINE_ITEM_ID) AS OMS_MO_LINE_ITEM_ID,
  MAX(ORDERS.OMS_CREATED_TSTMP) AS OMS_DO_CREATED_TSTMP,
  MAX(OMS_MASTER_ORDER.ORDER_NBR) AS ORDER_NBR,
  MAX(OMS_MASTER_ORDER.PO_OMS_CREATED_TSTMP) AS OMS_ORDER_CREATED_TSTMP,
  MAX(ORDERS.OMS_O_FACILITY_ALIAS_ID) AS OMS_O_FACILITY_ALIAS_ID,
  MAX(FACILITY.FACILITY_TYPE_BITS) AS O_FACILITY_TYPE_ID,
  MAX(OMS_MASTER_ORDER.ORDER_CREATION_CHANNEL) AS ORDER_CREATION_CHANNEL,
  MAX(OMS_MASTER_ORDER.ORDER_FULFILLMENT_CHANNEL) AS ORDER_FULFILLMENT_CHANNEL,
  MAX(OMS_MASTER_ORDER.ORDER_CHANNEL) AS ORDER_CHANNEL,
  MAX(PO_LINE_ITEM_REF_FIELDS.SCHED_DELIVERY_FLG) AS SCHED_DELIVERY_FLG,
  MAX(PO_LINE_ITEM_REF_FIELDS.SUBSCRIPTION_ORDER_FLG) AS SUBSCRIPTION_ORDER_FLG,
  MAX(PO_LINE_ITEM_REF_FIELDS.ADD_ON_FLAG) AS ADD_ON_FLAG,
  MAX(
    PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA.ISPU_PXY_FIRST_NAME
  ) AS ISPU_PXY_FIRST_NAME,
  MAX(
    PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA.ISPU_PXY_LAST_NAME
  ) AS ISPU_PXY_LAST_NAME,
  MAX(
    PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA.ISPU_PXY_ADD_LINE1
  ) AS ISPU_PXY_ADD_LINE1,
  MAX(
    PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA.ISPU_PXY_ADD_LINE2
  ) AS ISPU_PXY_ADD_LINE2,
  MAX(
    PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA.ISPU_PXY_ADD_LINE3
  ) AS ISPU_PXY_ADD_LINE3,
  MAX(PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA.ISPU_PXY_CITY) AS ISPU_PXY_CITY,
  MAX(PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA.ISPU_PXY_STATE) AS ISPU_PXY_STATE,
  MAX(
    PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA.ISPU_PXY_POSTAL_CD
  ) AS ISPU_PXY_POSTAL_CD,
  MAX(PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA.ISPU_PXY_COUNTRY) AS ISPU_PXY_COUNTRY,
  MAX(PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA.ISPU_PXY_EMAIL) AS ISPU_PXY_EMAIL,
  MAX(PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA.ISUP_PXY_PHONE) AS ISUP_PXY_PHONE,
  MAX(ORDER_LINE_ITEM.OMS_TC_COMPANY_ID) AS OMS_TC_COMPANY_ID,
  MAX(PO_LINE_ITEM_REF_FIELDS.RX_ORDER_FLG) AS RX_ORDER_FLG,
  MAX(
    CASE
      WHEN ORDER_LINE_ITEM.CANCELLED_FLAG = '1'
      AND ORDER_LINE_ITEM.OMS_DO_DTL_STATUS_ID = 200 THEN ORDER_LINE_ITEM.OMS_LAST_UPDATED_TSTMP
      ELSE NULL
    END
  ) AS CANCEL_DTTM,
  MAX(CURRENT_DATE) AS LOAD_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_ORDER_LINE_ITEM_7 ORDER_LINE_ITEM
  INNER JOIN Shortcut_to_OMS_EDW_LOAD_CTRL_PRE_1 OMS_MASTER_ORDER ON OMS_MASTER_ORDER.OMS_PURCHASE_ORDERS_ID = ORDER_LINE_ITEM.OMS_MASTER_ORDER_ID
  AND OMS_MASTER_ORDER.OMS_PURCHASE_ORDERS_LINE_ITEM_ID = ORDER_LINE_ITEM.OMS_MO_LINE_ITEM_ID
  INNER JOIN Shortcut_to_OMS_ORDERS_2 ORDERS ON ORDERS.OMS_ORDER_ID = ORDER_LINE_ITEM.OMS_ORDER_ID
  AND (
    ORDER_LINE_ITEM.UPDATE_TSTMP > CURRENT_DATE
    OR ORDERS.UPDATE_TSTMP > CURRENT_DATE
  )
  LEFT OUTER JOIN Shortcut_to_OMS_FACILITY_0 FACILITY ON FACILITY.OMS_FACILITY_ID = ORDERS.OMS_O_FACILITY_ID
  LEFT OUTER JOIN (
    SELECT
      ORDER_EVENT.OMS_ORDER_ID,
      ORDER_EVENT.OMS_LINE_ITEM_ID,
      MAX(
        CASE
          WHEN ORDER_EVENT.NEW_VALUE = 'Released' THEN ORDER_EVENT.OMS_CREATED_TSTMP
        END
      ) AS EV_RELEASED_TSTMP,
      MAX(
        CASE
          WHEN ORDER_EVENT.NEW_VALUE = 'DC Allocated'
          OR ORDER_EVENT.NEW_VALUE = 'Partially DC Allocated' THEN ORDER_EVENT.OMS_CREATED_TSTMP
        END
      ) AS EV_ALLOCATED_TSTMP,
      MAX(
        CASE
          WHEN ORDER_EVENT.NEW_VALUE = 'Shipped'
          OR ORDER_EVENT.NEW_VALUE = 'Partially Shipped'
          OR ORDER_EVENT.NEW_VALUE = 'Delivered' THEN ORDER_EVENT.OMS_CREATED_TSTMP
        END
      ) AS EV_SHIPPED_TSTMP
    FROM
      Shortcut_to_OMS_ORDER_EVENT_6 ORDER_EVENT
    WHERE
      ORDER_EVENT.FIELD_NAME = 'LINE ITEM: STATUS'
    GROUP BY
      ORDER_EVENT.OMS_ORDER_ID,
      ORDER_EVENT.OMS_LINE_ITEM_ID
  ) PM_ASARBDBYJMEMGKWZUNLXJPJDMNU ON PM_ASARBDBYJMEMGKWZUNLXJPJDMNU.OMS_ORDER_ID = ORDER_LINE_ITEM.OMS_ORDER_ID
  AND PM_ASARBDBYJMEMGKWZUNLXJPJDMNU.OMS_LINE_ITEM_ID = ORDER_LINE_ITEM.OMS_LINE_ITEM_ID
  LEFT OUTER JOIN Shortcut_to_OMS_ORDER_EVENT_6 ORDER_EVENT ON ORDER_EVENT.OMS_ORDER_ID = ORDERS.OMS_ORDER_ID
  AND ORDER_EVENT.FIELD_NAME = 'REF_NUM1'
  AND ORDER_EVENT.NEW_VALUE = 'No'
  LEFT OUTER JOIN (
    SELECT
      PO_LINE_ITEM_REF_FIELDS.OMS_PURCHASE_ORDERS_ID,
      PO_LINE_ITEM_REF_FIELDS.OMS_PURCHASE_ORDERS_LINE_ITEM_ID,
      MAX(
        CASE
          WHEN PO_LINE_ITEM_REF_FIELDS.REF_FIELD3 IS NULL
          OR UPPER(PO_LINE_ITEM_REF_FIELDS.REF_FIELD3) = 'FALSE' THEN 0
          ELSE 1
        END
      ) OVER (
        PARTITION BY
          PO_LINE_ITEM_REF_FIELDS.OMS_PURCHASE_ORDERS_ID
      ) AS SUBSCRIPTION_ORDER_FLG,
      MAX(
        CASE
          WHEN PO_LINE_ITEM_REF_FIELDS.REF_FIELD1 IS NULL THEN 0
          ELSE ROUND(PO_LINE_ITEM_REF_FIELDS.REF_FIELD1)
        END
      ) OVER (
        PARTITION BY
          PO_LINE_ITEM_REF_FIELDS.OMS_PURCHASE_ORDERS_ID
      ) AS SCHED_DELIVERY_FLG,
      MAX(
        CASE
          WHEN PO_LINE_ITEM_REF_FIELDS.REF_FIELD4 IS NOT NULL THEN 1
          ELSE 0
        END
      ) OVER (
        PARTITION BY
          PO_LINE_ITEM_REF_FIELDS.OMS_PURCHASE_ORDERS_ID
      ) AS RX_ORDER_FLG,
      CASE
        WHEN UPPER(PO_LINE_ITEM_REF_FIELDS.REF_FIELD3) = 'TRUE' THEN 1
        ELSE 0
      END AS ADD_ON_FLAG
    FROM
      Shortcut_to_OMS_PO_LINE_ITEM_REF_FIELDS1_3 PO_LINE_ITEM_REF_FIELDS
  ) PO_LINE_ITEM_REF_FIELDS ON PO_LINE_ITEM_REF_FIELDS.OMS_PURCHASE_ORDERS_ID = ORDER_LINE_ITEM.OMS_MASTER_ORDER_ID
  AND PO_LINE_ITEM_REF_FIELDS.OMS_PURCHASE_ORDERS_LINE_ITEM_ID = ORDER_LINE_ITEM.OMS_MO_LINE_ITEM_ID
  LEFT OUTER JOIN (
    SELECT
      OMS_ORDER_ID,
      OMS_LINE_ITEM_ID,
      MAX(
        CASE
          WHEN ATTRIBUTE_NAME = 'Proxy_FirstName' THEN ATTRIBUTE_VALUE
        END
      ) AS ISPU_PXY_FIRST_NAME,
      MAX(
        CASE
          WHEN ATTRIBUTE_NAME = 'Proxy_LastName' THEN ATTRIBUTE_VALUE
        END
      ) AS ISPU_PXY_LAST_NAME,
      MAX(
        CASE
          WHEN ATTRIBUTE_NAME = 'Proxy_Add_Line1' THEN ATTRIBUTE_VALUE
        END
      ) AS ISPU_PXY_ADD_LINE1,
      MAX(
        CASE
          WHEN ATTRIBUTE_NAME = 'Proxy_Add_Line2' THEN ATTRIBUTE_VALUE
        END
      ) AS ISPU_PXY_ADD_LINE2,
      MAX(
        CASE
          WHEN ATTRIBUTE_NAME = 'Proxy_Add_Line3' THEN ATTRIBUTE_VALUE
        END
      ) AS ISPU_PXY_ADD_LINE3,
      MAX(
        CASE
          WHEN ATTRIBUTE_NAME = 'Proxy_City' THEN ATTRIBUTE_VALUE
        END
      ) AS ISPU_PXY_CITY,
      MAX(
        CASE
          WHEN ATTRIBUTE_NAME = 'Proxy_State' THEN ATTRIBUTE_VALUE
        END
      ) AS ISPU_PXY_STATE,
      MAX(
        CASE
          WHEN ATTRIBUTE_NAME = 'Proxy_PostalCd' THEN ATTRIBUTE_VALUE
        END
      ) AS ISPU_PXY_POSTAL_CD,
      MAX(
        CASE
          WHEN ATTRIBUTE_NAME = 'Proxy_Country' THEN ATTRIBUTE_VALUE
        END
      ) AS ISPU_PXY_COUNTRY,
      MAX(
        CASE
          WHEN ATTRIBUTE_NAME = 'Proxy_Email' THEN ATTRIBUTE_VALUE
        END
      ) AS ISPU_PXY_EMAIL,
      MAX(
        CASE
          WHEN ATTRIBUTE_NAME = 'Proxy_Phone' THEN ATTRIBUTE_VALUE
        END
      ) AS ISUP_PXY_PHONE
    FROM
      Shortcut_to_OMS_ORDER_LINE_ITEM_ATTRIBUTE_5 ORDER_LINE_ITEM_ATTRIBUTE
    GROUP BY
      OMS_ORDER_ID,
      OMS_LINE_ITEM_ID
  ) PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA ON PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA.OMS_ORDER_ID = ORDER_LINE_ITEM.OMS_ORDER_ID
  AND PM_AHIP4OT6NYZ3CWRW7ROARHVMCBA.OMS_LINE_ITEM_ID = ORDER_LINE_ITEM.OMS_LINE_ITEM_ID
GROUP BY
  ORDER_LINE_ITEM.OMS_ORDER_ID,
  ORDER_LINE_ITEM.OMS_LINE_ITEM_ID"""

df_9 = spark.sql(query_9)

df_9.createOrReplaceTempView("SQ_ORDER_LINE_ITEM_9")

# COMMAND ----------
# DBTITLE 1, Exp_Field_10


query_10 = f"""SELECT
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  UNIT_TAX_AMT AS UNIT_TAX_AMT,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  SHIPPED_QTY AS SHIPPED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  OMS_DO_DTL_STATUS_ID AS OMS_DO_DTL_STATUS_ID,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  UNIT_COST_AMT AS UNIT_COST_AMT,
  UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  USER_CANCELED_QTY AS USER_CANCELED_QTY,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_EVENT_CD AS OMS_EVENT_CD,
  OMS_REASON_CD AS OMS_REASON_CD,
  PARTIAL_FILL_FLAG AS PARTIAL_FILL_FLAG,
  ORDER_QTY AS ORDER_QTY,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  OMS_TC_ORDER_LINE_ID AS OMS_TC_ORDER_LINE_ID,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PURCHASE_ORDER_LINE_NBR AS OMS_PURCHASE_ORDER_LINE_NBR,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  OMS_ITEM_NAME AS OMS_ITEM_NAME,
  TO_INTEGER(LTRIM(RTRIM(OMS_ITEM_NAME))) AS OMS_ITEM_NAME_LKP,
  OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  EV_RELEASED_TSTMP AS EV_RELEASED_TSTMP,
  EV_ALLOCATED_TSTMP AS EV_ALLOCATED_TSTMP,
  EV_SHIPPED_TSTMP AS EV_SHIPPED_TSTMP,
  EV_PICKEDUP_TSTMP AS EV_PICKEDUP_TSTMP,
  OMS_MASTER_ORDER_ID AS OMS_MASTER_ORDER_ID,
  OMS_MO_LINE_ITEM_ID AS OMS_MO_LINE_ITEM_ID,
  OMS_DO_CREATED_TSTMP AS OMS_DO_CREATED_TSTMP,
  ORDER_NBR AS ORDER_NBR,
  OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  O_FACILITY_TYPE_ID AS O_FACILITY_TYPE_ID,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  ORDER_FULFILLMENT_CHANNEL AS ORDER_FULFILLMENT_CHANNEL,
  ORDER_CHANNEL AS ORDER_CHANNEL,
  SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  ADD_ON_FLAG AS ADD_ON_FLAG,
  ISPU_PXY_FIRST_NAME AS ISPU_PXY_FIRST_NAME,
  ISPU_PXY_LAST_NAME AS ISPU_PXY_LAST_NAME,
  ISPU_PXY_ADD_LINE1 AS ISPU_PXY_ADD_LINE1,
  ISPU_PXY_ADD_LINE2 AS ISPU_PXY_ADD_LINE2,
  ISPU_PXY_ADD_LINE3 AS ISPU_PXY_ADD_LINE3,
  ISPU_PXY_CITY AS ISPU_PXY_CITY,
  ISPU_PXY_STATE AS ISPU_PXY_STATE,
  ISPU_PXY_POSTAL_CD AS ISPU_PXY_POSTAL_CD,
  ISPU_PXY_COUNTRY AS ISPU_PXY_COUNTRY,
  ISPU_PXY_EMAIL AS ISPU_PXY_EMAIL,
  ISUP_PXY_PHONE AS ISUP_PXY_PHONE,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  RX_ORDER_FLG AS RX_ORDER_FLG,
  CANCEL_DTTM AS CANCEL_DTTM,
  LOAD_TSTMP AS LOAD_TSTMP,
  OMS_O_FACILITY_ALIAS_ID AS TOKEN_1_O_FACILITY_ALIAS_ID,
  15 AS TOKEN_1_15,
  IFF(
    TO_INTEGER(O_FACILITY_TYPE_ID) = 9,
    LTRIM(OMS_O_FACILITY_ALIAS_ID, '0'),
    OMS_O_FACILITY_ALIAS_ID
  ) AS TOKEN_2_O_FACILITY_ALIAS_ID,
  DECODE(
    TO_INTEGER(O_FACILITY_TYPE_ID),
    64,
    8,
    545,
    6,
    33,
    6,
    9,
    19,
    8
  ) AS TOKEN_2_FACILITY_TYPE,
  TRUNC(OMS_ORDER_CREATED_TSTMP) AS TOKEN_LKP_CRCY,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_ORDER_LINE_ITEM_9"""

df_10 = spark.sql(query_10)

df_10.createOrReplaceTempView("Exp_Field_10")

# COMMAND ----------
# DBTITLE 1, lkp_SKU_PROFILE_11


query_11 = f"""SELECT
  SP.PRODUCT_ID AS PRODUCT_ID,
  SP.SKU_NBR AS SKU_NBR,
  EF1.OMS_ITEM_NAME_LKP AS OMS_ITEM_ID_LKP,
  EF1.OMS_ORDER_ID AS OMS_ORDER_ID,
  EF1.OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  EF1.TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  EF1.UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  EF1.UNIT_TAX_AMT AS UNIT_TAX_AMT,
  EF1.MV_CURRENCY_CD AS MV_CURRENCY_CD,
  EF1.SHIPPED_QTY AS SHIPPED_QTY,
  EF1.RECEIVED_QTY AS RECEIVED_QTY,
  EF1.OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  EF1.OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  EF1.OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  EF1.OMS_DO_DTL_STATUS_ID AS OMS_DO_DTL_STATUS_ID,
  EF1.ALLOCATED_QTY AS ALLOCATED_QTY,
  EF1.UNIT_COST_AMT AS UNIT_COST_AMT,
  EF1.UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  EF1.USER_CANCELED_QTY AS USER_CANCELED_QTY,
  EF1.OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  EF1.OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  EF1.OMS_EVENT_CD AS OMS_EVENT_CD,
  EF1.OMS_REASON_CD AS OMS_REASON_CD,
  EF1.PARTIAL_FILL_FLAG AS PARTIAL_FILL_FLAG,
  EF1.ORDER_QTY AS ORDER_QTY,
  EF1.ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  EF1.RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  EF1.OMS_TC_ORDER_LINE_ID AS OMS_TC_ORDER_LINE_ID,
  EF1.OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  EF1.OMS_PURCHASE_ORDER_LINE_NBR AS OMS_PURCHASE_ORDER_LINE_NBR,
  EF1.OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  EF1.CANCELLED_FLAG AS CANCELLED_FLAG,
  EF1.OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  EF1.FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  EF1.FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  EF1.ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  EF1.EV_RELEASED_TSTMP AS EV_RELEASED_TSTMP,
  EF1.EV_ALLOCATED_TSTMP AS EV_ALLOCATED_TSTMP,
  EF1.EV_SHIPPED_TSTMP AS EV_SHIPPED_TSTMP,
  EF1.EV_PICKEDUP_TSTMP AS EV_PICKEDUP_TSTMP,
  EF1.OMS_MASTER_ORDER_ID AS OMS_MASTER_ORDER_ID,
  EF1.OMS_MO_LINE_ITEM_ID AS OMS_MO_LINE_ITEM_ID,
  EF1.OMS_DO_CREATED_TSTMP AS OMS_DO_CREATED_TSTMP,
  EF1.ORDER_NBR AS ORDER_NBR,
  EF1.OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  EF1.OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  EF1.O_FACILITY_TYPE_ID AS O_FACILITY_TYPE_ID,
  EF1.ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  EF1.ORDER_FULFILLMENT_CHANNEL AS ORDER_FULFILLMENT_CHANNEL,
  EF1.ORDER_CHANNEL AS ORDER_CHANNEL,
  EF1.SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  EF1.SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  EF1.ADD_ON_FLAG AS ADD_ON_FLAG,
  EF1.ISPU_PXY_FIRST_NAME AS ISPU_PXY_FIRST_NAME,
  EF1.ISPU_PXY_LAST_NAME AS ISPU_PXY_LAST_NAME,
  EF1.ISPU_PXY_ADD_LINE1 AS ISPU_PXY_ADD_LINE1,
  EF1.ISPU_PXY_ADD_LINE2 AS ISPU_PXY_ADD_LINE2,
  EF1.ISPU_PXY_ADD_LINE3 AS ISPU_PXY_ADD_LINE3,
  EF1.ISPU_PXY_CITY AS ISPU_PXY_CITY,
  EF1.ISPU_PXY_STATE AS ISPU_PXY_STATE,
  EF1.ISPU_PXY_POSTAL_CD AS ISPU_PXY_POSTAL_CD,
  EF1.ISPU_PXY_COUNTRY AS ISPU_PXY_COUNTRY,
  EF1.ISPU_PXY_EMAIL AS ISPU_PXY_EMAIL,
  EF1.ISUP_PXY_PHONE AS ISUP_PXY_PHONE,
  EF1.OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  EF1.RX_ORDER_FLG AS RX_ORDER_FLG,
  EF1.CANCEL_DTTM AS CANCEL_DTTM,
  EF1.LOAD_TSTMP AS LOAD_TSTMP,
  EF1.TOKEN_1_O_FACILITY_ALIAS_ID AS TOKEN_1_O_FACILITY_ALIAS_ID,
  EF1.TOKEN_1_15 AS TOKEN_1_15,
  EF1.TOKEN_2_O_FACILITY_ALIAS_ID AS TOKEN_2_O_FACILITY_ALIAS_ID,
  EF1.TOKEN_2_FACILITY_TYPE AS TOKEN_2_FACILITY_TYPE,
  EF1.TOKEN_LKP_CRCY AS TOKEN_LKP_CRCY,
  EF1.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  Exp_Field_10 EF1
  LEFT JOIN SKU_PROFILE SP ON SP.SKU_NBR = EF1.OMS_ITEM_NAME_LKP"""

df_11 = spark.sql(query_11)

df_11.createOrReplaceTempView("lkp_SKU_PROFILE_11")

# COMMAND ----------
# DBTITLE 1, lkp_SITE_PROFILE_12


query_12 = f"""SELECT
  SP.LOCATION_ID AS LOCATION_ID,
  SP.LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
  SP.LOCATION_NBR AS LOCATION_NBR,
  lSP1.PRODUCT_ID AS PRODUCT_ID,
  lSP1.TOKEN_1_O_FACILITY_ALIAS_ID AS TOKEN_1_O_FACILITY_ALIAS_ID,
  lSP1.TOKEN_1_15 AS TOKEN_1_15,
  lSP1.TOKEN_2_O_FACILITY_ALIAS_ID AS TOKEN_2_O_FACILITY_ALIAS_ID1,
  lSP1.TOKEN_2_FACILITY_TYPE AS TOKEN_2_FACILITY_TYPE,
  lSP1.OMS_ORDER_ID AS OMS_ORDER_ID,
  lSP1.OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  lSP1.TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  lSP1.UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  lSP1.UNIT_TAX_AMT AS UNIT_TAX_AMT,
  lSP1.MV_CURRENCY_CD AS MV_CURRENCY_CD,
  lSP1.SHIPPED_QTY AS SHIPPED_QTY,
  lSP1.RECEIVED_QTY AS RECEIVED_QTY,
  lSP1.OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  lSP1.OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  lSP1.OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  lSP1.OMS_DO_DTL_STATUS_ID AS OMS_DO_DTL_STATUS_ID,
  lSP1.ALLOCATED_QTY AS ALLOCATED_QTY,
  lSP1.UNIT_COST_AMT AS UNIT_COST_AMT,
  lSP1.UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  lSP1.USER_CANCELED_QTY AS USER_CANCELED_QTY,
  lSP1.OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  lSP1.OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  lSP1.OMS_EVENT_CD AS OMS_EVENT_CD,
  lSP1.OMS_REASON_CD AS OMS_REASON_CD,
  lSP1.PARTIAL_FILL_FLAG AS PARTIAL_FILL_FLAG,
  lSP1.ORDER_QTY AS ORDER_QTY,
  lSP1.ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  lSP1.RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  lSP1.OMS_TC_ORDER_LINE_ID AS OMS_TC_ORDER_LINE_ID,
  lSP1.OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  lSP1.OMS_PURCHASE_ORDER_LINE_NBR AS OMS_PURCHASE_ORDER_LINE_NBR,
  lSP1.OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  lSP1.CANCELLED_FLAG AS CANCELLED_FLAG,
  lSP1.OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  lSP1.FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  lSP1.FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  lSP1.ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  lSP1.EV_RELEASED_TSTMP AS EV_RELEASED_TSTMP,
  lSP1.EV_ALLOCATED_TSTMP AS EV_ALLOCATED_TSTMP,
  lSP1.EV_SHIPPED_TSTMP AS EV_SHIPPED_TSTMP,
  lSP1.EV_PICKEDUP_TSTMP AS EV_PICKEDUP_TSTMP,
  lSP1.OMS_MASTER_ORDER_ID AS OMS_MASTER_ORDER_ID,
  lSP1.OMS_MO_LINE_ITEM_ID AS OMS_MO_LINE_ITEM_ID,
  lSP1.OMS_DO_CREATED_TSTMP AS OMS_DO_CREATED_TSTMP,
  lSP1.ORDER_NBR AS ORDER_NBR,
  lSP1.OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  lSP1.OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  lSP1.O_FACILITY_TYPE_ID AS O_FACILITY_TYPE_ID,
  lSP1.ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  lSP1.ORDER_FULFILLMENT_CHANNEL AS ORDER_FULFILLMENT_CHANNEL,
  lSP1.ORDER_CHANNEL AS ORDER_CHANNEL,
  lSP1.SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  lSP1.SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  lSP1.ADD_ON_FLAG AS ADD_ON_FLAG,
  lSP1.ISPU_PXY_FIRST_NAME AS ISPU_PXY_FIRST_NAME,
  lSP1.ISPU_PXY_LAST_NAME AS ISPU_PXY_LAST_NAME,
  lSP1.ISPU_PXY_ADD_LINE1 AS ISPU_PXY_ADD_LINE1,
  lSP1.ISPU_PXY_ADD_LINE2 AS ISPU_PXY_ADD_LINE2,
  lSP1.ISPU_PXY_ADD_LINE3 AS ISPU_PXY_ADD_LINE3,
  lSP1.ISPU_PXY_CITY AS ISPU_PXY_CITY,
  lSP1.ISPU_PXY_STATE AS ISPU_PXY_STATE,
  lSP1.ISPU_PXY_POSTAL_CD AS ISPU_PXY_POSTAL_CD,
  lSP1.ISPU_PXY_COUNTRY AS ISPU_PXY_COUNTRY,
  lSP1.ISPU_PXY_EMAIL AS ISPU_PXY_EMAIL,
  lSP1.ISUP_PXY_PHONE AS ISUP_PXY_PHONE,
  lSP1.OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  lSP1.RX_ORDER_FLG AS RX_ORDER_FLG,
  lSP1.CANCEL_DTTM AS CANCEL_DTTM,
  lSP1.LOAD_TSTMP AS LOAD_TSTMP,
  lSP1.TOKEN_LKP_CRCY AS TOKEN_LKP_CRCY,
  lSP1.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  lkp_SKU_PROFILE_11 lSP1
  LEFT JOIN (
    SELECT
      MAX(SITE_PROFILE.LOCATION_ID) as LOCATION_ID,
      SITE_PROFILE.LOCATION_TYPE_ID as LOCATION_TYPE_ID,
      CASE
        WHEN SITE_PROFILE.LOCATION_TYPE_ID = 19 THEN LTRIM(SITE_PROFILE.LOCATION_NBR, '0')
        ELSE SITE_PROFILE.LOCATION_NBR
      END as LOCATION_NBR
    FROM
      SITE_PROFILE
    GROUP BY
      SITE_PROFILE.LOCATION_TYPE_ID,
      CASE
        WHEN SITE_PROFILE.LOCATION_TYPE_ID = 19 THEN LTRIM(SITE_PROFILE.LOCATION_NBR, '0')
        ELSE SITE_PROFILE.LOCATION_NBR
      END
  ) AS SP ON SP.LOCATION_NBR = lSP1.TOKEN_1_O_FACILITY_ALIAS_ID
  AND SP.LOCATION_TYPE_ID = lSP1.TOKEN_1_15"""

df_12 = spark.sql(query_12)

df_12.createOrReplaceTempView("lkp_SITE_PROFILE_12")

# COMMAND ----------
# DBTITLE 1, lkp_SITE_PROFILE_2_13


query_13 = f"""SELECT
  SP.LOCATION_ID AS LOCATION_ID,
  SP.LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
  SP.LOCATION_NBR AS LOCATION_NBR,
  lSP1.LOCATION_ID AS TOKEN_1_LKP_RTN,
  lSP1.PRODUCT_ID AS PRODUCT_ID,
  lSP1.TOKEN_2_O_FACILITY_ALIAS_ID1 AS TOKEN_2_O_FACILITY_ALIAS_ID1,
  lSP1.TOKEN_2_FACILITY_TYPE AS TOKEN_2_FACILITY_TYPE,
  lSP1.OMS_ORDER_ID AS OMS_ORDER_ID,
  lSP1.OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  lSP1.TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  lSP1.UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  lSP1.UNIT_TAX_AMT AS UNIT_TAX_AMT,
  lSP1.MV_CURRENCY_CD AS MV_CURRENCY_CD,
  lSP1.SHIPPED_QTY AS SHIPPED_QTY,
  lSP1.RECEIVED_QTY AS RECEIVED_QTY,
  lSP1.OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  lSP1.OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  lSP1.OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  lSP1.OMS_DO_DTL_STATUS_ID AS OMS_DO_DTL_STATUS_ID,
  lSP1.ALLOCATED_QTY AS ALLOCATED_QTY,
  lSP1.UNIT_COST_AMT AS UNIT_COST_AMT,
  lSP1.UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  lSP1.USER_CANCELED_QTY AS USER_CANCELED_QTY,
  lSP1.OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  lSP1.OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  lSP1.OMS_EVENT_CD AS OMS_EVENT_CD,
  lSP1.OMS_REASON_CD AS OMS_REASON_CD,
  lSP1.PARTIAL_FILL_FLAG AS PARTIAL_FILL_FLAG,
  lSP1.ORDER_QTY AS ORDER_QTY,
  lSP1.ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  lSP1.RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  lSP1.OMS_TC_ORDER_LINE_ID AS OMS_TC_ORDER_LINE_ID,
  lSP1.OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  lSP1.OMS_PURCHASE_ORDER_LINE_NBR AS OMS_PURCHASE_ORDER_LINE_NBR,
  lSP1.OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  lSP1.CANCELLED_FLAG AS CANCELLED_FLAG,
  lSP1.OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  lSP1.FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  lSP1.FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  lSP1.ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  lSP1.EV_RELEASED_TSTMP AS EV_RELEASED_TSTMP,
  lSP1.EV_ALLOCATED_TSTMP AS EV_ALLOCATED_TSTMP,
  lSP1.EV_SHIPPED_TSTMP AS EV_SHIPPED_TSTMP,
  lSP1.EV_PICKEDUP_TSTMP AS EV_PICKEDUP_TSTMP,
  lSP1.OMS_MASTER_ORDER_ID AS OMS_MASTER_ORDER_ID,
  lSP1.OMS_MO_LINE_ITEM_ID AS OMS_MO_LINE_ITEM_ID,
  lSP1.OMS_DO_CREATED_TSTMP AS OMS_DO_CREATED_TSTMP,
  lSP1.ORDER_NBR AS ORDER_NBR,
  lSP1.OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  lSP1.OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  lSP1.O_FACILITY_TYPE_ID AS O_FACILITY_TYPE_ID,
  lSP1.ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  lSP1.ORDER_FULFILLMENT_CHANNEL AS ORDER_FULFILLMENT_CHANNEL,
  lSP1.ORDER_CHANNEL AS ORDER_CHANNEL,
  lSP1.SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  lSP1.SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  lSP1.ADD_ON_FLAG AS ADD_ON_FLAG,
  lSP1.ISPU_PXY_FIRST_NAME AS ISPU_PXY_FIRST_NAME,
  lSP1.ISPU_PXY_LAST_NAME AS ISPU_PXY_LAST_NAME,
  lSP1.ISPU_PXY_ADD_LINE1 AS ISPU_PXY_ADD_LINE1,
  lSP1.ISPU_PXY_ADD_LINE2 AS ISPU_PXY_ADD_LINE2,
  lSP1.ISPU_PXY_ADD_LINE3 AS ISPU_PXY_ADD_LINE3,
  lSP1.ISPU_PXY_CITY AS ISPU_PXY_CITY,
  lSP1.ISPU_PXY_STATE AS ISPU_PXY_STATE,
  lSP1.ISPU_PXY_POSTAL_CD AS ISPU_PXY_POSTAL_CD,
  lSP1.ISPU_PXY_COUNTRY AS ISPU_PXY_COUNTRY,
  lSP1.ISPU_PXY_EMAIL AS ISPU_PXY_EMAIL,
  lSP1.ISUP_PXY_PHONE AS ISUP_PXY_PHONE,
  lSP1.OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  lSP1.RX_ORDER_FLG AS RX_ORDER_FLG,
  lSP1.CANCEL_DTTM AS CANCEL_DTTM,
  lSP1.LOAD_TSTMP AS LOAD_TSTMP,
  lSP1.TOKEN_LKP_CRCY AS TOKEN_LKP_CRCY,
  lSP1.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  lkp_SITE_PROFILE_12 lSP1
  LEFT JOIN (
    SELECT
      MAX(SITE_PROFILE.LOCATION_ID) as LOCATION_ID,
      SITE_PROFILE.LOCATION_TYPE_ID as LOCATION_TYPE_ID,
      CASE
        WHEN SITE_PROFILE.LOCATION_TYPE_ID = 19 THEN LTRIM(SITE_PROFILE.LOCATION_NBR, '0')
        ELSE SITE_PROFILE.LOCATION_NBR
      END as LOCATION_NBR
    FROM
      SITE_PROFILE
    GROUP BY
      SITE_PROFILE.LOCATION_TYPE_ID,
      CASE
        WHEN SITE_PROFILE.LOCATION_TYPE_ID = 19 THEN LTRIM(SITE_PROFILE.LOCATION_NBR, '0')
        ELSE SITE_PROFILE.LOCATION_NBR
      END
  ) AS SP ON SP.LOCATION_NBR = lSP1.TOKEN_2_O_FACILITY_ALIAS_ID1
  AND SP.LOCATION_TYPE_ID = lSP1.TOKEN_2_FACILITY_TYPE"""

df_13 = spark.sql(query_13)

df_13.createOrReplaceTempView("lkp_SITE_PROFILE_2_13")

# COMMAND ----------
# DBTITLE 1, lkp_Currency_Day_14


query_14 = f"""SELECT
  CD.DAY_DT AS DAY_DT,
  CD.EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  lSP21.LOCATION_ID AS TOKEN_2_LKP_RTN,
  lSP21.TOKEN_1_LKP_RTN AS TOKEN_1_LKP_RTN,
  lSP21.OMS_ORDER_ID AS OMS_ORDER_ID,
  lSP21.OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  lSP21.TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  lSP21.UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  lSP21.UNIT_TAX_AMT AS UNIT_TAX_AMT,
  lSP21.MV_CURRENCY_CD AS MV_CURRENCY_CD,
  lSP21.SHIPPED_QTY AS SHIPPED_QTY,
  lSP21.RECEIVED_QTY AS RECEIVED_QTY,
  lSP21.OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  lSP21.OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  lSP21.OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  lSP21.OMS_DO_DTL_STATUS_ID AS OMS_DO_DTL_STATUS_ID,
  lSP21.ALLOCATED_QTY AS ALLOCATED_QTY,
  lSP21.UNIT_COST_AMT AS UNIT_COST_AMT,
  lSP21.UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  lSP21.USER_CANCELED_QTY AS USER_CANCELED_QTY,
  lSP21.OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  lSP21.OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  lSP21.OMS_EVENT_CD AS OMS_EVENT_CD,
  lSP21.OMS_REASON_CD AS OMS_REASON_CD,
  lSP21.PARTIAL_FILL_FLAG AS PARTIAL_FILL_FLAG,
  lSP21.ORDER_QTY AS ORDER_QTY,
  lSP21.ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  lSP21.RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  lSP21.OMS_TC_ORDER_LINE_ID AS OMS_TC_ORDER_LINE_ID,
  lSP21.OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  lSP21.OMS_PURCHASE_ORDER_LINE_NBR AS OMS_PURCHASE_ORDER_LINE_NBR,
  lSP21.OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  lSP21.CANCELLED_FLAG AS CANCELLED_FLAG,
  lSP21.OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  lSP21.FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  lSP21.FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  lSP21.ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  lSP21.EV_RELEASED_TSTMP AS EV_RELEASED_TSTMP,
  lSP21.EV_ALLOCATED_TSTMP AS EV_ALLOCATED_TSTMP,
  lSP21.EV_SHIPPED_TSTMP AS EV_SHIPPED_TSTMP,
  lSP21.EV_PICKEDUP_TSTMP AS EV_PICKEDUP_TSTMP,
  lSP21.OMS_MASTER_ORDER_ID AS OMS_MASTER_ORDER_ID,
  lSP21.OMS_MO_LINE_ITEM_ID AS OMS_MO_LINE_ITEM_ID,
  lSP21.OMS_DO_CREATED_TSTMP AS OMS_DO_CREATED_TSTMP,
  lSP21.ORDER_NBR AS ORDER_NBR,
  lSP21.OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  lSP21.OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  lSP21.O_FACILITY_TYPE_ID AS O_FACILITY_TYPE_ID,
  lSP21.ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  lSP21.ORDER_FULFILLMENT_CHANNEL AS ORDER_FULFILLMENT_CHANNEL,
  lSP21.ORDER_CHANNEL AS ORDER_CHANNEL,
  lSP21.SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  lSP21.SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  lSP21.ADD_ON_FLAG AS ADD_ON_FLAG,
  lSP21.ISPU_PXY_FIRST_NAME AS ISPU_PXY_FIRST_NAME,
  lSP21.ISPU_PXY_LAST_NAME AS ISPU_PXY_LAST_NAME,
  lSP21.ISPU_PXY_ADD_LINE1 AS ISPU_PXY_ADD_LINE1,
  lSP21.ISPU_PXY_ADD_LINE2 AS ISPU_PXY_ADD_LINE2,
  lSP21.ISPU_PXY_ADD_LINE3 AS ISPU_PXY_ADD_LINE3,
  lSP21.ISPU_PXY_CITY AS ISPU_PXY_CITY,
  lSP21.ISPU_PXY_STATE AS ISPU_PXY_STATE,
  lSP21.ISPU_PXY_POSTAL_CD AS ISPU_PXY_POSTAL_CD,
  lSP21.ISPU_PXY_COUNTRY AS ISPU_PXY_COUNTRY,
  lSP21.ISPU_PXY_EMAIL AS ISPU_PXY_EMAIL,
  lSP21.ISUP_PXY_PHONE AS ISUP_PXY_PHONE,
  lSP21.OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  lSP21.RX_ORDER_FLG AS RX_ORDER_FLG,
  lSP21.CANCEL_DTTM AS CANCEL_DTTM,
  lSP21.LOAD_TSTMP AS LOAD_TSTMP,
  lSP21.TOKEN_LKP_CRCY AS TOKEN_LKP_CRCY,
  lSP21.PRODUCT_ID AS PRODUCT_ID,
  lSP21.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  lkp_SITE_PROFILE_2_13 lSP21
  LEFT JOIN CURRENCY_DAY CD ON CD.DAY_DT = lSP21.TOKEN_LKP_CRCY"""

df_14 = spark.sql(query_14)

df_14.createOrReplaceTempView("lkp_Currency_Day_14")

# COMMAND ----------
# DBTITLE 1, EXP_SRC_15


query_15 = f"""SELECT
  TO_INTEGER(OMS_ORDER_ID) AS OMS_ORDER_ID,
  TO_INTEGER(OMS_LINE_ITEM_ID) AS OMS_LINE_ITEM_ID,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  UNIT_TAX_AMT AS UNIT_TAX_AMT,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  SHIPPED_QTY AS SHIPPED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  OMS_DO_DTL_STATUS_ID AS OMS_DO_DTL_STATUS_ID,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  UNIT_COST_AMT AS UNIT_COST_AMT,
  UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  USER_CANCELED_QTY AS USER_CANCELED_QTY,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_EVENT_CD AS OMS_EVENT_CD,
  OMS_REASON_CD AS OMS_REASON_CD,
  PARTIAL_FILL_FLAG AS PARTIAL_FILL_FLAG,
  ORDER_QTY AS ORDER_QTY,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  OMS_TC_ORDER_LINE_ID AS OMS_TC_ORDER_LINE_ID,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PURCHASE_ORDER_LINE_NBR AS OMS_PURCHASE_ORDER_LINE_NBR,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  EV_RELEASED_TSTMP AS EV_RELEASED_TSTMP,
  EV_ALLOCATED_TSTMP AS EV_ALLOCATED_TSTMP,
  EV_SHIPPED_TSTMP AS EV_SHIPPED_TSTMP,
  EV_PICKEDUP_TSTMP AS EV_PICKEDUP_TSTMP,
  OMS_MASTER_ORDER_ID AS OMS_MASTER_ORDER_ID,
  OMS_MO_LINE_ITEM_ID AS OMS_MO_LINE_ITEM_ID,
  OMS_DO_CREATED_TSTMP AS OMS_DO_CREATED_TSTMP,
  ORDER_NBR AS ORDER_NBR,
  OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  O_FACILITY_TYPE_ID AS O_FACILITY_TYPE_ID,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  ORDER_FULFILLMENT_CHANNEL AS ORDER_FULFILLMENT_CHANNEL,
  ORDER_CHANNEL AS ORDER_CHANNEL,
  IFF(
    ISNULL(SCHED_DELIVERY_FLG)
    OR SCHED_DELIVERY_FLG = 0,
    0,
    1
  ) AS SCHED_DELIVERY_FLG,
  IFF(
    ISNULL(SUBSCRIPTION_ORDER_FLG)
    OR SUBSCRIPTION_ORDER_FLG = 0,
    0,
    1
  ) AS SUBSCRIPTION_ORDER_FLG,
  ADD_ON_FLAG AS ADD_ON_FLAG,
  ISPU_PXY_FIRST_NAME AS ISPU_PXY_FIRST_NAME,
  ISPU_PXY_LAST_NAME AS ISPU_PXY_LAST_NAME,
  ISPU_PXY_ADD_LINE1 AS ISPU_PXY_ADD_LINE1,
  ISPU_PXY_ADD_LINE2 AS ISPU_PXY_ADD_LINE2,
  ISPU_PXY_ADD_LINE3 AS ISPU_PXY_ADD_LINE3,
  ISPU_PXY_CITY AS ISPU_PXY_CITY,
  ISPU_PXY_STATE AS ISPU_PXY_STATE,
  ISPU_PXY_POSTAL_CD AS ISPU_PXY_POSTAL_CD,
  ISPU_PXY_COUNTRY AS ISPU_PXY_COUNTRY,
  ISPU_PXY_EMAIL AS ISPU_PXY_EMAIL,
  ISUP_PXY_PHONE AS ISUP_PXY_PHONE,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  IFF(
    ISNULL(RX_ORDER_FLG)
    OR RX_ORDER_FLG = 0,
    0,
    1
  ) AS RX_ORDER_FLG,
  CANCEL_DTTM AS CANCEL_DTTM,
  LOAD_TSTMP AS LOAD_TSTMP,
  PRODUCT_ID AS PRODUCT_ID,
  IFF(OMS_TC_COMPANY_ID = 8840, 1, EXCHANGE_RATE_PCNT) AS EXCHANGE_RATE_PCNT,
  IFF(
    OMS_O_FACILITY_ALIAS_ID = '2956',
    TOKEN_1_LKP_RTN,
    IFF(
      NOT ISNULL(OMS_O_FACILITY_ALIAS_ID),
      TOKEN_2_LKP_RTN,
      NULL
    )
  ) AS ORIG_LOCATION_ID,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  lkp_Currency_Day_14"""

df_15 = spark.sql(query_15)

df_15.createOrReplaceTempView("EXP_SRC_15")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_OMS_DIST_ORDER_LN_16


query_16 = f"""SELECT
  OMS_DIST_ORDER_ID AS OMS_DIST_ORDER_ID,
  OMS_DIST_ORDER_LN_ID AS OMS_DIST_ORDER_LN_ID,
  TOTAL_MONETARY_VALUE_AMT AS TOTAL_MONETARY_VALUE_AMT,
  UNIT_MONETARY_VALUE_AMT AS UNIT_MONETARY_VALUE_AMT,
  UNIT_TAX_AMT AS UNIT_TAX_AMT,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  SHIPPED_QTY AS SHIPPED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  CREATED_SOURCE AS CREATED_SOURCE,
  CREATED_TSTMP AS CREATED_TSTMP,
  LAST_UPDATED_TSTMP AS LAST_UPDATED_TSTMP,
  OMS_DIST_ORDER_LN_STATUS_ID AS OMS_DIST_ORDER_LN_STATUS_ID,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  UNIT_COST_AMT AS UNIT_COST_AMT,
  UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  USER_CANCELED_QTY AS USER_CANCELED_QTY,
  DELIVERY_END_DT AS DELIVERY_END_DT,
  DELIVERY_START_DT AS DELIVERY_START_DT,
  EVENT_CD AS EVENT_CD,
  REASON_CODE AS REASON_CODE,
  PARTL_FILL_FLG AS PARTL_FILL_FLG,
  ORDER_QTY AS ORDER_QTY,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  RETAIL_PRICE AS RETAIL_PRICE,
  OMS_DIST_ORDER_LN_NBR AS OMS_DIST_ORDER_LN_NBR,
  PICKUP_END_DTTM AS PICKUP_END_DTTM,
  OMS_ORDER_LN_NBR AS OMS_ORDER_LN_NBR,
  PICKUP_START_DTTM AS PICKUP_START_DTTM,
  CANCELLED_FLG AS CANCELLED_FLG,
  PRODUCT_ID AS PRODUCT_ID,
  OMS_ORDER_NBR AS OMS_ORDER_NBR,
  FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  FREIGHT_REVENUE AS FREIGHT_REVENUE,
  ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  EV_RELEASED_TSTMP AS EV_RELEASED_TSTMP,
  EV_ALLOCATED_TSTMP AS EV_ALLOCATED_TSTMP,
  EV_SHIPPED_TSTMP AS EV_SHIPPED_TSTMP,
  EV_PICKEDUP_TSTMP AS EV_PICKEDUP_TSTMP,
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_ORDER_LN_ID AS OMS_ORDER_LN_ID,
  OMS_DO_CREATED_TSTMP AS OMS_DO_CREATED_TSTMP,
  ORDER_NBR AS ORDER_NBR,
  OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  ORDER_FULFILLMENT_CHANNEL AS ORDER_FULFILLMENT_CHANNEL,
  ORDER_CHANNEL AS ORDER_CHANNEL,
  SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  ADD_ON_FLAG AS ADD_ON_FLAG,
  ISPU_PXY_FIRST_NAME AS ISPU_PXY_FIRST_NAME,
  ISPU_PXY_LAST_NAME AS ISPU_PXY_LAST_NAME,
  ISPU_PXY_ADD_LINE1 AS ISPU_PXY_ADD_LINE1,
  ISPU_PXY_ADD_LINE2 AS ISPU_PXY_ADD_LINE2,
  ISPU_PXY_ADD_LINE3 AS ISPU_PXY_ADD_LINE3,
  ISPU_PXY_CITY AS ISPU_PXY_CITY,
  ISPU_PXY_STATE AS ISPU_PXY_STATE,
  ISPU_PXY_POSTAL_CD AS ISPU_PXY_POSTAL_CD,
  ISPU_PXY_COUNTRY AS ISPU_PXY_COUNTRY,
  ISPU_PXY_EMAIL AS ISPU_PXY_EMAIL,
  ISUP_PXY_PHONE AS ISUP_PXY_PHONE,
  OMS_COMPANY_ID AS OMS_COMPANY_ID,
  EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  RX_ORDER_FLG AS RX_ORDER_FLG,
  CANCEL_TSTMP AS CANCEL_TSTMP,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_OMS_DIST_ORDER_LN_8"""

df_16 = spark.sql(query_16)

df_16.createOrReplaceTempView("SQ_Shortcut_to_OMS_DIST_ORDER_LN_16")

# COMMAND ----------
# DBTITLE 1, JNR_OMS_DIST_ORDER_LN_NEW_17


query_17 = f"""SELECT
  DETAIL.OMS_DIST_ORDER_ID AS lkp_OMS_DIST_ORDER_ID,
  DETAIL.OMS_DIST_ORDER_LN_ID AS lkp_OMS_DIST_ORDER_LN_ID,
  DETAIL.TOTAL_MONETARY_VALUE_AMT AS lkp_TOTAL_MONETARY_VALUE_AMT,
  DETAIL.UNIT_MONETARY_VALUE_AMT AS lkp_UNIT_MONETARY_VALUE_AMT,
  DETAIL.UNIT_TAX_AMT AS lkp_UNIT_TAX_AMT,
  DETAIL.MV_CURRENCY_CD AS lkp_MV_CURRENCY_CD,
  DETAIL.SHIPPED_QTY AS lkp_SHIPPED_QTY,
  DETAIL.RECEIVED_QTY AS lkp_RECEIVED_QTY,
  DETAIL.CREATED_SOURCE AS lkp_CREATED_SOURCE,
  DETAIL.CREATED_TSTMP AS lkp_CREATED_TSTMP,
  DETAIL.LAST_UPDATED_TSTMP AS lkp_LAST_UPDATED_TSTMP,
  DETAIL.OMS_DIST_ORDER_LN_STATUS_ID AS lkp_OMS_DIST_ORDER_LN_STATUS_ID,
  DETAIL.ALLOCATED_QTY AS lkp_ALLOCATED_QTY,
  DETAIL.UNIT_COST_AMT AS lkp_UNIT_COST_AMT,
  DETAIL.UNIT_PRICE_AMT AS lkp_UNIT_PRICE_AMT,
  DETAIL.USER_CANCELED_QTY AS lkp_USER_CANCELED_QTY,
  DETAIL.DELIVERY_END_DT AS lkp_DELIVERY_END_DT,
  DETAIL.DELIVERY_START_DT AS lkp_DELIVERY_START_DT,
  DETAIL.EVENT_CD AS lkp_EVENT_CD,
  DETAIL.REASON_CODE AS lkp_REASON_CODE,
  DETAIL.PARTL_FILL_FLG AS lkp_PARTL_FILL_FLG,
  DETAIL.ORDER_QTY AS lkp_ORDER_QTY,
  DETAIL.ORIG_ORDER_QTY AS lkp_ORIG_ORDER_QTY,
  DETAIL.RETAIL_PRICE AS lkp_RETAIL_PRICE,
  DETAIL.OMS_DIST_ORDER_LN_NBR AS lkp_OMS_DIST_ORDER_LN_NBR,
  DETAIL.PICKUP_END_DTTM AS lkp_PICKUP_END_DTTM,
  DETAIL.OMS_ORDER_LN_NBR AS lkp_OMS_ORDER_LN_NBR,
  DETAIL.PICKUP_START_DTTM AS lkp_PICKUP_START_DTTM,
  DETAIL.CANCELLED_FLG AS lkp_CANCELLED_FLG,
  DETAIL.PRODUCT_ID AS lkp_PRODUCT_ID,
  DETAIL.OMS_ORDER_NBR AS lkp_OMS_ORDER_NBR,
  DETAIL.FREIGHT_REVENUE_CURRENCY_CD AS lkp_FREIGHT_REVENUE_CURRENCY_CD,
  DETAIL.FREIGHT_REVENUE AS lkp_FREIGHT_REVENUE,
  DETAIL.ADJUSTED_ORDER_QTY AS lkp_ADJUSTED_ORDER_QTY,
  DETAIL.EV_RELEASED_TSTMP AS lkp_EV_RELEASED_TSTMP,
  DETAIL.EV_ALLOCATED_TSTMP AS lkp_EV_ALLOCATED_TSTMP,
  DETAIL.EV_SHIPPED_TSTMP AS lkp_EV_SHIPPED_TSTMP,
  DETAIL.EV_PICKEDUP_TSTMP AS lkp_EV_PICKEDUP_TSTMP,
  DETAIL.OMS_ORDER_ID AS lkp_OMS_ORDER_ID,
  DETAIL.OMS_ORDER_LN_ID AS lkp_OMS_ORDER_LN_ID,
  DETAIL.OMS_DO_CREATED_TSTMP AS lkp_OMS_DO_CREATED_TSTMP,
  DETAIL.ORDER_NBR AS lkp_ORDER_NBR,
  DETAIL.OMS_ORDER_CREATED_TSTMP AS lkp_OMS_ORDER_CREATED_TSTMP,
  DETAIL.ORIG_LOCATION_ID AS lkp_ORIG_LOCATION_ID,
  DETAIL.ORDER_CREATION_CHANNEL AS lkp_ORDER_CREATION_CHANNEL,
  DETAIL.ORDER_FULFILLMENT_CHANNEL AS lkp_ORDER_FULFILLMENT_CHANNEL,
  DETAIL.ORDER_CHANNEL AS lkp_ORDER_CHANNEL,
  DETAIL.SCHED_DELIVERY_FLG AS lkp_SCHED_DELIVERY_FLG,
  DETAIL.SUBSCRIPTION_ORDER_FLG AS lkp_SUBSCRIPTION_ORDER_FLG,
  DETAIL.ADD_ON_FLAG AS lkp_ADD_ON_FLAG,
  DETAIL.ISPU_PXY_FIRST_NAME AS lkp_ISPU_PXY_FIRST_NAME,
  DETAIL.ISPU_PXY_LAST_NAME AS lkp_ISPU_PXY_LAST_NAME,
  DETAIL.ISPU_PXY_ADD_LINE1 AS lkp_ISPU_PXY_ADD_LINE1,
  DETAIL.ISPU_PXY_ADD_LINE2 AS lkp_ISPU_PXY_ADD_LINE2,
  DETAIL.ISPU_PXY_ADD_LINE3 AS lkp_ISPU_PXY_ADD_LINE3,
  DETAIL.ISPU_PXY_CITY AS lkp_ISPU_PXY_CITY,
  DETAIL.ISPU_PXY_STATE AS lkp_ISPU_PXY_STATE,
  DETAIL.ISPU_PXY_POSTAL_CD AS lkp_ISPU_PXY_POSTAL_CD,
  DETAIL.ISPU_PXY_COUNTRY AS lkp_ISPU_PXY_COUNTRY,
  DETAIL.ISPU_PXY_EMAIL AS lkp_ISPU_PXY_EMAIL,
  DETAIL.ISUP_PXY_PHONE AS lkp_ISUP_PXY_PHONE,
  DETAIL.OMS_COMPANY_ID AS lkp_OMS_COMPANY_ID,
  DETAIL.EXCHANGE_RATE_PCNT AS lkp_EXCHANGE_RATE_PCNT,
  DETAIL.RX_ORDER_FLG AS lkp_RX_ORDER_FLG,
  DETAIL.CANCEL_TSTMP AS lkp_CANCEL_TSTMP,
  DETAIL.LOAD_TSTMP AS lkp_LOAD_TSTMP,
  MASTER.EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  MASTER.ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  MASTER.OMS_ORDER_ID AS OMS_ORDER_ID,
  MASTER.OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  MASTER.TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  MASTER.UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  MASTER.UNIT_TAX_AMT AS UNIT_TAX_AMT,
  MASTER.MV_CURRENCY_CD AS MV_CURRENCY_CD,
  MASTER.SHIPPED_QTY AS SHIPPED_QTY,
  MASTER.RECEIVED_QTY AS RECEIVED_QTY,
  MASTER.OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  MASTER.OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  MASTER.OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  MASTER.OMS_DO_DTL_STATUS_ID AS OMS_DO_DTL_STATUS_ID,
  MASTER.ALLOCATED_QTY AS ALLOCATED_QTY,
  MASTER.UNIT_COST_AMT AS UNIT_COST_AMT,
  MASTER.UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  MASTER.USER_CANCELED_QTY AS USER_CANCELED_QTY,
  MASTER.OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  MASTER.OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  MASTER.OMS_EVENT_CD AS OMS_EVENT_CD,
  MASTER.OMS_REASON_CD AS OMS_REASON_CD,
  MASTER.PARTIAL_FILL_FLAG AS PARTIAL_FILL_FLAG,
  MASTER.ORDER_QTY AS ORDER_QTY,
  MASTER.ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  MASTER.RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  MASTER.OMS_TC_ORDER_LINE_ID AS OMS_TC_ORDER_LINE_ID,
  MASTER.OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  MASTER.OMS_PURCHASE_ORDER_LINE_NBR AS OMS_PURCHASE_ORDER_LINE_NBR,
  MASTER.OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  MASTER.CANCELLED_FLAG AS CANCELLED_FLAG,
  MASTER.OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  MASTER.FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  MASTER.FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  MASTER.ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  MASTER.EV_RELEASED_TSTMP AS EV_RELEASED_TSTMP,
  MASTER.EV_ALLOCATED_TSTMP AS EV_ALLOCATED_TSTMP,
  MASTER.EV_SHIPPED_TSTMP AS EV_SHIPPED_TSTMP,
  MASTER.EV_PICKEDUP_TSTMP AS EV_PICKEDUP_TSTMP,
  MASTER.OMS_MASTER_ORDER_ID AS OMS_MASTER_ORDER_ID,
  MASTER.OMS_MO_LINE_ITEM_ID AS OMS_MO_LINE_ITEM_ID,
  MASTER.OMS_DO_CREATED_TSTMP AS OMS_DO_CREATED_TSTMP,
  MASTER.ORDER_NBR AS ORDER_NBR,
  MASTER.OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  MASTER.OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  MASTER.O_FACILITY_TYPE_ID AS O_FACILITY_TYPE_ID,
  MASTER.ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  MASTER.ORDER_FULFILLMENT_CHANNEL AS ORDER_FULFILLMENT_CHANNEL,
  MASTER.ORDER_CHANNEL AS ORDER_CHANNEL,
  MASTER.SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  MASTER.SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  MASTER.ADD_ON_FLAG AS ADD_ON_FLAG,
  MASTER.ISPU_PXY_FIRST_NAME AS ISPU_PXY_FIRST_NAME,
  MASTER.ISPU_PXY_LAST_NAME AS ISPU_PXY_LAST_NAME,
  MASTER.ISPU_PXY_ADD_LINE1 AS ISPU_PXY_ADD_LINE1,
  MASTER.ISPU_PXY_ADD_LINE2 AS ISPU_PXY_ADD_LINE2,
  MASTER.ISPU_PXY_ADD_LINE3 AS ISPU_PXY_ADD_LINE3,
  MASTER.ISPU_PXY_CITY AS ISPU_PXY_CITY,
  MASTER.ISPU_PXY_STATE AS ISPU_PXY_STATE,
  MASTER.ISPU_PXY_POSTAL_CD AS ISPU_PXY_POSTAL_CD,
  MASTER.ISPU_PXY_COUNTRY AS ISPU_PXY_COUNTRY,
  MASTER.ISPU_PXY_EMAIL AS ISPU_PXY_EMAIL,
  MASTER.ISUP_PXY_PHONE AS ISUP_PXY_PHONE,
  MASTER.OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  MASTER.RX_ORDER_FLG AS RX_ORDER_FLG,
  MASTER.CANCEL_DTTM AS CANCEL_DTTM,
  MASTER.PRODUCT_ID AS PRODUCT_ID,
  MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  EXP_SRC_15 MASTER
  LEFT JOIN SQ_Shortcut_to_OMS_DIST_ORDER_LN_16 DETAIL ON MASTER.OMS_ORDER_ID = DETAIL.OMS_DIST_ORDER_ID
  AND MASTER.OMS_LINE_ITEM_ID = DETAIL.OMS_DIST_ORDER_LN_ID"""

df_17 = spark.sql(query_17)

df_17.createOrReplaceTempView("JNR_OMS_DIST_ORDER_LN_NEW_17")

# COMMAND ----------
# DBTITLE 1, EXP_FLAG_18


query_18 = f"""SELECT
  lkp_OMS_DIST_ORDER_ID AS lkp_OMS_DIST_ORDER_ID,
  lkp_OMS_DIST_ORDER_LN_ID AS lkp_OMS_DIST_ORDER_LN_ID,
  lkp_TOTAL_MONETARY_VALUE_AMT AS lkp_TOTAL_MONETARY_VALUE_AMT,
  lkp_UNIT_MONETARY_VALUE_AMT AS lkp_UNIT_MONETARY_VALUE_AMT,
  lkp_UNIT_TAX_AMT AS lkp_UNIT_TAX_AMT,
  lkp_MV_CURRENCY_CD AS lkp_MV_CURRENCY_CD,
  lkp_SHIPPED_QTY AS lkp_SHIPPED_QTY,
  lkp_RECEIVED_QTY AS lkp_RECEIVED_QTY,
  lkp_CREATED_SOURCE AS lkp_CREATED_SOURCE,
  lkp_CREATED_TSTMP AS lkp_CREATED_TSTMP,
  lkp_LAST_UPDATED_TSTMP AS lkp_LAST_UPDATED_TSTMP,
  lkp_OMS_DIST_ORDER_LN_STATUS_ID AS lkp_OMS_DIST_ORDER_LN_STATUS_ID,
  lkp_ALLOCATED_QTY AS lkp_ALLOCATED_QTY,
  lkp_UNIT_COST_AMT AS lkp_UNIT_COST_AMT,
  lkp_UNIT_PRICE_AMT AS lkp_UNIT_PRICE_AMT,
  lkp_USER_CANCELED_QTY AS lkp_USER_CANCELED_QTY,
  lkp_DELIVERY_END_DT AS lkp_DELIVERY_END_DT,
  lkp_DELIVERY_START_DT AS lkp_DELIVERY_START_DT,
  lkp_EVENT_CD AS lkp_EVENT_CD,
  lkp_REASON_CODE AS lkp_REASON_CODE,
  lkp_PARTL_FILL_FLG AS lkp_PARTL_FILL_FLG,
  lkp_ORDER_QTY AS lkp_ORDER_QTY,
  lkp_ORIG_ORDER_QTY AS lkp_ORIG_ORDER_QTY,
  lkp_RETAIL_PRICE AS lkp_RETAIL_PRICE,
  lkp_OMS_DIST_ORDER_LN_NBR AS lkp_OMS_DIST_ORDER_LN_NBR,
  lkp_PICKUP_END_DTTM AS lkp_PICKUP_END_DTTM,
  lkp_OMS_ORDER_LN_NBR AS lkp_OMS_ORDER_LN_NBR,
  lkp_PICKUP_START_DTTM AS lkp_PICKUP_START_DTTM,
  lkp_CANCELLED_FLG AS lkp_CANCELLED_FLG,
  lkp_PRODUCT_ID AS lkp_PRODUCT_ID,
  lkp_OMS_ORDER_NBR AS lkp_OMS_ORDER_NBR,
  lkp_FREIGHT_REVENUE_CURRENCY_CD AS lkp_FREIGHT_REVENUE_CURRENCY_CD,
  lkp_FREIGHT_REVENUE AS lkp_FREIGHT_REVENUE,
  lkp_ADJUSTED_ORDER_QTY AS lkp_ADJUSTED_ORDER_QTY,
  lkp_EV_RELEASED_TSTMP AS lkp_EV_RELEASED_TSTMP,
  lkp_EV_ALLOCATED_TSTMP AS lkp_EV_ALLOCATED_TSTMP,
  lkp_EV_SHIPPED_TSTMP AS lkp_EV_SHIPPED_TSTMP,
  lkp_EV_PICKEDUP_TSTMP AS lkp_EV_PICKEDUP_TSTMP,
  lkp_OMS_ORDER_ID AS lkp_OMS_ORDER_ID,
  lkp_OMS_ORDER_LN_ID AS lkp_OMS_ORDER_LN_ID,
  lkp_OMS_DO_CREATED_TSTMP AS lkp_OMS_DO_CREATED_TSTMP,
  lkp_ORDER_NBR AS lkp_ORDER_NBR,
  lkp_OMS_ORDER_CREATED_TSTMP AS lkp_OMS_ORDER_CREATED_TSTMP,
  lkp_ORIG_LOCATION_ID AS lkp_ORIG_LOCATION_ID,
  lkp_ORDER_CREATION_CHANNEL AS lkp_ORDER_CREATION_CHANNEL,
  lkp_ORDER_FULFILLMENT_CHANNEL AS lkp_ORDER_FULFILLMENT_CHANNEL,
  lkp_ORDER_CHANNEL AS lkp_ORDER_CHANNEL,
  lkp_SCHED_DELIVERY_FLG AS lkp_SCHED_DELIVERY_FLG,
  lkp_SUBSCRIPTION_ORDER_FLG AS lkp_SUBSCRIPTION_ORDER_FLG,
  lkp_ADD_ON_FLAG AS lkp_ADD_ON_FLAG,
  lkp_ISPU_PXY_FIRST_NAME AS lkp_ISPU_PXY_FIRST_NAME,
  lkp_ISPU_PXY_LAST_NAME AS lkp_ISPU_PXY_LAST_NAME,
  lkp_ISPU_PXY_ADD_LINE1 AS lkp_ISPU_PXY_ADD_LINE1,
  lkp_ISPU_PXY_ADD_LINE2 AS lkp_ISPU_PXY_ADD_LINE2,
  lkp_ISPU_PXY_ADD_LINE3 AS lkp_ISPU_PXY_ADD_LINE3,
  lkp_ISPU_PXY_CITY AS lkp_ISPU_PXY_CITY,
  lkp_ISPU_PXY_STATE AS lkp_ISPU_PXY_STATE,
  lkp_ISPU_PXY_POSTAL_CD AS lkp_ISPU_PXY_POSTAL_CD,
  lkp_ISPU_PXY_COUNTRY AS lkp_ISPU_PXY_COUNTRY,
  lkp_ISPU_PXY_EMAIL AS lkp_ISPU_PXY_EMAIL,
  lkp_ISUP_PXY_PHONE AS lkp_ISUP_PXY_PHONE,
  lkp_OMS_COMPANY_ID AS lkp_OMS_COMPANY_ID,
  lkp_EXCHANGE_RATE_PCNT AS lkp_EXCHANGE_RATE_PCNT,
  lkp_RX_ORDER_FLG AS lkp_RX_ORDER_FLG,
  lkp_CANCEL_TSTMP AS lkp_CANCEL_TSTMP,
  lkp_LOAD_TSTMP AS lkp_LOAD_TSTMP,
  EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  UNIT_TAX_AMT AS UNIT_TAX_AMT,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  SHIPPED_QTY AS SHIPPED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  OMS_DO_DTL_STATUS_ID AS OMS_DO_DTL_STATUS_ID,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  UNIT_COST_AMT AS UNIT_COST_AMT,
  UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  USER_CANCELED_QTY AS USER_CANCELED_QTY,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_EVENT_CD AS OMS_EVENT_CD,
  OMS_REASON_CD AS OMS_REASON_CD,
  PARTIAL_FILL_FLAG AS PARTIAL_FILL_FLAG,
  ORDER_QTY AS ORDER_QTY,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  OMS_TC_ORDER_LINE_ID AS OMS_TC_ORDER_LINE_ID,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PURCHASE_ORDER_LINE_NBR AS OMS_PURCHASE_ORDER_LINE_NBR,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  EV_RELEASED_TSTMP AS EV_RELEASED_TSTMP,
  EV_ALLOCATED_TSTMP AS EV_ALLOCATED_TSTMP,
  EV_SHIPPED_TSTMP AS EV_SHIPPED_TSTMP,
  EV_PICKEDUP_TSTMP AS EV_PICKEDUP_TSTMP,
  OMS_MASTER_ORDER_ID AS OMS_MASTER_ORDER_ID,
  OMS_MO_LINE_ITEM_ID AS OMS_MO_LINE_ITEM_ID,
  OMS_DO_CREATED_TSTMP AS OMS_DO_CREATED_TSTMP,
  ORDER_NBR AS ORDER_NBR,
  OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  O_FACILITY_TYPE_ID AS O_FACILITY_TYPE_ID,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  ORDER_FULFILLMENT_CHANNEL AS ORDER_FULFILLMENT_CHANNEL,
  ORDER_CHANNEL AS ORDER_CHANNEL,
  SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  ADD_ON_FLAG AS ADD_ON_FLAG,
  ISPU_PXY_FIRST_NAME AS ISPU_PXY_FIRST_NAME,
  ISPU_PXY_LAST_NAME AS ISPU_PXY_LAST_NAME,
  ISPU_PXY_ADD_LINE1 AS ISPU_PXY_ADD_LINE1,
  ISPU_PXY_ADD_LINE2 AS ISPU_PXY_ADD_LINE2,
  ISPU_PXY_ADD_LINE3 AS ISPU_PXY_ADD_LINE3,
  ISPU_PXY_CITY AS ISPU_PXY_CITY,
  ISPU_PXY_STATE AS ISPU_PXY_STATE,
  ISPU_PXY_POSTAL_CD AS ISPU_PXY_POSTAL_CD,
  ISPU_PXY_COUNTRY AS ISPU_PXY_COUNTRY,
  ISPU_PXY_EMAIL AS ISPU_PXY_EMAIL,
  ISUP_PXY_PHONE AS ISUP_PXY_PHONE,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  RX_ORDER_FLG AS RX_ORDER_FLG,
  CANCEL_DTTM AS CANCEL_DTTM,
  PRODUCT_ID AS PRODUCT_ID,
  IFF(ISNULL(lkp_LOAD_TSTMP), now(), lkp_LOAD_TSTMP) AS LOAD_TSTMP,
  now() AS UPDATE_TSTMP,
  IFF(
    (
      ISNULL(lkp_OMS_DIST_ORDER_ID)
      AND ISNULL(lkp_OMS_DIST_ORDER_LN_ID)
    ),
    'INSERT',
    IFF(
      (
        (
          NOT ISNULL(lkp_OMS_DIST_ORDER_ID)
          AND NOT ISNULL(lkp_OMS_DIST_ORDER_LN_ID)
        )
        AND (
          lkp_TOTAL_MONETARY_VALUE_AMT != TOTAL_MONETARY_VALUE
          OR lkp_UNIT_MONETARY_VALUE_AMT != UNIT_MONETARY_VALUE
          OR lkp_UNIT_TAX_AMT != UNIT_TAX_AMT
          OR lkp_MV_CURRENCY_CD != MV_CURRENCY_CD
          OR lkp_SHIPPED_QTY != SHIPPED_QTY
          OR lkp_RECEIVED_QTY != RECEIVED_QTY
          OR lkp_CREATED_SOURCE != OMS_CREATED_SOURCE
          OR lkp_CREATED_TSTMP != OMS_CREATED_TSTMP
          OR lkp_LAST_UPDATED_TSTMP != OMS_LAST_UPDATED_TSTMP
          OR lkp_OMS_DIST_ORDER_LN_STATUS_ID != OMS_DO_DTL_STATUS_ID
          OR lkp_ALLOCATED_QTY != ALLOCATED_QTY
          OR lkp_UNIT_COST_AMT != UNIT_COST_AMT
          OR lkp_UNIT_PRICE_AMT != UNIT_PRICE_AMT
          OR lkp_USER_CANCELED_QTY != USER_CANCELED_QTY
          OR lkp_DELIVERY_END_DT != OMS_DELIVERY_END_TSTMP
          OR lkp_DELIVERY_START_DT != OMS_DELIVERY_START_TSTMP
          OR lkp_EVENT_CD != OMS_EVENT_CD
          OR lkp_REASON_CODE != OMS_REASON_CD
          OR lkp_PARTL_FILL_FLG != PARTIAL_FILL_FLAG
          OR lkp_ORDER_QTY != ORDER_QTY
          OR lkp_ORIG_ORDER_QTY != ORIG_ORDER_QTY
          OR lkp_RETAIL_PRICE != RETAIL_PRICE_AMT
          OR lkp_OMS_DIST_ORDER_LN_NBR != OMS_TC_ORDER_LINE_ID
          OR lkp_PICKUP_END_DTTM != OMS_PICKUP_END_TSTMP
          OR lkp_OMS_ORDER_LN_NBR != OMS_PURCHASE_ORDER_LINE_NBR
          OR lkp_PICKUP_START_DTTM != OMS_PICKUP_START_TSTMP
          OR lkp_CANCELLED_FLG != CANCELLED_FLAG
          OR lkp_PRODUCT_ID != PRODUCT_ID
          OR lkp_OMS_ORDER_NBR != OMS_TC_PURCHASE_ORDERS_ID
          OR lkp_FREIGHT_REVENUE_CURRENCY_CD != FREIGHT_REVENUE_CURRENCY_CD
          OR lkp_FREIGHT_REVENUE != FREIGHT_REVENUE_AMT
          OR lkp_ADJUSTED_ORDER_QTY != ADJUSTED_ORDER_QTY
          OR lkp_EV_RELEASED_TSTMP != EV_RELEASED_TSTMP
          OR lkp_EV_ALLOCATED_TSTMP != EV_ALLOCATED_TSTMP
          OR lkp_EV_SHIPPED_TSTMP != EV_SHIPPED_TSTMP
          OR lkp_EV_PICKEDUP_TSTMP != EV_PICKEDUP_TSTMP
          OR lkp_OMS_ORDER_ID != OMS_MASTER_ORDER_ID
          OR lkp_OMS_ORDER_LN_ID != OMS_MO_LINE_ITEM_ID
          OR lkp_OMS_DO_CREATED_TSTMP != OMS_DO_CREATED_TSTMP
          OR lkp_ORDER_NBR != ORDER_NBR
          OR lkp_OMS_ORDER_CREATED_TSTMP != OMS_ORDER_CREATED_TSTMP
          OR lkp_ORIG_LOCATION_ID != ORIG_LOCATION_ID
          OR lkp_ORDER_CREATION_CHANNEL != ORDER_CREATION_CHANNEL
          OR lkp_ORDER_FULFILLMENT_CHANNEL != ORDER_FULFILLMENT_CHANNEL
          OR lkp_ORDER_CHANNEL != ORDER_CHANNEL
          OR lkp_SCHED_DELIVERY_FLG != SCHED_DELIVERY_FLG
          OR lkp_SUBSCRIPTION_ORDER_FLG != SUBSCRIPTION_ORDER_FLG
          OR lkp_ADD_ON_FLAG != ADD_ON_FLAG
          OR lkp_ISPU_PXY_FIRST_NAME != ISPU_PXY_FIRST_NAME
          OR lkp_ISPU_PXY_LAST_NAME != ISPU_PXY_LAST_NAME
          OR lkp_ISPU_PXY_ADD_LINE1 != ISPU_PXY_ADD_LINE1
          OR lkp_ISPU_PXY_ADD_LINE2 != ISPU_PXY_ADD_LINE2
          OR lkp_ISPU_PXY_ADD_LINE3 != ISPU_PXY_ADD_LINE3
          OR lkp_ISPU_PXY_CITY != ISPU_PXY_CITY
          OR lkp_ISPU_PXY_STATE != ISPU_PXY_STATE
          OR lkp_ISPU_PXY_POSTAL_CD != ISPU_PXY_POSTAL_CD
          OR lkp_ISPU_PXY_COUNTRY != ISPU_PXY_COUNTRY
          OR lkp_ISPU_PXY_EMAIL != ISPU_PXY_EMAIL
          OR lkp_ISUP_PXY_PHONE != ISUP_PXY_PHONE
          OR lkp_OMS_COMPANY_ID != OMS_TC_COMPANY_ID
          OR lkp_EXCHANGE_RATE_PCNT != EXCHANGE_RATE_PCNT
          OR lkp_RX_ORDER_FLG != RX_ORDER_FLG
          OR lkp_CANCEL_TSTMP != CANCEL_DTTM
        )
      ),
      'UPDATE',
      'REJECT'
    )
  ) AS UPD_INS_FLG,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  JNR_OMS_DIST_ORDER_LN_NEW_17"""

df_18 = spark.sql(query_18)

df_18.createOrReplaceTempView("EXP_FLAG_18")

# COMMAND ----------
# DBTITLE 1, FIL_changed_rec_19


query_19 = f"""SELECT
  UPD_INS_FLG AS UPD_INS_FLG,
  EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  UNIT_TAX_AMT AS UNIT_TAX_AMT,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  SHIPPED_QTY AS SHIPPED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  OMS_DO_DTL_STATUS_ID AS OMS_DO_DTL_STATUS_ID,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  UNIT_COST_AMT AS UNIT_COST_AMT,
  UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  USER_CANCELED_QTY AS USER_CANCELED_QTY,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_EVENT_CD AS OMS_EVENT_CD,
  OMS_REASON_CD AS OMS_REASON_CD,
  PARTIAL_FILL_FLAG AS PARTIAL_FILL_FLAG,
  ORDER_QTY AS ORDER_QTY,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  OMS_TC_ORDER_LINE_ID AS OMS_TC_ORDER_LINE_ID,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PURCHASE_ORDER_LINE_NBR AS OMS_PURCHASE_ORDER_LINE_NBR,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  EV_RELEASED_TSTMP AS EV_RELEASED_TSTMP,
  EV_ALLOCATED_TSTMP AS EV_ALLOCATED_TSTMP,
  EV_SHIPPED_TSTMP AS EV_SHIPPED_TSTMP,
  EV_PICKEDUP_TSTMP AS EV_PICKEDUP_TSTMP,
  OMS_MASTER_ORDER_ID AS OMS_MASTER_ORDER_ID,
  OMS_MO_LINE_ITEM_ID AS OMS_MO_LINE_ITEM_ID,
  OMS_DO_CREATED_TSTMP AS OMS_DO_CREATED_TSTMP,
  ORDER_NBR AS ORDER_NBR,
  OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  O_FACILITY_TYPE_ID AS O_FACILITY_TYPE_ID,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  ORDER_FULFILLMENT_CHANNEL AS ORDER_FULFILLMENT_CHANNEL,
  ORDER_CHANNEL AS ORDER_CHANNEL,
  SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  ADD_ON_FLAG AS ADD_ON_FLAG,
  ISPU_PXY_FIRST_NAME AS ISPU_PXY_FIRST_NAME,
  ISPU_PXY_LAST_NAME AS ISPU_PXY_LAST_NAME,
  ISPU_PXY_ADD_LINE1 AS ISPU_PXY_ADD_LINE1,
  ISPU_PXY_ADD_LINE2 AS ISPU_PXY_ADD_LINE2,
  ISPU_PXY_ADD_LINE3 AS ISPU_PXY_ADD_LINE3,
  ISPU_PXY_CITY AS ISPU_PXY_CITY,
  ISPU_PXY_STATE AS ISPU_PXY_STATE,
  ISPU_PXY_POSTAL_CD AS ISPU_PXY_POSTAL_CD,
  ISPU_PXY_COUNTRY AS ISPU_PXY_COUNTRY,
  ISPU_PXY_EMAIL AS ISPU_PXY_EMAIL,
  ISUP_PXY_PHONE AS ISUP_PXY_PHONE,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  RX_ORDER_FLG AS RX_ORDER_FLG,
  CANCEL_DTTM AS CANCEL_DTTM,
  PRODUCT_ID AS PRODUCT_ID,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  EXP_FLAG_18
WHERE
  IN(UPD_INS_FLG, 'INSERT', 'UPDATE')"""

df_19 = spark.sql(query_19)

df_19.createOrReplaceTempView("FIL_changed_rec_19")

# COMMAND ----------
# DBTITLE 1, UPD_INS_UPD_20


query_20 = f"""SELECT
  UPD_INS_FLG AS UPD_INS_FLG,
  EXCHANGE_RATE_PCNT AS EXCHANGE_RATE_PCNT,
  ORIG_LOCATION_ID AS ORIG_LOCATION_ID,
  OMS_ORDER_ID AS OMS_ORDER_ID,
  OMS_LINE_ITEM_ID AS OMS_LINE_ITEM_ID,
  TOTAL_MONETARY_VALUE AS TOTAL_MONETARY_VALUE,
  UNIT_MONETARY_VALUE AS UNIT_MONETARY_VALUE,
  UNIT_TAX_AMT AS UNIT_TAX_AMT,
  MV_CURRENCY_CD AS MV_CURRENCY_CD,
  SHIPPED_QTY AS SHIPPED_QTY,
  RECEIVED_QTY AS RECEIVED_QTY,
  OMS_CREATED_SOURCE AS OMS_CREATED_SOURCE,
  OMS_CREATED_TSTMP AS OMS_CREATED_TSTMP,
  OMS_LAST_UPDATED_TSTMP AS OMS_LAST_UPDATED_TSTMP,
  OMS_DO_DTL_STATUS_ID AS OMS_DO_DTL_STATUS_ID,
  ALLOCATED_QTY AS ALLOCATED_QTY,
  UNIT_COST_AMT AS UNIT_COST_AMT,
  UNIT_PRICE_AMT AS UNIT_PRICE_AMT,
  USER_CANCELED_QTY AS USER_CANCELED_QTY,
  OMS_DELIVERY_END_TSTMP AS OMS_DELIVERY_END_TSTMP,
  OMS_DELIVERY_START_TSTMP AS OMS_DELIVERY_START_TSTMP,
  OMS_EVENT_CD AS OMS_EVENT_CD,
  OMS_REASON_CD AS OMS_REASON_CD,
  PARTIAL_FILL_FLAG AS PARTIAL_FILL_FLAG,
  ORDER_QTY AS ORDER_QTY,
  ORIG_ORDER_QTY AS ORIG_ORDER_QTY,
  RETAIL_PRICE_AMT AS RETAIL_PRICE_AMT,
  OMS_TC_ORDER_LINE_ID AS OMS_TC_ORDER_LINE_ID,
  OMS_PICKUP_END_TSTMP AS OMS_PICKUP_END_TSTMP,
  OMS_PURCHASE_ORDER_LINE_NBR AS OMS_PURCHASE_ORDER_LINE_NBR,
  OMS_PICKUP_START_TSTMP AS OMS_PICKUP_START_TSTMP,
  CANCELLED_FLAG AS CANCELLED_FLAG,
  OMS_TC_PURCHASE_ORDERS_ID AS OMS_TC_PURCHASE_ORDERS_ID,
  FREIGHT_REVENUE_CURRENCY_CD AS FREIGHT_REVENUE_CURRENCY_CD,
  FREIGHT_REVENUE_AMT AS FREIGHT_REVENUE_AMT,
  ADJUSTED_ORDER_QTY AS ADJUSTED_ORDER_QTY,
  EV_RELEASED_TSTMP AS EV_RELEASED_TSTMP,
  EV_ALLOCATED_TSTMP AS EV_ALLOCATED_TSTMP,
  EV_SHIPPED_TSTMP AS EV_SHIPPED_TSTMP,
  EV_PICKEDUP_TSTMP AS EV_PICKEDUP_TSTMP,
  OMS_MASTER_ORDER_ID AS OMS_MASTER_ORDER_ID,
  OMS_MO_LINE_ITEM_ID AS OMS_MO_LINE_ITEM_ID,
  OMS_DO_CREATED_TSTMP AS OMS_DO_CREATED_TSTMP,
  ORDER_NBR AS ORDER_NBR,
  OMS_ORDER_CREATED_TSTMP AS OMS_ORDER_CREATED_TSTMP,
  OMS_O_FACILITY_ALIAS_ID AS OMS_O_FACILITY_ALIAS_ID,
  O_FACILITY_TYPE_ID AS O_FACILITY_TYPE_ID,
  ORDER_CREATION_CHANNEL AS ORDER_CREATION_CHANNEL,
  ORDER_FULFILLMENT_CHANNEL AS ORDER_FULFILLMENT_CHANNEL,
  ORDER_CHANNEL AS ORDER_CHANNEL,
  SCHED_DELIVERY_FLG AS SCHED_DELIVERY_FLG,
  SUBSCRIPTION_ORDER_FLG AS SUBSCRIPTION_ORDER_FLG,
  ADD_ON_FLAG AS ADD_ON_FLAG,
  ISPU_PXY_FIRST_NAME AS ISPU_PXY_FIRST_NAME,
  ISPU_PXY_LAST_NAME AS ISPU_PXY_LAST_NAME,
  ISPU_PXY_ADD_LINE1 AS ISPU_PXY_ADD_LINE1,
  ISPU_PXY_ADD_LINE2 AS ISPU_PXY_ADD_LINE2,
  ISPU_PXY_ADD_LINE3 AS ISPU_PXY_ADD_LINE3,
  ISPU_PXY_CITY AS ISPU_PXY_CITY,
  ISPU_PXY_STATE AS ISPU_PXY_STATE,
  ISPU_PXY_POSTAL_CD AS ISPU_PXY_POSTAL_CD,
  ISPU_PXY_COUNTRY AS ISPU_PXY_COUNTRY,
  ISPU_PXY_EMAIL AS ISPU_PXY_EMAIL,
  ISUP_PXY_PHONE AS ISUP_PXY_PHONE,
  OMS_TC_COMPANY_ID AS OMS_TC_COMPANY_ID,
  RX_ORDER_FLG AS RX_ORDER_FLG,
  CANCEL_DTTM AS CANCEL_DTTM,
  PRODUCT_ID AS PRODUCT_ID,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id,
  DECODE(
    UPD_INS_FLG,
    'INSERT',
    'DD_INSERT',
    'UPDATE',
    'DD_UPDATE',
    'DD_REJECT'
  ) AS UPDATE_STRATEGY_FLAG
FROM
  FIL_changed_rec_19"""

df_20 = spark.sql(query_20)

df_20.createOrReplaceTempView("UPD_INS_UPD_20")

# COMMAND ----------
# DBTITLE 1, OMS_DIST_ORDER_LN


spark.sql("""MERGE INTO OMS_DIST_ORDER_LN AS TARGET
USING
  UPD_INS_UPD_20 AS SOURCE ON TARGET.OMS_DIST_ORDER_LN_ID = SOURCE.OMS_LINE_ITEM_ID
  AND TARGET.OMS_DIST_ORDER_ID = SOURCE.OMS_ORDER_ID
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_UPDATE" THEN
UPDATE
SET
  TARGET.OMS_DIST_ORDER_ID = SOURCE.OMS_ORDER_ID,
  TARGET.OMS_DIST_ORDER_LN_ID = SOURCE.OMS_LINE_ITEM_ID,
  TARGET.TOTAL_MONETARY_VALUE_AMT = SOURCE.TOTAL_MONETARY_VALUE,
  TARGET.UNIT_MONETARY_VALUE_AMT = SOURCE.UNIT_MONETARY_VALUE,
  TARGET.UNIT_TAX_AMT = SOURCE.UNIT_TAX_AMT,
  TARGET.MV_CURRENCY_CD = SOURCE.MV_CURRENCY_CD,
  TARGET.SHIPPED_QTY = SOURCE.SHIPPED_QTY,
  TARGET.RECEIVED_QTY = SOURCE.RECEIVED_QTY,
  TARGET.CREATED_SOURCE = SOURCE.OMS_CREATED_SOURCE,
  TARGET.CREATED_TSTMP = SOURCE.OMS_CREATED_TSTMP,
  TARGET.LAST_UPDATED_TSTMP = SOURCE.OMS_LAST_UPDATED_TSTMP,
  TARGET.OMS_DIST_ORDER_LN_STATUS_ID = SOURCE.OMS_DO_DTL_STATUS_ID,
  TARGET.ALLOCATED_QTY = SOURCE.ALLOCATED_QTY,
  TARGET.UNIT_COST_AMT = SOURCE.UNIT_COST_AMT,
  TARGET.UNIT_PRICE_AMT = SOURCE.UNIT_PRICE_AMT,
  TARGET.USER_CANCELED_QTY = SOURCE.USER_CANCELED_QTY,
  TARGET.DELIVERY_END_DT = SOURCE.OMS_DELIVERY_END_TSTMP,
  TARGET.DELIVERY_START_DT = SOURCE.OMS_DELIVERY_START_TSTMP,
  TARGET.EVENT_CD = SOURCE.OMS_EVENT_CD,
  TARGET.REASON_CODE = SOURCE.OMS_REASON_CD,
  TARGET.PARTL_FILL_FLG = SOURCE.PARTIAL_FILL_FLAG,
  TARGET.ORDER_QTY = SOURCE.ORDER_QTY,
  TARGET.ORIG_ORDER_QTY = SOURCE.ORIG_ORDER_QTY,
  TARGET.RETAIL_PRICE = SOURCE.RETAIL_PRICE_AMT,
  TARGET.OMS_DIST_ORDER_LN_NBR = SOURCE.OMS_TC_ORDER_LINE_ID,
  TARGET.PICKUP_END_DTTM = SOURCE.OMS_PICKUP_END_TSTMP,
  TARGET.OMS_ORDER_LN_NBR = SOURCE.OMS_PURCHASE_ORDER_LINE_NBR,
  TARGET.PICKUP_START_DTTM = SOURCE.OMS_PICKUP_START_TSTMP,
  TARGET.CANCELLED_FLG = SOURCE.CANCELLED_FLAG,
  TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID,
  TARGET.OMS_ORDER_NBR = SOURCE.OMS_TC_PURCHASE_ORDERS_ID,
  TARGET.FREIGHT_REVENUE_CURRENCY_CD = SOURCE.FREIGHT_REVENUE_CURRENCY_CD,
  TARGET.FREIGHT_REVENUE = SOURCE.FREIGHT_REVENUE_AMT,
  TARGET.ADJUSTED_ORDER_QTY = SOURCE.ADJUSTED_ORDER_QTY,
  TARGET.EV_RELEASED_TSTMP = SOURCE.EV_RELEASED_TSTMP,
  TARGET.EV_ALLOCATED_TSTMP = SOURCE.EV_ALLOCATED_TSTMP,
  TARGET.EV_SHIPPED_TSTMP = SOURCE.EV_SHIPPED_TSTMP,
  TARGET.EV_PICKEDUP_TSTMP = SOURCE.EV_PICKEDUP_TSTMP,
  TARGET.OMS_ORDER_ID = SOURCE.OMS_MASTER_ORDER_ID,
  TARGET.OMS_ORDER_LN_ID = SOURCE.OMS_MO_LINE_ITEM_ID,
  TARGET.OMS_DO_CREATED_TSTMP = SOURCE.OMS_DO_CREATED_TSTMP,
  TARGET.ORDER_NBR = SOURCE.ORDER_NBR,
  TARGET.OMS_ORDER_CREATED_TSTMP = SOURCE.OMS_ORDER_CREATED_TSTMP,
  TARGET.ORIG_LOCATION_ID = SOURCE.ORIG_LOCATION_ID,
  TARGET.ORDER_CREATION_CHANNEL = SOURCE.ORDER_CREATION_CHANNEL,
  TARGET.ORDER_FULFILLMENT_CHANNEL = SOURCE.ORDER_FULFILLMENT_CHANNEL,
  TARGET.ORDER_CHANNEL = SOURCE.ORDER_CHANNEL,
  TARGET.SCHED_DELIVERY_FLG = SOURCE.SCHED_DELIVERY_FLG,
  TARGET.SUBSCRIPTION_ORDER_FLG = SOURCE.SUBSCRIPTION_ORDER_FLG,
  TARGET.ADD_ON_FLAG = SOURCE.ADD_ON_FLAG,
  TARGET.ISPU_PXY_FIRST_NAME = SOURCE.ISPU_PXY_FIRST_NAME,
  TARGET.ISPU_PXY_LAST_NAME = SOURCE.ISPU_PXY_LAST_NAME,
  TARGET.ISPU_PXY_ADD_LINE1 = SOURCE.ISPU_PXY_ADD_LINE1,
  TARGET.ISPU_PXY_ADD_LINE2 = SOURCE.ISPU_PXY_ADD_LINE2,
  TARGET.ISPU_PXY_ADD_LINE3 = SOURCE.ISPU_PXY_ADD_LINE3,
  TARGET.ISPU_PXY_CITY = SOURCE.ISPU_PXY_CITY,
  TARGET.ISPU_PXY_STATE = SOURCE.ISPU_PXY_STATE,
  TARGET.ISPU_PXY_POSTAL_CD = SOURCE.ISPU_PXY_POSTAL_CD,
  TARGET.ISPU_PXY_COUNTRY = SOURCE.ISPU_PXY_COUNTRY,
  TARGET.ISPU_PXY_EMAIL = SOURCE.ISPU_PXY_EMAIL,
  TARGET.ISUP_PXY_PHONE = SOURCE.ISUP_PXY_PHONE,
  TARGET.OMS_COMPANY_ID = SOURCE.OMS_TC_COMPANY_ID,
  TARGET.EXCHANGE_RATE_PCNT = SOURCE.EXCHANGE_RATE_PCNT,
  TARGET.RX_ORDER_FLG = SOURCE.RX_ORDER_FLG,
  TARGET.CANCEL_TSTMP = SOURCE.CANCEL_DTTM,
  TARGET.UPDATE_TSTMP = SOURCE.UPDATE_TSTMP,
  TARGET.LOAD_TSTMP = SOURCE.LOAD_TSTMP
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_DELETE"
  AND TARGET.TOTAL_MONETARY_VALUE_AMT = SOURCE.TOTAL_MONETARY_VALUE
  AND TARGET.UNIT_MONETARY_VALUE_AMT = SOURCE.UNIT_MONETARY_VALUE
  AND TARGET.UNIT_TAX_AMT = SOURCE.UNIT_TAX_AMT
  AND TARGET.MV_CURRENCY_CD = SOURCE.MV_CURRENCY_CD
  AND TARGET.SHIPPED_QTY = SOURCE.SHIPPED_QTY
  AND TARGET.RECEIVED_QTY = SOURCE.RECEIVED_QTY
  AND TARGET.CREATED_SOURCE = SOURCE.OMS_CREATED_SOURCE
  AND TARGET.CREATED_TSTMP = SOURCE.OMS_CREATED_TSTMP
  AND TARGET.LAST_UPDATED_TSTMP = SOURCE.OMS_LAST_UPDATED_TSTMP
  AND TARGET.OMS_DIST_ORDER_LN_STATUS_ID = SOURCE.OMS_DO_DTL_STATUS_ID
  AND TARGET.ALLOCATED_QTY = SOURCE.ALLOCATED_QTY
  AND TARGET.UNIT_COST_AMT = SOURCE.UNIT_COST_AMT
  AND TARGET.UNIT_PRICE_AMT = SOURCE.UNIT_PRICE_AMT
  AND TARGET.USER_CANCELED_QTY = SOURCE.USER_CANCELED_QTY
  AND TARGET.DELIVERY_END_DT = SOURCE.OMS_DELIVERY_END_TSTMP
  AND TARGET.DELIVERY_START_DT = SOURCE.OMS_DELIVERY_START_TSTMP
  AND TARGET.EVENT_CD = SOURCE.OMS_EVENT_CD
  AND TARGET.REASON_CODE = SOURCE.OMS_REASON_CD
  AND TARGET.PARTL_FILL_FLG = SOURCE.PARTIAL_FILL_FLAG
  AND TARGET.ORDER_QTY = SOURCE.ORDER_QTY
  AND TARGET.ORIG_ORDER_QTY = SOURCE.ORIG_ORDER_QTY
  AND TARGET.RETAIL_PRICE = SOURCE.RETAIL_PRICE_AMT
  AND TARGET.OMS_DIST_ORDER_LN_NBR = SOURCE.OMS_TC_ORDER_LINE_ID
  AND TARGET.PICKUP_END_DTTM = SOURCE.OMS_PICKUP_END_TSTMP
  AND TARGET.OMS_ORDER_LN_NBR = SOURCE.OMS_PURCHASE_ORDER_LINE_NBR
  AND TARGET.PICKUP_START_DTTM = SOURCE.OMS_PICKUP_START_TSTMP
  AND TARGET.CANCELLED_FLG = SOURCE.CANCELLED_FLAG
  AND TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID
  AND TARGET.OMS_ORDER_NBR = SOURCE.OMS_TC_PURCHASE_ORDERS_ID
  AND TARGET.FREIGHT_REVENUE_CURRENCY_CD = SOURCE.FREIGHT_REVENUE_CURRENCY_CD
  AND TARGET.FREIGHT_REVENUE = SOURCE.FREIGHT_REVENUE_AMT
  AND TARGET.ADJUSTED_ORDER_QTY = SOURCE.ADJUSTED_ORDER_QTY
  AND TARGET.EV_RELEASED_TSTMP = SOURCE.EV_RELEASED_TSTMP
  AND TARGET.EV_ALLOCATED_TSTMP = SOURCE.EV_ALLOCATED_TSTMP
  AND TARGET.EV_SHIPPED_TSTMP = SOURCE.EV_SHIPPED_TSTMP
  AND TARGET.EV_PICKEDUP_TSTMP = SOURCE.EV_PICKEDUP_TSTMP
  AND TARGET.OMS_ORDER_ID = SOURCE.OMS_MASTER_ORDER_ID
  AND TARGET.OMS_ORDER_LN_ID = SOURCE.OMS_MO_LINE_ITEM_ID
  AND TARGET.OMS_DO_CREATED_TSTMP = SOURCE.OMS_DO_CREATED_TSTMP
  AND TARGET.ORDER_NBR = SOURCE.ORDER_NBR
  AND TARGET.OMS_ORDER_CREATED_TSTMP = SOURCE.OMS_ORDER_CREATED_TSTMP
  AND TARGET.ORIG_LOCATION_ID = SOURCE.ORIG_LOCATION_ID
  AND TARGET.ORDER_CREATION_CHANNEL = SOURCE.ORDER_CREATION_CHANNEL
  AND TARGET.ORDER_FULFILLMENT_CHANNEL = SOURCE.ORDER_FULFILLMENT_CHANNEL
  AND TARGET.ORDER_CHANNEL = SOURCE.ORDER_CHANNEL
  AND TARGET.SCHED_DELIVERY_FLG = SOURCE.SCHED_DELIVERY_FLG
  AND TARGET.SUBSCRIPTION_ORDER_FLG = SOURCE.SUBSCRIPTION_ORDER_FLG
  AND TARGET.ADD_ON_FLAG = SOURCE.ADD_ON_FLAG
  AND TARGET.ISPU_PXY_FIRST_NAME = SOURCE.ISPU_PXY_FIRST_NAME
  AND TARGET.ISPU_PXY_LAST_NAME = SOURCE.ISPU_PXY_LAST_NAME
  AND TARGET.ISPU_PXY_ADD_LINE1 = SOURCE.ISPU_PXY_ADD_LINE1
  AND TARGET.ISPU_PXY_ADD_LINE2 = SOURCE.ISPU_PXY_ADD_LINE2
  AND TARGET.ISPU_PXY_ADD_LINE3 = SOURCE.ISPU_PXY_ADD_LINE3
  AND TARGET.ISPU_PXY_CITY = SOURCE.ISPU_PXY_CITY
  AND TARGET.ISPU_PXY_STATE = SOURCE.ISPU_PXY_STATE
  AND TARGET.ISPU_PXY_POSTAL_CD = SOURCE.ISPU_PXY_POSTAL_CD
  AND TARGET.ISPU_PXY_COUNTRY = SOURCE.ISPU_PXY_COUNTRY
  AND TARGET.ISPU_PXY_EMAIL = SOURCE.ISPU_PXY_EMAIL
  AND TARGET.ISUP_PXY_PHONE = SOURCE.ISUP_PXY_PHONE
  AND TARGET.OMS_COMPANY_ID = SOURCE.OMS_TC_COMPANY_ID
  AND TARGET.EXCHANGE_RATE_PCNT = SOURCE.EXCHANGE_RATE_PCNT
  AND TARGET.RX_ORDER_FLG = SOURCE.RX_ORDER_FLG
  AND TARGET.CANCEL_TSTMP = SOURCE.CANCEL_DTTM
  AND TARGET.UPDATE_TSTMP = SOURCE.UPDATE_TSTMP
  AND TARGET.LOAD_TSTMP = SOURCE.LOAD_TSTMP THEN DELETE
  WHEN NOT MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_INSERT" THEN
INSERT
  (
    TARGET.OMS_DIST_ORDER_ID,
    TARGET.OMS_DIST_ORDER_LN_ID,
    TARGET.TOTAL_MONETARY_VALUE_AMT,
    TARGET.UNIT_MONETARY_VALUE_AMT,
    TARGET.UNIT_TAX_AMT,
    TARGET.MV_CURRENCY_CD,
    TARGET.SHIPPED_QTY,
    TARGET.RECEIVED_QTY,
    TARGET.CREATED_SOURCE,
    TARGET.CREATED_TSTMP,
    TARGET.LAST_UPDATED_TSTMP,
    TARGET.OMS_DIST_ORDER_LN_STATUS_ID,
    TARGET.ALLOCATED_QTY,
    TARGET.UNIT_COST_AMT,
    TARGET.UNIT_PRICE_AMT,
    TARGET.USER_CANCELED_QTY,
    TARGET.DELIVERY_END_DT,
    TARGET.DELIVERY_START_DT,
    TARGET.EVENT_CD,
    TARGET.REASON_CODE,
    TARGET.PARTL_FILL_FLG,
    TARGET.ORDER_QTY,
    TARGET.ORIG_ORDER_QTY,
    TARGET.RETAIL_PRICE,
    TARGET.OMS_DIST_ORDER_LN_NBR,
    TARGET.PICKUP_END_DTTM,
    TARGET.OMS_ORDER_LN_NBR,
    TARGET.PICKUP_START_DTTM,
    TARGET.CANCELLED_FLG,
    TARGET.PRODUCT_ID,
    TARGET.OMS_ORDER_NBR,
    TARGET.FREIGHT_REVENUE_CURRENCY_CD,
    TARGET.FREIGHT_REVENUE,
    TARGET.ADJUSTED_ORDER_QTY,
    TARGET.EV_RELEASED_TSTMP,
    TARGET.EV_ALLOCATED_TSTMP,
    TARGET.EV_SHIPPED_TSTMP,
    TARGET.EV_PICKEDUP_TSTMP,
    TARGET.OMS_ORDER_ID,
    TARGET.OMS_ORDER_LN_ID,
    TARGET.OMS_DO_CREATED_TSTMP,
    TARGET.ORDER_NBR,
    TARGET.OMS_ORDER_CREATED_TSTMP,
    TARGET.ORIG_LOCATION_ID,
    TARGET.ORDER_CREATION_CHANNEL,
    TARGET.ORDER_FULFILLMENT_CHANNEL,
    TARGET.ORDER_CHANNEL,
    TARGET.SCHED_DELIVERY_FLG,
    TARGET.SUBSCRIPTION_ORDER_FLG,
    TARGET.ADD_ON_FLAG,
    TARGET.ISPU_PXY_FIRST_NAME,
    TARGET.ISPU_PXY_LAST_NAME,
    TARGET.ISPU_PXY_ADD_LINE1,
    TARGET.ISPU_PXY_ADD_LINE2,
    TARGET.ISPU_PXY_ADD_LINE3,
    TARGET.ISPU_PXY_CITY,
    TARGET.ISPU_PXY_STATE,
    TARGET.ISPU_PXY_POSTAL_CD,
    TARGET.ISPU_PXY_COUNTRY,
    TARGET.ISPU_PXY_EMAIL,
    TARGET.ISUP_PXY_PHONE,
    TARGET.OMS_COMPANY_ID,
    TARGET.EXCHANGE_RATE_PCNT,
    TARGET.RX_ORDER_FLG,
    TARGET.CANCEL_TSTMP,
    TARGET.UPDATE_TSTMP,
    TARGET.LOAD_TSTMP
  )
VALUES
  (
    SOURCE.OMS_ORDER_ID,
    SOURCE.OMS_LINE_ITEM_ID,
    SOURCE.TOTAL_MONETARY_VALUE,
    SOURCE.UNIT_MONETARY_VALUE,
    SOURCE.UNIT_TAX_AMT,
    SOURCE.MV_CURRENCY_CD,
    SOURCE.SHIPPED_QTY,
    SOURCE.RECEIVED_QTY,
    SOURCE.OMS_CREATED_SOURCE,
    SOURCE.OMS_CREATED_TSTMP,
    SOURCE.OMS_LAST_UPDATED_TSTMP,
    SOURCE.OMS_DO_DTL_STATUS_ID,
    SOURCE.ALLOCATED_QTY,
    SOURCE.UNIT_COST_AMT,
    SOURCE.UNIT_PRICE_AMT,
    SOURCE.USER_CANCELED_QTY,
    SOURCE.OMS_DELIVERY_END_TSTMP,
    SOURCE.OMS_DELIVERY_START_TSTMP,
    SOURCE.OMS_EVENT_CD,
    SOURCE.OMS_REASON_CD,
    SOURCE.PARTIAL_FILL_FLAG,
    SOURCE.ORDER_QTY,
    SOURCE.ORIG_ORDER_QTY,
    SOURCE.RETAIL_PRICE_AMT,
    SOURCE.OMS_TC_ORDER_LINE_ID,
    SOURCE.OMS_PICKUP_END_TSTMP,
    SOURCE.OMS_PURCHASE_ORDER_LINE_NBR,
    SOURCE.OMS_PICKUP_START_TSTMP,
    SOURCE.CANCELLED_FLAG,
    SOURCE.PRODUCT_ID,
    SOURCE.OMS_TC_PURCHASE_ORDERS_ID,
    SOURCE.FREIGHT_REVENUE_CURRENCY_CD,
    SOURCE.FREIGHT_REVENUE_AMT,
    SOURCE.ADJUSTED_ORDER_QTY,
    SOURCE.EV_RELEASED_TSTMP,
    SOURCE.EV_ALLOCATED_TSTMP,
    SOURCE.EV_SHIPPED_TSTMP,
    SOURCE.EV_PICKEDUP_TSTMP,
    SOURCE.OMS_MASTER_ORDER_ID,
    SOURCE.OMS_MO_LINE_ITEM_ID,
    SOURCE.OMS_DO_CREATED_TSTMP,
    SOURCE.ORDER_NBR,
    SOURCE.OMS_ORDER_CREATED_TSTMP,
    SOURCE.ORIG_LOCATION_ID,
    SOURCE.ORDER_CREATION_CHANNEL,
    SOURCE.ORDER_FULFILLMENT_CHANNEL,
    SOURCE.ORDER_CHANNEL,
    SOURCE.SCHED_DELIVERY_FLG,
    SOURCE.SUBSCRIPTION_ORDER_FLG,
    SOURCE.ADD_ON_FLAG,
    SOURCE.ISPU_PXY_FIRST_NAME,
    SOURCE.ISPU_PXY_LAST_NAME,
    SOURCE.ISPU_PXY_ADD_LINE1,
    SOURCE.ISPU_PXY_ADD_LINE2,
    SOURCE.ISPU_PXY_ADD_LINE3,
    SOURCE.ISPU_PXY_CITY,
    SOURCE.ISPU_PXY_STATE,
    SOURCE.ISPU_PXY_POSTAL_CD,
    SOURCE.ISPU_PXY_COUNTRY,
    SOURCE.ISPU_PXY_EMAIL,
    SOURCE.ISUP_PXY_PHONE,
    SOURCE.OMS_TC_COMPANY_ID,
    SOURCE.EXCHANGE_RATE_PCNT,
    SOURCE.RX_ORDER_FLG,
    SOURCE.CANCEL_DTTM,
    SOURCE.UPDATE_TSTMP,
    SOURCE.LOAD_TSTMP
  )""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_OMS_Dist_Order_LN")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_OMS_Dist_Order_LN", mainWorkflowId, parentName)
