# Databricks notebook source
# COMMAND ----------

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.WM_E_DEPT_PRE(DC_NBR INT,
DEPT_ID INT,
DEPT_CODE STRING,
DESCRIPTION STRING,
CREATE_DATE_TIME TIMESTAMP,
MOD_DATE_TIME TIMESTAMP,
USER_ID STRING,
WHSE STRING,
MISC_TXT_1 STRING,
MISC_TXT_2 STRING,
MISC_NUM_1 INT,
MISC_NUM_2 INT,
PERF_GOAL INT,
VERSION_ID INT,
CREATED_DTTM TIMESTAMP,
LAST_UPDATED_DTTM TIMESTAMP,
LOAD_TSTMP TIMESTAMP) USING DELTA;