# Databricks notebook source
# COMMAND ----------

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.ALLIVET_ORDER_STATUS_DAY_v2(ALLIVET_ORDER_NBR STRING,
RX_HOLD_DT_v2 DATE,
OPEN_DT DATE,
COMPLETE_DT_v2 DATE,
VOID_DT DATE,
UPDATE_TSTMP TIMESTAMP,
LOAD_TSTMP TIMESTAMP) USING DELTA;