# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ./MappingUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_location_from_site_profile")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_location_from_site_profile", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_To_LOCATION_0


query_0 = f"""SELECT
  LOCATION_ID AS LOCATION_ID,
  COMPANY_DESC AS COMPANY_DESC,
  COMPANY_ID AS COMPANY_ID,
  DATE_CLOSED AS DATE_CLOSED,
  DATE_OPEN AS DATE_OPEN,
  DATE_LOC_ADDED AS DATE_LOC_ADDED,
  DATE_LOC_DELETED AS DATE_LOC_DELETED,
  DATE_LOC_REFRESHED AS DATE_LOC_REFRESHED,
  DISTRICT_DESC AS DISTRICT_DESC,
  DISTRICT_ID AS DISTRICT_ID,
  PRICE_AD_ZONE_DESC AS PRICE_AD_ZONE_DESC,
  PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
  PRICE_ZONE_DESC AS PRICE_ZONE_DESC,
  PRICE_ZONE_ID AS PRICE_ZONE_ID,
  REGION_DESC AS REGION_DESC,
  REGION_ID AS REGION_ID,
  REPL_DC_NBR AS REPL_DC_NBR,
  REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
  REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
  STORE_CTRY_ABBR AS STORE_CTRY_ABBR,
  STORE_CTRY AS STORE_CTRY,
  STORE_NAME AS STORE_NAME,
  STORE_NBR AS STORE_NBR,
  STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
  STORE_STATE_ABBR AS STORE_STATE_ABBR,
  STORE_TYPE_DESC AS STORE_TYPE_DESC,
  STORE_TYPE_ID AS STORE_TYPE_ID,
  EQUINE_MERCH AS EQUINE_MERCH,
  DATE_GR_OPEN AS DATE_GR_OPEN,
  SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
  SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
  BP_COMPANY_NBR AS BP_COMPANY_NBR,
  BP_GL_ACCT AS BP_GL_ACCT,
  TP_LOC_FLAG AS TP_LOC_FLAG,
  TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
  TP_START_DT AS TP_START_DT,
  SITE_ADDRESS AS SITE_ADDRESS,
  SITE_CITY AS SITE_CITY,
  SITE_POSTAL_CD AS SITE_POSTAL_CD,
  SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
  SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO
FROM
  LOCATION"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_To_LOCATION_0")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_SITE_PROFILE_1


query_1 = f"""SELECT
  LOCATION_ID AS LOCATION_ID,
  LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
  STORE_NBR AS STORE_NBR,
  STORE_NAME AS STORE_NAME,
  STORE_TYPE_ID AS STORE_TYPE_ID,
  STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
  COMPANY_ID AS COMPANY_ID,
  REGION_ID AS REGION_ID,
  DISTRICT_ID AS DISTRICT_ID,
  PRICE_ZONE_ID AS PRICE_ZONE_ID,
  PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
  REPL_DC_NBR AS REPL_DC_NBR,
  REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
  REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
  SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
  SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
  SITE_ADDRESS AS SITE_ADDRESS,
  SITE_CITY AS SITE_CITY,
  STATE_CD AS STATE_CD,
  COUNTRY_CD AS COUNTRY_CD,
  POSTAL_CD AS POSTAL_CD,
  SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
  SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
  SITE_EMAIL_ADDRESS AS SITE_EMAIL_ADDRESS,
  SITE_SALES_FLAG AS SITE_SALES_FLAG,
  EQUINE_MERCH_ID AS EQUINE_MERCH_ID,
  EQUINE_SITE_ID AS EQUINE_SITE_ID,
  EQUINE_SITE_OPEN_DT AS EQUINE_SITE_OPEN_DT,
  GEO_LATITUDE_NBR AS GEO_LATITUDE_NBR,
  GEO_LONGITUDE_NBR AS GEO_LONGITUDE_NBR,
  PETSMART_DMA_CD AS PETSMART_DMA_CD,
  LOYALTY_PGM_TYPE_ID AS LOYALTY_PGM_TYPE_ID,
  LOYALTY_PGM_STATUS_ID AS LOYALTY_PGM_STATUS_ID,
  LOYALTY_PGM_START_DT AS LOYALTY_PGM_START_DT,
  LOYALTY_PGM_CHANGE_DT AS LOYALTY_PGM_CHANGE_DT,
  BP_COMPANY_NBR AS BP_COMPANY_NBR,
  BP_GL_ACCT AS BP_GL_ACCT,
  TP_LOC_FLAG AS TP_LOC_FLAG,
  TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
  PROMO_LABEL_CD AS PROMO_LABEL_CD,
  PARENT_LOCATION_ID AS PARENT_LOCATION_ID,
  LOCATION_NBR AS LOCATION_NBR,
  TIME_ZONE_ID AS TIME_ZONE_ID,
  DELV_SERVICE_CLASS_ID AS DELV_SERVICE_CLASS_ID,
  PICK_SERVICE_CLASS_ID AS PICK_SERVICE_CLASS_ID,
  SITE_LOGIN_ID AS SITE_LOGIN_ID,
  SITE_MANAGER_ID AS SITE_MANAGER_ID,
  SITE_OPEN_YRS_AMT AS SITE_OPEN_YRS_AMT,
  HOTEL_FLAG AS HOTEL_FLAG,
  DAYCAMP_FLAG AS DAYCAMP_FLAG,
  VET_FLAG AS VET_FLAG,
  DIST_MGR_NAME AS DIST_MGR_NAME,
  DIST_SVC_MGR_NAME AS DIST_SVC_MGR_NAME,
  REGION_VP_NAME AS REGION_VP_NAME,
  REGION_TRAINER_NAME AS REGION_TRAINER_NAME,
  ASSET_PROTECT_NAME AS ASSET_PROTECT_NAME,
  SITE_COUNTY AS SITE_COUNTY,
  SITE_FAX_NO AS SITE_FAX_NO,
  SFT_OPEN_DT AS SFT_OPEN_DT,
  DM_EMAIL_ADDRESS AS DM_EMAIL_ADDRESS,
  DSM_EMAIL_ADDRESS AS DSM_EMAIL_ADDRESS,
  RVP_EMAIL_ADDRESS AS RVP_EMAIL_ADDRESS,
  TRADE_AREA AS TRADE_AREA,
  FDLPS_NAME AS FDLPS_NAME,
  FDLPS_EMAIL AS FDLPS_EMAIL,
  OVERSITE_MGR_NAME AS OVERSITE_MGR_NAME,
  OVERSITE_MGR_EMAIL AS OVERSITE_MGR_EMAIL,
  SAFETY_DIRECTOR_NAME AS SAFETY_DIRECTOR_NAME,
  SAFETY_DIRECTOR_EMAIL AS SAFETY_DIRECTOR_EMAIL,
  RETAIL_MANAGER_SAFETY_NAME AS RETAIL_MANAGER_SAFETY_NAME,
  RETAIL_MANAGER_SAFETY_EMAIL AS RETAIL_MANAGER_SAFETY_EMAIL,
  AREA_DIRECTOR_NAME AS AREA_DIRECTOR_NAME,
  AREA_DIRECTOR_EMAIL AS AREA_DIRECTOR_EMAIL,
  DC_GENERAL_MANAGER_NAME AS DC_GENERAL_MANAGER_NAME,
  DC_GENERAL_MANAGER_EMAIL AS DC_GENERAL_MANAGER_EMAIL,
  ASST_DC_GENERAL_MANAGER_NAME1 AS ASST_DC_GENERAL_MANAGER_NAME1,
  ASST_DC_GENERAL_MANAGER_EMAIL1 AS ASST_DC_GENERAL_MANAGER_EMAIL1,
  ASST_DC_GENERAL_MANAGER_NAME2 AS ASST_DC_GENERAL_MANAGER_NAME2,
  ASST_DC_GENERAL_MANAGER_EMAIL2 AS ASST_DC_GENERAL_MANAGER_EMAIL2,
  REGIONAL_DC_SAFETY_MGR_NAME AS REGIONAL_DC_SAFETY_MGR_NAME,
  REGIONAL_DC_SAFETY_MGR_EMAIL AS REGIONAL_DC_SAFETY_MGR_EMAIL,
  DC_PEOPLE_SUPERVISOR_NAME AS DC_PEOPLE_SUPERVISOR_NAME,
  DC_PEOPLE_SUPERVISOR_EMAIL AS DC_PEOPLE_SUPERVISOR_EMAIL,
  PEOPLE_MANAGER_NAME AS PEOPLE_MANAGER_NAME,
  PEOPLE_MANAGER_EMAIL AS PEOPLE_MANAGER_EMAIL,
  ASSET_PROT_DIR_NAME AS ASSET_PROT_DIR_NAME,
  ASSET_PROT_DIR_EMAIL AS ASSET_PROT_DIR_EMAIL,
  SR_REG_ASSET_PROT_MGR_NAME AS SR_REG_ASSET_PROT_MGR_NAME,
  SR_REG_ASSET_PROT_MGR_EMAIL AS SR_REG_ASSET_PROT_MGR_EMAIL,
  REG_ASSET_PROT_MGR_NAME AS REG_ASSET_PROT_MGR_NAME,
  REG_ASSET_PROT_MGR_EMAIL AS REG_ASSET_PROT_MGR_EMAIL,
  ASSET_PROTECT_EMAIL AS ASSET_PROTECT_EMAIL,
  TP_START_DT AS TP_START_DT,
  OPEN_DT AS OPEN_DT,
  GR_OPEN_DT AS GR_OPEN_DT,
  CLOSE_DT AS CLOSE_DT,
  HOTEL_OPEN_DT AS HOTEL_OPEN_DT,
  ADD_DT AS ADD_DT,
  DELETE_DT AS DELETE_DT,
  UPDATE_DT AS UPDATE_DT,
  LOAD_DT AS LOAD_DT
FROM
  SITE_PROFILE"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("Shortcut_to_SITE_PROFILE_1")

# COMMAND ----------
# DBTITLE 1, ASQ_Shortcut_to_SITE_PROFILE_2


query_2 = f"""SELECT
  SITE.LOCATION_ID AS LOCATION_ID,
  L.LOCATION_ID AS LOC_LOCATION_ID,
  C.COMPANY_DESC AS COMPANY_DESC,
  SITE.COMPANY_ID AS COMPANY_ID,
  SITE.CLOSE_DT AS CLOSE_DT,
  SITE.OPEN_DT AS OPEN_DT,
  SITE.ADD_DT AS ADD_DT,
  SITE.DELETE_DT AS DELETE_DT,
  SITE.LOAD_DT AS LOAD_DT,
  D.DISTRICT_DESC AS DISTRICT_DESC,
  SITE.DISTRICT_ID AS DISTRICT_ID,
  PA.PRICE_AD_ZONE_DESC AS PRICE_AD_ZONE_DESC,
  SITE.PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
  P.PRICE_ZONE_DESC AS PRICE_ZONE_DESC,
  SITE.PRICE_ZONE_ID AS PRICE_ZONE_ID,
  R.REGION_DESC AS REGION_DESC,
  SITE.REGION_ID AS REGION_ID,
  SITE.REPL_DC_NBR AS REPL_DC_NBR,
  SITE.REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
  SITE.REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
  SITE.COUNTRY_CD AS COUNTRY_CD,
  CT.COUNTRY_NAME AS COUNTRY_NAME,
  SITE.STORE_NAME AS STORE_NAME,
  SITE.STORE_NBR AS STORE_NBR,
  SITE.STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
  SITE.STATE_CD AS STATE_CD,
  ST.STORE_TYPE_DESC AS STORE_TYPE_DESC,
  SITE.STORE_TYPE_ID AS STORE_TYPE_ID,
  EM.EQUINE_MERCH_DESC AS EQUINE_MERCH_DESC,
  SITE.GR_OPEN_DT AS GR_OPEN_DT,
  SITE.SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
  SITE.SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
  SITE.BP_COMPANY_NBR AS BP_COMPANY_NBR,
  SITE.BP_GL_ACCT AS BP_GL_ACCT,
  SITE.TP_LOC_FLAG AS TP_LOC_FLAG,
  SITE.TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
  SITE.TP_START_DT AS TP_START_DT,
  SITE.SITE_ADDRESS AS SITE_ADDRESS,
  SITE.SITE_CITY AS SITE_CITY,
  SITE.POSTAL_CD AS POSTAL_CD,
  SITE.SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
  SITE.SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_SITE_PROFILE_1 SITE
  LEFT OUTER JOIN Shortcut_To_LOCATION_0 L ON SITE.LOCATION_ID = L.LOCATION_ID
  LEFT OUTER JOIN STORE_TYPE ST ON SITE.STORE_TYPE_ID = ST.STORE_TYPE_ID
  LEFT OUTER JOIN COMPANY C ON SITE.COMPANY_ID = C.COMPANY_ID
  LEFT OUTER JOIN REGION R ON SITE.REGION_ID = R.REGION_ID
  LEFT OUTER JOIN DISTRICT D ON SITE.DISTRICT_ID = D.DISTRICT_ID
  LEFT OUTER JOIN PRICE_ZONE P ON SITE.PRICE_ZONE_ID = P.PRICE_ZONE_ID
  LEFT OUTER JOIN PRICE_AD_ZONE PA ON SITE.PRICE_AD_ZONE_ID = PA.PRICE_AD_ZONE_ID
  LEFT OUTER JOIN COUNTRY CT ON SITE.COUNTRY_CD = CT.COUNTRY_CD
  LEFT OUTER JOIN EQUINE_MERCH EM ON SITE.EQUINE_MERCH_ID = EM.EQUINE_MERCH_ID
WHERE
  SITE.LOAD_DT = CURRENT_DATE"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("ASQ_Shortcut_to_SITE_PROFILE_2")

# COMMAND ----------
# DBTITLE 1, UPD_LOCATION_3


query_3 = f"""SELECT
  LOCATION_ID AS LOCATION_ID,
  LOC_LOCATION_ID AS LOC_LOCATION_ID,
  COMPANY_DESC AS COMPANY_DESC,
  COMPANY_ID AS COMPANY_ID,
  CLOSE_DT AS DATE_CLOSED,
  OPEN_DT AS DATE_OPEN,
  ADD_DT AS DATE_LOC_ADDED,
  DELETE_DT AS DATE_LOC_DELETED,
  LOAD_DT AS DATE_LOC_REFRESHED,
  DISTRICT_DESC AS DISTRICT_DESC,
  DISTRICT_ID AS DISTRICT_ID,
  PRICE_AD_ZONE_DESC AS PRICE_AD_ZONE_DESC,
  PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
  PRICE_ZONE_DESC AS PRICE_ZONE_DESC,
  PRICE_ZONE_ID AS PRICE_ZONE_ID,
  REGION_DESC AS REGION_DESC,
  REGION_ID AS REGION_ID,
  REPL_DC_NBR AS REPL_DC_NBR,
  REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
  REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
  COUNTRY_CD AS STORE_CTRY_ABBR,
  COUNTRY_NAME AS STORE_CTRY,
  STORE_NAME AS STORE_NAME,
  STORE_NBR AS STORE_NBR,
  STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
  STATE_CD AS STORE_STATE_ABBR,
  STORE_TYPE_DESC AS STORE_TYPE_DESC,
  STORE_TYPE_ID AS STORE_TYPE_ID,
  EQUINE_MERCH_DESC AS EQUINE_MERCH,
  GR_OPEN_DT AS DATE_GR_OPEN,
  SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
  SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
  BP_COMPANY_NBR AS BP_COMPANY_NBR,
  BP_GL_ACCT AS BP_GL_ACCT,
  TP_LOC_FLAG AS TP_LOC_FLAG,
  TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
  TP_START_DT AS TP_START_DT,
  SITE_ADDRESS AS SITE_ADDRESS,
  SITE_CITY AS SITE_CITY,
  POSTAL_CD AS SITE_POSTAL_CD,
  SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
  SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id,
  IFF(ISNULL(LOC_LOCATION_ID), 'DD_INSERT', 'DD_UPDATE') AS UPDATE_STRATEGY_FLAG
FROM
  ASQ_Shortcut_to_SITE_PROFILE_2"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("UPD_LOCATION_3")

# COMMAND ----------
# DBTITLE 1, LOCATION


spark.sql("""MERGE INTO LOCATION AS TARGET
USING
  UPD_LOCATION_3 AS SOURCE ON TARGET.LOCATION_ID = SOURCE.LOCATION_ID
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_UPDATE" THEN
UPDATE
SET
  TARGET.LOCATION_ID = SOURCE.LOCATION_ID,
  TARGET.COMPANY_DESC = SOURCE.COMPANY_DESC,
  TARGET.COMPANY_ID = SOURCE.COMPANY_ID,
  TARGET.DATE_CLOSED = SOURCE.DATE_CLOSED,
  TARGET.DATE_OPEN = SOURCE.DATE_OPEN,
  TARGET.DATE_LOC_ADDED = SOURCE.DATE_LOC_ADDED,
  TARGET.DATE_LOC_DELETED = SOURCE.DATE_LOC_DELETED,
  TARGET.DATE_LOC_REFRESHED = SOURCE.DATE_LOC_REFRESHED,
  TARGET.DISTRICT_DESC = SOURCE.DISTRICT_DESC,
  TARGET.DISTRICT_ID = SOURCE.DISTRICT_ID,
  TARGET.PRICE_AD_ZONE_DESC = SOURCE.PRICE_AD_ZONE_DESC,
  TARGET.PRICE_AD_ZONE_ID = SOURCE.PRICE_AD_ZONE_ID,
  TARGET.PRICE_ZONE_DESC = SOURCE.PRICE_ZONE_DESC,
  TARGET.PRICE_ZONE_ID = SOURCE.PRICE_ZONE_ID,
  TARGET.REGION_DESC = SOURCE.REGION_DESC,
  TARGET.REGION_ID = SOURCE.REGION_ID,
  TARGET.REPL_DC_NBR = SOURCE.REPL_DC_NBR,
  TARGET.REPL_FISH_DC_NBR = SOURCE.REPL_FISH_DC_NBR,
  TARGET.REPL_FWD_DC_NBR = SOURCE.REPL_FWD_DC_NBR,
  TARGET.STORE_CTRY_ABBR = SOURCE.STORE_CTRY_ABBR,
  TARGET.STORE_CTRY = SOURCE.STORE_CTRY,
  TARGET.STORE_NAME = SOURCE.STORE_NAME,
  TARGET.STORE_NBR = SOURCE.STORE_NBR,
  TARGET.STORE_OPEN_CLOSE_FLAG = SOURCE.STORE_OPEN_CLOSE_FLAG,
  TARGET.STORE_STATE_ABBR = SOURCE.STORE_STATE_ABBR,
  TARGET.STORE_TYPE_DESC = SOURCE.STORE_TYPE_DESC,
  TARGET.STORE_TYPE_ID = SOURCE.STORE_TYPE_ID,
  TARGET.EQUINE_MERCH = SOURCE.EQUINE_MERCH,
  TARGET.DATE_GR_OPEN = SOURCE.DATE_GR_OPEN,
  TARGET.SQ_FEET_RETAIL = SOURCE.SQ_FEET_RETAIL,
  TARGET.SQ_FEET_TOTAL = SOURCE.SQ_FEET_TOTAL,
  TARGET.BP_COMPANY_NBR = SOURCE.BP_COMPANY_NBR,
  TARGET.BP_GL_ACCT = SOURCE.BP_GL_ACCT,
  TARGET.TP_LOC_FLAG = SOURCE.TP_LOC_FLAG,
  TARGET.TP_ACTIVE_CNT = SOURCE.TP_ACTIVE_CNT,
  TARGET.TP_START_DT = SOURCE.TP_START_DT,
  TARGET.SITE_ADDRESS = SOURCE.SITE_ADDRESS,
  TARGET.SITE_CITY = SOURCE.SITE_CITY,
  TARGET.SITE_POSTAL_CD = SOURCE.SITE_POSTAL_CD,
  TARGET.SITE_MAIN_TELE_NO = SOURCE.SITE_MAIN_TELE_NO,
  TARGET.SITE_GROOM_TELE_NO = SOURCE.SITE_GROOM_TELE_NO
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_DELETE"
  AND TARGET.COMPANY_DESC = SOURCE.COMPANY_DESC
  AND TARGET.COMPANY_ID = SOURCE.COMPANY_ID
  AND TARGET.DATE_CLOSED = SOURCE.DATE_CLOSED
  AND TARGET.DATE_OPEN = SOURCE.DATE_OPEN
  AND TARGET.DATE_LOC_ADDED = SOURCE.DATE_LOC_ADDED
  AND TARGET.DATE_LOC_DELETED = SOURCE.DATE_LOC_DELETED
  AND TARGET.DATE_LOC_REFRESHED = SOURCE.DATE_LOC_REFRESHED
  AND TARGET.DISTRICT_DESC = SOURCE.DISTRICT_DESC
  AND TARGET.DISTRICT_ID = SOURCE.DISTRICT_ID
  AND TARGET.PRICE_AD_ZONE_DESC = SOURCE.PRICE_AD_ZONE_DESC
  AND TARGET.PRICE_AD_ZONE_ID = SOURCE.PRICE_AD_ZONE_ID
  AND TARGET.PRICE_ZONE_DESC = SOURCE.PRICE_ZONE_DESC
  AND TARGET.PRICE_ZONE_ID = SOURCE.PRICE_ZONE_ID
  AND TARGET.REGION_DESC = SOURCE.REGION_DESC
  AND TARGET.REGION_ID = SOURCE.REGION_ID
  AND TARGET.REPL_DC_NBR = SOURCE.REPL_DC_NBR
  AND TARGET.REPL_FISH_DC_NBR = SOURCE.REPL_FISH_DC_NBR
  AND TARGET.REPL_FWD_DC_NBR = SOURCE.REPL_FWD_DC_NBR
  AND TARGET.STORE_CTRY_ABBR = SOURCE.STORE_CTRY_ABBR
  AND TARGET.STORE_CTRY = SOURCE.STORE_CTRY
  AND TARGET.STORE_NAME = SOURCE.STORE_NAME
  AND TARGET.STORE_NBR = SOURCE.STORE_NBR
  AND TARGET.STORE_OPEN_CLOSE_FLAG = SOURCE.STORE_OPEN_CLOSE_FLAG
  AND TARGET.STORE_STATE_ABBR = SOURCE.STORE_STATE_ABBR
  AND TARGET.STORE_TYPE_DESC = SOURCE.STORE_TYPE_DESC
  AND TARGET.STORE_TYPE_ID = SOURCE.STORE_TYPE_ID
  AND TARGET.EQUINE_MERCH = SOURCE.EQUINE_MERCH
  AND TARGET.DATE_GR_OPEN = SOURCE.DATE_GR_OPEN
  AND TARGET.SQ_FEET_RETAIL = SOURCE.SQ_FEET_RETAIL
  AND TARGET.SQ_FEET_TOTAL = SOURCE.SQ_FEET_TOTAL
  AND TARGET.BP_COMPANY_NBR = SOURCE.BP_COMPANY_NBR
  AND TARGET.BP_GL_ACCT = SOURCE.BP_GL_ACCT
  AND TARGET.TP_LOC_FLAG = SOURCE.TP_LOC_FLAG
  AND TARGET.TP_ACTIVE_CNT = SOURCE.TP_ACTIVE_CNT
  AND TARGET.TP_START_DT = SOURCE.TP_START_DT
  AND TARGET.SITE_ADDRESS = SOURCE.SITE_ADDRESS
  AND TARGET.SITE_CITY = SOURCE.SITE_CITY
  AND TARGET.SITE_POSTAL_CD = SOURCE.SITE_POSTAL_CD
  AND TARGET.SITE_MAIN_TELE_NO = SOURCE.SITE_MAIN_TELE_NO
  AND TARGET.SITE_GROOM_TELE_NO = SOURCE.SITE_GROOM_TELE_NO THEN DELETE
  WHEN NOT MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_INSERT" THEN
INSERT
  (
    TARGET.LOCATION_ID,
    TARGET.COMPANY_DESC,
    TARGET.COMPANY_ID,
    TARGET.DATE_CLOSED,
    TARGET.DATE_OPEN,
    TARGET.DATE_LOC_ADDED,
    TARGET.DATE_LOC_DELETED,
    TARGET.DATE_LOC_REFRESHED,
    TARGET.DISTRICT_DESC,
    TARGET.DISTRICT_ID,
    TARGET.PRICE_AD_ZONE_DESC,
    TARGET.PRICE_AD_ZONE_ID,
    TARGET.PRICE_ZONE_DESC,
    TARGET.PRICE_ZONE_ID,
    TARGET.REGION_DESC,
    TARGET.REGION_ID,
    TARGET.REPL_DC_NBR,
    TARGET.REPL_FISH_DC_NBR,
    TARGET.REPL_FWD_DC_NBR,
    TARGET.STORE_CTRY_ABBR,
    TARGET.STORE_CTRY,
    TARGET.STORE_NAME,
    TARGET.STORE_NBR,
    TARGET.STORE_OPEN_CLOSE_FLAG,
    TARGET.STORE_STATE_ABBR,
    TARGET.STORE_TYPE_DESC,
    TARGET.STORE_TYPE_ID,
    TARGET.EQUINE_MERCH,
    TARGET.DATE_GR_OPEN,
    TARGET.SQ_FEET_RETAIL,
    TARGET.SQ_FEET_TOTAL,
    TARGET.BP_COMPANY_NBR,
    TARGET.BP_GL_ACCT,
    TARGET.TP_LOC_FLAG,
    TARGET.TP_ACTIVE_CNT,
    TARGET.TP_START_DT,
    TARGET.SITE_ADDRESS,
    TARGET.SITE_CITY,
    TARGET.SITE_POSTAL_CD,
    TARGET.SITE_MAIN_TELE_NO,
    TARGET.SITE_GROOM_TELE_NO
  )
VALUES
  (
    SOURCE.LOCATION_ID,
    SOURCE.COMPANY_DESC,
    SOURCE.COMPANY_ID,
    SOURCE.DATE_CLOSED,
    SOURCE.DATE_OPEN,
    SOURCE.DATE_LOC_ADDED,
    SOURCE.DATE_LOC_DELETED,
    SOURCE.DATE_LOC_REFRESHED,
    SOURCE.DISTRICT_DESC,
    SOURCE.DISTRICT_ID,
    SOURCE.PRICE_AD_ZONE_DESC,
    SOURCE.PRICE_AD_ZONE_ID,
    SOURCE.PRICE_ZONE_DESC,
    SOURCE.PRICE_ZONE_ID,
    SOURCE.REGION_DESC,
    SOURCE.REGION_ID,
    SOURCE.REPL_DC_NBR,
    SOURCE.REPL_FISH_DC_NBR,
    SOURCE.REPL_FWD_DC_NBR,
    SOURCE.STORE_CTRY_ABBR,
    SOURCE.STORE_CTRY,
    SOURCE.STORE_NAME,
    SOURCE.STORE_NBR,
    SOURCE.STORE_OPEN_CLOSE_FLAG,
    SOURCE.STORE_STATE_ABBR,
    SOURCE.STORE_TYPE_DESC,
    SOURCE.STORE_TYPE_ID,
    SOURCE.EQUINE_MERCH,
    SOURCE.DATE_GR_OPEN,
    SOURCE.SQ_FEET_RETAIL,
    SOURCE.SQ_FEET_TOTAL,
    SOURCE.BP_COMPANY_NBR,
    SOURCE.BP_GL_ACCT,
    SOURCE.TP_LOC_FLAG,
    SOURCE.TP_ACTIVE_CNT,
    SOURCE.TP_START_DT,
    SOURCE.SITE_ADDRESS,
    SOURCE.SITE_CITY,
    SOURCE.SITE_POSTAL_CD,
    SOURCE.SITE_MAIN_TELE_NO,
    SOURCE.SITE_GROOM_TELE_NO
  )""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_location_from_site_profile")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_location_from_site_profile", mainWorkflowId, parentName)
