# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ./MappingUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_national_cost_day")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_national_cost_day", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_To_NATIONAL_COST_PRE_0


query_0 = f"""SELECT
  SKU_NBR AS SKU_NBR,
  VENDOR_ID AS VENDOR_ID,
  PURCH_ORG_CD AS PURCH_ORG_CD,
  COND_TYPE_CD AS COND_TYPE_CD,
  PURCH_INFO_CD AS PURCH_INFO_CD,
  COND_END_DT AS COND_END_DT,
  DELETE_IND AS DELETE_IND,
  COND_EFF_DT AS COND_EFF_DT,
  COND_RECORD_NBR AS COND_RECORD_NBR,
  COND_AMT AS COND_AMT,
  PROMOTION_CD AS PROMOTION_CD,
  COND_RT_UNIT AS COND_RT_UNIT,
  COND_PRICE_UNIT AS COND_PRICE_UNIT,
  COND_UNIT AS COND_UNIT,
  UNIT_NUMERATOR AS UNIT_NUMERATOR,
  UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
  LOAD_DT AS LOAD_DT
FROM
  NATIONAL_COST_PRE"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_To_NATIONAL_COST_PRE_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_To_NATIONAL_COST_PRE_1


query_1 = f"""SELECT
  NCP.SKU_NBR AS SKU_NBR,
  NCP.VENDOR_ID AS VENDOR_ID,
  NCP.PURCH_ORG_CD AS PURCH_ORG_CD,
  NCP.COND_TYPE_CD AS COND_TYPE_CD,
  NCP.PURCH_INFO_CD AS PURCH_INFO_CD,
  NCP.COND_END_DT AS COND_END_DT,
  NCP.DELETE_IND AS DELETE_IND,
  NCP.COND_EFF_DT AS COND_EFF_DT,
  NCP.COND_RECORD_NBR AS COND_RECORD_NBR,
  NCP.COND_AMT AS COND_AMT,
  NCP.PROMOTION_CD AS PROMOTION_CD,
  NCP.COND_RT_UNIT AS COND_RT_UNIT,
  NCP.COND_PRICE_UNIT AS COND_PRICE_UNIT,
  NCP.COND_UNIT AS COND_UNIT,
  NCP.UNIT_NUMERATOR AS UNIT_NUMERATOR,
  NCP.UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
  NCP.LOAD_DT AS LOAD_DT,
  CASE
    WHEN NCD.SKU_NBR IS NULL THEN 0
    ELSE 1
  END AS UPDATE_FLAG,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_To_NATIONAL_COST_PRE_0 NCP
  LEFT OUTER JOIN NATIONAL_COST_DAY NCD ON NCP.SKU_NBR = NCD.SKU_NBR
  AND NCP.VENDOR_ID = NCD.VENDOR_ID
  AND NCP.PURCH_ORG_CD = NCD.PURCH_ORG_CD
  AND NCP.COND_TYPE_CD = NCD.COND_TYPE_CD
  AND NCP.PURCH_INFO_CD = NCD.PURCH_INFO_CD
  AND NCP.COND_END_DT = NCD.COND_END_DT"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("SQ_Shortcut_To_NATIONAL_COST_PRE_1")

# COMMAND ----------
# DBTITLE 1, UPD_Insert_Update_2


query_2 = f"""SELECT
  SKU_NBR AS SKU_NBR,
  VENDOR_ID AS VENDOR_ID,
  PURCH_ORG_CD AS PURCH_ORG_CD,
  COND_TYPE_CD AS COND_TYPE_CD,
  PURCH_INFO_CD AS PURCH_INFO_CD,
  COND_END_DT AS COND_END_DT,
  DELETE_IND AS DELETE_IND,
  COND_EFF_DT AS COND_EFF_DT,
  COND_RECORD_NBR AS COND_RECORD_NBR,
  COND_AMT AS COND_AMT,
  PROMOTION_CD AS PROMOTION_CD,
  COND_RT_UNIT AS COND_RT_UNIT,
  COND_PRICE_UNIT AS COND_PRICE_UNIT,
  COND_UNIT AS COND_UNIT,
  UNIT_NUMERATOR AS UNIT_NUMERATOR,
  UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
  LOAD_DT AS LOAD_DT,
  UPDATE_FLAG AS UPDATE_FLAG,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id,
  IFF(UPDATE_FLAG = 0, 'DD_INSERT', 'DD_UPDATE') AS UPDATE_STRATEGY_FLAG
FROM
  SQ_Shortcut_To_NATIONAL_COST_PRE_1"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("UPD_Insert_Update_2")

# COMMAND ----------
# DBTITLE 1, NATIONAL_COST_DAY


spark.sql("""MERGE INTO NATIONAL_COST_DAY AS TARGET
USING
  UPD_Insert_Update_2 AS SOURCE ON TARGET.PURCH_ORG_CD = SOURCE.PURCH_ORG_CD
  AND TARGET.PURCH_INFO_CD = SOURCE.PURCH_INFO_CD
  AND TARGET.SKU_NBR = SOURCE.SKU_NBR
  AND TARGET.VENDOR_ID = SOURCE.VENDOR_ID
  AND TARGET.COND_TYPE_CD = SOURCE.COND_TYPE_CD
  AND TARGET.COND_END_DT = SOURCE.COND_END_DT
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_UPDATE" THEN
UPDATE
SET
  TARGET.SKU_NBR = SOURCE.SKU_NBR,
  TARGET.VENDOR_ID = SOURCE.VENDOR_ID,
  TARGET.PURCH_ORG_CD = SOURCE.PURCH_ORG_CD,
  TARGET.COND_TYPE_CD = SOURCE.COND_TYPE_CD,
  TARGET.PURCH_INFO_CD = SOURCE.PURCH_INFO_CD,
  TARGET.COND_END_DT = SOURCE.COND_END_DT,
  TARGET.DELETE_IND = SOURCE.DELETE_IND,
  TARGET.COND_EFF_DT = SOURCE.COND_EFF_DT,
  TARGET.COND_RECORD_NBR = SOURCE.COND_RECORD_NBR,
  TARGET.COND_AMT = SOURCE.COND_AMT,
  TARGET.PROMOTION_CD = SOURCE.PROMOTION_CD,
  TARGET.COND_RT_UNIT = SOURCE.COND_RT_UNIT,
  TARGET.COND_PRICE_UNIT = SOURCE.COND_PRICE_UNIT,
  TARGET.COND_UNIT = SOURCE.COND_UNIT,
  TARGET.UNIT_NUMERATOR = SOURCE.UNIT_NUMERATOR,
  TARGET.UNIT_DENOMINATOR = SOURCE.UNIT_DENOMINATOR,
  TARGET.LOAD_DT = SOURCE.LOAD_DT
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_DELETE"
  AND TARGET.DELETE_IND = SOURCE.DELETE_IND
  AND TARGET.COND_EFF_DT = SOURCE.COND_EFF_DT
  AND TARGET.COND_RECORD_NBR = SOURCE.COND_RECORD_NBR
  AND TARGET.COND_AMT = SOURCE.COND_AMT
  AND TARGET.PROMOTION_CD = SOURCE.PROMOTION_CD
  AND TARGET.COND_RT_UNIT = SOURCE.COND_RT_UNIT
  AND TARGET.COND_PRICE_UNIT = SOURCE.COND_PRICE_UNIT
  AND TARGET.COND_UNIT = SOURCE.COND_UNIT
  AND TARGET.UNIT_NUMERATOR = SOURCE.UNIT_NUMERATOR
  AND TARGET.UNIT_DENOMINATOR = SOURCE.UNIT_DENOMINATOR
  AND TARGET.LOAD_DT = SOURCE.LOAD_DT THEN DELETE
  WHEN NOT MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_INSERT" THEN
INSERT
  (
    TARGET.SKU_NBR,
    TARGET.VENDOR_ID,
    TARGET.PURCH_ORG_CD,
    TARGET.COND_TYPE_CD,
    TARGET.PURCH_INFO_CD,
    TARGET.COND_END_DT,
    TARGET.DELETE_IND,
    TARGET.COND_EFF_DT,
    TARGET.COND_RECORD_NBR,
    TARGET.COND_AMT,
    TARGET.PROMOTION_CD,
    TARGET.COND_RT_UNIT,
    TARGET.COND_PRICE_UNIT,
    TARGET.COND_UNIT,
    TARGET.UNIT_NUMERATOR,
    TARGET.UNIT_DENOMINATOR,
    TARGET.LOAD_DT
  )
VALUES
  (
    SOURCE.SKU_NBR,
    SOURCE.VENDOR_ID,
    SOURCE.PURCH_ORG_CD,
    SOURCE.COND_TYPE_CD,
    SOURCE.PURCH_INFO_CD,
    SOURCE.COND_END_DT,
    SOURCE.DELETE_IND,
    SOURCE.COND_EFF_DT,
    SOURCE.COND_RECORD_NBR,
    SOURCE.COND_AMT,
    SOURCE.PROMOTION_CD,
    SOURCE.COND_RT_UNIT,
    SOURCE.COND_PRICE_UNIT,
    SOURCE.COND_UNIT,
    SOURCE.UNIT_NUMERATOR,
    SOURCE.UNIT_DENOMINATOR,
    SOURCE.LOAD_DT
  )""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_national_cost_day")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_national_cost_day", mainWorkflowId, parentName)
