# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ./MappingUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_national_price_day")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_national_price_day", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_NATIONAL_PRICE_PRE_0


query_0 = f"""SELECT
  SKU_NBR AS SKU_NBR,
  SALES_ORG_CD AS SALES_ORG_CD,
  COND_TYPE_CD AS COND_TYPE_CD,
  COND_END_DT AS COND_END_DT,
  COND_EFF_DT AS COND_EFF_DT,
  COND_RECORD_NBR AS COND_RECORD_NBR,
  DELETE_IND AS DELETE_IND,
  PROMOTION_CD AS PROMOTION_CD,
  COND_AMT AS COND_AMT,
  COND_RT_UNIT AS COND_RT_UNIT,
  COND_PRICE_UNIT AS COND_PRICE_UNIT,
  COND_UNIT AS COND_UNIT,
  UNIT_NUMERATOR AS UNIT_NUMERATOR,
  UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
  PRICING_REASON_CD AS PRICING_REASON_CD
FROM
  NATIONAL_PRICE_PRE"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_NATIONAL_PRICE_PRE_0")

# COMMAND ----------
# DBTITLE 1, ASQ_Shortcut_to_NATIONAL_PRICE_PRE_1


query_1 = f"""SELECT
  np.SKU_NBR AS SKU_NBR,
  np.SALES_ORG_CD AS SALES_ORG_CD,
  np.COND_TYPE_CD AS COND_TYPE_CD,
  np.COND_RECORD_NBR AS COND_RECORD_NBR,
  np.COND_END_DT AS COND_END_DT,
  np.COND_EFF_DT AS COND_EFF_DT,
  np.DELETE_IND AS DELETE_IND,
  np.COND_AMT AS COND_AMT,
  np.PROMOTION_CD AS PROMOTION_CD,
  np.COND_RT_UNIT AS COND_RT_UNIT,
  np.COND_PRICE_UNIT AS COND_PRICE_UNIT,
  np.COND_UNIT AS COND_UNIT,
  np.UNIT_NUMERATOR AS UNIT_NUMERATOR,
  np.UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
  np.PRICING_REASON_CD AS PRICING_REASON_CD,
  CURRENT_DATE AS UPDATE_DT,
  NVL(nd.LOAD_DT, CURRENT_DATE) AS LOAD_DT,
  CASE
    WHEN nd.sku_nbr IS NULL THEN 1
    ELSE 2
  END AS ROW_ACTION,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_NATIONAL_PRICE_PRE_0 np
  LEFT OUTER JOIN NATIONAL_PRICE_DAY nd ON np.sku_nbr = nd.sku_nbr
  AND np.sales_org_cd = nd.sales_org_cd
  AND np.cond_type_cd = nd.cond_type_cd
  AND np.cond_end_dt = nd.cond_end_dt"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("ASQ_Shortcut_to_NATIONAL_PRICE_PRE_1")

# COMMAND ----------
# DBTITLE 1, UPD_ins_upd_2


query_2 = f"""SELECT
  SKU_NBR AS SKU_NBR,
  SALES_ORG_CD AS SALES_ORG_CD,
  COND_TYPE_CD AS COND_TYPE_CD,
  COND_RECORD_NBR AS COND_RECORD_NBR,
  COND_END_DT AS COND_END_DT,
  COND_EFF_DT AS COND_EFF_DT,
  DELETE_IND AS DELETE_IND,
  COND_AMT AS COND_AMT,
  PROMOTION_CD AS PROMOTION_CD,
  COND_RT_UNIT AS COND_RT_UNIT,
  COND_PRICE_UNIT AS COND_PRICE_UNIT,
  COND_UNIT AS COND_UNIT,
  UNIT_NUMERATOR AS UNIT_NUMERATOR,
  UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
  PRICING_REASON_CD AS PRICING_REASON_CD,
  UPDATE_DT AS UPDATE_DT,
  LOAD_DT AS LOAD_DT,
  ROW_ACTION AS ROWACTION,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id,
  IFF(ROW_ACTION = 1, dd_insert, dd_update) AS UPDATE_STRATEGY_FLAG
FROM
  ASQ_Shortcut_to_NATIONAL_PRICE_PRE_1"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("UPD_ins_upd_2")

# COMMAND ----------
# DBTITLE 1, NATIONAL_PRICE_DAY


spark.sql("""MERGE INTO NATIONAL_PRICE_DAY AS TARGET
USING
  UPD_ins_upd_2 AS SOURCE ON TARGET.SALES_ORG_CD = SOURCE.SALES_ORG_CD
  AND TARGET.SKU_NBR = SOURCE.SKU_NBR
  AND TARGET.COND_TYPE_CD = SOURCE.COND_TYPE_CD
  AND TARGET.COND_END_DT = SOURCE.COND_END_DT
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_UPDATE" THEN
UPDATE
SET
  TARGET.SKU_NBR = SOURCE.SKU_NBR,
  TARGET.SALES_ORG_CD = SOURCE.SALES_ORG_CD,
  TARGET.COND_TYPE_CD = SOURCE.COND_TYPE_CD,
  TARGET.COND_END_DT = SOURCE.COND_END_DT,
  TARGET.COND_EFF_DT = SOURCE.COND_EFF_DT,
  TARGET.COND_RECORD_NBR = SOURCE.COND_RECORD_NBR,
  TARGET.DELETE_IND = SOURCE.DELETE_IND,
  TARGET.PROMOTION_CD = SOURCE.PROMOTION_CD,
  TARGET.COND_AMT = SOURCE.COND_AMT,
  TARGET.COND_RT_UNIT = SOURCE.COND_RT_UNIT,
  TARGET.COND_PRICE_UNIT = SOURCE.COND_PRICE_UNIT,
  TARGET.COND_UNIT = SOURCE.COND_UNIT,
  TARGET.UNIT_NUMERATOR = SOURCE.UNIT_NUMERATOR,
  TARGET.UNIT_DENOMINATOR = SOURCE.UNIT_DENOMINATOR,
  TARGET.PRICING_REASON_CD = SOURCE.PRICING_REASON_CD,
  TARGET.UPDATE_DT = SOURCE.UPDATE_DT,
  TARGET.LOAD_DT = SOURCE.LOAD_DT
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_DELETE"
  AND TARGET.COND_EFF_DT = SOURCE.COND_EFF_DT
  AND TARGET.COND_RECORD_NBR = SOURCE.COND_RECORD_NBR
  AND TARGET.DELETE_IND = SOURCE.DELETE_IND
  AND TARGET.PROMOTION_CD = SOURCE.PROMOTION_CD
  AND TARGET.COND_AMT = SOURCE.COND_AMT
  AND TARGET.COND_RT_UNIT = SOURCE.COND_RT_UNIT
  AND TARGET.COND_PRICE_UNIT = SOURCE.COND_PRICE_UNIT
  AND TARGET.COND_UNIT = SOURCE.COND_UNIT
  AND TARGET.UNIT_NUMERATOR = SOURCE.UNIT_NUMERATOR
  AND TARGET.UNIT_DENOMINATOR = SOURCE.UNIT_DENOMINATOR
  AND TARGET.PRICING_REASON_CD = SOURCE.PRICING_REASON_CD
  AND TARGET.UPDATE_DT = SOURCE.UPDATE_DT
  AND TARGET.LOAD_DT = SOURCE.LOAD_DT THEN DELETE
  WHEN NOT MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_INSERT" THEN
INSERT
  (
    TARGET.SKU_NBR,
    TARGET.SALES_ORG_CD,
    TARGET.COND_TYPE_CD,
    TARGET.COND_END_DT,
    TARGET.COND_EFF_DT,
    TARGET.COND_RECORD_NBR,
    TARGET.DELETE_IND,
    TARGET.PROMOTION_CD,
    TARGET.COND_AMT,
    TARGET.COND_RT_UNIT,
    TARGET.COND_PRICE_UNIT,
    TARGET.COND_UNIT,
    TARGET.UNIT_NUMERATOR,
    TARGET.UNIT_DENOMINATOR,
    TARGET.PRICING_REASON_CD,
    TARGET.UPDATE_DT,
    TARGET.LOAD_DT
  )
VALUES
  (
    SOURCE.SKU_NBR,
    SOURCE.SALES_ORG_CD,
    SOURCE.COND_TYPE_CD,
    SOURCE.COND_END_DT,
    SOURCE.COND_EFF_DT,
    SOURCE.COND_RECORD_NBR,
    SOURCE.DELETE_IND,
    SOURCE.PROMOTION_CD,
    SOURCE.COND_AMT,
    SOURCE.COND_RT_UNIT,
    SOURCE.COND_PRICE_UNIT,
    SOURCE.COND_UNIT,
    SOURCE.UNIT_NUMERATOR,
    SOURCE.UNIT_DENOMINATOR,
    SOURCE.PRICING_REASON_CD,
    SOURCE.UPDATE_DT,
    SOURCE.LOAD_DT
  )""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_national_price_day")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_national_price_day", mainWorkflowId, parentName)
