# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ./MappingUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_product_history_3")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_product_history_3", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_To_PRODUCT_KEY_PRE_0


query_0 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  BUYER_ID AS BUYER_ID,
  PRIMARY_UPC AS PRIMARY_UPC,
  PRIMARY_VENDOR_ID AS PRIMARY_VENDOR_ID,
  PURCH_GROUP_ID AS PURCH_GROUP_ID,
  SKU_NBR AS SKU_NBR,
  SAP_CATEGORY_ID AS SAP_CATEGORY_ID,
  OLD_ARTICLE_NBR AS OLD_ARTICLE_NBR,
  ITEM_CONCATENATED AS ITEM_CONCATENATED
FROM
  PRODUCT_KEY_PRE"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_To_PRODUCT_KEY_PRE_0")

# COMMAND ----------
# DBTITLE 1, Shortcut_To_PRODUCT_HISTORY_1


query_1 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  PROD_HIST_EFF_DT AS PROD_HIST_EFF_DT,
  PROD_HIST_END_DT AS PROD_HIST_END_DT,
  BUYER_ID AS BUYER_ID,
  PRIMARY_UPC AS PRIMARY_UPC,
  PRIMARY_VENDOR_ID AS PRIMARY_VENDOR_ID,
  PURCH_GROUP_ID AS PURCH_GROUP_ID,
  SKU_NBR AS SKU_NBR,
  SAP_CATEGORY_ID AS SAP_CATEGORY_ID,
  OLD_ARTICLE_NBR AS OLD_ARTICLE_NBR,
  ITEM_CONCATENATED AS ITEM_CONCATENATED
FROM
  PRODUCT_HISTORY"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("Shortcut_To_PRODUCT_HISTORY_1")

# COMMAND ----------
# DBTITLE 1, ASQ_Shortcut_To_PRODUCT_HISTORY_2


query_2 = f"""SELECT
  HIST.PRODUCT_ID AS PRODUCT_ID,
  HIST.PROD_HIST_EFF_DT AS PROD_HIST_EFF_DT,
  CURRENT_DATE - 1 AS PROD_HIST_END_DT,
  HIST.BUYER_ID AS BUYER_ID,
  HIST.PRIMARY_UPC AS PRIMARY_UPC,
  HIST.PRIMARY_VENDOR_ID AS PRIMARY_VENDOR_ID,
  HIST.PURCH_GROUP_ID AS PURCH_GROUP_ID,
  HIST.SKU_NBR AS SKU_NBR,
  HIST.SAP_CATEGORY_ID AS SAP_CATEGORY_ID,
  HIST.OLD_ARTICLE_NBR AS OLD_ARTICLE_NBR,
  HIST.ITEM_CONCATENATED AS ITEM_CONCATENATED,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_To_PRODUCT_KEY_PRE_0 PROD,
  Shortcut_To_PRODUCT_HISTORY_1 HIST
WHERE
  HIST.PROD_HIST_END_DT = TO_DATE('9999-12-31', 'YYYY-MM-DD')
  AND PROD.PRODUCT_ID = HIST.PRODUCT_ID
  AND (
    PROD.BUYER_ID <> HIST.BUYER_ID
    OR PROD.PRIMARY_UPC <> HIST.PRIMARY_UPC
    OR PROD.PRIMARY_VENDOR_ID <> HIST.PRIMARY_VENDOR_ID
    OR PROD.PURCH_GROUP_ID <> HIST.PURCH_GROUP_ID
    OR PROD.SKU_NBR <> HIST.SKU_NBR
    OR PROD.SAP_CATEGORY_ID <> HIST.SAP_CATEGORY_ID
    OR PROD.OLD_ARTICLE_NBR <> NVL(HIST.OLD_ARTICLE_NBR, ' ')
    OR PROD.ITEM_CONCATENATED <> NVL(HIST.ITEM_CONCATENATED, ' ')
  )"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("ASQ_Shortcut_To_PRODUCT_HISTORY_2")

# COMMAND ----------
# DBTITLE 1, UPD_ENDDT_CHG_3


query_3 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  PROD_HIST_EFF_DT AS PROD_HIST_EFF_DT,
  PROD_HIST_END_DT AS PROD_HIST_END_DT,
  BUYER_ID AS BUYER_ID,
  PRIMARY_UPC AS PRIMARY_UPC,
  PRIMARY_VENDOR_ID AS PRIMARY_VENDOR_ID,
  PURCH_GROUP_ID AS PURCH_GROUP_ID,
  SKU_NBR AS SKU_NBR,
  SAP_CATEGORY_ID AS SAP_CATEGORY_ID,
  OLD_ARTICLE_NBR AS OLD_ARTICLE_NBR,
  ITEM_CONCATENATED AS ITEM_CONCATENATED,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id,
  dd_update AS UPDATE_STRATEGY_FLAG
FROM
  ASQ_Shortcut_To_PRODUCT_HISTORY_2"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("UPD_ENDDT_CHG_3")

# COMMAND ----------
# DBTITLE 1, PRODUCT_HISTORY


spark.sql("""MERGE INTO PRODUCT_HISTORY AS TARGET
USING
  UPD_ENDDT_CHG_3 AS SOURCE ON TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID
  AND TARGET.PROD_HIST_EFF_DT = SOURCE.PROD_HIST_EFF_DT
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_UPDATE" THEN
UPDATE
SET
  TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID,
  TARGET.PROD_HIST_EFF_DT = SOURCE.PROD_HIST_EFF_DT,
  TARGET.PROD_HIST_END_DT = SOURCE.PROD_HIST_END_DT,
  TARGET.BUYER_ID = SOURCE.BUYER_ID,
  TARGET.PRIMARY_UPC = SOURCE.PRIMARY_UPC,
  TARGET.PRIMARY_VENDOR_ID = SOURCE.PRIMARY_VENDOR_ID,
  TARGET.PURCH_GROUP_ID = SOURCE.PURCH_GROUP_ID,
  TARGET.SKU_NBR = SOURCE.SKU_NBR,
  TARGET.SAP_CATEGORY_ID = SOURCE.SAP_CATEGORY_ID,
  TARGET.OLD_ARTICLE_NBR = SOURCE.OLD_ARTICLE_NBR,
  TARGET.ITEM_CONCATENATED = SOURCE.ITEM_CONCATENATED
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_DELETE"
  AND TARGET.PROD_HIST_END_DT = SOURCE.PROD_HIST_END_DT
  AND TARGET.BUYER_ID = SOURCE.BUYER_ID
  AND TARGET.PRIMARY_UPC = SOURCE.PRIMARY_UPC
  AND TARGET.PRIMARY_VENDOR_ID = SOURCE.PRIMARY_VENDOR_ID
  AND TARGET.PURCH_GROUP_ID = SOURCE.PURCH_GROUP_ID
  AND TARGET.SKU_NBR = SOURCE.SKU_NBR
  AND TARGET.SAP_CATEGORY_ID = SOURCE.SAP_CATEGORY_ID
  AND TARGET.OLD_ARTICLE_NBR = SOURCE.OLD_ARTICLE_NBR
  AND TARGET.ITEM_CONCATENATED = SOURCE.ITEM_CONCATENATED THEN DELETE
  WHEN NOT MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_INSERT" THEN
INSERT
  (
    TARGET.PRODUCT_ID,
    TARGET.PROD_HIST_EFF_DT,
    TARGET.PROD_HIST_END_DT,
    TARGET.BUYER_ID,
    TARGET.PRIMARY_UPC,
    TARGET.PRIMARY_VENDOR_ID,
    TARGET.PURCH_GROUP_ID,
    TARGET.SKU_NBR,
    TARGET.SAP_CATEGORY_ID,
    TARGET.OLD_ARTICLE_NBR,
    TARGET.ITEM_CONCATENATED
  )
VALUES
  (
    SOURCE.PRODUCT_ID,
    SOURCE.PROD_HIST_EFF_DT,
    SOURCE.PROD_HIST_END_DT,
    SOURCE.BUYER_ID,
    SOURCE.PRIMARY_UPC,
    SOURCE.PRIMARY_VENDOR_ID,
    SOURCE.PURCH_GROUP_ID,
    SOURCE.SKU_NBR,
    SOURCE.SAP_CATEGORY_ID,
    SOURCE.OLD_ARTICLE_NBR,
    SOURCE.ITEM_CONCATENATED
  )""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_product_history_3")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_product_history_3", mainWorkflowId, parentName)
