# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ./MappingUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_sap_t001w_site_pre")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_sap_t001w_site_pre", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_T005F_0


query_0 = f"""SELECT
  MANDT AS MANDT,
  SPRAS AS SPRAS,
  LAND1 AS LAND1,
  REGIO AS REGIO,
  COUNC AS COUNC,
  BEZEI AS BEZEI
FROM
  T005F"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_T005F_0")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_T001W_1


query_1 = f"""SELECT
  MANDT AS MANDT,
  WERKS AS WERKS,
  NAME1 AS NAME1,
  BWKEY AS BWKEY,
  KUNNR AS KUNNR,
  LIFNR AS LIFNR,
  FABKL AS FABKL,
  NAME2 AS NAME2,
  STRAS AS STRAS,
  PFACH AS PFACH,
  PSTLZ AS PSTLZ,
  ORT01 AS ORT01,
  EKORG AS EKORG,
  VKORG AS VKORG,
  CHAZV AS CHAZV,
  KKOWK AS KKOWK,
  KORDB AS KORDB,
  BEDPL AS BEDPL,
  LAND1 AS LAND1,
  REGIO AS REGIO,
  COUNC AS COUNC,
  CITYC AS CITYC,
  ADRNR AS ADRNR,
  IWERK AS IWERK,
  TXJCD AS TXJCD,
  VTWEG AS VTWEG,
  SPART AS SPART,
  SPRAS AS SPRAS,
  WKSOP AS WKSOP,
  AWSLS AS AWSLS,
  CHAZV_OLD AS CHAZV_OLD,
  VLFKZ AS VLFKZ,
  BZIRK AS BZIRK,
  ZONE1 AS ZONE1,
  TAXIW AS TAXIW,
  BZQHL AS BZQHL,
  LET01 AS LET01,
  LET02 AS LET02,
  LET03 AS LET03,
  TXNAM_MA1 AS TXNAM_MA1,
  TXNAM_MA2 AS TXNAM_MA2,
  TXNAM_MA3 AS TXNAM_MA3,
  BETOL AS BETOL,
  J_1BBRANCH AS J_1BBRANCH,
  VTBFI AS VTBFI,
  FPRFW AS FPRFW,
  ACHVM AS ACHVM,
  DVSART AS DVSART,
  NODETYPE AS NODETYPE,
  NSCHEMA AS NSCHEMA,
  PKOSA AS PKOSA,
  MISCH AS MISCH,
  MGVUPD AS MGVUPD,
  VSTEL AS VSTEL,
  MGVLAUPD AS MGVLAUPD,
  ZZBROCK_CO AS ZZBROCK_CO,
  ZZPOST_SITE AS ZZPOST_SITE,
  MGVLAREVAL AS MGVLAREVAL,
  SOURCING AS SOURCING,
  OILIVAL AS OILIVAL,
  OIHVTYPE AS OIHVTYPE,
  OIHCREDIPI AS OIHCREDIPI,
  STORETYPE AS STORETYPE,
  DEP_STORE AS DEP_STORE
FROM
  T001W"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("Shortcut_to_T001W_1")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_T001W_2


query_2 = f"""SELECT
  SITE.MANDT AS MANDT,
  SITE.WERKS AS WERKS,
  SITE.NAME1 AS NAME1,
  SITE.BWKEY AS BWKEY,
  SITE.KUNNR AS KUNNR,
  SITE.LIFNR AS LIFNR,
  SITE.FABKL AS FABKL,
  SITE.NAME2 AS NAME2,
  SITE.STRAS AS STRAS,
  SITE.PFACH AS PFACH,
  SITE.PSTLZ AS PSTLZ,
  SITE.ORT01 AS ORT01,
  SITE.EKORG AS EKORG,
  SITE.VKORG AS VKORG,
  SITE.CHAZV AS CHAZV,
  SITE.KKOWK AS KKOWK,
  SITE.KORDB AS KORDB,
  SITE.BEDPL AS BEDPL,
  SITE.LAND1 AS LAND1,
  SITE.REGIO AS REGIO,
  SITE.COUNC AS COUNC,
  SITE.CITYC AS CITYC,
  SITE.ADRNR AS ADRNR,
  SITE.IWERK AS IWERK,
  SITE.TXJCD AS TXJCD,
  SITE.VTWEG AS VTWEG,
  SITE.SPART AS SPART,
  SITE.SPRAS AS SPRAS,
  SITE.WKSOP AS WKSOP,
  SITE.AWSLS AS AWSLS,
  SITE.CHAZV_OLD AS CHAZV_OLD,
  SITE.VLFKZ AS VLFKZ,
  SITE.BZIRK AS BZIRK,
  SITE.ZONE1 AS ZONE1,
  SITE.TAXIW AS TAXIW,
  SITE.BZQHL AS BZQHL,
  SITE.LET01 AS LET01,
  SITE.LET02 AS LET02,
  SITE.LET03 AS LET03,
  SITE.TXNAM_MA1 AS TXNAM_MA1,
  SITE.TXNAM_MA2 AS TXNAM_MA2,
  SITE.TXNAM_MA3 AS TXNAM_MA3,
  SITE.BETOL AS BETOL,
  SITE.J_1BBRANCH AS J_1BBRANCH,
  SITE.VTBFI AS VTBFI,
  SITE.FPRFW AS FPRFW,
  SITE.ACHVM AS ACHVM,
  SITE.DVSART AS DVSART,
  SITE.NODETYPE AS NODETYPE,
  SITE.NSCHEMA AS NSCHEMA,
  SITE.PKOSA AS PKOSA,
  SITE.MISCH AS MISCH,
  SITE.MGVUPD AS MGVUPD,
  SITE.VSTEL AS VSTEL,
  SITE.MGVLAUPD AS MGVLAUPD,
  SITE.ZZBROCK_CO AS ZZBROCK_CO,
  SITE.ZZPOST_SITE AS ZZPOST_SITE,
  SITE.MGVLAREVAL AS MGVLAREVAL,
  SITE.SOURCING AS SOURCING,
  SITE.OILIVAL AS OILIVAL,
  SITE.OIHVTYPE AS OIHVTYPE,
  SITE.OIHCREDIPI AS OIHCREDIPI,
  SITE.STORETYPE AS STORETYPE,
  SITE.DEP_STORE AS DEP_STORE,
  COUNTY.BEZEI AS BEZEI,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  sappr3.Shortcut_to_T001W_1 SITE,
  sappr3.Shortcut_to_T005F_0 COUNTY
WHERE
  site.mandt = county.mandt
  AND site.SPRAS = county.SPRAS
  AND site.land1 = county.land1
  AND site.regio = county.regio
  AND site.counc = county.counc"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("SQ_Shortcut_to_T001W_2")

# COMMAND ----------
# DBTITLE 1, SAP_T001W_SITE_PRE


spark.sql("""INSERT INTO
  SAP_T001W_SITE_PRE
SELECT
  MANDT AS MANDT,
  WERKS AS WERKS,
  NAME1 AS NAME1,
  BWKEY AS BWKEY,
  KUNNR AS KUNNR,
  LIFNR AS LIFNR,
  FABKL AS FABKL,
  NAME2 AS NAME2,
  STRAS AS STRAS,
  PFACH AS PFACH,
  PSTLZ AS PSTLZ,
  ORT01 AS ORT01,
  EKORG AS EKORG,
  VKORG AS VKORG,
  CHAZV AS CHAZV,
  KKOWK AS KKOWK,
  KORDB AS KORDB,
  BEDPL AS BEDPL,
  LAND1 AS LAND1,
  REGIO AS REGIO,
  COUNC AS COUNC,
  CITYC AS CITYC,
  ADRNR AS ADRNR,
  IWERK AS IWERK,
  TXJCD AS TXJCD,
  VTWEG AS VTWEG,
  SPART AS SPART,
  SPRAS AS SPRAS,
  WKSOP AS WKSOP,
  AWSLS AS AWSLS,
  CHAZV_OLD AS CHAZV_OLD,
  VLFKZ AS VLFKZ,
  BZIRK AS BZIRK,
  ZONE1 AS ZONE1,
  TAXIW AS TAXIW,
  BZQHL AS BZQHL,
  LET01 AS LET01,
  LET02 AS LET02,
  LET03 AS LET03,
  TXNAM_MA1 AS TXNAM_MA1,
  TXNAM_MA2 AS TXNAM_MA2,
  TXNAM_MA3 AS TXNAM_MA3,
  BETOL AS BETOL,
  J_1BBRANCH AS J_1BBRANCH,
  VTBFI AS VTBFI,
  FPRFW AS FPRFW,
  ACHVM AS ACHVM,
  DVSART AS DVSART,
  NODETYPE AS NODETYPE,
  NSCHEMA AS NSCHEMA,
  PKOSA AS PKOSA,
  MISCH AS MISCH,
  MGVUPD AS MGVUPD,
  VSTEL AS VSTEL,
  MGVLAUPD AS MGVLAUPD,
  ZZBROCK_CO AS ZZBROCK_CO,
  ZZPOST_SITE AS ZZPOST_SITE,
  MGVLAREVAL AS MGVLAREVAL,
  SOURCING AS SOURCING,
  OILIVAL AS OILIVAL,
  OIHVTYPE AS OIHVTYPE,
  OIHCREDIPI AS OIHCREDIPI,
  STORETYPE AS STORETYPE,
  DEP_STORE AS DEP_STORE,
  BEZEI AS BEZEI
FROM
  SQ_Shortcut_to_T001W_2""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_sap_t001w_site_pre")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_sap_t001w_site_pre", mainWorkflowId, parentName)
