# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ./MappingUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_site_profile_EQUINE_SITE_ID")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_site_profile_EQUINE_SITE_ID", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_To_POG_STORE_PRO_0


query_0 = f"""SELECT
  POG_ID AS POG_ID,
  LOCATION_ID AS LOCATION_ID,
  POG_STATUS AS POG_STATUS,
  LAST_CHNG_DT AS LAST_CHNG_DT,
  POG_CANADIAN AS POG_CANADIAN,
  POG_EQUINE AS POG_EQUINE,
  POG_REGISTER AS POG_REGISTER,
  POG_GENERIC_MAP AS POG_GENERIC_MAP,
  DATE_POG_ADDED AS DATE_POG_ADDED,
  DATE_POG_REFRESHED AS DATE_POG_REFRESHED,
  DATE_POG_DELETED AS DATE_POG_DELETED
FROM
  POG_STORE_PRO"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_To_POG_STORE_PRO_0")

# COMMAND ----------
# DBTITLE 1, ASQ_Shortcut_to_POG_STORE_PRO_1


query_1 = f"""SELECT
  DISTINCT PSP.LOCATION_ID,
  CASE
    WHEN PP.POG_NBR LIKE 'EBM%' THEN 1
    WHEN PP.POG_NBR LIKE 'ESLT%' THEN 2
    ELSE 0
  END EQUINE_SITE_ID
FROM
  PLANOGRAM_PRO PP,
  Shortcut_To_POG_STORE_PRO_0 PSP
WHERE
  PP.POG_ID = PSP.POG_ID
  AND PSP.POG_STATUS <> 'D'
ORDER BY
  PSP.LOCATION_ID,
  EQUINE_SITE_ID"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("ASQ_Shortcut_to_POG_STORE_PRO_1")

# COMMAND ----------
# DBTITLE 1, Shortcut_To_PLANOGRAM_PRO_2


query_2 = f"""SELECT
  POG_ID AS POG_ID,
  POG_DBKEY AS POG_DBKEY,
  PROJECT_ID AS PROJECT_ID,
  FIXTURE_TYPE AS FIXTURE_TYPE,
  POG_NBR AS POG_NBR,
  PROJECT_NAME AS PROJECT_NAME,
  POG_DESC AS POG_DESC,
  POG_IMPLEMENT_DT AS POG_IMPLEMENT_DT,
  POG_REVIEW_YM AS POG_REVIEW_YM,
  POG_REV_DT AS POG_REV_DT,
  FIX_LINEAR_IN AS FIX_LINEAR_IN,
  FIX_CUBIC_IN AS FIX_CUBIC_IN,
  FIX_FLOOR_FT AS FIX_FLOOR_FT,
  MIX_FLAG AS MIX_FLAG,
  US_FLAG AS US_FLAG,
  CA_FLAG AS CA_FLAG,
  POG_STATUS AS POG_STATUS,
  LAST_CHNG_DT AS LAST_CHNG_DT,
  LISTING_FLAG AS LISTING_FLAG,
  EVENT_ID AS EVENT_ID,
  POG_DISPLAY_FLAG AS POG_DISPLAY_FLAG,
  EFF_START_DT AS EFF_START_DT,
  EFF_END_DT AS EFF_END_DT,
  POG_TYPE_CD AS POG_TYPE_CD,
  POG_DIVISION AS POG_DIVISION,
  POG_DEPT AS POG_DEPT,
  DATE_POG_ADDED AS DATE_POG_ADDED,
  DATE_POG_REFRESHED AS DATE_POG_REFRESHED,
  DATE_POG_DELETED AS DATE_POG_DELETED
FROM
  PLANOGRAM_PRO"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("Shortcut_To_PLANOGRAM_PRO_2")

# COMMAND ----------
# DBTITLE 1, SITE_PROFILE


spark.sql("""INSERT INTO
  SITE_PROFILE
SELECT
  LOCATION_ID AS LOCATION_ID,
  LOCATION_ID21 AS LOCATION_ID,
  LOCATION_ID AS LOCATION_ID,
  LocationID AS LOCATION_ID,
  LOCATION_ID AS LOCATION_ID,
  LOCATION_ID AS LOCATION_ID,
  LOCATION_ID AS LOCATION_ID,
  LOCATION_ID AS LOCATION_ID,
  LOCATION_ID AS LOCATION_ID,
  LOCATION_ID AS LOCATION_ID,
  LOCATION_ID AS LOCATION_ID,
  LOCATION_TYPE_ID1 AS LOCATION_TYPE_ID,
  STORE_NBR1 AS STORE_NBR,
  VENDOR_NAME AS STORE_NAME,
  VENDOR_NAME AS STORE_NAME,
  STORE_TYPE_ID1 AS STORE_TYPE_ID,
  STORE_OPEN_CLOSE_FLAG1 AS STORE_OPEN_CLOSE_FLAG,
  COMPANY_ID1 AS COMPANY_ID,
  ZERO_DEFAULT1 AS REGION_ID,
  ZERO_DEFAULT1 AS DISTRICT_ID,
  ZERO_DEFAULT1 AS PRICE_ZONE_ID,
  ZERO_DEFAULT1 AS PRICE_AD_ZONE_ID,
  ZERO_DEFAULT1 AS REPL_DC_NBR,
  ZERO_DEFAULT1 AS REPL_FISH_DC_NBR,
  ZERO_DEFAULT1 AS REPL_FWD_DC_NBR,
  ZERO_DEFAULT1 AS SQ_FEET_RETAIL,
  SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
  ZERO_DEFAULT1 AS SQ_FEET_TOTAL,
  SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
  ADDRESS AS SITE_ADDRESS,
  ADDRESS AS SITE_ADDRESS,
  CITY AS SITE_CITY,
  CITY AS SITE_CITY,
  STATE AS STATE_CD,
  STATE AS STATE_CD,
  COUNTRY_CD AS COUNTRY_CD,
  COUNTRY_CD AS COUNTRY_CD,
  ZIP AS POSTAL_CD,
  ZIP AS POSTAL_CD,
  PHONE AS SITE_MAIN_TELE_NO,
  PHONE AS SITE_MAIN_TELE_NO,
  ZERO_DEFAULT1 AS SITE_GROOM_TELE_NO,
  DEFAULT_NOT_DEFINED1 AS SITE_EMAIL_ADDRESS,
  DC_GM_EMAIL AS SITE_EMAIL_ADDRESS,
  ZERO_DEFAULT1 AS SITE_SALES_FLAG,
  EQUINE_MERCH_ID1 AS EQUINE_MERCH_ID,
  EQUINE_MERCH_ID AS EQUINE_MERCH_ID,
  ZERO_DEFAULT1 AS EQUINE_SITE_ID,
  EQUINE_SITE_ID_SQL AS EQUINE_SITE_ID,
  DEFAULT_DT1 AS EQUINE_SITE_OPEN_DT,
  NULL AS GEO_LATITUDE_NBR,
  NULL AS GEO_LONGITUDE_NBR,
  ZERO_DEFAULT1 AS PETSMART_DMA_CD,
  ZERO_DEFAULT1 AS LOYALTY_PGM_TYPE_ID,
  ZERO_DEFAULT1 AS LOYALTY_PGM_STATUS_ID,
  DEFAULT_DT1 AS LOYALTY_PGM_START_DT,
  DEFAULT_DT1 AS LOYALTY_PGM_CHANGE_DT,
  ZERO_DEFAULT1 AS BP_COMPANY_NBR,
  ZERO_DEFAULT1 AS BP_GL_ACCT,
  TP_LOC_FLAG1 AS TP_LOC_FLAG,
  ZERO_DEFAULT1 AS TP_ACTIVE_CNT,
  ZERO_DEFAULT1 AS PROMO_LABEL_CD,
  PARENT_VENDOR_ID AS PARENT_LOCATION_ID,
  PARENT_VENDOR_ID AS PARENT_LOCATION_ID,
  VENDOR_NBR AS LOCATION_NBR,
  VENDOR_NBR AS LOCATION_NBR,
  ZERO_DEFAULT1 AS TIME_ZONE_ID,
  TimeZoneDesc AS TIME_ZONE_ID,
  ZERO_DEFAULT1 AS DELV_SERVICE_CLASS_ID,
  ZERO_DEFAULT1 AS PICK_SERVICE_CLASS_ID,
  ZERO_DEFAULT1 AS SITE_LOGIN_ID,
  ZERO_DEFAULT1 AS SITE_MANAGER_ID,
  EMPLOYEE_ID AS SITE_MANAGER_ID,
  EMPLOYEE_ID AS SITE_MANAGER_ID,
  ZERO_DEFAULT1 AS SITE_OPEN_YRS_AMT,
  ZERO_DEFAULT1 AS HOTEL_FLAG,
  HOTEL_FLAG AS HOTEL_FLAG,
  ZERO_DEFAULT1 AS DAYCAMP_FLAG,
  DAYCAMP_FLAG AS DAYCAMP_FLAG,
  ZERO_DEFAULT1 AS VET_FLAG,
  DEFAULT_NOT_DEFINED1 AS DIST_MGR_NAME,
  Output_DM_NAME AS DIST_MGR_NAME,
  DEFAULT_NOT_DEFINED1 AS DIST_SVC_MGR_NAME,
  DEFAULT_NOT_DEFINED1 AS REGION_VP_NAME,
  DEFAULT_NOT_DEFINED1 AS REGION_TRAINER_NAME,
  DEFAULT_NOT_DEFINED1 AS ASSET_PROTECT_NAME,
  NULL AS SITE_COUNTY,
  NULL AS SITE_FAX_NO,
  NULL AS SFT_OPEN_DT,
  Output_DM_EMAIL AS DM_EMAIL_ADDRESS,
  NULL AS DSM_EMAIL_ADDRESS,
  NULL AS RVP_EMAIL_ADDRESS,
  NULL AS TRADE_AREA,
  NULL AS FDLPS_NAME,
  NULL AS FDLPS_EMAIL,
  NULL AS OVERSITE_MGR_NAME,
  NULL AS OVERSITE_MGR_EMAIL,
  NULL AS SAFETY_DIRECTOR_NAME,
  NULL AS SAFETY_DIRECTOR_EMAIL,
  NULL AS RETAIL_MANAGER_SAFETY_NAME,
  NULL AS RETAIL_MANAGER_SAFETY_EMAIL,
  NULL AS AREA_DIRECTOR_NAME,
  NULL AS AREA_DIRECTOR_EMAIL,
  NULL AS DC_GENERAL_MANAGER_NAME,
  NULL AS DC_GENERAL_MANAGER_EMAIL,
  NULL AS ASST_DC_GENERAL_MANAGER_NAME1,
  NULL AS ASST_DC_GENERAL_MANAGER_EMAIL1,
  NULL AS ASST_DC_GENERAL_MANAGER_NAME2,
  NULL AS ASST_DC_GENERAL_MANAGER_EMAIL2,
  NULL AS REGIONAL_DC_SAFETY_MGR_NAME,
  NULL AS REGIONAL_DC_SAFETY_MGR_EMAIL,
  NULL AS DC_PEOPLE_SUPERVISOR_NAME,
  NULL AS DC_PEOPLE_SUPERVISOR_EMAIL,
  NULL AS PEOPLE_MANAGER_NAME,
  NULL AS PEOPLE_MANAGER_EMAIL,
  NULL AS ASSET_PROT_DIR_NAME,
  NULL AS ASSET_PROT_DIR_EMAIL,
  NULL AS SR_REG_ASSET_PROT_MGR_NAME,
  NULL AS SR_REG_ASSET_PROT_MGR_EMAIL,
  NULL AS REG_ASSET_PROT_MGR_NAME,
  NULL AS REG_ASSET_PROT_MGR_EMAIL,
  NULL AS ASSET_PROTECT_EMAIL,
  DEFAULT_DT1 AS TP_START_DT,
  DEFAULT_DT1 AS OPEN_DT,
  DEFAULT_DT1 AS GR_OPEN_DT,
  DEFAULT_DT1 AS CLOSE_DT,
  DEFAULT_DT1 AS HOTEL_OPEN_DT,
  ADD_DT AS ADD_DT,
  DEFAULT_DT1 AS DELETE_DT,
  UPDATE_DT AS UPDATE_DT,
  UPDATE_DT AS UPDATE_DT,
  Update_Dt AS UPDATE_DT,
  Update_DT AS UPDATE_DT,
  LOAD_DT AS LOAD_DT
FROM
  ASQ_Shortcut_to_POG_STORE_PRO_1""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_site_profile_EQUINE_SITE_ID")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_site_profile_EQUINE_SITE_ID", mainWorkflowId, parentName)
