# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ./MappingUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_sku_profile")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_sku_profile", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_To_SKU_PROFILE_PRE_0


query_0 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  DELETE_IND AS DELETE_IND,
  ALT_DESC AS ALT_DESC,
  BUM_QTY AS BUM_QTY,
  BUYER_ID AS BUYER_ID,
  BUYER_NAME AS BUYER_NAME,
  CONTENTS AS CONTENTS,
  CONTENTS_UNITS AS CONTENTS_UNITS,
  ADD_DT AS ADD_DT,
  DELETE_DT AS DELETE_DT,
  HTS_CODE_ID AS HTS_CODE_ID,
  HTS_CODE_DESC AS HTS_CODE_DESC,
  PRIMARY_UPC_ID AS PRIMARY_UPC_ID,
  PURCH_GROUP_ID AS PURCH_GROUP_ID,
  PURCH_GROUP_NAME AS PURCH_GROUP_NAME,
  SKU_TYPE AS SKU_TYPE,
  SKU_DESC AS SKU_DESC,
  SKU_NBR AS SKU_NBR,
  PURCH_COST_AMT AS PURCH_COST_AMT,
  WEIGHT_NET_AMT AS WEIGHT_NET_AMT,
  WEIGHT_UNIT_DESC AS WEIGHT_UNIT_DESC,
  SAP_CATEGORY_DESC AS SAP_CATEGORY_DESC,
  SAP_CATEGORY_ID AS SAP_CATEGORY_ID,
  SAP_CLASS_DESC AS SAP_CLASS_DESC,
  SAP_CLASS_ID AS SAP_CLASS_ID,
  SAP_DEPT_DESC AS SAP_DEPT_DESC,
  SAP_DEPT_ID AS SAP_DEPT_ID,
  SAP_DIVISION_DESC AS SAP_DIVISION_DESC,
  SAP_DIVISION_ID AS SAP_DIVISION_ID,
  DISC_START_DT AS DISC_START_DT,
  BRAND_NAME AS BRAND_NAME,
  IMPORT_FLAG AS IMPORT_FLAG,
  STATELINE_FLAG AS STATELINE_FLAG,
  SIZE_DESC AS SIZE_DESC,
  INIT_MKDN_DT AS INIT_MKDN_DT,
  STATUS_ID AS STATUS_ID,
  STATUS_NAME AS STATUS_NAME,
  OLD_ARTICLE_NBR AS OLD_ARTICLE_NBR,
  TAX_CLASS_ID AS TAX_CLASS_ID,
  TAX_CLASS_DESC AS TAX_CLASS_DESC,
  VALUATION_CLASS_CD AS VALUATION_CLASS_CD,
  BASE_UOM_CD AS BASE_UOM_CD,
  SIGN_TYPE_CD AS SIGN_TYPE_CD,
  OWNBRAND_FLAG AS OWNBRAND_FLAG,
  COUNTRY_CD AS COUNTRY_CD,
  COUNTRY_NAME AS COUNTRY_NAME,
  CANADIAN_HTS_CD AS CANADIAN_HTS_CD,
  RTV_DEPT_CD AS RTV_DEPT_CD
FROM
  SKU_PROFILE_PRE"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_To_SKU_PROFILE_PRE_0")

# COMMAND ----------
# DBTITLE 1, ASQ_Shortcut_To_SKU_PROFILE_PRE_1


query_1 = f"""SELECT
  DISTINCT PRODUCT_ID AS PRODUCT_ID,
  SKU_NBR AS SKU_NBR,
  SKU_TYPE AS SKU_TYPE,
  PRIMARY_UPC_ID AS PRIMARY_UPC_ID,
  STATUS_ID AS STATUS_ID,
  SKU_DESC AS SKU_DESC,
  ALT_DESC AS ALT_DESC,
  SAP_CATEGORY_ID AS SAP_CATEGORY_ID,
  SAP_CLASS_ID AS SAP_CLASS_ID,
  SAP_DEPT_ID AS SAP_DEPT_ID,
  SAP_DIVISION_ID AS SAP_DIVISION_ID,
  COUNTRY_CD AS COUNTRY_CD,
  IMPORT_FLAG AS IMPORT_FLAG,
  HTS_CODE_ID AS HTS_CODE_ID,
  CONTENTS AS CONTENTS,
  CONTENTS_UNITS AS CONTENTS_UNIT,
  WEIGHT_NET_AMT AS WEIGHT_NET_AMT,
  WEIGHT_UNIT_DESC AS WEIGHT_UOM_CD,
  SIZE_DESC AS SIZE_DESC,
  BUM_QTY AS BUM_QTY,
  BASE_UOM_CD AS UOM_CD,
  BUYER_ID AS BUYER_ID,
  PURCH_GROUP_ID AS PURCH_GROUP_ID,
  TAX_CLASS_ID AS TAX_CLASS_ID,
  VALUATION_CLASS_CD AS VALUATION_CLASS_CD,
  BRAND_NAME AS BRAND_NAME,
  OWNBRAND_FLAG AS OWNBRAND_FLAG,
  STATELINE_FLAG AS STATELINE_FLAG,
  SIGN_TYPE_CD AS SIGN_TYPE_CD,
  OLD_ARTICLE_NBR AS OLD_ARTICLE_NBR,
  INIT_MKDN_DT AS DATE_INIT_MKDN,
  DISC_START_DT AS DATE_DISC_START,
  ADD_DT AS DATE_ADDED,
  DELETE_DT AS DATE_DELETED,
  CANADIAN_HTS_CD AS CANADIAN_HTS_CD,
  RTV_DEPT_CD AS RTV_DEPT_CD,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_To_SKU_PROFILE_PRE_0"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("ASQ_Shortcut_To_SKU_PROFILE_PRE_1")

# COMMAND ----------
# DBTITLE 1, LKP_Brand_2


query_2 = f"""SELECT
  SBP.BRAND_CD AS BRAND_CD,
  SBP.BRAND_CLASSIFICATION_ID AS BRAND_CLASSIFICATION_ID,
  ASTSPP1.SKU_NBR AS SKU_NBR1,
  ASTSPP1.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  ASQ_Shortcut_To_SKU_PROFILE_PRE_1 ASTSPP1
  LEFT JOIN SKU_BRAND_PRE SBP ON SBP.SKU_NBR = ASTSPP1.SKU_NBR"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("LKP_Brand_2")

# COMMAND ----------
# DBTITLE 1, Exp_Brand_3


query_3 = f"""SELECT
  IFF(ISNULL(BRAND_CD), NULL, BRAND_CD) AS BRAND_CD,
  IFF(
    ISNULL(BRAND_CLASSIFICATION_ID),
    NULL,
    BRAND_CLASSIFICATION_ID
  ) AS BRAND_CLASSIFICATION_ID,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  LKP_Brand_2"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("Exp_Brand_3")

# COMMAND ----------
# DBTITLE 1, Exp_conversion_4


query_4 = f"""SELECT
  TO_INTEGER(BUM_QTY) AS BUM_QTY,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  ASQ_Shortcut_To_SKU_PROFILE_PRE_1"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("Exp_conversion_4")

# COMMAND ----------
# DBTITLE 1, EXP_LOAD_DT_5


query_5 = f"""SELECT
  TRUNC(now()) AS UPDATE_DT,
  now() AS LOAD_DT,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  ASQ_Shortcut_To_SKU_PROFILE_PRE_1"""

df_5 = spark.sql(query_5)

df_5.createOrReplaceTempView("EXP_LOAD_DT_5")

# COMMAND ----------
# DBTITLE 1, SKU_PROFILE


spark.sql("""INSERT INTO
  SKU_PROFILE
SELECT
  null.PRODUCT_ID AS PRODUCT_ID,
  ASTSPP1.PRODUCT_ID AS PRODUCT_ID,
  ASTSPP1.SKU_NBR AS SKU_NBR,
  ASTSPP1.SKU_TYPE AS SKU_TYPE,
  ASTSPP1.PRIMARY_UPC_ID AS PRIMARY_UPC_ID,
  ASTSPP1.STATUS_ID AS STATUS_ID,
  NULL AS SUBS_HIST_FLAG,
  NULL AS SUBS_CURR_FLAG,
  ASTSPP1.SKU_DESC AS SKU_DESC,
  ASTSPP1.ALT_DESC AS ALT_DESC,
  ASTSPP1.SAP_CATEGORY_ID AS SAP_CATEGORY_ID,
  ASTSPP1.SAP_CLASS_ID AS SAP_CLASS_ID,
  ASTSPP1.SAP_DEPT_ID AS SAP_DEPT_ID,
  ASTSPP1.SAP_DIVISION_ID AS SAP_DIVISION_ID,
  NULL AS PRIMARY_VENDOR_ID,
  NULL AS PARENT_VENDOR_ID,
  ASTSPP1.COUNTRY_CD AS COUNTRY_CD,
  ASTSPP1.IMPORT_FLAG AS IMPORT_FLAG,
  ASTSPP1.HTS_CODE_ID AS HTS_CODE_ID,
  ASTSPP1.CONTENTS AS CONTENTS,
  ASTSPP1.CONTENTS_UNIT AS CONTENTS_UNITS,
  ASTSPP1.WEIGHT_NET_AMT AS WEIGHT_NET_AMT,
  ASTSPP1.WEIGHT_UOM_CD AS WEIGHT_UOM_CD,
  ASTSPP1.SIZE_DESC AS SIZE_DESC,
  Ec4.BUM_QTY AS BUM_QTY,
  ASTSPP1.UOM_CD AS UOM_CD,
  NULL AS UNIT_NUMERATOR,
  NULL AS UNIT_DENOMINATOR,
  ASTSPP1.BUYER_ID AS BUYER_ID,
  ASTSPP1.PURCH_GROUP_ID AS PURCH_GROUP_ID,
  NULL AS PURCH_COST_AMT,
  NULL AS NAT_PRICE_US_AMT,
  ASTSPP1.TAX_CLASS_ID AS TAX_CLASS_ID,
  ASTSPP1.VALUATION_CLASS_CD AS VALUATION_CLASS_CD,
  EB3.BRAND_CD AS BRAND_CD,
  EB3.BRAND_CLASSIFICATION_ID AS BRAND_CLASSIFICATION_ID,
  ASTSPP1.OWNBRAND_FLAG AS OWNBRAND_FLAG,
  ASTSPP1.STATELINE_FLAG AS STATELINE_FLAG,
  ASTSPP1.SIGN_TYPE_CD AS SIGN_TYPE_CD,
  ASTSPP1.OLD_ARTICLE_NBR AS OLD_ARTICLE_NBR,
  NULL AS VENDOR_ARTICLE_NBR,
  ASTSPP1.DATE_INIT_MKDN AS INIT_MKDN_DT,
  ASTSPP1.DATE_DISC_START AS DISC_START_DT,
  ASTSPP1.DATE_ADDED AS ADD_DT,
  ASTSPP1.DATE_DELETED AS DELETE_DT,
  ELD5.UPDATE_DT AS UPDATE_DT,
  NULL AS FIRST_SALE_DT,
  NULL AS LAST_SALE_DT,
  NULL AS FIRST_INV_DT,
  NULL AS LAST_INV_DT,
  ELD5.LOAD_DT AS LOAD_DT,
  NULL AS BASE_NBR,
  NULL AS BP_COLOR_ID,
  NULL AS BP_SIZE_ID,
  NULL AS BP_BREED_ID,
  NULL AS BP_ITEM_CONCATENATED,
  NULL AS BP_AEROSOL_FLAG,
  NULL AS BP_HAZMAT_FLAG,
  ASTSPP1.CANADIAN_HTS_CD AS CANADIAN_HTS_CD,
  NULL AS NAT_PRICE_CA_AMT,
  NULL AS NAT_PRICE_PR_AMT,
  ASTSPP1.RTV_DEPT_CD AS RTV_DEPT_CD,
  null.GL_ACCT_NBR AS GL_ACCT_NBR,
  null.ARTICLE_CATEGORY_ID AS ARTICLE_CATEGORY_ID,
  null.COMPONENT_FLAG AS COMPONENT_FLAG,
  null.ZDISCO_SCHED_TYPE_ID AS ZDISCO_SCHED_TYPE_ID,
  null.ZDISCO_MKDN_SCHED_ID AS ZDISCO_MKDN_SCHED_ID,
  null.ZDISCO_PID_DT AS ZDISCO_PID_DT,
  null.ZDISCO_START_DT AS ZDISCO_START_DT,
  null.ZDISCO_INIT_MKDN_DT AS ZDISCO_INIT_MKDN_DT,
  null.ZDISCO_DC_DT AS ZDISCO_DC_DT,
  null.ZDISCO_STR_DT AS ZDISCO_STR_DT,
  null.ZDISCO_STR_OWNRSHP_DT AS ZDISCO_STR_OWNRSHP_DT,
  null.ZDISCO_STR_WRT_OFF_DT AS ZDISCO_STR_WRT_OFF_DT
FROM
  ASQ_Shortcut_To_SKU_PROFILE_PRE_1 ASTSPP1
  INNER JOIN Exp_conversion_4 Ec4 ON ASTSPP1.Monotonically_Increasing_Id = Ec4.Monotonically_Increasing_Id
  INNER JOIN Exp_Brand_3 EB3 ON Ec4.Monotonically_Increasing_Id = EB3.Monotonically_Increasing_Id
  INNER JOIN EXP_LOAD_DT_5 ELD5 ON EB3.Monotonically_Increasing_Id = ELD5.Monotonically_Increasing_Id""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_sku_profile")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_sku_profile", mainWorkflowId, parentName)
