# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ./MappingUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_sku_uom_UPD_scm")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_sku_uom_UPD_scm", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_SCM_ITEM_MASTER_PRE_0


query_0 = f"""SELECT
  SCM_SKU_GID AS SCM_SKU_GID,
  SCM_SKU_NBR AS SCM_SKU_NBR,
  SCM_SKU_UOM_CD AS SCM_SKU_UOM_CD,
  SCM_SKU_DESC AS SCM_SKU_DESC,
  SCM_VOLUME_UOM_CD AS SCM_VOLUME_UOM_CD,
  SCM_VOLUME_AMT AS SCM_VOLUME_AMT,
  SCM_WEIGHT_UOM_CD AS SCM_WEIGHT_UOM_CD,
  SCM_WEIGHT_NET_AMT AS SCM_WEIGHT_NET_AMT,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  SCM_ITEM_MASTER_PRE"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_SCM_ITEM_MASTER_PRE_0")

# COMMAND ----------
# DBTITLE 1, Shortcut_To_SKU_UOM1_1


query_1 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  UOM_CD AS UOM_CD,
  UOM_NUMERATOR AS UOM_NUMERATOR,
  UOM_DENOMINATOR AS UOM_DENOMINATOR,
  LENGTH_AMT AS LENGTH_AMT,
  WIDTH_AMT AS WIDTH_AMT,
  HEIGHT_AMT AS HEIGHT_AMT,
  DIMENSION_UNIT_DESC AS DIMENSION_UNIT_DESC,
  VOLUME_AMT AS VOLUME_AMT,
  VOLUME_UOM_CD AS VOLUME_UOM_CD,
  WEIGHT_GROSS_AMT AS WEIGHT_GROSS_AMT,
  WEIGHT_UOM_CD AS WEIGHT_UOM_CD,
  WEIGHT_NET_AMT AS WEIGHT_NET_AMT,
  SCM_VOLUME_UOM_CD AS SCM_VOLUME_UOM_CD,
  SCM_VOLUME_AMT AS SCM_VOLUME_AMT,
  SCM_WEIGHT_UOM_CD AS SCM_WEIGHT_UOM_CD,
  SCM_WEIGHT_NET_AMT AS SCM_WEIGHT_NET_AMT,
  DELETE_DT AS DELETE_DT,
  LOAD_DT AS LOAD_DT
FROM
  SKU_UOM"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("Shortcut_To_SKU_UOM1_1")

# COMMAND ----------
# DBTITLE 1, Shortcut_To_SKU_PROFILE_2


query_2 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  SKU_NBR AS SKU_NBR,
  SKU_TYPE AS SKU_TYPE,
  PRIMARY_UPC_ID AS PRIMARY_UPC_ID,
  STATUS_ID AS STATUS_ID,
  SUBS_HIST_FLAG AS SUBS_HIST_FLAG,
  SUBS_CURR_FLAG AS SUBS_CURR_FLAG,
  SKU_DESC AS SKU_DESC,
  ALT_DESC AS ALT_DESC,
  SAP_CATEGORY_ID AS SAP_CATEGORY_ID,
  SAP_CLASS_ID AS SAP_CLASS_ID,
  SAP_DEPT_ID AS SAP_DEPT_ID,
  SAP_DIVISION_ID AS SAP_DIVISION_ID,
  PRIMARY_VENDOR_ID AS PRIMARY_VENDOR_ID,
  PARENT_VENDOR_ID AS PARENT_VENDOR_ID,
  COUNTRY_CD AS COUNTRY_CD,
  IMPORT_FLAG AS IMPORT_FLAG,
  HTS_CODE_ID AS HTS_CODE_ID,
  CONTENTS AS CONTENTS,
  CONTENTS_UNITS AS CONTENTS_UNITS,
  WEIGHT_NET_AMT AS WEIGHT_NET_AMT,
  WEIGHT_UOM_CD AS WEIGHT_UOM_CD,
  SIZE_DESC AS SIZE_DESC,
  BUM_QTY AS BUM_QTY,
  UOM_CD AS UOM_CD,
  UNIT_NUMERATOR AS UNIT_NUMERATOR,
  UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
  BUYER_ID AS BUYER_ID,
  PURCH_GROUP_ID AS PURCH_GROUP_ID,
  PURCH_COST_AMT AS PURCH_COST_AMT,
  NAT_PRICE_US_AMT AS NAT_PRICE_US_AMT,
  TAX_CLASS_ID AS TAX_CLASS_ID,
  VALUATION_CLASS_CD AS VALUATION_CLASS_CD,
  BRAND_CD AS BRAND_CD,
  BRAND_CLASSIFICATION_ID AS BRAND_CLASSIFICATION_ID,
  OWNBRAND_FLAG AS OWNBRAND_FLAG,
  STATELINE_FLAG AS STATELINE_FLAG,
  SIGN_TYPE_CD AS SIGN_TYPE_CD,
  OLD_ARTICLE_NBR AS OLD_ARTICLE_NBR,
  VENDOR_ARTICLE_NBR AS VENDOR_ARTICLE_NBR,
  INIT_MKDN_DT AS INIT_MKDN_DT,
  DISC_START_DT AS DISC_START_DT,
  ADD_DT AS ADD_DT,
  DELETE_DT AS DELETE_DT,
  UPDATE_DT AS UPDATE_DT,
  FIRST_SALE_DT AS FIRST_SALE_DT,
  LAST_SALE_DT AS LAST_SALE_DT,
  FIRST_INV_DT AS FIRST_INV_DT,
  LAST_INV_DT AS LAST_INV_DT,
  LOAD_DT AS LOAD_DT,
  BASE_NBR AS BASE_NBR,
  BP_COLOR_ID AS BP_COLOR_ID,
  BP_SIZE_ID AS BP_SIZE_ID,
  BP_BREED_ID AS BP_BREED_ID,
  BP_ITEM_CONCATENATED AS BP_ITEM_CONCATENATED,
  BP_AEROSOL_FLAG AS BP_AEROSOL_FLAG,
  BP_HAZMAT_FLAG AS BP_HAZMAT_FLAG,
  CANADIAN_HTS_CD AS CANADIAN_HTS_CD,
  NAT_PRICE_CA_AMT AS NAT_PRICE_CA_AMT,
  NAT_PRICE_PR_AMT AS NAT_PRICE_PR_AMT,
  RTV_DEPT_CD AS RTV_DEPT_CD,
  GL_ACCT_NBR AS GL_ACCT_NBR,
  ARTICLE_CATEGORY_ID AS ARTICLE_CATEGORY_ID,
  COMPONENT_FLAG AS COMPONENT_FLAG,
  ZDISCO_SCHED_TYPE_ID AS ZDISCO_SCHED_TYPE_ID,
  ZDISCO_MKDN_SCHED_ID AS ZDISCO_MKDN_SCHED_ID,
  ZDISCO_PID_DT AS ZDISCO_PID_DT,
  ZDISCO_START_DT AS ZDISCO_START_DT,
  ZDISCO_INIT_MKDN_DT AS ZDISCO_INIT_MKDN_DT,
  ZDISCO_DC_DT AS ZDISCO_DC_DT,
  ZDISCO_STR_DT AS ZDISCO_STR_DT,
  ZDISCO_STR_OWNRSHP_DT AS ZDISCO_STR_OWNRSHP_DT,
  ZDISCO_STR_WRT_OFF_DT AS ZDISCO_STR_WRT_OFF_DT
FROM
  SKU_PROFILE"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("Shortcut_To_SKU_PROFILE_2")

# COMMAND ----------
# DBTITLE 1, SQ_SKU_UOM__SCM_ITEM_MASTER_3


query_3 = f"""SELECT
  Shortcut_to_SCM_ITEM_MASTER_PRE_0.SCM_SKU_NBR AS SCM_SKU_NBR,
  Shortcut_to_SCM_ITEM_MASTER_PRE_0.SCM_SKU_UOM_CD AS SCM_SKU_UOM_CD,
  Shortcut_to_SCM_ITEM_MASTER_PRE_0.SCM_VOLUME_UOM_CD AS SCM_VOLUME_UOM_CD,
  Shortcut_to_SCM_ITEM_MASTER_PRE_0.SCM_VOLUME_AMT AS SCM_VOLUME_AMT,
  Shortcut_to_SCM_ITEM_MASTER_PRE_0.SCM_WEIGHT_UOM_CD AS SCM_WEIGHT_UOM_CD,
  Shortcut_to_SCM_ITEM_MASTER_PRE_0.SCM_WEIGHT_NET_AMT AS SCM_WEIGHT_NET_AMT,
  Shortcut_to_SCM_ITEM_MASTER_PRE_0.LOAD_TSTMP AS LOAD_TSTMP,
  Shortcut_To_SKU_UOM1_1.PRODUCT_ID AS PRODUCT_ID,
  Shortcut_To_SKU_UOM1_1.UOM_CD AS UOM_CD,
  Shortcut_To_SKU_UOM1_1.SCM_VOLUME_UOM_CD AS SCM_VOLUME_UOM_CD1,
  Shortcut_To_SKU_UOM1_1.SCM_VOLUME_AMT AS SCM_VOLUME_AMT1,
  Shortcut_To_SKU_UOM1_1.SCM_WEIGHT_UOM_CD AS SCM_WEIGHT_UOM_CD1,
  Shortcut_To_SKU_UOM1_1.SCM_WEIGHT_NET_AMT AS SCM_WEIGHT_NET_AMT1,
  Shortcut_To_SKU_UOM1_1.DELETE_DT AS DELETE_DT,
  Shortcut_To_SKU_UOM1_1.LOAD_DT AS LOAD_DT,
  Shortcut_To_SKU_PROFILE_2.PRODUCT_ID AS PRODUCT_ID1,
  Shortcut_To_SKU_PROFILE_2.SKU_NBR AS SKU_NBR,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_To_SKU_UOM1_1,
  Shortcut_to_SCM_ITEM_MASTER_PRE_0,
  Shortcut_To_SKU_PROFILE_2
WHERE
  Shortcut_To_SKU_PROFILE_2.PRODUCT_ID = Shortcut_To_SKU_UOM1_1.PRODUCT_ID
  AND Shortcut_To_SKU_PROFILE_2.SKU_NBR = Shortcut_to_SCM_ITEM_MASTER_PRE_0.SCM_SKU_NBR
  AND Shortcut_To_SKU_UOM1_1.UOM_CD = Shortcut_to_SCM_ITEM_MASTER_PRE_0.SCM_SKU_UOM_CD
  AND (
    Shortcut_to_SCM_ITEM_MASTER_PRE_0.SCM_VOLUME_AMT != NVL(Shortcut_To_SKU_UOM1_1.SCM_VOLUME_AMT, 0)
    OR Shortcut_to_SCM_ITEM_MASTER_PRE_0.SCM_WEIGHT_NET_AMT != NVL(Shortcut_To_SKU_UOM1_1.SCM_WEIGHT_NET_AMT, 0)
    OR Shortcut_to_SCM_ITEM_MASTER_PRE_0.SCM_VOLUME_UOM_CD != NVL(Shortcut_To_SKU_UOM1_1.VOLUME_UOM_CD, '0')
    OR Shortcut_to_SCM_ITEM_MASTER_PRE_0.SCM_WEIGHT_UOM_CD != NVL(Shortcut_To_SKU_UOM1_1.WEIGHT_UOM_CD, '0')
  )"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("SQ_SKU_UOM__SCM_ITEM_MASTER_3")

# COMMAND ----------
# DBTITLE 1, EXP_FIELDS_4


query_4 = f"""SELECT
  SCM_SKU_UOM_CD AS SCM_SKU_UOM_CD,
  PRODUCT_ID AS PRODUCT_ID,
  now() AS LOAD_DT,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_SKU_UOM__SCM_ITEM_MASTER_3"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("EXP_FIELDS_4")

# COMMAND ----------
# DBTITLE 1, UPS_SKU_UOM_5


query_5 = f"""SELECT
  EF4.PRODUCT_ID AS PRODUCT_ID,
  EF4.SCM_SKU_UOM_CD AS SCM_SKU_UOM_CD,
  SSUSIM3.SCM_VOLUME_UOM_CD AS SCM_VOLUME_UOM_CD,
  SSUSIM3.SCM_VOLUME_AMT AS SCM_VOLUME_AMT,
  SSUSIM3.SCM_WEIGHT_UOM_CD AS SCM_WEIGHT_UOM_CD,
  SSUSIM3.SCM_WEIGHT_NET_AMT AS SCM_WEIGHT_NET_AMT,
  EF4.LOAD_DT AS LOAD_DT,
  EF4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  EXP_FIELDS_4 EF4
  INNER JOIN SQ_SKU_UOM__SCM_ITEM_MASTER_3 SSUSIM3 ON EF4.Monotonically_Increasing_Id = SSUSIM3.Monotonically_Increasing_Id"""

df_5 = spark.sql(query_5)

df_5.createOrReplaceTempView("UPS_SKU_UOM_5")

# COMMAND ----------
# DBTITLE 1, SKU_UOM


spark.sql("""MERGE INTO SKU_UOM AS TARGET
USING
  UPS_SKU_UOM_5 AS SOURCE ON TARGET.UOM_CD = SOURCE.SCM_SKU_UOM_CD
  AND TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID
  WHEN MATCHED THEN
UPDATE
SET
  TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID,
  TARGET.UOM_CD = SOURCE.SCM_SKU_UOM_CD,
  TARGET.SCM_VOLUME_UOM_CD = SOURCE.SCM_VOLUME_UOM_CD,
  TARGET.SCM_VOLUME_AMT = SOURCE.SCM_VOLUME_AMT,
  TARGET.SCM_WEIGHT_UOM_CD = SOURCE.SCM_WEIGHT_UOM_CD,
  TARGET.SCM_WEIGHT_NET_AMT = SOURCE.SCM_WEIGHT_NET_AMT,
  TARGET.LOAD_DT = SOURCE.LOAD_DT""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_sku_uom_UPD_scm")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_sku_uom_UPD_scm", mainWorkflowId, parentName)
