# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ./MappingUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_SKU_SAP_Attr")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_SKU_SAP_Attr", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_SKU_SAP_ATTR_PRE_0


query_0 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  SKU_NBR AS SKU_NBR,
  SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
  SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
  SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
  SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
  SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
  SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
  SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
  SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
  SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
  SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
  SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
  SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
  SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
  SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  SKU_SAP_ATTR_PRE"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_SKU_SAP_ATTR_PRE_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_SKU_SAP_ATTR_PRE_1


query_1 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  SKU_NBR AS SKU_NBR,
  SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
  SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
  SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
  SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
  SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
  SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
  SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
  SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
  SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
  SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
  SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
  SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
  LOAD_TSTMP AS LOAD_TSTMP,
  SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
  SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_SKU_SAP_ATTR_PRE_0"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("SQ_Shortcut_to_SKU_SAP_ATTR_PRE_1")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_SKU_SAP_ATTR_2


query_2 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  SKU_NBR AS SKU_NBR,
  SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
  SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
  SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
  SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
  SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
  SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
  SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
  SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
  SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
  SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
  SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
  SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
  SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
  SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  SKU_SAP_ATTR"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("Shortcut_to_SKU_SAP_ATTR_2")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_SKU_SAP_ATTR_3


query_3 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  SKU_NBR AS SKU_NBR,
  SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
  SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
  SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
  SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
  SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
  SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
  SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
  SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
  SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
  SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
  SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
  SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
  SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_SKU_SAP_ATTR_2"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("SQ_Shortcut_to_SKU_SAP_ATTR_3")

# COMMAND ----------
# DBTITLE 1, JNR_SKU_SAP_ATTR_4


query_4 = f"""SELECT
  DETAIL.PRODUCT_ID AS PRODUCT_ID,
  DETAIL.SKU_NBR AS SKU_NBR,
  DETAIL.SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
  DETAIL.SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
  DETAIL.SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
  DETAIL.SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
  DETAIL.SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
  DETAIL.SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
  DETAIL.SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
  DETAIL.SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
  DETAIL.SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
  DETAIL.SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
  DETAIL.SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
  DETAIL.SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
  DETAIL.SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
  DETAIL.SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
  DETAIL.SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
  DETAIL.SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
  DETAIL.LOAD_TSTMP AS LOAD_TSTMP,
  MASTER.PRODUCT_ID AS PRODUCT_ID1,
  MASTER.SKU_NBR AS SKU_NBR1,
  MASTER.SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID1,
  MASTER.SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC1,
  MASTER.SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID1,
  MASTER.SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC1,
  MASTER.SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID1,
  MASTER.SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC1,
  MASTER.SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID1,
  MASTER.SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC1,
  MASTER.SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID1,
  MASTER.SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC1,
  MASTER.SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID1,
  MASTER.SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC1,
  MASTER.SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID1,
  MASTER.SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC1,
  MASTER.UPDATE_TSTMP AS UPDATE_TSTMP,
  MASTER.LOAD_TSTMP AS LOAD_TSTMP1,
  MASTER.SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID1,
  MASTER.SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC1,
  DETAIL.Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_SKU_SAP_ATTR_3 MASTER
  RIGHT JOIN SQ_Shortcut_to_SKU_SAP_ATTR_PRE_1 DETAIL ON MASTER.PRODUCT_ID = DETAIL.PRODUCT_ID"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("JNR_SKU_SAP_ATTR_4")

# COMMAND ----------
# DBTITLE 1, EXP_UPDT_TSTMP_5


query_5 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  SKU_NBR AS SKU_NBR,
  SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
  SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
  SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
  SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
  SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
  SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
  SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
  SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
  SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
  SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
  SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
  SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
  SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID1,
  SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC1,
  PRODUCT_ID1 AS PRODUCT_ID1,
  SKU_NBR1 AS SKU_NBR1,
  SKU_SAP_PROD_GROUP_ID1 AS SKU_SAP_PROD_GROUP_ID1,
  SKU_SAP_PROD_GROUP_DESC1 AS SKU_SAP_PROD_GROUP_DESC1,
  SKU_SAP_FAMILY_ID1 AS SKU_SAP_FAMILY_ID1,
  SKU_SAP_FAMILY_DESC1 AS SKU_SAP_FAMILY_DESC1,
  SKU_SAP_PPU_GROUP_ID1 AS SKU_SAP_PPU_GROUP_ID1,
  SKU_SAP_PPU_GROUP_DESC1 AS SKU_SAP_PPU_GROUP_DESC1,
  SKU_SAP_PRVT_LABEL_ID1 AS SKU_SAP_PRVT_LABEL_ID1,
  SKU_SAP_PRVT_LABEL_DESC1 AS SKU_SAP_PRVT_LABEL_DESC1,
  SKU_SAP_PRVT_LABEL_TIER_ID1 AS SKU_SAP_PRVT_LABEL_TIER_ID1,
  SKU_SAP_PRVT_LABEL_TIER_DESC1 AS SKU_SAP_PRVT_LABEL_TIER_DESC1,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_ID1 AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID1,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC1 AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC1,
  SKU_SAP_MAP_ID1 AS SKU_SAP_MAP_ID1,
  SKU_SAP_MAP_DESC1 AS SKU_SAP_MAP_DESC1,
  SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
  SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
  SYSTIMESTAMP() AS o_UPDATE_TSTMP,
  IFF(ISNULL(LOAD_TSTMP1), SYSTIMESTAMP(), LOAD_TSTMP1) AS o_LOAD_TSTMP,
  IFF(
    ISNULL(PRODUCT_ID1),
    'I',
    IFF(
      (SKU_NBR <> SKU_NBR1)
      OR IFF(
        ISNULL(SKU_SAP_PROD_GROUP_ID),
        9999,
        SKU_SAP_PROD_GROUP_ID
      ) <> IFF(
        ISNULL(SKU_SAP_PROD_GROUP_ID1),
        9999,
        SKU_SAP_PROD_GROUP_ID1
      )
      OR IFF(
        ISNULL(SKU_SAP_PROD_GROUP_DESC),
        ' ',
        SKU_SAP_PROD_GROUP_DESC
      ) <> IFF(
        ISNULL(SKU_SAP_PROD_GROUP_DESC1),
        ' ',
        SKU_SAP_PROD_GROUP_DESC1
      )
      OR IFF(ISNULL(SKU_SAP_FAMILY_ID), 9999, SKU_SAP_FAMILY_ID) <> IFF(
        ISNULL(SKU_SAP_FAMILY_ID1),
        9999,
        SKU_SAP_FAMILY_ID1
      )
      OR IFF(
        ISNULL(SKU_SAP_FAMILY_DESC),
        ' ',
        SKU_SAP_FAMILY_DESC
      ) <> IFF(
        ISNULL(SKU_SAP_FAMILY_DESC1),
        ' ',
        SKU_SAP_FAMILY_DESC1
      )
      OR IFF(
        ISNULL(SKU_SAP_PPU_GROUP_ID),
        9999,
        SKU_SAP_PPU_GROUP_ID
      ) <> IFF(
        ISNULL(SKU_SAP_PPU_GROUP_ID1),
        9999,
        SKU_SAP_PPU_GROUP_ID1
      )
      OR IFF(
        ISNULL(SKU_SAP_PPU_GROUP_DESC),
        ' ',
        SKU_SAP_PPU_GROUP_DESC
      ) <> IFF(
        ISNULL(SKU_SAP_PPU_GROUP_DESC1),
        ' ',
        SKU_SAP_PPU_GROUP_DESC1
      )
      OR IFF(
        ISNULL(SKU_SAP_PRVT_LABEL_ID),
        9999,
        SKU_SAP_PRVT_LABEL_ID
      ) <> IFF(
        ISNULL(SKU_SAP_PRVT_LABEL_ID1),
        9999,
        SKU_SAP_PRVT_LABEL_ID1
      )
      OR IFF(
        ISNULL(SKU_SAP_PRVT_LABEL_DESC),
        ' ',
        SKU_SAP_PRVT_LABEL_DESC
      ) <> IFF(
        ISNULL(SKU_SAP_PRVT_LABEL_DESC1),
        ' ',
        SKU_SAP_PRVT_LABEL_DESC1
      )
      OR IFF(ISNULL(SKU_SAP_MAP_DESC), ' ', SKU_SAP_MAP_DESC) <> IFF(ISNULL(SKU_SAP_MAP_DESC1), ' ', SKU_SAP_MAP_DESC1)
      OR IFF(
        ISNULL(SKU_SAP_PRVT_LABEL_TIER_DESC),
        ' ',
        SKU_SAP_PRVT_LABEL_TIER_DESC
      ) <> IFF(
        ISNULL(SKU_SAP_PRVT_LABEL_TIER_DESC1),
        ' ',
        SKU_SAP_PRVT_LABEL_TIER_DESC1
      )
      OR IFF(
        ISNULL(SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC),
        ' ',
        SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC
      ) <> IFF(
        ISNULL(SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC1),
        ' ',
        SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC1
      )
      OR IFF(ISNULL(SKU_SAP_KOI_ID), 9999, SKU_SAP_KOI_ID) <> IFF(ISNULL(SKU_SAP_KOI_ID), 9999, SKU_SAP_KOI_ID)
      OR IFF(ISNULL(SKU_SAP_KOI_DESC), 'ZZZ', SKU_SAP_KOI_DESC) <> IFF(ISNULL(SKU_SAP_KOI_DESC), 'ZZZ', SKU_SAP_KOI_DESC),
      'U',
      'R'
    )
  ) AS o_UPD_FLG,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  JNR_SKU_SAP_ATTR_4"""

df_5 = spark.sql(query_5)

df_5.createOrReplaceTempView("EXP_UPDT_TSTMP_5")

# COMMAND ----------
# DBTITLE 1, FIL_UPD_FLG_6


query_6 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  SKU_NBR AS SKU_NBR,
  SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
  SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
  SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
  SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
  SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
  SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
  SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
  SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
  SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
  SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
  SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
  SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
  SKU_SAP_KOI_ID1 AS SKU_SAP_KOI_ID,
  SKU_SAP_KOI_DESC1 AS SKU_SAP_KOI_DESC,
  o_UPDATE_TSTMP AS o_UPDATE_TSTMP,
  o_LOAD_TSTMP AS o_LOAD_TSTMP,
  o_UPD_FLG AS o_UPD_FLG,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  EXP_UPDT_TSTMP_5
WHERE
  o_UPD_FLG = 'I'
  OR o_UPD_FLG = 'U'"""

df_6 = spark.sql(query_6)

df_6.createOrReplaceTempView("FIL_UPD_FLG_6")

# COMMAND ----------
# DBTITLE 1, UPD_SKU_SAP_ATTR_7


query_7 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  SKU_NBR AS SKU_NBR,
  SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
  SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
  SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
  SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
  SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
  SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
  SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
  SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
  SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
  SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
  SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
  SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
  SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
  SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
  SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
  o_UPDATE_TSTMP AS o_UPDATE_TSTMP,
  o_LOAD_TSTMP AS o_LOAD_TSTMP,
  o_UPD_FLG AS o_UPD_FLG,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id,
  IFF(
    o_UPD_FLG = 'I',
    'DD_INSERT',
    IFF(o_UPD_FLG = 'U', 'DD_UPDATE')
  ) AS UPDATE_STRATEGY_FLAG
FROM
  FIL_UPD_FLG_6"""

df_7 = spark.sql(query_7)

df_7.createOrReplaceTempView("UPD_SKU_SAP_ATTR_7")

# COMMAND ----------
# DBTITLE 1, SKU_SAP_ATTR


spark.sql("""MERGE INTO SKU_SAP_ATTR AS TARGET
USING
  UPD_SKU_SAP_ATTR_7 AS SOURCE ON TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_UPDATE" THEN
UPDATE
SET
  TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID,
  TARGET.SKU_NBR = SOURCE.SKU_NBR,
  TARGET.SKU_SAP_PROD_GROUP_ID = SOURCE.SKU_SAP_PROD_GROUP_ID,
  TARGET.SKU_SAP_PROD_GROUP_DESC = SOURCE.SKU_SAP_PROD_GROUP_DESC,
  TARGET.SKU_SAP_FAMILY_ID = SOURCE.SKU_SAP_FAMILY_ID,
  TARGET.SKU_SAP_FAMILY_DESC = SOURCE.SKU_SAP_FAMILY_DESC,
  TARGET.SKU_SAP_PPU_GROUP_ID = SOURCE.SKU_SAP_PPU_GROUP_ID,
  TARGET.SKU_SAP_PPU_GROUP_DESC = SOURCE.SKU_SAP_PPU_GROUP_DESC,
  TARGET.SKU_SAP_PRVT_LABEL_ID = SOURCE.SKU_SAP_PRVT_LABEL_ID,
  TARGET.SKU_SAP_PRVT_LABEL_DESC = SOURCE.SKU_SAP_PRVT_LABEL_DESC,
  TARGET.SKU_SAP_PRVT_LABEL_TIER_ID = SOURCE.SKU_SAP_PRVT_LABEL_TIER_ID,
  TARGET.SKU_SAP_PRVT_LABEL_TIER_DESC = SOURCE.SKU_SAP_PRVT_LABEL_TIER_DESC,
  TARGET.SKU_SAP_PRVT_LABEL_PARENT_TIER_ID = SOURCE.SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
  TARGET.SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC = SOURCE.SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
  TARGET.SKU_SAP_MAP_ID = SOURCE.SKU_SAP_MAP_ID,
  TARGET.SKU_SAP_MAP_DESC = SOURCE.SKU_SAP_MAP_DESC,
  TARGET.SKU_SAP_KOI_ID = SOURCE.SKU_SAP_KOI_ID,
  TARGET.SKU_SAP_KOI_DESC = SOURCE.SKU_SAP_KOI_DESC,
  TARGET.UPDATE_TSTMP = SOURCE.o_UPDATE_TSTMP,
  TARGET.LOAD_TSTMP = SOURCE.o_LOAD_TSTMP
  WHEN MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_DELETE"
  AND TARGET.SKU_NBR = SOURCE.SKU_NBR
  AND TARGET.SKU_SAP_PROD_GROUP_ID = SOURCE.SKU_SAP_PROD_GROUP_ID
  AND TARGET.SKU_SAP_PROD_GROUP_DESC = SOURCE.SKU_SAP_PROD_GROUP_DESC
  AND TARGET.SKU_SAP_FAMILY_ID = SOURCE.SKU_SAP_FAMILY_ID
  AND TARGET.SKU_SAP_FAMILY_DESC = SOURCE.SKU_SAP_FAMILY_DESC
  AND TARGET.SKU_SAP_PPU_GROUP_ID = SOURCE.SKU_SAP_PPU_GROUP_ID
  AND TARGET.SKU_SAP_PPU_GROUP_DESC = SOURCE.SKU_SAP_PPU_GROUP_DESC
  AND TARGET.SKU_SAP_PRVT_LABEL_ID = SOURCE.SKU_SAP_PRVT_LABEL_ID
  AND TARGET.SKU_SAP_PRVT_LABEL_DESC = SOURCE.SKU_SAP_PRVT_LABEL_DESC
  AND TARGET.SKU_SAP_PRVT_LABEL_TIER_ID = SOURCE.SKU_SAP_PRVT_LABEL_TIER_ID
  AND TARGET.SKU_SAP_PRVT_LABEL_TIER_DESC = SOURCE.SKU_SAP_PRVT_LABEL_TIER_DESC
  AND TARGET.SKU_SAP_PRVT_LABEL_PARENT_TIER_ID = SOURCE.SKU_SAP_PRVT_LABEL_PARENT_TIER_ID
  AND TARGET.SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC = SOURCE.SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC
  AND TARGET.SKU_SAP_MAP_ID = SOURCE.SKU_SAP_MAP_ID
  AND TARGET.SKU_SAP_MAP_DESC = SOURCE.SKU_SAP_MAP_DESC
  AND TARGET.SKU_SAP_KOI_ID = SOURCE.SKU_SAP_KOI_ID
  AND TARGET.SKU_SAP_KOI_DESC = SOURCE.SKU_SAP_KOI_DESC
  AND TARGET.UPDATE_TSTMP = SOURCE.o_UPDATE_TSTMP
  AND TARGET.LOAD_TSTMP = SOURCE.o_LOAD_TSTMP THEN DELETE
  WHEN NOT MATCHED
  AND SOURCE.UPDATE_STRATEGY_FLAG = "DD_INSERT" THEN
INSERT
  (
    TARGET.PRODUCT_ID,
    TARGET.SKU_NBR,
    TARGET.SKU_SAP_PROD_GROUP_ID,
    TARGET.SKU_SAP_PROD_GROUP_DESC,
    TARGET.SKU_SAP_FAMILY_ID,
    TARGET.SKU_SAP_FAMILY_DESC,
    TARGET.SKU_SAP_PPU_GROUP_ID,
    TARGET.SKU_SAP_PPU_GROUP_DESC,
    TARGET.SKU_SAP_PRVT_LABEL_ID,
    TARGET.SKU_SAP_PRVT_LABEL_DESC,
    TARGET.SKU_SAP_PRVT_LABEL_TIER_ID,
    TARGET.SKU_SAP_PRVT_LABEL_TIER_DESC,
    TARGET.SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
    TARGET.SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
    TARGET.SKU_SAP_MAP_ID,
    TARGET.SKU_SAP_MAP_DESC,
    TARGET.SKU_SAP_KOI_ID,
    TARGET.SKU_SAP_KOI_DESC,
    TARGET.UPDATE_TSTMP,
    TARGET.LOAD_TSTMP
  )
VALUES
  (
    SOURCE.PRODUCT_ID,
    SOURCE.SKU_NBR,
    SOURCE.SKU_SAP_PROD_GROUP_ID,
    SOURCE.SKU_SAP_PROD_GROUP_DESC,
    SOURCE.SKU_SAP_FAMILY_ID,
    SOURCE.SKU_SAP_FAMILY_DESC,
    SOURCE.SKU_SAP_PPU_GROUP_ID,
    SOURCE.SKU_SAP_PPU_GROUP_DESC,
    SOURCE.SKU_SAP_PRVT_LABEL_ID,
    SOURCE.SKU_SAP_PRVT_LABEL_DESC,
    SOURCE.SKU_SAP_PRVT_LABEL_TIER_ID,
    SOURCE.SKU_SAP_PRVT_LABEL_TIER_DESC,
    SOURCE.SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
    SOURCE.SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
    SOURCE.SKU_SAP_MAP_ID,
    SOURCE.SKU_SAP_MAP_DESC,
    SOURCE.SKU_SAP_KOI_ID,
    SOURCE.SKU_SAP_KOI_DESC,
    SOURCE.o_UPDATE_TSTMP,
    SOURCE.o_LOAD_TSTMP
  )""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_SKU_SAP_Attr")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_SKU_SAP_Attr", mainWorkflowId, parentName)
