# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ./MappingUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_sku_profile_brand")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_sku_profile_brand", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_SKU_BRAND_PRE_0


query_0 = f"""SELECT
  SKU_NBR AS SKU_NBR,
  BRAND_CD AS BRAND_CD,
  BRAND_CLASSIFICATION_ID AS BRAND_CLASSIFICATION_ID
FROM
  SKU_BRAND_PRE"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_SKU_BRAND_PRE_0")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_SKU_PROFILE_1


query_1 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  SKU_NBR AS SKU_NBR,
  SKU_TYPE AS SKU_TYPE,
  PRIMARY_UPC_ID AS PRIMARY_UPC_ID,
  STATUS_ID AS STATUS_ID,
  SUBS_HIST_FLAG AS SUBS_HIST_FLAG,
  SUBS_CURR_FLAG AS SUBS_CURR_FLAG,
  SKU_DESC AS SKU_DESC,
  ALT_DESC AS ALT_DESC,
  SAP_CATEGORY_ID AS SAP_CATEGORY_ID,
  SAP_CLASS_ID AS SAP_CLASS_ID,
  SAP_DEPT_ID AS SAP_DEPT_ID,
  SAP_DIVISION_ID AS SAP_DIVISION_ID,
  PRIMARY_VENDOR_ID AS PRIMARY_VENDOR_ID,
  PARENT_VENDOR_ID AS PARENT_VENDOR_ID,
  COUNTRY_CD AS COUNTRY_CD,
  IMPORT_FLAG AS IMPORT_FLAG,
  HTS_CODE_ID AS HTS_CODE_ID,
  CONTENTS AS CONTENTS,
  CONTENTS_UNITS AS CONTENTS_UNITS,
  WEIGHT_NET_AMT AS WEIGHT_NET_AMT,
  WEIGHT_UOM_CD AS WEIGHT_UOM_CD,
  SIZE_DESC AS SIZE_DESC,
  BUM_QTY AS BUM_QTY,
  UOM_CD AS UOM_CD,
  UNIT_NUMERATOR AS UNIT_NUMERATOR,
  UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
  BUYER_ID AS BUYER_ID,
  PURCH_GROUP_ID AS PURCH_GROUP_ID,
  PURCH_COST_AMT AS PURCH_COST_AMT,
  NAT_PRICE_US_AMT AS NAT_PRICE_US_AMT,
  TAX_CLASS_ID AS TAX_CLASS_ID,
  VALUATION_CLASS_CD AS VALUATION_CLASS_CD,
  BRAND_CD AS BRAND_CD,
  BRAND_CLASSIFICATION_ID AS BRAND_CLASSIFICATION_ID,
  OWNBRAND_FLAG AS OWNBRAND_FLAG,
  STATELINE_FLAG AS STATELINE_FLAG,
  SIGN_TYPE_CD AS SIGN_TYPE_CD,
  OLD_ARTICLE_NBR AS OLD_ARTICLE_NBR,
  VENDOR_ARTICLE_NBR AS VENDOR_ARTICLE_NBR,
  INIT_MKDN_DT AS INIT_MKDN_DT,
  DISC_START_DT AS DISC_START_DT,
  ADD_DT AS ADD_DT,
  DELETE_DT AS DELETE_DT,
  UPDATE_DT AS UPDATE_DT,
  FIRST_SALE_DT AS FIRST_SALE_DT,
  LAST_SALE_DT AS LAST_SALE_DT,
  FIRST_INV_DT AS FIRST_INV_DT,
  LAST_INV_DT AS LAST_INV_DT,
  LOAD_DT AS LOAD_DT,
  BASE_NBR AS BASE_NBR,
  BP_COLOR_ID AS BP_COLOR_ID,
  BP_SIZE_ID AS BP_SIZE_ID,
  BP_BREED_ID AS BP_BREED_ID,
  BP_ITEM_CONCATENATED AS BP_ITEM_CONCATENATED,
  BP_AEROSOL_FLAG AS BP_AEROSOL_FLAG,
  BP_HAZMAT_FLAG AS BP_HAZMAT_FLAG,
  CANADIAN_HTS_CD AS CANADIAN_HTS_CD,
  NAT_PRICE_CA_AMT AS NAT_PRICE_CA_AMT,
  NAT_PRICE_PR_AMT AS NAT_PRICE_PR_AMT,
  RTV_DEPT_CD AS RTV_DEPT_CD,
  GL_ACCT_NBR AS GL_ACCT_NBR,
  ARTICLE_CATEGORY_ID AS ARTICLE_CATEGORY_ID,
  COMPONENT_FLAG AS COMPONENT_FLAG,
  ZDISCO_SCHED_TYPE_ID AS ZDISCO_SCHED_TYPE_ID,
  ZDISCO_MKDN_SCHED_ID AS ZDISCO_MKDN_SCHED_ID,
  ZDISCO_PID_DT AS ZDISCO_PID_DT,
  ZDISCO_START_DT AS ZDISCO_START_DT,
  ZDISCO_INIT_MKDN_DT AS ZDISCO_INIT_MKDN_DT,
  ZDISCO_DC_DT AS ZDISCO_DC_DT,
  ZDISCO_STR_DT AS ZDISCO_STR_DT,
  ZDISCO_STR_OWNRSHP_DT AS ZDISCO_STR_OWNRSHP_DT,
  ZDISCO_STR_WRT_OFF_DT AS ZDISCO_STR_WRT_OFF_DT
FROM
  SKU_PROFILE"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("Shortcut_to_SKU_PROFILE_1")

# COMMAND ----------
# DBTITLE 1, SQ_SKU_PROFILE_BRAND_2


query_2 = f"""SELECT
  Shortcut_to_SKU_BRAND_PRE_0.SKU_NBR AS SKU_NBR,
  Shortcut_to_SKU_BRAND_PRE_0.BRAND_CD AS BRAND_CD,
  Shortcut_to_SKU_BRAND_PRE_0.BRAND_CLASSIFICATION_ID AS BRAND_CLASSIFICATION_ID,
  Shortcut_to_SKU_PROFILE_1.PRODUCT_ID AS PRODUCT_ID,
  Shortcut_to_SKU_PROFILE_1.SKU_NBR AS SKU_NBR1,
  Shortcut_to_SKU_PROFILE_1.SKU_TYPE AS SKU_TYPE,
  Shortcut_to_SKU_PROFILE_1.PRIMARY_UPC_ID AS PRIMARY_UPC_ID,
  Shortcut_to_SKU_PROFILE_1.STATUS_ID AS STATUS_ID,
  Shortcut_to_SKU_PROFILE_1.SUBS_HIST_FLAG AS SUBS_HIST_FLAG,
  Shortcut_to_SKU_PROFILE_1.SUBS_CURR_FLAG AS SUBS_CURR_FLAG,
  Shortcut_to_SKU_PROFILE_1.SKU_DESC AS SKU_DESC,
  Shortcut_to_SKU_PROFILE_1.ALT_DESC AS ALT_DESC,
  Shortcut_to_SKU_PROFILE_1.SAP_CATEGORY_ID AS SAP_CATEGORY_ID,
  Shortcut_to_SKU_PROFILE_1.SAP_CLASS_ID AS SAP_CLASS_ID,
  Shortcut_to_SKU_PROFILE_1.SAP_DEPT_ID AS SAP_DEPT_ID,
  Shortcut_to_SKU_PROFILE_1.SAP_DIVISION_ID AS SAP_DIVISION_ID,
  Shortcut_to_SKU_PROFILE_1.PRIMARY_VENDOR_ID AS PRIMARY_VENDOR_ID,
  Shortcut_to_SKU_PROFILE_1.PARENT_VENDOR_ID AS PARENT_VENDOR_ID,
  Shortcut_to_SKU_PROFILE_1.COUNTRY_CD AS COUNTRY_CD,
  Shortcut_to_SKU_PROFILE_1.IMPORT_FLAG AS IMPORT_FLAG,
  Shortcut_to_SKU_PROFILE_1.HTS_CODE_ID AS HTS_CODE_ID,
  Shortcut_to_SKU_PROFILE_1.CONTENTS AS CONTENTS,
  Shortcut_to_SKU_PROFILE_1.CONTENTS_UNITS AS CONTENTS_UNITS,
  Shortcut_to_SKU_PROFILE_1.WEIGHT_NET_AMT AS WEIGHT_NET_AMT,
  Shortcut_to_SKU_PROFILE_1.WEIGHT_UOM_CD AS WEIGHT_UOM_CD,
  Shortcut_to_SKU_PROFILE_1.SIZE_DESC AS SIZE_DESC,
  Shortcut_to_SKU_PROFILE_1.BUM_QTY AS BUM_QTY,
  Shortcut_to_SKU_PROFILE_1.UOM_CD AS UOM_CD,
  Shortcut_to_SKU_PROFILE_1.UNIT_NUMERATOR AS UNIT_NUMERATOR,
  Shortcut_to_SKU_PROFILE_1.UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
  Shortcut_to_SKU_PROFILE_1.BUYER_ID AS BUYER_ID,
  Shortcut_to_SKU_PROFILE_1.PURCH_GROUP_ID AS PURCH_GROUP_ID,
  Shortcut_to_SKU_PROFILE_1.PURCH_COST_AMT AS PURCH_COST_AMT,
  Shortcut_to_SKU_PROFILE_1.NAT_PRICE_US_AMT AS NAT_PRICE_US_AMT,
  Shortcut_to_SKU_PROFILE_1.TAX_CLASS_ID AS TAX_CLASS_ID,
  Shortcut_to_SKU_PROFILE_1.VALUATION_CLASS_CD AS VALUATION_CLASS_CD,
  NULL AS BRAND_NAME,
  Shortcut_to_SKU_PROFILE_1.OWNBRAND_FLAG AS OWNBRAND_FLAG,
  Shortcut_to_SKU_PROFILE_1.STATELINE_FLAG AS STATELINE_FLAG,
  Shortcut_to_SKU_PROFILE_1.SIGN_TYPE_CD AS SIGN_TYPE_CD,
  Shortcut_to_SKU_PROFILE_1.OLD_ARTICLE_NBR AS OLD_ARTICLE_NBR,
  Shortcut_to_SKU_PROFILE_1.VENDOR_ARTICLE_NBR AS VENDOR_ARTICLE_NBR,
  Shortcut_to_SKU_PROFILE_1.INIT_MKDN_DT AS INIT_MKDN_DT,
  Shortcut_to_SKU_PROFILE_1.DISC_START_DT AS DISC_START_DT,
  Shortcut_to_SKU_PROFILE_1.ADD_DT AS ADD_DT,
  Shortcut_to_SKU_PROFILE_1.DELETE_DT AS DELETE_DT,
  Shortcut_to_SKU_PROFILE_1.UPDATE_DT AS UPDATE_DT,
  Shortcut_to_SKU_PROFILE_1.FIRST_SALE_DT AS FIRST_SALE_DT,
  Shortcut_to_SKU_PROFILE_1.LAST_SALE_DT AS LAST_SALE_DT,
  Shortcut_to_SKU_PROFILE_1.FIRST_INV_DT AS FIRST_INV_DT,
  Shortcut_to_SKU_PROFILE_1.LAST_INV_DT AS LAST_INV_DT,
  Shortcut_to_SKU_PROFILE_1.LOAD_DT AS LOAD_DT,
  Shortcut_to_SKU_PROFILE_1.BASE_NBR AS BASE_NBR,
  Shortcut_to_SKU_PROFILE_1.BP_COLOR_ID AS BP_COLOR_ID,
  Shortcut_to_SKU_PROFILE_1.BP_SIZE_ID AS BP_SIZE_ID,
  Shortcut_to_SKU_PROFILE_1.BP_BREED_ID AS BP_BREED_ID,
  Shortcut_to_SKU_PROFILE_1.BP_ITEM_CONCATENATED AS BP_ITEM_CONCATENATED,
  Shortcut_to_SKU_PROFILE_1.BP_AEROSOL_FLAG AS BP_AEROSOL_FLAG,
  Shortcut_to_SKU_PROFILE_1.BP_HAZMAT_FLAG AS BP_HAZMAT_FLAG,
  Shortcut_to_SKU_PROFILE_1.CANADIAN_HTS_CD AS CANADIAN_HTS_CD,
  Shortcut_to_SKU_PROFILE_1.NAT_PRICE_CA_AMT AS NAT_PRICE_CA_AMT,
  Shortcut_to_SKU_PROFILE_1.NAT_PRICE_PR_AMT AS NAT_PRICE_PR_AMT,
  Shortcut_to_SKU_PROFILE_1.RTV_DEPT_CD AS RTV_DEPT_CD,
  Shortcut_to_SKU_PROFILE_1.GL_ACCT_NBR AS GL_ACCT_NBR,
  Shortcut_to_SKU_PROFILE_1.ARTICLE_CATEGORY_ID AS ARTICLE_CATEGORY_ID,
  Shortcut_to_SKU_PROFILE_1.COMPONENT_FLAG AS COMPONENT_FLAG,
  Shortcut_to_SKU_PROFILE_1.ZDISCO_SCHED_TYPE_ID AS ZDISCO_SCHED_TYPE_ID,
  Shortcut_to_SKU_PROFILE_1.ZDISCO_MKDN_SCHED_ID AS ZDISCO_MKDN_SCHED_ID,
  Shortcut_to_SKU_PROFILE_1.ZDISCO_PID_DT AS ZDISCO_PID_DT,
  Shortcut_to_SKU_PROFILE_1.ZDISCO_START_DT AS ZDISCO_START_DT,
  Shortcut_to_SKU_PROFILE_1.ZDISCO_INIT_MKDN_DT AS ZDISCO_INIT_MKDN_DT,
  Shortcut_to_SKU_PROFILE_1.ZDISCO_DC_DT AS ZDISCO_DC_DT,
  Shortcut_to_SKU_PROFILE_1.ZDISCO_STR_DT AS ZDISCO_STR_DT,
  Shortcut_to_SKU_PROFILE_1.ZDISCO_STR_OWNRSHP_DT AS ZDISCO_STR_OWNRSHP_DT,
  Shortcut_to_SKU_PROFILE_1.ZDISCO_STR_WRT_OFF_DT AS ZDISCO_STR_WRT_OFF_DT,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_SKU_PROFILE_1,
  Shortcut_to_SKU_BRAND_PRE_0
WHERE
  Shortcut_to_SKU_BRAND_PRE_0.SKU_NBR = Shortcut_to_SKU_PROFILE_1.SKU_NBR"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("SQ_SKU_PROFILE_BRAND_2")

# COMMAND ----------
# DBTITLE 1, EXP_SKU_BRAND_3


query_3 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  BRAND_CD AS BRAND_CD,
  BRAND_CLASSIFICATION_ID AS BRAND_CLASSIFICATION_ID,
  now() AS UPDATE_DT,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_SKU_PROFILE_BRAND_2"""

df_3 = spark.sql(query_3)

df_3.createOrReplaceTempView("EXP_SKU_BRAND_3")

# COMMAND ----------
# DBTITLE 1, UPS_SKU_PROFILE_4


query_4 = f"""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  BRAND_CD AS BRAND_CD,
  BRAND_CLASSIFICATION_ID AS BRAND_CLASSIFICATION_ID,
  UPDATE_DT AS UPDATE_DT,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  EXP_SKU_BRAND_3"""

df_4 = spark.sql(query_4)

df_4.createOrReplaceTempView("UPS_SKU_PROFILE_4")

# COMMAND ----------
# DBTITLE 1, SKU_PROFILE


spark.sql("""MERGE INTO SKU_PROFILE AS TARGET
USING
  UPS_SKU_PROFILE_4 AS SOURCE ON TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID
  WHEN MATCHED THEN
UPDATE
SET
  TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID,
  TARGET.BRAND_CD = SOURCE.BRAND_CD,
  TARGET.BRAND_CLASSIFICATION_ID = SOURCE.BRAND_CLASSIFICATION_ID,
  TARGET.UPDATE_DT = SOURCE.UPDATE_DT""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_sku_profile_brand")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_sku_profile_brand", mainWorkflowId, parentName)
