# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")


# COMMAND ----------
# DBTITLE 1, Shortcut_to_ADOPTION_GROUP_0


df_0 = spark.sql("""SELECT
  ADOPTION_GROUP_ID AS ADOPTION_GROUP_ID,
  ADOPTION_GROUP_NAME AS ADOPTION_GROUP_NAME,
  ADOPTION_GROUP_PARENT_ID AS ADOPTION_GROUP_PARENT_ID,
  ADOPTION_GROUP_PARENT_NAME AS ADOPTION_GROUP_PARENT_NAME,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  ADOPTION_GROUP""")

df_0.createOrReplaceTempView("Shortcut_to_ADOPTION_GROUP_0")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_SALES_TRANS_ADOPTION_1


df_1 = spark.sql("""SELECT
  DAY_DT AS DAY_DT,
  LOCATION_ID AS LOCATION_ID,
  SALES_INSTANCE_ID AS SALES_INSTANCE_ID,
  UPC_ID AS UPC_ID,
  ADOPTION_GROUP_ID AS ADOPTION_GROUP_ID,
  POS_TXN_SEQ_NBR AS POS_TXN_SEQ_NBR,
  VOID_TYPE_CD AS VOID_TYPE_CD,
  SALES_TYPE_ID AS SALES_TYPE_ID,
  CUST_TRANS_ID AS CUST_TRANS_ID,
  PRODUCT_ID AS PRODUCT_ID,
  ADOPTION_QTY AS ADOPTION_QTY,
  ADOPTION_RETURN_QTY AS ADOPTION_RETURN_QTY,
  DATE_LOADED AS DATE_LOADED
FROM
  SALES_TRANS_ADOPTION""")

df_1.createOrReplaceTempView("Shortcut_to_SALES_TRANS_ADOPTION_1")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_SKU_PROFILE_RPT_2


df_2 = spark.sql("""SELECT
  PRODUCT_ID AS PRODUCT_ID,
  SKU_NBR AS SKU_NBR,
  SKU_TYPE AS SKU_TYPE,
  PRIMARY_UPC_ID AS PRIMARY_UPC_ID,
  STATUS_ID AS STATUS_ID,
  STATUS_NAME AS STATUS_NAME,
  SUBS_HIST_FLAG AS SUBS_HIST_FLAG,
  SUBS_CURR_FLAG AS SUBS_CURR_FLAG,
  SKU_DESC AS SKU_DESC,
  ALT_DESC AS ALT_DESC,
  SAP_CATEGORY_ID AS SAP_CATEGORY_ID,
  SAP_CATEGORY_DESC AS SAP_CATEGORY_DESC,
  GL_CATEGORY_CD AS GL_CATEGORY_CD,
  GL_CATEGORY_DESC AS GL_CATEGORY_DESC,
  BUS_UNIT_ID AS BUS_UNIT_ID,
  BUS_UNIT_DESC AS BUS_UNIT_DESC,
  SVP_ID AS SVP_ID,
  SVP_DESC AS SVP_DESC,
  VP_ID AS VP_ID,
  VP_NM AS VP_NM,
  VP_DESC AS VP_DESC,
  CATEGORY_BUYER_ID AS CATEGORY_BUYER_ID,
  CATEGORY_BUYER_NM AS CATEGORY_BUYER_NM,
  CA_BUYER_ID AS CA_BUYER_ID,
  CA_BUYER_NM AS CA_BUYER_NM,
  DIRECTOR_ID AS DIRECTOR_ID,
  DIRECTOR_DESC AS DIRECTOR_DESC,
  CA_DIRECTOR_ID AS CA_DIRECTOR_ID,
  CA_DIRECTOR_DESC AS CA_DIRECTOR_DESC,
  PRICING_ROLE_ID AS PRICING_ROLE_ID,
  PRICING_ROLE_DESC AS PRICING_ROLE_DESC,
  SAP_CLASS_ID AS SAP_CLASS_ID,
  SAP_CLASS_DESC AS SAP_CLASS_DESC,
  SAP_DEPT_ID AS SAP_DEPT_ID,
  SAP_DEPT_DESC AS SAP_DEPT_DESC,
  CONSUM_ID AS CONSUM_ID,
  CONSUM_DESC AS CONSUM_DESC,
  SEGMENT_ID AS SEGMENT_ID,
  SEGMENT_DESC AS SEGMENT_DESC,
  SAP_DIVISION_ID AS SAP_DIVISION_ID,
  SAP_DIVISION_DESC AS SAP_DIVISION_DESC,
  PRIMARY_VENDOR_ID AS PRIMARY_VENDOR_ID,
  PRIMARY_VENDOR_NAME AS PRIMARY_VENDOR_NAME,
  VENDOR_SUBRANGE_CD AS VENDOR_SUBRANGE_CD,
  PURCH_GROUP_ID AS PURCH_GROUP_ID,
  PURCH_GROUP_NAME AS PURCH_GROUP_NAME,
  PARENT_VENDOR_ID AS PARENT_VENDOR_ID,
  PARENT_VENDOR_NAME AS PARENT_VENDOR_NAME,
  COUNTRY_CD AS COUNTRY_CD,
  COUNTRY_NAME AS COUNTRY_NAME,
  IMPORT_FLAG AS IMPORT_FLAG,
  IMPORT_DESC AS IMPORT_DESC,
  HTS_CODE_ID AS HTS_CODE_ID,
  HTS_CODE_DESC AS HTS_CODE_DESC,
  CONTENTS AS CONTENTS,
  CONTENTS_UNITS AS CONTENTS_UNITS,
  WEIGHT_NET_AMT AS WEIGHT_NET_AMT,
  WEIGHT_UOM_CD AS WEIGHT_UOM_CD,
  SIZE_DESC AS SIZE_DESC,
  BUM_QTY AS BUM_QTY,
  UOM_CD AS UOM_CD,
  UNIT_NUMERATOR AS UNIT_NUMERATOR,
  UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
  BUYER_ID AS BUYER_ID,
  BUYER_NAME AS BUYER_NAME,
  PURCH_COST_AMT AS PURCH_COST_AMT,
  NAT_PRICE_US_AMT AS NAT_PRICE_US_AMT,
  TAX_CLASS_ID AS TAX_CLASS_ID,
  TAX_CLASS_DESC AS TAX_CLASS_DESC,
  VALUATION_CLASS_CD AS VALUATION_CLASS_CD,
  VALUATION_CLASS_DESC AS VALUATION_CLASS_DESC,
  BRAND_CD AS BRAND_CD,
  BRAND_NAME AS BRAND_NAME,
  BRAND_CLASSIFICATION_ID AS BRAND_CLASSIFICATION_ID,
  BRAND_CLASSIFICATION_NAME AS BRAND_CLASSIFICATION_NAME,
  OWNBRAND_FLAG AS OWNBRAND_FLAG,
  OWNBRAND_DESC AS OWNBRAND_DESC,
  STATELINE_FLAG AS STATELINE_FLAG,
  SIGN_TYPE_CD AS SIGN_TYPE_CD,
  SIGN_TYPE_DESC AS SIGN_TYPE_DESC,
  OLD_ARTICLE_NBR AS OLD_ARTICLE_NBR,
  VENDOR_ARTICLE_NBR AS VENDOR_ARTICLE_NBR,
  INIT_MKDN_DT AS INIT_MKDN_DT,
  DISC_START_DT AS DISC_START_DT,
  ADD_DT AS ADD_DT,
  DELETE_DT AS DELETE_DT,
  FIRST_SALE_DT AS FIRST_SALE_DT,
  LAST_SALE_DT AS LAST_SALE_DT,
  FIRST_INV_DT AS FIRST_INV_DT,
  LAST_INV_DT AS LAST_INV_DT,
  BASE_NBR AS BASE_NBR,
  BP_COLOR_ID AS BP_COLOR_ID,
  BP_SIZE_ID AS BP_SIZE_ID,
  BP_BREED_ID AS BP_BREED_ID,
  BP_ITEM_CONCATENATED AS BP_ITEM_CONCATENATED,
  CANADIAN_HTS_CD AS CANADIAN_HTS_CD,
  NAT_PRICE_CA_AMT AS NAT_PRICE_CA_AMT,
  NAT_PRICE_PR_AMT AS NAT_PRICE_PR_AMT,
  RTV_DEPT_CD AS RTV_DEPT_CD,
  RTV_DESC AS RTV_DESC,
  HAZ_FLAG AS HAZ_FLAG,
  AEROSOL_FLAG AS AEROSOL_FLAG,
  GL_ACCT_NBR AS GL_ACCT_NBR,
  ARTICLE_CATEGORY_ID AS ARTICLE_CATEGORY_ID,
  ARTICLE_CATEGORY_DESC AS ARTICLE_CATEGORY_DESC,
  ARTICLE_CATEGORY_CD AS ARTICLE_CATEGORY_CD,
  COMPONENT_FLAG AS COMPONENT_FLAG,
  ZDISCO_SCHED_TYPE_ID AS ZDISCO_SCHED_TYPE_ID,
  ZDISCO_SCHED_TYPE_DESC AS ZDISCO_SCHED_TYPE_DESC,
  ZDISCO_MKDN_SCHED_ID AS ZDISCO_MKDN_SCHED_ID,
  ZDISCO_MKDN_SCHED_DESC AS ZDISCO_MKDN_SCHED_DESC,
  ZDISCO_PID_DT AS ZDISCO_PID_DT,
  ZDISCO_START_DT AS ZDISCO_START_DT,
  ZDISCO_INIT_MKDN_DT AS ZDISCO_INIT_MKDN_DT,
  ZDISCO_DC_DT AS ZDISCO_DC_DT,
  ZDISCO_STR_DT AS ZDISCO_STR_DT,
  ZDISCO_STR_OWNRSHP_DT AS ZDISCO_STR_OWNRSHP_DT,
  ZDISCO_STR_WRT_OFF_DT AS ZDISCO_STR_WRT_OFF_DT,
  OPT_DEMAND_GROUP AS OPT_DEMAND_GROUP,
  OPT_PRODUCT_LINE AS OPT_PRODUCT_LINE,
  OPT_PRICE_FAMILY AS OPT_PRICE_FAMILY,
  OPT_EFFECTIVE_SIZE AS OPT_EFFECTIVE_SIZE,
  OPT_SELL_UNITS AS OPT_SELL_UNITS,
  OPT_UNIT_PRICE AS OPT_UNIT_PRICE,
  OPT_MOD_PRICE AS OPT_MOD_PRICE,
  OPT_MOD_COST AS OPT_MOD_COST,
  OPT_IS_NEW AS OPT_IS_NEW,
  OPT_ERROR_CODE AS OPT_ERROR_CODE,
  OPT_RELATIONSHIP AS OPT_RELATIONSHIP,
  OPT_METRIC AS OPT_METRIC,
  OPT_DIFF AS OPT_DIFF,
  OPT_ASSOC_PROD AS OPT_ASSOC_PROD,
  OPT_DELETE_OPTION AS OPT_DELETE_OPTION,
  DISC_SKU_NBR AS DISC_SKU_NBR,
  AVG_SALES AS AVG_SALES,
  COPY_SKU_NBR AS COPY_SKU_NBR,
  COPY_SKU_PCT AS COPY_SKU_PCT,
  PROCUREMENT_RULE_CD AS PROCUREMENT_RULE_CD,
  PROCUREMENT_RULE_DESC AS PROCUREMENT_RULE_DESC,
  CATEGORY_ANALYST_ID AS CATEGORY_ANALYST_ID,
  CATEGORY_ANALYST_NM AS CATEGORY_ANALYST_NM,
  CATEGORY_REPLENISHMENT_MGR_ID AS CATEGORY_REPLENISHMENT_MGR_ID,
  CATEGORY_REPLENISHMENT_MGR_NM AS CATEGORY_REPLENISHMENT_MGR_NM,
  CREATED_BY AS CREATED_BY,
  SHELF_LIFE_REM_CNT AS SHELF_LIFE_REM_CNT,
  TEMP_SKU AS TEMP_SKU,
  CONTENTS_METRICS AS CONTENTS_METRICS,
  CONTENTS_UNITS_METRICS AS CONTENTS_UNITS_METRICS,
  FLAVOR_CD AS FLAVOR_CD,
  FLAVOR_DESC AS FLAVOR_DESC,
  BASIC_MATERIAL AS BASIC_MATERIAL,
  CONTAINER_CD AS CONTAINER_CD,
  CONTAINER_DESC AS CONTAINER_DESC,
  RX_FLAG AS RX_FLAG,
  UPDATE_DT AS UPDATE_DT,
  LOAD_DT AS LOAD_DT
FROM
  SKU_PROFILE_RPT""")

df_2.createOrReplaceTempView("Shortcut_to_SKU_PROFILE_RPT_2")

# COMMAND ----------
# DBTITLE 1, Shortcut_to_SITE_PROFILE_RPT_3


df_3 = spark.sql("""SELECT
  LOCATION_ID AS LOCATION_ID,
  LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
  LOCATION_TYPE_DESC AS LOCATION_TYPE_DESC,
  STORE_NBR AS STORE_NBR,
  STORE_NAME AS STORE_NAME,
  STORE_TYPE_ID AS STORE_TYPE_ID,
  STORE_TYPE_DESC AS STORE_TYPE_DESC,
  PARENT_LOCATION_ID AS PARENT_LOCATION_ID,
  LOCATION_NBR AS LOCATION_NBR,
  COMPANY_ID AS COMPANY_ID,
  COMPANY_DESC AS COMPANY_DESC,
  SUPER_REGION_ID AS SUPER_REGION_ID,
  SUPER_REGION_DESC AS SUPER_REGION_DESC,
  REGION_ID AS REGION_ID,
  REGION_DESC AS REGION_DESC,
  DISTRICT_ID AS DISTRICT_ID,
  DISTRICT_DESC AS DISTRICT_DESC,
  SITE_ADDRESS AS SITE_ADDRESS,
  SITE_CITY AS SITE_CITY,
  SITE_COUNTY AS SITE_COUNTY,
  STATE_CD AS STATE_CD,
  STATE_NAME AS STATE_NAME,
  POSTAL_CD AS POSTAL_CD,
  COUNTRY_CD AS COUNTRY_CD,
  COUNTRY_NAME AS COUNTRY_NAME,
  GEO_LATITUDE_NBR AS GEO_LATITUDE_NBR,
  GEO_LONGITUDE_NBR AS GEO_LONGITUDE_NBR,
  PETSMART_DMA_CD AS PETSMART_DMA_CD,
  PETSMART_DMA_DESC AS PETSMART_DMA_DESC,
  SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
  SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
  SITE_FAX_NO AS SITE_FAX_NO,
  SITE_EMAIL_ADDRESS AS SITE_EMAIL_ADDRESS,
  STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
  SFT_OPEN_DT AS SFT_OPEN_DT,
  OPEN_DT AS OPEN_DT,
  GR_OPEN_DT AS GR_OPEN_DT,
  CLOSE_DT AS CLOSE_DT,
  SITE_SALES_FLAG AS SITE_SALES_FLAG,
  SALES_CURR_FLAG AS SALES_CURR_FLAG,
  SITE_OPEN_YRS_AMT AS SITE_OPEN_YRS_AMT,
  FIRST_SALE_DT AS FIRST_SALE_DT,
  FIRST_MEASURED_SALE_DT AS FIRST_MEASURED_SALE_DT,
  LAST_SALE_DT AS LAST_SALE_DT,
  COMP_CURR_FLAG AS COMP_CURR_FLAG,
  COMP_EFF_DT AS COMP_EFF_DT,
  COMP_END_DT AS COMP_END_DT,
  TP_LOC_FLAG AS TP_LOC_FLAG,
  TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
  TP_START_DT AS TP_START_DT,
  HOTEL_FLAG AS HOTEL_FLAG,
  HOTEL_OPEN_DT AS HOTEL_OPEN_DT,
  DAYCAMP_FLAG AS DAYCAMP_FLAG,
  VET_FLAG AS VET_FLAG,
  TIME_ZONE_ID AS TIME_ZONE_ID,
  TIME_ZONE AS TIME_ZONE,
  SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
  SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
  TRADE_AREA AS TRADE_AREA,
  DELV_SERVICE_CLASS_ID AS DELV_SERVICE_CLASS_ID,
  PICK_SERVICE_CLASS_ID AS PICK_SERVICE_CLASS_ID,
  REPL_DC_NBR AS REPL_DC_NBR,
  REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
  REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
  PROMO_LABEL_CD AS PROMO_LABEL_CD,
  PRICE_ZONE_ID AS PRICE_ZONE_ID,
  PRICE_ZONE_DESC AS PRICE_ZONE_DESC,
  PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
  PRICE_AD_ZONE_DESC AS PRICE_AD_ZONE_DESC,
  EQUINE_MERCH_ID AS EQUINE_MERCH_ID,
  EQUINE_MERCH_DESC AS EQUINE_MERCH_DESC,
  EQUINE_SITE_ID AS EQUINE_SITE_ID,
  EQUINE_SITE_DESC AS EQUINE_SITE_DESC,
  EQUINE_SITE_OPEN_DT AS EQUINE_SITE_OPEN_DT,
  LOYALTY_PGM_TYPE_ID AS LOYALTY_PGM_TYPE_ID,
  LOYALTY_PGM_TYPE_DESC AS LOYALTY_PGM_TYPE_DESC,
  LOYALTY_PGM_STATUS_ID AS LOYALTY_PGM_STATUS_ID,
  LOYALTY_PGM_STATUS_DESC AS LOYALTY_PGM_STATUS_DESC,
  LOYALTY_PGM_START_DT AS LOYALTY_PGM_START_DT,
  LOYALTY_PGM_CHANGE_DT AS LOYALTY_PGM_CHANGE_DT,
  BP_COMPANY_NBR AS BP_COMPANY_NBR,
  BP_GL_ACCT AS BP_GL_ACCT,
  SITE_LOGIN_ID AS SITE_LOGIN_ID,
  SITE_MANAGER_ID AS SITE_MANAGER_ID,
  SITE_MANAGER_NAME AS SITE_MANAGER_NAME,
  MGR_ID AS MGR_ID,
  MGR_DESC AS MGR_DESC,
  DVL_ID AS DVL_ID,
  DVL_DESC AS DVL_DESC,
  PURCH_GROUP_ID AS PURCH_GROUP_ID,
  PURCH_GROUP_NAME AS PURCH_GROUP_NAME,
  TOTAL_SALES_RANKING_CD AS TOTAL_SALES_RANKING_CD,
  MERCH_SALES_RANKING_CD AS MERCH_SALES_RANKING_CD,
  SERVICES_SALES_RANKING_CD AS SERVICES_SALES_RANKING_CD,
  SALON_SALES_RANKING_CD AS SALON_SALES_RANKING_CD,
  TRAINING_SALES_RANKING_CD AS TRAINING_SALES_RANKING_CD,
  HOTEL_DDC_SALES_RANKING_CD AS HOTEL_DDC_SALES_RANKING_CD,
  CONSUMABLES_SALES_RANKING_CD AS CONSUMABLES_SALES_RANKING_CD,
  HARDGOODS_SALES_RANKING_CD AS HARDGOODS_SALES_RANKING_CD,
  SPECIALTY_SALES_RANKING_CD AS SPECIALTY_SALES_RANKING_CD,
  DIST_MGR_NAME AS DIST_MGR_NAME,
  DM_EMAIL_ADDRESS AS DM_EMAIL_ADDRESS,
  DC_AREA_DIRECTOR_NAME AS DC_AREA_DIRECTOR_NAME,
  DC_AREA_DIRECTOR_EMAIL AS DC_AREA_DIRECTOR_EMAIL,
  DIST_SVC_MGR_NAME AS DIST_SVC_MGR_NAME,
  DSM_EMAIL_ADDRESS AS DSM_EMAIL_ADDRESS,
  REGION_VP_NAME AS REGION_VP_NAME,
  RVP_EMAIL_ADDRESS AS RVP_EMAIL_ADDRESS,
  REGION_TRAINER_NAME AS REGION_TRAINER_NAME,
  ASSET_PROTECT_NAME AS ASSET_PROTECT_NAME,
  ASSET_PROTECT_EMAIL AS ASSET_PROTECT_EMAIL,
  LP_SAFETY_DIRECTOR_NAME AS LP_SAFETY_DIRECTOR_NAME,
  LP_SAFETY_DIRECTOR_EMAIL AS LP_SAFETY_DIRECTOR_EMAIL,
  SR_LP_SAFETY_MGR_NAME AS SR_LP_SAFETY_MGR_NAME,
  SR_LP_SAFETY_MGR_EMAIL AS SR_LP_SAFETY_MGR_EMAIL,
  REGIONAL_LP_SAFETY_MGR_NAME AS REGIONAL_LP_SAFETY_MGR_NAME,
  REGIONAL_LP_SAFETY_MGR_EMAIL AS REGIONAL_LP_SAFETY_MGR_EMAIL,
  RETAIL_MANAGER_SAFETY_NAME AS RETAIL_MANAGER_SAFETY_NAME,
  RETAIL_MANAGER_SAFETY_EMAIL AS RETAIL_MANAGER_SAFETY_EMAIL,
  DC_GENERAL_MANAGER_NAME AS DC_GENERAL_MANAGER_NAME,
  DC_GENERAL_MANAGER_EMAIL AS DC_GENERAL_MANAGER_EMAIL,
  ASST_DC_GENERAL_MANAGER_NAME1 AS ASST_DC_GENERAL_MANAGER_NAME1,
  ASST_DC_GENERAL_MANAGER_EMAIL1 AS ASST_DC_GENERAL_MANAGER_EMAIL1,
  ASST_DC_GENERAL_MANAGER_NAME2 AS ASST_DC_GENERAL_MANAGER_NAME2,
  ASST_DC_GENERAL_MANAGER_EMAIL2 AS ASST_DC_GENERAL_MANAGER_EMAIL2,
  HR_MANAGER_NAME AS HR_MANAGER_NAME,
  HR_MANAGER_EMAIL AS HR_MANAGER_EMAIL,
  HR_SUPERVISOR_NAME1 AS HR_SUPERVISOR_NAME1,
  HR_SUPERVISOR_EMAIL1 AS HR_SUPERVISOR_EMAIL1,
  HR_SUPERVISOR_NAME2 AS HR_SUPERVISOR_NAME2,
  HR_SUPERVISOR_EMAIL2 AS HR_SUPERVISOR_EMAIL2,
  LEARN_SOLUTION_MGR_NAME AS LEARN_SOLUTION_MGR_NAME,
  LEARN_SOLUTION_MGR_EMAIL AS LEARN_SOLUTION_MGR_EMAIL,
  ADD_DT AS ADD_DT,
  DELETE_DT AS DELETE_DT,
  UPDATE_DT AS UPDATE_DT,
  LOAD_DT AS LOAD_DT
FROM
  SITE_PROFILE_RPT""")

df_3.createOrReplaceTempView("Shortcut_to_SITE_PROFILE_RPT_3")

# COMMAND ----------
# DBTITLE 1, SQ_Adoptions_4


df_4 = spark.sql("""SELECT
  Shortcut_to_SALES_TRANS_ADOPTION_1.DAY_DT AS DAY_DT,
  Shortcut_to_SALES_TRANS_ADOPTION_1.DATE_LOADED AS DATE_LOADED,
  Shortcut_to_ADOPTION_GROUP_0.ADOPTION_GROUP_ID AS ADOPTION_GROUP_ID,
  Shortcut_to_ADOPTION_GROUP_0.ADOPTION_GROUP_NAME AS ADOPTION_GROUP_NAME,
  Shortcut_to_ADOPTION_GROUP_0.ADOPTION_GROUP_PARENT_ID AS ADOPTION_GROUP_PARENT_ID,
  Shortcut_to_ADOPTION_GROUP_0.ADOPTION_GROUP_PARENT_NAME AS ADOPTION_GROUP_PARENT_NAME,
  Shortcut_to_ADOPTION_GROUP_0.UPDATE_TSTMP AS UPDATE_TSTMP,
  Shortcut_to_ADOPTION_GROUP_0.LOAD_TSTMP AS LOAD_TSTMP,
  Shortcut_to_SALES_TRANS_ADOPTION_1.SALES_INSTANCE_ID AS SALES_INSTANCE_ID,
  Shortcut_to_SITE_PROFILE_RPT_3.STORE_NAME AS STORE_NAME,
  Shortcut_to_SITE_PROFILE_RPT_3.STORE_NBR AS STORE_NBR,
  Shortcut_to_SKU_PROFILE_RPT_2.SKU_NBR AS SKU_NBR,
  Shortcut_to_SALES_TRANS_ADOPTION_1.ADOPTION_QTY AS ADOPTION_QTY,
  Shortcut_to_SALES_TRANS_ADOPTION_1.ADOPTION_RETURN_QTY AS ADOPTION_RETURN_QTY,
  Shortcut_to_SKU_PROFILE_RPT_2.SKU_DESC AS SKU_DESC,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_SITE_PROFILE_RPT_3,
  Shortcut_to_SKU_PROFILE_RPT_2,
  Shortcut_to_ADOPTION_GROUP_0,
  Shortcut_to_SALES_TRANS_ADOPTION_1
WHERE
  Shortcut_to_SALES_TRANS_ADOPTION_1.UPC_ID = Shortcut_to_SKU_PROFILE_RPT_2.PRIMARY_UPC_ID
  AND Shortcut_to_SALES_TRANS_ADOPTION_1.LOCATION_ID = Shortcut_to_SITE_PROFILE_RPT_3.LOCATION_ID
  AND Shortcut_to_SALES_TRANS_ADOPTION_1.ADOPTION_GROUP_ID = Shortcut_to_ADOPTION_GROUP_0.ADOPTION_GROUP_ID
  AND $$Flag_Filter
  AND $$Load_Filter
ORDER BY
  DAY_DT,
  DATE_LOADED""")

df_4.createOrReplaceTempView("SQ_Adoptions_4")

# COMMAND ----------
# DBTITLE 1, EXP_Species_5


df_5 = spark.sql("""SELECT
  ADOPTION_GROUP_ID AS ADOPTION_GROUP_ID,
  $$Species AS SPECIES,
  ADOPTION_QTY - ADOPTION_RETURN_QTY AS NET_ADOPTIONS,
  ADOPTION_GROUP_NAME AS ADOPTION_GROUP_NAME,
  ADOPTION_GROUP_PARENT_ID AS ADOPTION_GROUP_PARENT_ID,
  ADOPTION_GROUP_PARENT_NAME AS ADOPTION_GROUP_PARENT_NAME,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP,
  TO_CHAR(DAY_DT, 'YYYY-MM-DD') AS DAY_DT,
  SALES_INSTANCE_ID AS SALES_INSTANCE_ID,
  STORE_NAME AS STORE_NAME,
  STORE_NBR AS STORE_NBR,
  SKU_NBR AS SKU_NBR,
  ADOPTION_QTY AS ADOPTION_QTY,
  ADOPTION_RETURN_QTY AS ADOPTION_RETURN_QTY,
  SKU_DESC AS SKU_DESC,
  DATE_LOADED AS DATE_LOADED,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Adoptions_4""")

df_5.createOrReplaceTempView("EXP_Species_5")

# COMMAND ----------
# DBTITLE 1, SmartSimple_CharitiesAdoptions_FF


spark.sql("""INSERT INTO
  SmartSimple_CharitiesAdoptions_FF
SELECT
  DAY_DT AS DAY_DT,
  SALES_INSTANCE_ID AS SALES_INSTANCE_ID,
  ADOPTION_GROUP_PARENT_ID AS ADOPTION_GROUP_PARENT_ID,
  STORE_NBR AS STORE_NBR,
  STORE_NAME AS STORE_NAME,
  SKU_NBR AS SKU_NBR,
  SPECIES AS SPECIES,
  ADOPTION_QTY AS ADOPTION_QTY,
  ADOPTION_RETURN_QTY AS ADOPTION_RETURN_QTY,
  NET_ADOPTIONS AS NET_ADOPTIONS
FROM
  EXP_Species_5""")