# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")


# COMMAND ----------
# DBTITLE 1, Shortcut_to_UDH_PCH_MEDIA_IMPRESSIONS_0


df_0 = spark.sql("""SELECT
  RECORD_GID AS RECORD_GID,
  MEDIA_TYPE AS MEDIA_TYPE,
  MEDIA_DT AS MEDIA_DT,
  MEDIA_OUTLET AS MEDIA_OUTLET,
  MEDIA_CITY AS MEDIA_CITY,
  MEDIA_STATE AS MEDIA_STATE,
  FREQUENCY AS FREQUENCY,
  IMPRESSIONS AS IMPRESSIONS,
  MEDIA_VALUE AS MEDIA_VALUE,
  HEADLINE_LEAD_IN AS HEADLINE_LEAD_IN,
  REPORT_MONTH AS REPORT_MONTH,
  ACTION AS ACTION,
  PCH_MI_GID AS PCH_MI_GID,
  USER_ID AS USER_ID,
  UPDATE_TSTMP AS UPDATE_TSTMP,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  UDH_PCH_MEDIA_IMPRESSIONS""")

df_0.createOrReplaceTempView("Shortcut_to_UDH_PCH_MEDIA_IMPRESSIONS_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_UDH_PCH_MEDIA_IMPRESSIONS_1


df_1 = spark.sql("""SELECT
  upmi.pch_mi_gid AS RECORD_GID,
  upmi.USER_ID AS USER_ID,
  upmi.record_gid AS PCH_MI_GID,
  1 AS DELETED_IND,
  GETDATE() AS LOAD_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_UDH_PCH_MEDIA_IMPRESSIONS_0 upmi
WHERE
  upmi.action = 'BI_DELETE'""")

df_1.createOrReplaceTempView("SQ_Shortcut_to_UDH_PCH_MEDIA_IMPRESSIONS_1")

# COMMAND ----------
# DBTITLE 1, UPD_UPDATE_2


df_2 = spark.sql("""SELECT
  RECORD_GID AS RECORD_GID,
  USER_ID AS USER_ID,
  PCH_MI_GID AS PCH_MI_GID,
  DELETED_IND AS DELETED_IND,
  LOAD_TSTMP AS LOAD_TSTMP,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_UDH_PCH_MEDIA_IMPRESSIONS_1""")

df_2.createOrReplaceTempView("UPD_UPDATE_2")

# COMMAND ----------
# DBTITLE 1, USR_PCH_MEDIA_IMPRESSIONS


spark.sql("""MERGE INTO USR_PCH_MEDIA_IMPRESSIONS AS TARGET
USING
  UPD_UPDATE_2 AS SOURCE ON TARGET.PCH_MI_GID = SOURCE.RECORD_GID
  WHEN MATCHED THEN
UPDATE
SET
  TARGET.PCH_MI_GID = SOURCE.RECORD_GID,
  TARGET.USER_ID = SOURCE.USER_ID,
  TARGET.RECORD_GID = SOURCE.PCH_MI_GID,
  TARGET.DELETED_IND = SOURCE.DELETED_IND,
  TARGET.UPDATE_TSTMP = SOURCE.LOAD_TSTMP""")